### PR TITLE
Fix resource cleanup for signal shutdown

### LINKED ISSUE #8805: alacritty --daemon doesn't close its socket
Running `alacritty` alone opens a new socket and upon graceful exit deletes it, but `alacritty --daemon` doesn't seem to clean up after itself.

Also see my comment in [#6231](https://github.com/alacritty/alacritty/issues/6231#issuecomment-3701922429).

### PR DESCRIPTION
**Pull request by chrisduerr**
This fixes an issue where Alacritty's resources, like its socket, would stick around after getting killed, since termination signals like SIGTERM were not handled explicitly.

To handle these signals, a new worker thread is spawned that just listens for SIGTERM and SIGINT using signal-hook, which we were already pulling for alacritty_terminal anyway.

While this does not provide support for Windows, we also do not have an IPC socket on Windows we need to clean up. The current `Signals` implementation does not support Windows, but alternatives like the `ctrlc` crate exist.

This does spawn a dedicated thread which is going to sit idle for the entire lifetime of Alacritty, which is somewhat unfortunate. However since Winit does not support listening for files like the pipes supported by signal-hook, this seems like the only solution which would not require significant effort in winit.

Closes #8805.

---

I kinda hate this, but it's probably better than not cleaning up the IPC socket.

### CODE REVIEW

File: alacritty/src/event.rs [hunk 1]
```diff
@@ -225,6 +235,28 @@ impl Processor {
                 | WindowEvent::Moved(_)
         )
     }
+
+    /// Spawn a thread for handling termination signals.
+    #[cfg(unix)]
+    fn spawn_signal_handler(proxy: EventLoopProxy<Event>) {
```
Comment (kchibisov) [inline alacritty/src/event.rs]: Can we integrate it on IPC reading thread? So we don't have to spawn more threads, but use already present one for that.

Comment (chrisduerr) [reply alacritty/src/event.rs]: I've been contemplating that, but we'd probably have to add some sort of event loop to sleep on file readiness for that. I *think* the pipe signal stuff could support read readiness.

Comment (kchibisov) [reply alacritty/src/event.rs]: Yeah, something like polling that we already use in `alacritty_terminal` for that. I think if we can e.g. plug file watcher into it, that would be better, but I'm not sure if it supports thread less mode now, probably not.

Comment (chrisduerr) [reply alacritty/src/event.rs]: Yeah the file watcher thread isn't actually watching an fd, so I'd imagine it would be harder to integrate than the socket stuff.

Comment (kchibisov) [reply alacritty/src/event.rs]: well, it kind of does, internally, but that is not exposed.

**Comment by chrisduerr** [comment]
Rewrote the IPC thread to act as a generic I/O event listener and that honestly cleaned up things *very* nicely. If inotify could integrate into that too it would be beautiful tbh (but not planning on that in this patch).

File: alacritty/src/main.rs [hunk 2]
```diff
@@ -63,6 +63,10 @@ use crate::config::monitor::ConfigMonitor;
 use crate::event::{Event, Processor};
 #[cfg(target_os = "macos")]
 use crate::macos::locale;
+#[cfg(unix)]
+use crate::polling::IoListener;
+#[cfg(unix)]
+use crate::polling::ipc;
```
Comment (kchibisov) [inline alacritty/src/main.rs]: those can be combined?
