### PR TITLE
Fix warnings for config imports

### LINKED ISSUE #6996: "Unused config key: import" warning when using .toml config file for selecting a theme
I try to configure my alacritty with an `alacritty.toml` file because otherwise i get a deprication warning for .yml.
This is my file:
```
import = [ "~/.config/alacritty/themes/themes/rose-pine.toml" ]

[env]
TERM = "alacritty"
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"

[window]
opacity = 0.98
decorations = "full"

[font]
size = 11.0

  [font.normal]
  family = "monospace"
  style = "Regular"
```
I migrated the rose-pine.yml file to a .toml file.
Everything works fine. **The theme is selected correctly.**
But whenever I start alacritty I get a warning:
`Unused config key: import`

Why is that and what do I need to do?

The [alacritty-themes](https://github.com/alacritty/alacritty-theme) page suggests using .yml, but I don't want those deprication warnings.

Thank you! :)

### System

```
            .-/+oossssoo+/-.               torben@torben-desktop
        `:+ssssssssssssssssss+:`           ---------------------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.2 LTS x86_64
    .ossssssssssssssssssdMMMNysssso.       Host: B550 Pro4
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.19.0-43-generic
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 1 hour
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 3606 (dpkg), 28 (snap)
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: zsh 5.8.1
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 42.5
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru-blue-dark [GTK2/3]
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru-blue [GTK2/3]
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: x-terminal-emul
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz
    .ossssssssssssssssssdMMMNysssso.       GPU: AMD ATI Radeon HD 6850
      -+sssssssssssssssssyyyssss+-         Memory: 3894MiB / 15727MiB
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
```
Version: `alacritty --version` output

`alacritty 0.13.0-dev (bd490672)`

### PR DESCRIPTION
**Pull request by chrisduerr**
Closes #6996.

### CODE REVIEW

File: alacritty/src/config/ui_config.rs [hunk 1]
```diff
@@ -85,6 +85,12 @@ pub struct UiConfig {
     /// Bindings for the mouse.
     #[config(deprecated = "use mouse.bindings instead")]
     mouse_bindings: MouseBindings,
+
+    /// Configuration file imports.
+    ///
+    /// This is never read since the field is directly accessed through the config's
+    /// [`toml::Value`], but still present to prevent unused field warnings.
+    xmport: Vec<String>,
```
Comment (kchibisov) [inline alacritty/src/config/ui_config.rs:93]: What's the reason to call it `xmport`? Just to clarify that it's dead?

Comment (chrisduerr) [reply alacritty/src/config/ui_config.rs:93]: Oh that was to test it doesn't work. I forgot to save it when changing it back. :D

**Review by kchibisov — APPROVED** [review]
