### PR TITLE
Fix overwriting of fullwidth character

### LINKED ISSUE #3726: Properly overwrite wide chars
Currently when the cursor is positioned above a wide char, or a wide char spacer, the underlying cell is simply overwritten without considering the previous fullwidth character content.

This can be reproduced with the following two escapes:
```
echo " 🥱🥱\b\b\ba"
```
This writes a character in the spacer of the first full width character, leading to overlapping glyphs.

```
echo " 🥱🥱\b\b\b\ba"
```
This overwrites the first full width character, which first seems to render correctly, however selecting the leftover wide char spacer will lead to the selection expanding across the other full width character incorrectly.

I'm not sure if this is ever a problem in practice, since usually content is cleared before it is rewritten to ensure correct behavior, but Alacritty's current behavior is probably the farthest away from correct in any of the terminal emulators I've tested.

The proper solution would likely to overwrite the entire fullwidth glyph when a character is written in either of its two cells, but there is one terminal that behaves differently (Kitty), which just doesn't write the character to the grid at all if it is written to the location of the spacer.

A proper resolution would likely not be very complicated, however certainly have some negative performance impact since I'd expect it to require two additional conditionals in the `input` function whenever any character is written. If there's a solution that can circumvent these in the hot path that would probably be ideal.

### PR DESCRIPTION
**Pull request by chrisduerr**
Fixes #3726.

### CODE REVIEW

**Comment by chrisduerr** [comment]
Performance of the current version is poor, the only version that doesn't introduce a significant regression I've found was applying only a minimal fix for deleting the characters without clearing any of the flags:

tmp

I'll have to investigate and maybe `perf` it, chances are there are some optimization oddities going on. In theory the intersection should be the same speed as the contains, but I've been getting mixed results.

**Comment by chrisduerr** [comment]
This should basically be good now, I've managed to match master's performance:

tmp

The benchmarks for `write_with_flag_fun` are a simple style improvement which moves the three instances where we write widechar/spacers to a generic function that takes the `c` and `Flags` and then inserts the flag, calls `write_at_cursor` and removes the flag automatically.

While this is a style enhancement, I'm somewhat hesitant to merge it since it has some unreliable performance characteristics (see `missing` benchmark for example).

**Comment by nixpulvis** [comment]
Here's what I'm seeing for performance on my ThinkPad X1 Carbon (5th)

summary

**Comment by chrisduerr** [comment]
I'm not sure about the reliability of your platform, but that seems within what I would expect.

**Comment by nixpulvis** [comment]
I could test the "fun" patch as well if it would be helpful to you?

**Comment by chrisduerr** [comment]
Feel free, though I don't really think it's worth it tbh.

File: alacritty_terminal/src/term/mod.rs [hunk 1]
```diff
@@ -860,14 +878,18 @@ impl<T: EventListener> Handler for Term<T> {
...
+            self.grid.cursor.template.flags.insert(Flags::WIDE_CHAR);
+            self.write_at_cursor(c);
+            self.grid.cursor.template.flags.remove(Flags::WIDE_CHAR);
 
             // Write spacer to cell following the wide glyph.
             self.grid.cursor.point.column += 1;
-            self.write_at_cursor(' ').flags.insert(Flags::WIDE_CHAR_SPACER);
+            self.grid.cursor.template.flags.insert(Flags::WIDE_CHAR_SPACER);
+            self.write_at_cursor(' ');
+            self.grid.cursor.template.flags.remove(Flags::WIDE_CHAR_SPACER);
```
Comment (nixpulvis) [inline alacritty_terminal/src/term/mod.rs:889]: I don't completely understand why you moved this to the template, but I'm completely fine assuming it was done for a good reason. Let me know if you care to explain.

**Review by nixpulvis — APPROVED** [review]
I tested this out a bit, and it looks like it's working as expected.

File: alacritty_terminal/src/term/mod.rs (hunk 1 above)
Comment (chrisduerr) [reply alacritty_terminal/src/term/mod.rs:889]: The `write_at_cursor` function previously returned a mutable reference. That made borrowing semantics complicated since branching while returning a mutable reference prevents you from reasigning that variable since borrowck assumes that is incorrect (which it is not).

So I found this alternative solution which allows us to do the same amount of work (except for one more branch) in our hottest path.
