### PR TITLE
Fix window being focused by default

### LINKED ISSUE #7866: alacritty believes its active but it is not
I do not expect alacritty to show a full cursor like it has input focus, when in fact, it has not.

https://www.youtube.com/watch?v=1Up2_n5b3s4

### System

OS: Linux
Version: alacritty 0.14.0-dev (6484ab84)
Linux/BSD: Wayland, River 0.2.6

### Logs
```
# alacritty --print-events
Created log file at "/tmp/Alacritty-32285.log"
[0.000005643s] [INFO ] [alacritty] Welcome to Alacritty
[0.000125498s] [INFO ] [alacritty] Version 0.14.0-dev (6484ab84)
[0.000147225s] [INFO ] [alacritty] Running on Wayland
[0.000695369s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/root/.config/alacritty/alacritty.toml"
                                     "/home/root/.config/alacritty/themes/themes/kanagawa_dragon.toml"
[0.001535520s] [INFO ] [alacritty] winit event: NewEvents(Init)
[0.001715795s] [INFO ] [alacritty] winit event: Resumed
[0.039071973s] [INFO ] [alacritty] Using EGL 1.5
[0.044618145s] [INFO ] [alacritty] Window scale factor: 1
[0.089383418s] [INFO ] [alacritty] Running on Mesa Intel(R) HD Graphics 520 (SKL GT2)
[0.089425646s] [INFO ] [alacritty] OpenGL version 4.6 (Core Profile) Mesa 24.0.1-arch1.1, shader_version 4.60
[0.089445959s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.124518163s] [INFO ] [alacritty] Cell size: 8 x 17
[0.124578123s] [INFO ] [alacritty] Padding: 0 x 0
[0.124595850s] [INFO ] [alacritty] Width: 800, Height: 600
[0.124653764s] [INFO ] [alacritty] PTY dimensions: 35 x 100
[0.128179753s] [INFO ] [alacritty] Initialisation complete
[0.128246128s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: Resized(PhysicalSize { width: 800, height: 600 }) }
[0.128323991s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[0.131240748s] [INFO ] [alacritty] winit event: AboutToWait
[0.131370811s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110739, tv_nsec: 400569828 }, requested_resume: None })
[0.131439029s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: Terminal(CursorBlinkingChange) })
[0.131494131s] [INFO ] [alacritty] winit event: AboutToWait
[0.131606073s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110739, tv_nsec: 400776705 }, requested_resume: Some(Instant { tv_sec: 110739, tv_nsec: 667771102 }) })
[0.131627658s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: ScaleFactorChanged { scale_factor: 2.0, inner_size_writer: InnerSizeWriter { new_inner_size: (Weak) } } }
[0.131679917s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: Resized(PhysicalSize { width: 1600, height: 1200 }) }
[0.131775584s] [INFO ] [alacritty] winit event: AboutToWait
[0.171750982s] [INFO ] [alacritty] Font size changed to 32.0 px
[0.171833329s] [INFO ] [alacritty] Cell size: 16 x 33
[0.177296049s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110739, tv_nsec: 446430762 }, requested_resume: Some(Instant { tv_sec: 110739, tv_nsec: 667771102 }) })
[0.177427566s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: Resized(PhysicalSize { width: 1280, height: 1356 }) }
[0.178810715s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[0.212208846s] [INFO ] [alacritty] Padding: 0 x 0
[0.212360441s] [INFO ] [alacritty] Width: 1280, Height: 1356
[0.217591405s] [INFO ] [alacritty] winit event: AboutToWait
[0.261988962s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110739, tv_nsec: 493091997 }, requested_resume: Some(Instant { tv_sec: 110739, tv_nsec: 667771102 }) })
[0.262039833s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: Terminal(Wakeup) })
[0.262065689s] [INFO ] [alacritty] winit event: AboutToWait
[0.262093865s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110739, tv_nsec: 531311998 }, requested_resume: Some(Instant { tv_sec: 110739, tv_nsec: 667771102 }) })
[0.262111762s] [INFO ] [alacritty] winit event: AboutToWait
[0.283391393s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110739, tv_nsec: 531357515 }, requested_resume: Some(Instant { tv_sec: 110739, tv_nsec: 667771102 }) })
[0.283441385s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: Terminal(Title(~/Videos)) })
[0.283461228s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: Terminal(Wakeup) })
[0.283476409s] [INFO ] [alacritty] winit event: AboutToWait
[0.283527727s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110739, tv_nsec: 552739328 }, requested_resume: Some(Instant { tv_sec: 110739, tv_nsec: 667771102 }) })
[0.283543435s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: Terminal(Wakeup) })
[0.283559901s] [INFO ] [alacritty] winit event: AboutToWait
[0.398675719s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110739, tv_nsec: 552805186 }, requested_resume: Instant { tv_sec: 110739, tv_nsec: 667771102 } })
[0.398867611s] [INFO ] [alacritty] winit event: AboutToWait
[0.399029297s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110739, tv_nsec: 668200913 }, requested_resume: Some(Instant { tv_sec: 110739, tv_nsec: 935186185 }) })
[0.399104722s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[0.399181267s] [INFO ] [alacritty] winit event: AboutToWait
[0.666001021s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110739, tv_nsec: 668476488 }, requested_resume: Instant { tv_sec: 110739, tv_nsec: 935186185 } })
[0.666081824s] [INFO ] [alacritty] winit event: AboutToWait
[0.666143427s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110739, tv_nsec: 935346197 }, requested_resume: Some(Instant { tv_sec: 110740, tv_nsec: 202338577 }) })
[0.666179233s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[0.666212095s] [INFO ] [alacritty] winit event: AboutToWait
[0.933234828s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110739, tv_nsec: 935463874 }, requested_resume: Instant { tv_sec: 110740, tv_nsec: 202338577 } })
[0.933386895s] [INFO ] [alacritty] winit event: AboutToWait
[0.933538318s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110740, tv_nsec: 202708272 }, requested_resume: Some(Instant { tv_sec: 110740, tv_nsec: 469694475 }) })
[0.933606375s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[0.933705453s] [INFO ] [alacritty] winit event: AboutToWait
[1.049646100s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110740, tv_nsec: 203041963 }, requested_resume: Some(Instant { tv_sec: 110740, tv_nsec: 469694475 }) })
[1.049882786s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: Resized(PhysicalSize { width: 1280, height: 678 }) }
[1.049994411s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[1.050133784s] [INFO ] [alacritty] Padding: 0 x 0
[1.050193703s] [INFO ] [alacritty] Width: 1280, Height: 678
[1.072839962s] [INFO ] [alacritty] winit event: AboutToWait
[1.084736189s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110740, tv_nsec: 342951289 }, requested_resume: Some(Instant { tv_sec: 110740, tv_nsec: 469694475 }) })
[1.084804043s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: Terminal(Title(~/Videos)) })
[1.084832013s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: Terminal(Wakeup) })
[1.084865494s] [INFO ] [alacritty] winit event: AboutToWait
[1.084936842s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110740, tv_nsec: 354139496 }, requested_resume: Some(Instant { tv_sec: 110740, tv_nsec: 469694475 }) })
[1.084959786s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: Terminal(Wakeup) })
[1.084980232s] [INFO ] [alacritty] winit event: AboutToWait
[1.114062886s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110740, tv_nsec: 376651343 }, requested_resume: Some(Instant { tv_sec: 110740, tv_nsec: 469694475 }) })
[1.114126608s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[1.122743796s] [INFO ] [alacritty] winit event: AboutToWait
[1.200533068s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110740, tv_nsec: 403269819 }, requested_resume: Instant { tv_sec: 110740, tv_nsec: 469694475 } })
[1.200587914s] [INFO ] [alacritty] winit event: AboutToWait
[1.200623591s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110740, tv_nsec: 469841789 }, requested_resume: Some(Instant { tv_sec: 110740, tv_nsec: 736837546 }) })
[1.200642504s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[1.200657711s] [INFO ] [alacritty] winit event: AboutToWait
[1.200683210s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110740, tv_nsec: 469904868 }, requested_resume: Some(Instant { tv_sec: 110740, tv_nsec: 736837546 }) })
[1.200696779s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[1.201024310s] [INFO ] [alacritty] winit event: AboutToWait
[1.467728477s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110740, tv_nsec: 483219894 }, requested_resume: Instant { tv_sec: 110740, tv_nsec: 736837546 } })
[1.468032751s] [INFO ] [alacritty] winit event: AboutToWait
[1.468219218s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110740, tv_nsec: 737362050 }, requested_resume: Some(Instant { tv_sec: 110741, tv_nsec: 4343336 }) })
[1.468309560s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[1.468390743s] [INFO ] [alacritty] winit event: AboutToWait
[1.468531957s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110740, tv_nsec: 737692187 }, requested_resume: Some(Instant { tv_sec: 110741, tv_nsec: 4343336 }) })
[1.468616085s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[1.469910480s] [INFO ] [alacritty] winit event: AboutToWait
[1.735218344s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110740, tv_nsec: 751269086 }, requested_resume: Instant { tv_sec: 110741, tv_nsec: 4343336 } })
[1.735269803s] [INFO ] [alacritty] winit event: AboutToWait
[1.735310242s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110741, tv_nsec: 4527010 }, requested_resume: Some(Instant { tv_sec: 110741, tv_nsec: 271521279 }) })
[1.735325527s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[1.735346995s] [INFO ] [alacritty] winit event: AboutToWait
[1.735377510s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110741, tv_nsec: 4595465 }, requested_resume: Some(Instant { tv_sec: 110741, tv_nsec: 271521279 }) })
[1.735398445s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[1.738921169s] [INFO ] [alacritty] winit event: AboutToWait
[2.002415699s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110741, tv_nsec: 16583475 }, requested_resume: Instant { tv_sec: 110741, tv_nsec: 271521279 } })
[2.002591791s] [INFO ] [alacritty] winit event: AboutToWait
[2.002733341s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110741, tv_nsec: 271900435 }, requested_resume: Some(Instant { tv_sec: 110741, tv_nsec: 538884443 }) })
[2.002874897s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[2.002971874s] [INFO ] [alacritty] winit event: AboutToWait
[2.003124222s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110741, tv_nsec: 272291318 }, requested_resume: Some(Instant { tv_sec: 110741, tv_nsec: 538884443 }) })
[2.003219305s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[2.004597677s] [INFO ] [alacritty] winit event: AboutToWait
[2.269900616s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110741, tv_nsec: 284977907 }, requested_resume: Instant { tv_sec: 110741, tv_nsec: 538884443 } })
[2.270008457s] [INFO ] [alacritty] winit event: AboutToWait
[2.270077061s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110741, tv_nsec: 539269804 }, requested_resume: Some(Instant { tv_sec: 110741, tv_nsec: 806264399 }) })
[2.270102228s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[2.270132285s] [INFO ] [alacritty] winit event: AboutToWait
[2.270177880s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110741, tv_nsec: 539391780 }, requested_resume: Some(Instant { tv_sec: 110741, tv_nsec: 806264399 }) })
[2.270202281s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[2.270672424s] [INFO ] [alacritty] winit event: AboutToWait
[2.537124780s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110741, tv_nsec: 549760763 }, requested_resume: Instant { tv_sec: 110741, tv_nsec: 806264399 } })
[2.537246581s] [INFO ] [alacritty] winit event: AboutToWait
[2.537378543s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110741, tv_nsec: 806552825 }, requested_resume: Some(Instant { tv_sec: 110742, tv_nsec: 73539030 }) })
[2.537453408s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[2.537521947s] [INFO ] [alacritty] winit event: AboutToWait
[2.537628671s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110741, tv_nsec: 806817437 }, requested_resume: Some(Instant { tv_sec: 110742, tv_nsec: 73539030 }) })
[2.537696114s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[2.538829261s] [INFO ] [alacritty] winit event: AboutToWait
[2.804446446s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110741, tv_nsec: 821148666 }, requested_resume: Instant { tv_sec: 110742, tv_nsec: 73539030 } })
[2.804585894s] [INFO ] [alacritty] winit event: AboutToWait
[2.804737799s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110742, tv_nsec: 73911187 }, requested_resume: Some(Instant { tv_sec: 110742, tv_nsec: 340896238 }) })
[2.804881704s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[2.804962338s] [INFO ] [alacritty] winit event: AboutToWait
[2.805078702s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110742, tv_nsec: 74259590 }, requested_resume: Some(Instant { tv_sec: 110742, tv_nsec: 340896238 }) })
[2.805141371s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[2.806452571s] [INFO ] [alacritty] winit event: AboutToWait
[3.071854037s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110742, tv_nsec: 84538679 }, requested_resume: Instant { tv_sec: 110742, tv_nsec: 340896238 } })
[3.072001101s] [INFO ] [alacritty] winit event: AboutToWait
[3.072119543s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110742, tv_nsec: 341297122 }, requested_resume: Some(Instant { tv_sec: 110742, tv_nsec: 608284103 }) })
[3.072184903s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[3.072514209s] [INFO ] [alacritty] winit event: AboutToWait
[3.072820557s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110742, tv_nsec: 341933936 }, requested_resume: Some(Instant { tv_sec: 110742, tv_nsec: 608284103 }) })
[3.072984328s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[3.074836195s] [INFO ] [alacritty] winit event: AboutToWait
[3.339133434s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110742, tv_nsec: 345789787 }, requested_resume: Instant { tv_sec: 110742, tv_nsec: 608284103 } })
[3.339289984s] [INFO ] [alacritty] winit event: AboutToWait
[3.339412569s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110742, tv_nsec: 608589371 }, requested_resume: Some(Instant { tv_sec: 110742, tv_nsec: 875577897 }) })
[3.339479386s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[3.339543952s] [INFO ] [alacritty] winit event: AboutToWait
[3.339644886s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110742, tv_nsec: 608833971 }, requested_resume: Some(Instant { tv_sec: 110742, tv_nsec: 875577897 }) })
[3.339711361s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[3.341008866s] [INFO ] [alacritty] winit event: AboutToWait
[3.606517013s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110742, tv_nsec: 617157272 }, requested_resume: Instant { tv_sec: 110742, tv_nsec: 875577897 } })
[3.606657485s] [INFO ] [alacritty] winit event: AboutToWait
[3.606824552s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110742, tv_nsec: 875947751 }, requested_resume: Some(Instant { tv_sec: 110743, tv_nsec: 142936120 }) })
[3.606924360s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[3.607010924s] [INFO ] [alacritty] winit event: AboutToWait
[3.607158924s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110742, tv_nsec: 876321196 }, requested_resume: Some(Instant { tv_sec: 110743, tv_nsec: 142936120 }) })
[3.607255132s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[3.608319657s] [INFO ] [alacritty] winit event: AboutToWait
[3.873811224s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110742, tv_nsec: 883763779 }, requested_resume: Instant { tv_sec: 110743, tv_nsec: 142936120 } })
[3.873974588s] [INFO ] [alacritty] winit event: AboutToWait
[3.874081485s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110743, tv_nsec: 143258694 }, requested_resume: Some(Instant { tv_sec: 110743, tv_nsec: 410243098 }) })
[3.874118597s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[3.874145359s] [INFO ] [alacritty] winit event: AboutToWait
[3.874180814s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110743, tv_nsec: 143398606 }, requested_resume: Some(Instant { tv_sec: 110743, tv_nsec: 410243098 }) })
[3.874220141s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[3.874593400s] [INFO ] [alacritty] winit event: AboutToWait
[4.141098324s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110743, tv_nsec: 144460425 }, requested_resume: Instant { tv_sec: 110743, tv_nsec: 410243098 } })
[4.141250330s] [INFO ] [alacritty] winit event: AboutToWait
[4.141506316s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110743, tv_nsec: 410562849 }, requested_resume: Some(Instant { tv_sec: 110743, tv_nsec: 677546576 }) })
[4.141614722s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[4.141721625s] [INFO ] [alacritty] winit event: AboutToWait
[4.141893744s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110743, tv_nsec: 411069554 }, requested_resume: Some(Instant { tv_sec: 110743, tv_nsec: 677546576 }) })
[4.141994983s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[4.145336447s] [INFO ] [alacritty] winit event: AboutToWait
[4.408471763s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110743, tv_nsec: 434381868 }, requested_resume: Instant { tv_sec: 110743, tv_nsec: 677546576 } })
[4.408614910s] [INFO ] [alacritty] winit event: AboutToWait
[4.408746826s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110743, tv_nsec: 677907867 }, requested_resume: Some(Instant { tv_sec: 110743, tv_nsec: 944892898 }) })
[4.408873096s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[4.408958138s] [INFO ] [alacritty] winit event: AboutToWait
[4.409092201s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110743, tv_nsec: 678274584 }, requested_resume: Some(Instant { tv_sec: 110743, tv_nsec: 944892898 }) })
[4.409173773s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[4.410554771s] [INFO ] [alacritty] winit event: AboutToWait
[4.675834947s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110743, tv_nsec: 684096023 }, requested_resume: Instant { tv_sec: 110743, tv_nsec: 944892898 } })
[4.675974322s] [INFO ] [alacritty] winit event: AboutToWait
[4.676087361s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110743, tv_nsec: 945266508 }, requested_resume: Some(Instant { tv_sec: 110744, tv_nsec: 212254883 }) })
[4.676144053s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[4.676245378s] [INFO ] [alacritty] winit event: AboutToWait
[4.676389212s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110743, tv_nsec: 945560588 }, requested_resume: Some(Instant { tv_sec: 110744, tv_nsec: 212254883 }) })
[4.676469870s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[4.677900589s] [INFO ] [alacritty] winit event: AboutToWait
[4.943183297s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110743, tv_nsec: 951283850 }, requested_resume: Instant { tv_sec: 110744, tv_nsec: 212254883 } })
[4.943385160s] [INFO ] [alacritty] winit event: AboutToWait
[4.943589030s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110744, tv_nsec: 212734727 }, requested_resume: Some(Instant { tv_sec: 110744, tv_nsec: 479714865 }) })
[4.943698711s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[4.943765202s] [INFO ] [alacritty] winit event: AboutToWait
[4.944033280s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110744, tv_nsec: 213190066 }, requested_resume: Some(Instant { tv_sec: 110744, tv_nsec: 479714865 }) })
[4.944153372s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[4.945514764s] [INFO ] [alacritty] winit event: AboutToWait
[5.210678948s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110744, tv_nsec: 216783299 }, requested_resume: Instant { tv_sec: 110744, tv_nsec: 479714865 } })
[5.210943426s] [INFO ] [alacritty] winit event: AboutToWait
[5.211152096s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110744, tv_nsec: 480304197 }, requested_resume: Some(Instant { tv_sec: 110744, tv_nsec: 747279461 }) })
[5.211293623s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[5.211386085s] [INFO ] [alacritty] winit event: AboutToWait
[5.211520279s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110744, tv_nsec: 480696572 }, requested_resume: Some(Instant { tv_sec: 110744, tv_nsec: 747279461 }) })
[5.211604437s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[5.213061448s] [INFO ] [alacritty] winit event: AboutToWait
[5.478177620s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110744, tv_nsec: 501063315 }, requested_resume: Instant { tv_sec: 110744, tv_nsec: 747279461 } })
[5.478318756s] [INFO ] [alacritty] winit event: AboutToWait
[5.478449256s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110744, tv_nsec: 747609944 }, requested_resume: Some(Instant { tv_sec: 110745, tv_nsec: 14597002 }) })
[5.478531025s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[5.478613667s] [INFO ] [alacritty] winit event: AboutToWait
[5.478747917s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110744, tv_nsec: 747927522 }, requested_resume: Some(Instant { tv_sec: 110745, tv_nsec: 14597002 }) })
[5.478897800s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[5.480370686s] [INFO ] [alacritty] winit event: AboutToWait
[5.745537482s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110744, tv_nsec: 752070766 }, requested_resume: Instant { tv_sec: 110745, tv_nsec: 14597002 } })
[5.745679935s] [INFO ] [alacritty] winit event: AboutToWait
[5.745837871s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110745, tv_nsec: 14971795 }, requested_resume: Some(Instant { tv_sec: 110745, tv_nsec: 281960126 }) })
[5.745905777s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[5.745976052s] [INFO ] [alacritty] winit event: AboutToWait
[5.746114874s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110745, tv_nsec: 15286387 }, requested_resume: Some(Instant { tv_sec: 110745, tv_nsec: 281960126 }) })
[5.746188666s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[5.747659193s] [INFO ] [alacritty] winit event: AboutToWait
[6.012874059s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110745, tv_nsec: 34186090 }, requested_resume: Instant { tv_sec: 110745, tv_nsec: 281960126 } })
[6.013041998s] [INFO ] [alacritty] winit event: AboutToWait
[6.013213317s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110745, tv_nsec: 282366225 }, requested_resume: Some(Instant { tv_sec: 110745, tv_nsec: 549350869 }) })
[6.013338284s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[6.013415309s] [INFO ] [alacritty] winit event: AboutToWait
[6.013547534s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110745, tv_nsec: 282726828 }, requested_resume: Some(Instant { tv_sec: 110745, tv_nsec: 549350869 }) })
[6.013616109s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[6.014938445s] [INFO ] [alacritty] winit event: AboutToWait
[6.280253453s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110745, tv_nsec: 285728470 }, requested_resume: Instant { tv_sec: 110745, tv_nsec: 549350869 } })
[6.280400447s] [INFO ] [alacritty] winit event: AboutToWait
[6.280566925s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110745, tv_nsec: 549729674 }, requested_resume: Some(Instant { tv_sec: 110745, tv_nsec: 816707199 }) })
[6.280633230s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[6.280717509s] [INFO ] [alacritty] winit event: AboutToWait
[6.280889986s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110745, tv_nsec: 550068990 }, requested_resume: Some(Instant { tv_sec: 110745, tv_nsec: 816707199 }) })
[6.280994925s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[6.282058405s] [INFO ] [alacritty] winit event: AboutToWait
[6.547619607s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110745, tv_nsec: 567603543 }, requested_resume: Instant { tv_sec: 110745, tv_nsec: 816707199 } })
[6.547803579s] [INFO ] [alacritty] winit event: AboutToWait
[6.547981432s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110745, tv_nsec: 817144468 }, requested_resume: Some(Instant { tv_sec: 110746, tv_nsec: 84129840 }) })
[6.548077990s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[6.548156687s] [INFO ] [alacritty] winit event: AboutToWait
[6.548284057s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110745, tv_nsec: 817458698 }, requested_resume: Some(Instant { tv_sec: 110746, tv_nsec: 84129840 }) })
[6.548365223s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[6.549685074s] [INFO ] [alacritty] winit event: AboutToWait
[6.815058734s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110745, tv_nsec: 820707762 }, requested_resume: Instant { tv_sec: 110746, tv_nsec: 84129840 } })
[6.815231103s] [INFO ] [alacritty] winit event: AboutToWait
[6.815393715s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110746, tv_nsec: 84563113 }, requested_resume: Some(Instant { tv_sec: 110746, tv_nsec: 351547149 }) })
[6.815497398s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[6.815689129s] [INFO ] [alacritty] winit event: AboutToWait
[6.815901787s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110746, tv_nsec: 85066044 }, requested_resume: Some(Instant { tv_sec: 110746, tv_nsec: 351547149 }) })
[6.816032264s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[6.817421387s] [INFO ] [alacritty] winit event: AboutToWait
[7.082473595s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110746, tv_nsec: 100800613 }, requested_resume: Instant { tv_sec: 110746, tv_nsec: 351547149 } })
[7.082617636s] [INFO ] [alacritty] winit event: AboutToWait
[7.082743305s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110746, tv_nsec: 351907824 }, requested_resume: Some(Instant { tv_sec: 110746, tv_nsec: 618896065 }) })
[7.083098188s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[7.083263319s] [INFO ] [alacritty] winit event: AboutToWait
[7.083420263s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110746, tv_nsec: 352585879 }, requested_resume: Some(Instant { tv_sec: 110746, tv_nsec: 618896065 }) })
[7.083525503s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[7.084931589s] [INFO ] [alacritty] winit event: AboutToWait
dk[7.349750146s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110746, tv_nsec: 367479385 }, requested_resume: Instant { tv_sec: 110746, tv_nsec: 618896065 } })
[7.349846049s] [INFO ] [alacritty] winit event: AboutToWait
[7.349899948s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110746, tv_nsec: 619105693 }, requested_resume: Some(Instant { tv_sec: 110746, tv_nsec: 886099132 }) })
[7.349925151s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[7.349956761s] [INFO ] [alacritty] winit event: AboutToWait
[7.349998004s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110746, tv_nsec: 619213335 }, requested_resume: Some(Instant { tv_sec: 110746, tv_nsec: 886099132 }) })
[7.350025998s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[7.350447138s] [INFO ] [alacritty] winit event: AboutToWait
kddk[7.616938059s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110746, tv_nsec: 620311402 }, requested_resume: Instant { tv_sec: 110746, tv_nsec: 886099132 } })
[7.617044021s] [INFO ] [alacritty] winit event: AboutToWait
[7.617127348s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110746, tv_nsec: 886313266 }, requested_resume: Some(Instant { tv_sec: 110747, tv_nsec: 153304464 }) })
[7.617158351s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[7.617190473s] [INFO ] [alacritty] winit event: AboutToWait
[7.617247276s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110746, tv_nsec: 886457421 }, requested_resume: Some(Instant { tv_sec: 110747, tv_nsec: 153304464 }) })
[7.617292671s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[7.618211859s] [INFO ] [alacritty] winit event: AboutToWait
dkd[7.884168036s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110746, tv_nsec: 888611191 }, requested_resume: Instant { tv_sec: 110747, tv_nsec: 153304464 } })
[7.884335177s] [INFO ] [alacritty] winit event: AboutToWait
[7.884507274s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110747, tv_nsec: 153672721 }, requested_resume: Some(Instant { tv_sec: 110747, tv_nsec: 420659379 }) })
[7.884589435s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[7.884661393s] [INFO ] [alacritty] winit event: AboutToWait
[7.884833968s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110747, tv_nsec: 153978374 }, requested_resume: Some(Instant { tv_sec: 110747, tv_nsec: 420659379 }) })
[7.884933343s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[7.886277322s] [INFO ] [alacritty] winit event: AboutToWait
kdk[8.151519613s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110747, tv_nsec: 167469501 }, requested_resume: Instant { tv_sec: 110747, tv_nsec: 420659379 } })
[8.151597290s] [INFO ] [alacritty] winit event: AboutToWait
[8.151658678s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110747, tv_nsec: 420861989 }, requested_resume: Some(Instant { tv_sec: 110747, tv_nsec: 687855466 }) })
[8.151694522s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[8.151722744s] [INFO ] [alacritty] winit event: AboutToWait
[8.151761152s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110747, tv_nsec: 420976838 }, requested_resume: Some(Instant { tv_sec: 110747, tv_nsec: 687855466 }) })
[8.151804833s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[8.152185024s] [INFO ] [alacritty] winit event: AboutToWait
dkdk[8.418699621s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110747, tv_nsec: 422056439 }, requested_resume: Instant { tv_sec: 110747, tv_nsec: 687855466 } })
[8.418788115s] [INFO ] [alacritty] winit event: AboutToWait
[8.418845302s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110747, tv_nsec: 688051166 }, requested_resume: Some(Instant { tv_sec: 110747, tv_nsec: 955045588 }) })
[8.418873762s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[8.418899779s] [INFO ] [alacritty] winit event: AboutToWait
[8.418938576s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110747, tv_nsec: 688151823 }, requested_resume: Some(Instant { tv_sec: 110747, tv_nsec: 955045588 }) })
[8.418964443s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[8.419389886s] [INFO ] [alacritty] winit event: AboutToWait
dk[8.685918717s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110747, tv_nsec: 699895560 }, requested_resume: Instant { tv_sec: 110747, tv_nsec: 955045588 } })
[8.686028681s] [INFO ] [alacritty] winit event: AboutToWait
[8.686095857s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110747, tv_nsec: 955304979 }, requested_resume: Some(Instant { tv_sec: 110748, tv_nsec: 222297735 }) })
[8.686119199s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[8.686140148s] [INFO ] [alacritty] winit event: AboutToWait
[8.686192931s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110747, tv_nsec: 955402320 }, requested_resume: Some(Instant { tv_sec: 110748, tv_nsec: 222297735 }) })
[8.686220101s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[8.686908941s] [INFO ] [alacritty] winit event: AboutToWait
dk[8.953146867s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110747, tv_nsec: 956873803 }, requested_resume: Instant { tv_sec: 110748, tv_nsec: 222297735 } })
[8.953208983s] [INFO ] [alacritty] winit event: AboutToWait
[8.953258468s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110748, tv_nsec: 222470291 }, requested_resume: Some(Instant { tv_sec: 110748, tv_nsec: 489465279 }) })
[8.953275274s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[8.953291450s] [INFO ] [alacritty] winit event: AboutToWait
[8.953319875s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110748, tv_nsec: 222540224 }, requested_resume: Some(Instant { tv_sec: 110748, tv_nsec: 489465279 }) })
[8.953338241s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[8.953875603s] [INFO ] [alacritty] winit event: AboutToWait
[9.220305679s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110748, tv_nsec: 223616147 }, requested_resume: Instant { tv_sec: 110748, tv_nsec: 489465279 } })
[9.220359931s] [INFO ] [alacritty] winit event: AboutToWait
[9.220402189s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110748, tv_nsec: 489614108 }, requested_resume: Some(Instant { tv_sec: 110748, tv_nsec: 756608154 }) })
[9.220423395s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[9.220444864s] [INFO ] [alacritty] winit event: AboutToWait
[9.220471281s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110748, tv_nsec: 489691604 }, requested_resume: Some(Instant { tv_sec: 110748, tv_nsec: 756608154 }) })
[9.220492023s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[9.220823221s] [INFO ] [alacritty] winit event: AboutToWait
[9.487505469s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110748, tv_nsec: 499211300 }, requested_resume: Instant { tv_sec: 110748, tv_nsec: 756608154 } })
[9.487553835s] [INFO ] [alacritty] winit event: AboutToWait
[9.487583453s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110748, tv_nsec: 756801291 }, requested_resume: Some(Instant { tv_sec: 110749, tv_nsec: 23797510 }) })
[9.487599142s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[9.487618859s] [INFO ] [alacritty] winit event: AboutToWait
[9.487647465s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110748, tv_nsec: 756867592 }, requested_resume: Some(Instant { tv_sec: 110749, tv_nsec: 23797510 }) })
[9.487664091s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[9.487979170s] [INFO ] [alacritty] winit event: AboutToWait
[9.754714263s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110748, tv_nsec: 765999603 }, requested_resume: Instant { tv_sec: 110749, tv_nsec: 23797510 } })
[9.754786069s] [INFO ] [alacritty] winit event: AboutToWait
[9.754824010s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110749, tv_nsec: 24040040 }, requested_resume: Some(Instant { tv_sec: 110749, tv_nsec: 291035354 }) })
[9.754839388s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[9.754851857s] [INFO ] [alacritty] winit event: AboutToWait
[9.754874206s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110749, tv_nsec: 24097495 }, requested_resume: Some(Instant { tv_sec: 110749, tv_nsec: 291035354 }) })
[9.754887245s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[9.755188056s] [INFO ] [alacritty] winit event: AboutToWait
[10.021865257s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110749, tv_nsec: 32486797 }, requested_resume: Instant { tv_sec: 110749, tv_nsec: 291035354 } })
[10.021917589s] [INFO ] [alacritty] winit event: AboutToWait
[10.021951439s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110749, tv_nsec: 291167562 }, requested_resume: Some(Instant { tv_sec: 110749, tv_nsec: 558163141 }) })
[10.021966032s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[10.021980321s] [INFO ] [alacritty] winit event: AboutToWait
[10.022005306s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110749, tv_nsec: 291227105 }, requested_resume: Some(Instant { tv_sec: 110749, tv_nsec: 558163141 }) })
[10.022017972s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[10.022433089s] [INFO ] [alacritty] winit event: AboutToWait
[10.288983447s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110749, tv_nsec: 299473742 }, requested_resume: Instant { tv_sec: 110749, tv_nsec: 558163141 } })
[10.289081377s] [INFO ] [alacritty] winit event: AboutToWait
[10.289138352s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110749, tv_nsec: 558346590 }, requested_resume: Some(Instant { tv_sec: 110749, tv_nsec: 825339403 }) })
[10.289158771s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[10.289185175s] [INFO ] [alacritty] winit event: AboutToWait
[10.289224449s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110749, tv_nsec: 558441621 }, requested_resume: Some(Instant { tv_sec: 110749, tv_nsec: 825339403 }) })
[10.289244550s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[10.289575925s] [INFO ] [alacritty] winit event: AboutToWait
[10.556249197s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110749, tv_nsec: 565528899 }, requested_resume: Instant { tv_sec: 110749, tv_nsec: 825339403 } })
[10.556296984s] [INFO ] [alacritty] winit event: AboutToWait
[10.556340665s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110749, tv_nsec: 825557570 }, requested_resume: Some(Instant { tv_sec: 110750, tv_nsec: 92553283 }) })
[10.556359102s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[10.556374875s] [INFO ] [alacritty] winit event: AboutToWait
[10.556400761s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110749, tv_nsec: 825623692 }, requested_resume: Some(Instant { tv_sec: 110750, tv_nsec: 92553283 }) })
[10.556416345s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[10.556725128s] [INFO ] [alacritty] winit event: AboutToWait
[10.823383435s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110749, tv_nsec: 832544395 }, requested_resume: Instant { tv_sec: 110750, tv_nsec: 92553283 } })
[10.823485726s] [INFO ] [alacritty] winit event: AboutToWait
[10.823571601s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110750, tv_nsec: 92768981 }, requested_resume: Some(Instant { tv_sec: 110750, tv_nsec: 359759453 }) })
[10.823617630s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[10.823664943s] [INFO ] [alacritty] winit event: AboutToWait
[10.823730818s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110750, tv_nsec: 92932395 }, requested_resume: Some(Instant { tv_sec: 110750, tv_nsec: 359759453 }) })
[10.823789693s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[10.824418672s] [INFO ] [alacritty] winit event: AboutToWait
[11.090603839s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110750, tv_nsec: 99045884 }, requested_resume: Instant { tv_sec: 110750, tv_nsec: 359759453 } })
[11.090653757s] [INFO ] [alacritty] winit event: AboutToWait
[11.090690796s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110750, tv_nsec: 359907068 }, requested_resume: Some(Instant { tv_sec: 110750, tv_nsec: 626902743 }) })
[11.090703992s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[11.090722765s] [INFO ] [alacritty] winit event: AboutToWait
[11.090752672s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110750, tv_nsec: 359971318 }, requested_resume: Some(Instant { tv_sec: 110750, tv_nsec: 626902743 }) })
[11.090789638s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[11.091129379s] [INFO ] [alacritty] winit event: AboutToWait
[11.358766339s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110750, tv_nsec: 365675225 }, requested_resume: Instant { tv_sec: 110750, tv_nsec: 626902743 } })
[11.359045803s] [INFO ] [alacritty] winit event: AboutToWait
[11.359221820s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110750, tv_nsec: 628380766 }, requested_resume: Some(Instant { tv_sec: 110750, tv_nsec: 895358674 }) })
[11.359300597s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[11.359369570s] [INFO ] [alacritty] winit event: AboutToWait
[11.359498850s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110750, tv_nsec: 628668980 }, requested_resume: Some(Instant { tv_sec: 110750, tv_nsec: 895358674 }) })
[11.359571231s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[11.363199805s] [INFO ] [alacritty] winit event: AboutToWait
[11.590458889s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110750, tv_nsec: 652441765 }, requested_resume: Some(Instant { tv_sec: 110750, tv_nsec: 895358674 }) })
[11.590574670s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: Focused(true) }
[11.590635290s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: ModifiersChanged(Modifiers { state: ModifiersState(SUPER), pressed_mods: ModifiersKeys(0x0) }) }
[11.590693944s] [INFO ] [alacritty] winit event: AboutToWait
[11.590812912s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110750, tv_nsec: 859985286 }, requested_resume: Some(Instant { tv_sec: 110751, tv_nsec: 126972684 }) })
[11.590891095s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[11.591730977s] [INFO ] [alacritty] winit event: AboutToWait
[11.749944231s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110750, tv_nsec: 868501385 }, requested_resume: Some(Instant { tv_sec: 110751, tv_nsec: 126972684 }) })
[11.750008129s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(SuperLeft), logical_key: Named(Super), text: None, location: Left, state: Released, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Named(Super), text_with_all_modifiers: None } }, is_synthetic: false } }
[11.750057310s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: ModifiersChanged(Modifiers { state: ModifiersState(0x0), pressed_mods: ModifiersKeys(0x0) }) }
[11.750085887s] [INFO ] [alacritty] winit event: AboutToWait
[11.857900245s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110751, tv_nsec: 19348818 }, requested_resume: Instant { tv_sec: 110751, tv_nsec: 126972684 } })
[11.858040071s] [INFO ] [alacritty] winit event: AboutToWait
[11.858168795s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110751, tv_nsec: 127329956 }, requested_resume: Some(Instant { tv_sec: 110751, tv_nsec: 394318045 }) })
[11.858246451s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[11.858334943s] [INFO ] [alacritty] winit event: AboutToWait
[11.858472209s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110751, tv_nsec: 127641617 }, requested_resume: Some(Instant { tv_sec: 110751, tv_nsec: 394318045 }) })
[11.858598151s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[11.859649818s] [INFO ] [alacritty] winit event: AboutToWait
[12.125239419s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110751, tv_nsec: 133473328 }, requested_resume: Instant { tv_sec: 110751, tv_nsec: 394318045 } })
[12.125551869s] [INFO ] [alacritty] winit event: AboutToWait
[12.125750041s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110751, tv_nsec: 394889077 }, requested_resume: Some(Instant { tv_sec: 110751, tv_nsec: 661872027 }) })
[12.125910124s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[12.126002644s] [INFO ] [alacritty] winit event: AboutToWait
[12.126154333s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110751, tv_nsec: 395323685 }, requested_resume: Some(Instant { tv_sec: 110751, tv_nsec: 661872027 }) })
[12.126244811s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[12.129577833s] [INFO ] [alacritty] winit event: AboutToWait
[12.392867146s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110751, tv_nsec: 400898410 }, requested_resume: Instant { tv_sec: 110751, tv_nsec: 661872027 } })
[12.393037368s] [INFO ] [alacritty] winit event: AboutToWait
[12.393209076s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110751, tv_nsec: 662375692 }, requested_resume: Some(Instant { tv_sec: 110751, tv_nsec: 929359967 }) })
[12.393336132s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[12.393460941s] [INFO ] [alacritty] winit event: AboutToWait
[12.393640566s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110751, tv_nsec: 662812300 }, requested_resume: Some(Instant { tv_sec: 110751, tv_nsec: 929359967 }) })
[12.393806951s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[12.395148701s] [INFO ] [alacritty] winit event: AboutToWait
[12.660282450s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110751, tv_nsec: 666211601 }, requested_resume: Instant { tv_sec: 110751, tv_nsec: 929359967 } })
[12.660472625s] [INFO ] [alacritty] winit event: AboutToWait
[12.660630467s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110751, tv_nsec: 929796028 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 196780781 }) })
[12.660723109s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[12.660855089s] [INFO ] [alacritty] winit event: AboutToWait
[12.660999098s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110751, tv_nsec: 930167852 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 196780781 }) })
[12.661095434s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[12.662393375s] [INFO ] [alacritty] winit event: AboutToWait
[12.739209179s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110751, tv_nsec: 933131316 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 196780781 }) })
[12.739266799s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyJ), logical_key: Character("j"), text: Some("j"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("j"), text_with_all_modifiers: Some("j") } }, is_synthetic: false } }
[12.739309629s] [INFO ] [alacritty] winit event: AboutToWait
[12.739367691s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 8578676 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 275568790 }) })
[12.739389179s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyD), logical_key: Character("d"), text: Some("d"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("d"), text_with_all_modifiers: Some("d") } }, is_synthetic: false } }
[12.739411439s] [INFO ] [alacritty] winit event: AboutToWait
[12.740558021s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 8670759 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 275665303 }) })
[12.740590874s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: Terminal(Wakeup) })
[12.740614698s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[12.740899416s] [INFO ] [alacritty] winit event: AboutToWait
[12.740942382s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 10159867 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 275665303 }) })
[12.740963565s] [INFO ] [alacritty] winit event: AboutToWait
[12.800034778s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 15671960 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 275665303 }) })
[12.800099955s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyJ), logical_key: Character("j"), text: Some("j"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("j"), text_with_all_modifiers: Some("j") } }, is_synthetic: false } }
[12.800133387s] [INFO ] [alacritty] winit event: AboutToWait
[12.800171383s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 69383004 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 275665303 }) })
[12.800189518s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyD), logical_key: Character("d"), text: Some("d"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("d"), text_with_all_modifiers: Some("d") } }, is_synthetic: false } }
[12.800213967s] [INFO ] [alacritty] winit event: AboutToWait
[12.909693681s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 69465552 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 275665303 }) })
[12.909766474s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyJ), logical_key: Character("j"), text: Some("j"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("j"), text_with_all_modifiers: Some("j") } }, is_synthetic: false } }
[12.909839069s] [INFO ] [alacritty] winit event: AboutToWait
[12.911039394s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 179130859 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 446120525 }) })
[12.911115384s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: Terminal(Wakeup) })
[12.911171431s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[12.911720338s] [INFO ] [alacritty] winit event: AboutToWait
[12.911818770s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 181023029 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 446120525 }) })
[12.911871227s] [INFO ] [alacritty] winit event: AboutToWait
[12.931395356s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 182473589 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 446120525 }) })
[12.931472768s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyD), logical_key: Character("d"), text: Some("d"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("d"), text_with_all_modifiers: Some("d") } }, is_synthetic: false } }
[12.931523687s] [INFO ] [alacritty] winit event: AboutToWait
[12.932034193s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 200809358 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 467796039 }) })
[12.932273954s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: Terminal(Wakeup) })
[12.932365710s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[12.933236098s] [INFO ] [alacritty] winit event: AboutToWait
[12.933363037s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 202552409 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 467796039 }) })
[12.933427975s] [INFO ] [alacritty] winit event: AboutToWait
[12.979317280s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 215687411 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 467796039 }) })
[12.979361384s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyJ), logical_key: Character("j"), text: Some("j"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("j"), text_with_all_modifiers: Some("j") } }, is_synthetic: false } }
[12.979386852s] [INFO ] [alacritty] winit event: AboutToWait
[13.001281129s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 248633646 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 467796039 }) })
[13.001378238s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyD), logical_key: Character("d"), text: Some("d"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("d"), text_with_all_modifiers: Some("d") } }, is_synthetic: false } }
[13.001440180s] [INFO ] [alacritty] winit event: AboutToWait
[13.093312894s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 270699884 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 467796039 }) })
[13.093454899s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyJ), logical_key: Character("j"), text: Some("j"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("j"), text_with_all_modifiers: Some("j") } }, is_synthetic: false } }
[13.093591313s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyD), logical_key: Character("d"), text: Some("d"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("d"), text_with_all_modifiers: Some("d") } }, is_synthetic: false } }
[13.093697572s] [INFO ] [alacritty] winit event: AboutToWait
[13.094926915s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 363090042 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 630084301 }) })
[13.095249407s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: Terminal(Wakeup) })
[13.095345865s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[13.096620121s] [INFO ] [alacritty] winit event: AboutToWait
[13.096876099s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 366038404 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 630084301 }) })
[13.096976138s] [INFO ] [alacritty] winit event: AboutToWait
[13.154629713s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 386228042 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 630084301 }) })
[13.154678005s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyJ), logical_key: Character("j"), text: Some("j"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("j"), text_with_all_modifiers: Some("j") } }, is_synthetic: false } }
[13.154702948s] [INFO ] [alacritty] winit event: AboutToWait
[13.154732716s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 423948466 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 630084301 }) })
[13.154747525s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyD), logical_key: Character("d"), text: Some("d"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("d"), text_with_all_modifiers: Some("d") } }, is_synthetic: false } }
[13.154765544s] [INFO ] [alacritty] winit event: AboutToWait
[13.253314068s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 424020373 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 630084301 }) })
[13.253424854s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyD), logical_key: Character("d"), text: Some("d"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("d"), text_with_all_modifiers: Some("d") } }, is_synthetic: false } }
[13.253511676s] [INFO ] [alacritty] winit event: AboutToWait
[13.256098205s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 522827882 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 789805139 }) })
[13.256312370s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: Terminal(Wakeup) })
[13.256447463s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[13.258201749s] [INFO ] [alacritty] winit event: AboutToWait
[13.258564860s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 527768870 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 789805139 }) })
[13.258938948s] [INFO ] [alacritty] winit event: AboutToWait
[13.276075569s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 534755620 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 789805139 }) })
[13.276127978s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyJ), logical_key: Character("j"), text: Some("j"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("j"), text_with_all_modifiers: Some("j") } }, is_synthetic: false } }
[13.276168239s] [INFO ] [alacritty] winit event: AboutToWait
[13.276490157s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 545497027 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 812426573 }) })
[13.276516909s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: Terminal(Wakeup) })
[13.276540720s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[13.276930534s] [INFO ] [alacritty] winit event: AboutToWait
[13.276988752s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 546206145 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 812426573 }) })
[13.277011347s] [INFO ] [alacritty] winit event: AboutToWait
[13.297998044s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 549308278 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 812426573 }) })
[13.298050060s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyD), logical_key: Character("d"), text: Some("d"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("d"), text_with_all_modifiers: Some("d") } }, is_synthetic: false } }
[13.298078615s] [INFO ] [alacritty] winit event: AboutToWait
[13.329986430s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 567325039 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 812426573 }) })
[13.330030482s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyJ), logical_key: Character("j"), text: Some("j"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("j"), text_with_all_modifiers: Some("j") } }, is_synthetic: false } }
[13.330050967s] [INFO ] [alacritty] winit event: AboutToWait
[13.389682712s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 608618488 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 812426573 }) })
[13.389837702s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyD), logical_key: Character("d"), text: Some("d"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("d"), text_with_all_modifiers: Some("d") } }, is_synthetic: false } }
[13.389908285s] [INFO ] [alacritty] winit event: AboutToWait
[13.391551966s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 659231806 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 926214848 }) })
[13.391764680s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: Terminal(Wakeup) })
[13.391886302s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[13.392609129s] [INFO ] [alacritty] winit event: AboutToWait
[13.392693056s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 661890256 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 926214848 }) })
[13.392752921s] [INFO ] [alacritty] winit event: AboutToWait
[13.442488871s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 665992708 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 926214848 }) })
[13.442549032s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyJ), logical_key: Character("j"), text: Some("j"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("j"), text_with_all_modifiers: Some("j") } }, is_synthetic: false } }
[13.442586201s] [INFO ] [alacritty] winit event: AboutToWait
[13.442660534s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 711858957 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 978850368 }) })
[13.442684081s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyD), logical_key: Character("d"), text: Some("d"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("d"), text_with_all_modifiers: Some("d") } }, is_synthetic: false } }
[13.442715584s] [INFO ] [alacritty] winit event: AboutToWait
[13.443310494s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 711965946 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 978850368 }) })
[13.443358822s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: Terminal(Wakeup) })
[13.443390534s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[13.443818050s] [INFO ] [alacritty] winit event: AboutToWait
[13.444022307s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 713201746 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 978850368 }) })
[13.444121452s] [INFO ] [alacritty] winit event: AboutToWait
[13.506192464s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 715700229 }, requested_resume: Some(Instant { tv_sec: 110752, tv_nsec: 978850368 }) })
[13.506237368s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(KeyJ), logical_key: Character("j"), text: Some("j"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("j"), text_with_all_modifiers: Some("j") } }, is_synthetic: false } }
[13.506260656s] [INFO ] [alacritty] winit event: AboutToWait
[13.709756779s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110752, tv_nsec: 962647343 }, requested_resume: Instant { tv_sec: 110752, tv_nsec: 978850368 } })
[13.709991118s] [INFO ] [alacritty] winit event: AboutToWait
[13.710201380s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 979340015 }, requested_resume: Some(Instant { tv_sec: 110753, tv_nsec: 246315282 }) })
[13.710395904s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[13.710527841s] [INFO ] [alacritty] winit event: AboutToWait
[13.710722410s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110752, tv_nsec: 979877090 }, requested_resume: Some(Instant { tv_sec: 110753, tv_nsec: 246315282 }) })
[13.710945416s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[13.712647939s] [INFO ] [alacritty] winit event: AboutToWait
[13.977207834s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110753, tv_nsec: 145358409 }, requested_resume: Instant { tv_sec: 110753, tv_nsec: 246315282 } })
[13.977360403s] [INFO ] [alacritty] winit event: AboutToWait
[13.977516893s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110753, tv_nsec: 246679445 }, requested_resume: Some(Instant { tv_sec: 110753, tv_nsec: 513664881 }) })
[13.977583362s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[13.977663938s] [INFO ] [alacritty] winit event: AboutToWait
[13.977846528s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110753, tv_nsec: 246975039 }, requested_resume: Some(Instant { tv_sec: 110753, tv_nsec: 513664881 }) })
[13.977930954s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[13.979038318s] [INFO ] [alacritty] winit event: AboutToWait
[14.244596359s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110753, tv_nsec: 311848469 }, requested_resume: Instant { tv_sec: 110753, tv_nsec: 513664881 } })
[14.244740145s] [INFO ] [alacritty] winit event: AboutToWait
[14.244943631s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110753, tv_nsec: 514113552 }, requested_resume: Some(Instant { tv_sec: 110753, tv_nsec: 781097305 }) })
[14.245024033s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[14.245160142s] [INFO ] [alacritty] winit event: AboutToWait
[14.245323758s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110753, tv_nsec: 514478894 }, requested_resume: Some(Instant { tv_sec: 110753, tv_nsec: 781097305 }) })
[14.245447211s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[14.247345817s] [INFO ] [alacritty] winit event: AboutToWait
[14.420203061s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110753, tv_nsec: 518300210 }, requested_resume: Some(Instant { tv_sec: 110753, tv_nsec: 781097305 }) })
[14.420247677s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), event: KeyEvent { physical_key: Code(SuperLeft), logical_key: Named(Super), text: None, location: Left, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Named(Super), text_with_all_modifiers: None } }, is_synthetic: false } }
[14.420266402s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: ModifiersChanged(Modifiers { state: ModifiersState(SUPER), pressed_mods: ModifiersKeys(0x0) }) }
[14.420277916s] [INFO ] [alacritty] winit event: AboutToWait
[14.511955594s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110753, tv_nsec: 689530391 }, requested_resume: Instant { tv_sec: 110753, tv_nsec: 781097305 } })
[14.512129582s] [INFO ] [alacritty] winit event: AboutToWait
[14.512318901s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110753, tv_nsec: 781440095 }, requested_resume: Some(Instant { tv_sec: 110754, tv_nsec: 48418054 }) })
[14.512517341s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[14.512638079s] [INFO ] [alacritty] winit event: AboutToWait
[14.512868966s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110753, tv_nsec: 781956715 }, requested_resume: Some(Instant { tv_sec: 110754, tv_nsec: 48418054 }) })
[14.513011377s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[14.514662519s] [INFO ] [alacritty] winit event: AboutToWait
[14.779290909s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 110753, tv_nsec: 799773059 }, requested_resume: Instant { tv_sec: 110754, tv_nsec: 48418054 } })
[14.779465984s] [INFO ] [alacritty] winit event: AboutToWait
[14.779632942s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110754, tv_nsec: 48797511 }, requested_resume: Some(Instant { tv_sec: 110754, tv_nsec: 315782386 }) })
[14.779723845s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(94732369875408))), payload: BlinkCursor })
[14.779837465s] [INFO ] [alacritty] winit event: AboutToWait
[14.780004531s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110754, tv_nsec: 49176005 }, requested_resume: Some(Instant { tv_sec: 110754, tv_nsec: 315782386 }) })
[14.780104723s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[14.781386859s] [INFO ] [alacritty] winit event: AboutToWait
[14.886873426s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110754, tv_nsec: 67353150 }, requested_resume: Some(Instant { tv_sec: 110754, tv_nsec: 315782386 }) })
[14.887036733s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: ModifiersChanged(Modifiers { state: ModifiersState(0x0), pressed_mods: ModifiersKeys(0x0) }) }
[14.887142775s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: Focused(false) }
[14.887265098s] [INFO ] [alacritty] winit event: AboutToWait
[14.887453709s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110754, tv_nsec: 156623886 }, requested_resume: None })
[14.887551192s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(94732369875408)), event: RedrawRequested }
[14.889144125s] [INFO ] [alacritty] winit event: AboutToWait
dkkddk^C⏎                                                                                                                                                       [I] root@trump ~/Videos [SIGINT]
#
```

### PR DESCRIPTION
**Pull request by kchibisov**
Winit explicitly states that the window is not focused by default and the `Focused` event will deliver the state later on.

Closes #7866.

--

An alternative would be to make the `focused` as `false` by default in `alacritty_terminal` as well. Maybe it's a better way forward.

### CODE REVIEW

File: alacritty/src/window_context.rs [hunk 1]
```diff
@@ -196,7 +196,10 @@ impl WindowContext {
         // This object contains all of the state about what's being displayed. It's
         // wrapped in a clonable mutex since both the I/O loop and display need to
         // access it.
-        let terminal = Term::new(config.term_options(), &display.size_info, event_proxy.clone());
+        let mut terminal =
+            Term::new(config.term_options(), &display.size_info, event_proxy.clone());
+        // Mark terminal not focused, because winit window is not focused by default.
```
Comment (chrisduerr) [inline alacritty/src/window_context.rs:201]:
```suggestion
        // Mark terminal unfocused, because winit window is not focused by default.
```

**Review by chrisduerr — CHANGES_REQUESTED** [review]
I'd assume you didn't change this in alacritty_terminal because your expectation is that usually new terminals are focused by default?

**Comment by kchibisov** [comment]
I haven't changed this in alacritty_terminal that we should somehow communicate this breaking change, hence why I've asked about the changelog. Logically it should be `unfocused` though.

**Comment by chrisduerr** [comment]
> Logically it should be unfocused though.

Then I'd make the change in alacritty_terminal. Communicating it properly is a separate issue.

File: CHANGELOG.md [hunk 2]
```diff
@@ -5,8 +5,15 @@ The sections should follow the order `Packaging`, `Added`, `Changed`, `Fixed` an
 
 The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
 
+Notable changes to `alacritty_terminal` crate should be documented in its
+[CHANGELOG](./alacritty_terminal/CHANGELOG.md).
```
Comment (chrisduerr) [inline CHANGELOG.md:9]: This is a user-facing document, however this is worded in a developer-centric fashion.

This would probably be better:

```suggestion
Notable changes to the `alacritty_terminal` crate are documented in its
[CHANGELOG](./alacritty_terminal/CHANGELOG.md).
```

Arguably the same could be said about the documentation about the sections, but that is a bit older.

File: CHANGELOG.md [hunk 3]
```diff
@@ -5,8 +5,15 @@ The sections should follow the order `Packaging`, `Added`, `Changed`, `Fixed` an
...
+
 ## 0.14.0-dev
 
+### Fixed
+
+- New window sometimes being treated as focused when it's not on Wayland
```
Comment (chrisduerr) [inline CHANGELOG.md:15]:
```suggestion
- New window being treated as focused when it's not on Wayland
```

File: CONTRIBUTING.md [hunk 4]
```diff
@@ -91,9 +91,10 @@ If any change has been made to the `config.rs` file, it should also be documente
 
 Changes compared to the latest Alacritty release which have a direct effect on the user (opposed to
 things like code refactorings or documentation/tests) additionally need to be documented in the
-`CHANGELOG.md`. The existing entries should be used as a style guideline. The change log should be
-used to document changes from a user-perspective, instead of explaining the technical background
-(like commit messages). More information about Alacritty's change log format can be found
+`CHANGELOG.md`. When notable change is made to `alacritty_terminal` it should be documnted in its
+`CHANGELOG.md` as well. The existing entries should be used as a style guideline. The change log
+should be used to document changes from a user-perspective, instead of explaining the technical
+background (like commit messages). More information about Alacritty's change log format can be found
```
Comment (chrisduerr) [inline CONTRIBUTING.md:97]:
```suggestion
`CHANGELOG.md`. When a notable change is made to `alacritty_terminal`, it should be documented in
`alacritty_terminal/CHANGELOG.md` as well. The existing entries should be used as a style guideline. The change log
should be used to document changes from a user-perspective, instead of explaining the technical
background (like commit messages). More information about Alacritty's change log format can be found
```

File: alacritty_terminal/CHANGELOG.md [hunk 5]
```diff
@@ -0,0 +1,13 @@
...
+sections should follow the order `Added`, `Changed`, `Deprecated`, `Fixed` and
+`Removed`.
+
+The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
+
+## 0.23.0-dev
+
+### Changed
+
+- `Term<T>` is not focused by default anymore
```
Comment (chrisduerr) [inline alacritty_terminal/CHANGELOG.md:13]:
```suggestion
- `Term` is not focused by default anymore
```

The generics are just unnecessary noise. Providing a full path could be nice, but shouldn't be necessary in this case.

**Review by chrisduerr — CHANGES_REQUESTED** [review]

File: CHANGELOG.md (hunk 3 above)
Comment (kchibisov) [reply CHANGELOG.md:15]: This bug is really hard to trigger though, I'm not sure you can even face it, but ok.

Comment (chrisduerr) [reply CHANGELOG.md]: Yeah it's just kinda unnecessary. Because people who aren't running into the bug just don't care. How frequently a bug occurred isn't really relevant. The people that ran into it know it's fixed, the people that never ran into it don't care either way.

File: alacritty_terminal/CHANGELOG.md [hunk 6]
```diff
@@ -0,0 +1,13 @@
...
+sections should follow the order `Added`, `Changed`, `Deprecated`, `Fixed` and
+`Removed`.
+
+The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
+
+## 0.23.0-dev
+
+### Changed
+
+- `Term` is not focused by default anymore
```
Comment (chrisduerr) [inline alacritty_terminal/CHANGELOG.md:13]: I wonder if we should somehow indicate breaking changes? Do you have any opinion on this?

Maybe a migration guide between versions?

**Review by chrisduerr — CHANGES_REQUESTED** [review]

File: alacritty_terminal/CHANGELOG.md (hunk 6 above)
Comment (kchibisov) [reply alacritty_terminal/CHANGELOG.md:13]: I'd suggest migration for bigger stuff, you can look at the changelog we have in winit now. For such a small change, I don't think you need it?

https://github.com/rust-windowing/winit/blob/master/src/changelog/unreleased.md

Comment (chrisduerr) [reply alacritty_terminal/CHANGELOG.md:13]: > you can look at the changelog we have in winit now

I mean that's exactly the issue right there. A ton of changes but no clear indication which changes require my attention.

I don't care if a bunch of new stuff was added or something was fixed when updating to a new version, but I **do** care if something needs manual intervention like this focus change to keep the behavior consistent.

Some changelogs have ugly prefixes like `[BREAKING]` for these kind of entries, but I don't think that's particularly nice. Maybe we can add a line at the top explaining that breaking changes are bold, then use that to indicate them?

Comment (kchibisov) [reply alacritty_terminal/CHANGELOG.md:13]: >I mean that's exactly the issue right there. A ton of changes but no clear indication which changes require my attention.

It has a big chunk of code and explanation for what you need. So it's just 2 changes where you need attention.

We can do a separate section with breaking changes.

Comment (chrisduerr) [reply alacritty_terminal/CHANGELOG.md:13]: > It has a big chunk of code and explanation for what you need. So it's just 2 changes where you need attention.

It doesn't though. It states nowhere that these are the only changes that require my attention. It just tells me what I need to do for those.

Comment (kchibisov) [reply alacritty_terminal/CHANGELOG.md:13]: >It doesn't though. It states nowhere that these are the only changes that require my attention. It just tells me what I need to do for those.

Hm, that's fair, because it'll start to warn you, since we don't remove the API. For real breaking change I just did `bold` iirc.

>Do you suggest adding an extra section with its own Fixed/Added/etc?

Just `Breaking`.

Comment (chrisduerr) [reply alacritty_terminal/CHANGELOG.md:13]: I like bold for breaking, it's unintrusive but still pretty clear.

**Review by chrisduerr — APPROVED** [review]
