### PR TITLE
fix crashes on multiple tabs in macos with decorations set to None

### LINKED ISSUE #7802: Crash when trying to create new tab with window.decorations set to "None"
**Description:**
When attempting to create a new tab in Alacritty with the window.decorations set to "None" in the configuration, the application crashes. Instead of creating a new tab, it attempts to create a new window, leading to the crash.

**Steps to reproduce:**
1. Set window.decorations to "None" in the alacritty.toml configuration file.
2. Open Alacritty.
3. Create the first tab.
4. Attempt to create a new tab.

https://github.com/alacritty/alacritty/assets/74539042/86d08aa1-d7e7-4f30-aaa3-6ca7d7f2b568

### System

OS: macOS
Version: alacritty 0.14.0-dev (63e94fd3)

### Logs

Crashes: STDERR, STDOUT

Font/Terminal size: `alacritty -vv`
```
$ cat /var/folders/jp/fy7jh6297b11rxf2lp28s2_40000gn/T/Alacritty-25037.log
[0.000029916s] [INFO ] [alacritty] Welcome to Alacritty
[0.000304416s] [INFO ] [alacritty] Version 0.14.0-dev (63e94fd3)
[0.001356750s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/Users/mteit/.config/alacritty/alacritty.toml"
[0.001794958s] [DEBUG] [alacritty] Using environment locale: en_US.UTF-8
[0.014920458s] [INFO ] [alacritty] Using Apple CGL
[0.026788041s] [DEBUG] [alacritty] Picked GL Config:
                                     buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                                     alpha_size: 8
                                     num_samples: 0
                                     hardware_accelerated: true
                                     supports_transparency: Some(true)
                                     config_api: Api(OPENGL)
                                     srgb_capable: true
[0.045206958s] [INFO ] [alacritty] Window scale factor: 2
[0.045957458s] [DEBUG] [alacritty] Loading "JetBrainsMono Nerd Font" font
[0.070459500s] [INFO ] [alacritty] Running on Apple M1
[0.070493208s] [INFO ] [alacritty] OpenGL version 4.1 Metal - 83.1, shader_version 4.10
[0.070508500s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.073819541s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.082594041s] [INFO ] [alacritty] Cell size: 20 x 45
[0.082636166s] [INFO ] [alacritty] Padding: 0 x 0
[0.082648375s] [INFO ] [alacritty] Width: 1800, Height: 1350
[0.088380166s] [INFO ] [alacritty] PTY dimensions: 30 x 90
[0.090057333s] [INFO ] [alacritty] Initialisation complete
```

Keyboard and bindings: `alacritty --print-events`
[crash.log](https://github.com/alacritty/alacritty/files/14470916/crash.log)
```
[0:02:00] ~/Develop/buid/alacritty/target/release/osx/Alacritty.app/Contents/MacOS on  master
[2] ƒ ./alacritty --print-events
Created log file at "/var/folders/jp/fy7jh6297b11rxf2lp28s2_40000gn/T/Alacritty-27088.log"
[0.000003625s] [INFO ] [alacritty] Welcome to Alacritty
[0.000217458s] [INFO ] [alacritty] Version 0.14.0-dev (63e94fd3)
[0.000483166s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/Users/mteit/.config/alacritty/alacritty.toml"
[0.013741583s] [INFO ] [alacritty] winit event: NewEvents(Init)
[0.013798333s] [INFO ] [alacritty] winit event: Resumed
[0.013819083s] [INFO ] [alacritty] Using Apple CGL
[0.035935583s] [INFO ] [alacritty] Window scale factor: 2
[0.063147958s] [INFO ] [alacritty] Running on Apple M1
[0.063190541s] [INFO ] [alacritty] OpenGL version 4.1 Metal - 83.1, shader_version 4.10
[0.063201375s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.075997666s] [INFO ] [alacritty] Cell size: 20 x 45
[0.076049750s] [INFO ] [alacritty] Padding: 0 x 0
[0.076061791s] [INFO ] [alacritty] Width: 1800, Height: 1350
[0.081129541s] [INFO ] [alacritty] PTY dimensions: 30 x 90
[0.083591208s] [INFO ] [alacritty] Initialisation complete
[0.085109458s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5251308032)), event: RedrawRequested }
[0.110510458s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5251308032))), payload: Terminal(Wakeup) })
[0.110551041s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5251308032)), event: Resized(PhysicalSize { width: 1600, height: 1200 }) }
[0.110565291s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5251308032)), event: Focused(false) }
[0.110574958s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5251308032)), event: Resized(PhysicalSize { width: 1800, height: 1350 }) }
[0.110584166s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5251308032)), event: Moved(PhysicalPosition { x: 1450, y: 500 }) }
[0.110593625s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5251308032)), event: Focused(true) }
[0.110602541s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5251308032)), event: RedrawRequested }
[0.111166416s] [INFO ] [alacritty] winit event: AboutToWait
[0.111197125s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 268337041 }, requested_resume: None })
[0.112122625s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5251308032))), payload: Frame })
[0.112141708s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5251308032))), payload: Frame })
[0.112151333s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5251308032)), event: Occluded(false) }
[0.112161208s] [INFO ] [alacritty] winit event: AboutToWait
[0.112174291s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 269320375 }, requested_resume: None })
[0.112198250s] [INFO ] [alacritty] winit event: AboutToWait
[0.113294250s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 269357916 }, requested_resume: None })
[0.113324083s] [INFO ] [alacritty] winit event: AboutToWait
[0.116085958s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 270487375 }, requested_resume: None })
[0.116164500s] [INFO ] [alacritty] winit event: AboutToWait
[0.116183333s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 273328916 }, requested_resume: None })
[0.116199791s] [INFO ] [alacritty] winit event: AboutToWait
[0.120212208s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 273359541 }, requested_resume: None })
[0.120272291s] [INFO ] [alacritty] winit event: AboutToWait
[0.120288458s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 277435208 }, requested_resume: None })
[0.120304083s] [INFO ] [alacritty] winit event: AboutToWait
[0.124289708s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 277465291 }, requested_resume: None })
[0.124353375s] [INFO ] [alacritty] winit event: AboutToWait
[0.124367458s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 281514541 }, requested_resume: None })
[0.124381166s] [INFO ] [alacritty] winit event: AboutToWait
[0.127565583s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 281539208 }, requested_resume: None })
[0.127614500s] [INFO ] [alacritty] winit event: AboutToWait
[0.127630583s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 284777375 }, requested_resume: None })
[0.127643791s] [INFO ] [alacritty] winit event: AboutToWait
[0.131442708s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 284802541 }, requested_resume: None })
[0.131489625s] [INFO ] [alacritty] winit event: AboutToWait
[0.131505041s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 288651500 }, requested_resume: None })
[0.131519500s] [INFO ] [alacritty] winit event: AboutToWait
[0.135455708s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 288677708 }, requested_resume: None })
[0.135507541s] [INFO ] [alacritty] winit event: AboutToWait
[0.135522333s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 292668750 }, requested_resume: None })
[0.135536666s] [INFO ] [alacritty] winit event: AboutToWait
[0.139258375s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 292694125 }, requested_resume: None })
[0.139290125s] [INFO ] [alacritty] winit event: AboutToWait
[0.139302625s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 296449708 }, requested_resume: None })
[0.139314333s] [INFO ] [alacritty] winit event: AboutToWait
[0.142467666s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 296472500 }, requested_resume: None })
[0.142497875s] [INFO ] [alacritty] winit event: AboutToWait
[0.142510750s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 299657500 }, requested_resume: None })
[0.142523041s] [INFO ] [alacritty] winit event: AboutToWait
[0.146534166s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 299680000 }, requested_resume: None })
[0.146572750s] [INFO ] [alacritty] winit event: AboutToWait
[0.146588958s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 303735833 }, requested_resume: None })
[0.146605041s] [INFO ] [alacritty] winit event: AboutToWait
[0.149893625s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 303763416 }, requested_resume: None })
[0.149950791s] [INFO ] [alacritty] winit event: AboutToWait
[0.149965333s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 307111875 }, requested_resume: None })
[0.149978041s] [INFO ] [alacritty] winit event: AboutToWait
[0.153276791s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 307139500 }, requested_resume: None })
[0.153326750s] [INFO ] [alacritty] winit event: AboutToWait
[0.153339500s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 310486458 }, requested_resume: None })
[0.153351416s] [INFO ] [alacritty] winit event: AboutToWait
[0.192765666s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 310508625 }, requested_resume: None })
[0.193447125s] [INFO ] [alacritty] winit event: AboutToWait
[0.195225750s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 350613791 }, requested_resume: None })
[0.195254416s] [INFO ] [alacritty] winit event: AboutToWait
[0.225101666s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 352413083 }, requested_resume: None })
[0.225149791s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5251308032))), payload: Terminal(Title(mteit@medelins-MacBook-Air:~)) })
[0.225164750s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5251308032))), payload: Terminal(Wakeup) })
[0.225181500s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5251308032)), event: RedrawRequested }
[0.226103541s] [INFO ] [alacritty] winit event: AboutToWait
[0.226141083s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 383283500 }, requested_resume: None })
[0.226462166s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5251308032))), payload: Frame })
[0.226482125s] [INFO ] [alacritty] winit event: AboutToWait
[0.227037625s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 383640375 }, requested_resume: None })
[0.227051500s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5251308032))), payload: Terminal(Wakeup) })
[0.227062541s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5251308032)), event: RedrawRequested }
[0.228256458s] [INFO ] [alacritty] winit event: AboutToWait
[0.228292750s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 385428833 }, requested_resume: Some(Instant { tv_sec: 80146, tv_nsec: 395101166 }) })
[0.228310750s] [INFO ] [alacritty] winit event: AboutToWait
[0.228696333s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 385469625 }, requested_resume: Some(Instant { tv_sec: 80146, tv_nsec: 395101166 }) })
[0.228725833s] [INFO ] [alacritty] winit event: AboutToWait
[0.238295375s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 80146, tv_nsec: 385885916 }, requested_resume: Instant { tv_sec: 80146, tv_nsec: 395101166 } })
[0.238327583s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5251308032))), payload: Terminal(Wakeup) })
[0.238340833s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5251308032))), payload: Terminal(Wakeup) })
[0.238350541s] [INFO ] [alacritty] winit event: AboutToWait
[0.238368791s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 395510791 }, requested_resume: None })
[0.238378833s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5251308032))), payload: Frame })
[0.238388125s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5251308032)), event: RedrawRequested }
[0.239050708s] [INFO ] [alacritty] winit event: AboutToWait
[0.239071166s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 396214458 }, requested_resume: Some(Instant { tv_sec: 80146, tv_nsec: 411767291 }) })
[0.239082833s] [INFO ] [alacritty] winit event: AboutToWait
[0.255687416s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 80146, tv_nsec: 396239958 }, requested_resume: Instant { tv_sec: 80146, tv_nsec: 411767291 } })
[0.255768833s] [INFO ] [alacritty] winit event: AboutToWait
[0.255788375s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 412932416 }, requested_resume: None })
[0.255804166s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5251308032))), payload: Frame })
[0.255814916s] [INFO ] [alacritty] winit event: AboutToWait
[0.255826375s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 412973625 }, requested_resume: None })
[0.255851208s] [INFO ] [alacritty] winit event: AboutToWait
[0.426683625s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 413008791 }, requested_resume: None })
[0.427407250s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5251308032)), event: KeyboardInput { device_id: DeviceId(DeviceId), event: KeyEvent { physical_key: Code(SuperLeft), logical_key: Named(Super), text: None, location: Left, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: None, key_without_modifiers: Named(Super) } }, is_synthetic: false } }
[0.427471000s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5251308032)), event: ModifiersChanged(Modifiers { state: ModifiersState(SUPER), pressed_mods: ModifiersKeys(LSUPER) }) }
[0.427511250s] [INFO ] [alacritty] winit event: AboutToWait
[0.534967125s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 584704083 }, requested_resume: None })
2024-03-03 00:02:14.295 alacritty[27088:647883] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
[0.545921041s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5251308032)), event: KeyboardInput { device_id: DeviceId(DeviceId), event: KeyEvent { physical_key: Code(KeyT), logical_key: Character("t"), text: Some("t"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("t"), key_without_modifiers: Character("t") } }, is_synthetic: false } }
[0.545986833s] [INFO ] [alacritty] winit event: AboutToWait
[0.546102958s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 703245000 }, requested_resume: None })
[0.546137458s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: None, payload: CreateWindow(WindowOptions { terminal_options: TerminalOptions { working_directory: Some("/Users/mteit"), hold: false, command: [] }, window_identity: WindowIdentity { title: None, class: None }, window_tabbing_id: Some("WinitWindow-WinitWindowDelegate-(null)-VT-"), option: [] }) })
[0.551461333s] [INFO ] [alacritty] Window scale factor: 2
[0.564209041s] [INFO ] [alacritty] Running on Apple M1
[0.564265291s] [INFO ] [alacritty] OpenGL version 4.1 Metal - 83.1, shader_version 4.10
[0.564288916s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.579051083s] [INFO ] [alacritty] Cell size: 20 x 45
[0.579136125s] [INFO ] [alacritty] Padding: 0 x 0
[0.579152625s] [INFO ] [alacritty] Width: 1800, Height: 1350
[0.603397500s] [INFO ] [alacritty] PTY dimensions: 30 x 90
[0.606166750s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5232411280)), event: Resized(PhysicalSize { width: 1600, height: 1200 }) }
[0.606215958s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5232411280)), event: Focused(false) }
[0.606237625s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5232411280)), event: Resized(PhysicalSize { width: 1800, height: 1350 }) }
[0.606253958s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5232411280)), event: Moved(PhysicalPosition { x: 1450, y: 500 }) }
[0.606277083s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5251308032)), event: ModifiersChanged(Modifiers { state: ModifiersState(0x0), pressed_mods: ModifiersKeys(0x0) }) }
[0.606297708s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5251308032)), event: Focused(false) }
[0.606312708s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5232411280)), event: Focused(true) }
[0.606328458s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5232411280)), event: RedrawRequested }
[0.608988916s] [INFO ] [alacritty] winit event: AboutToWait
[0.609170625s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 766187541 }, requested_resume: Some(Instant { tv_sec: 80146, tv_nsec: 782800416 }) })
[0.609747250s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5232411280)), event: RedrawRequested }
[0.613847916s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5251308032)), event: RedrawRequested }
[0.616936916s] [INFO ] [alacritty] winit event: AboutToWait
[0.616987333s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 774126333 }, requested_resume: Some(Instant { tv_sec: 80146, tv_nsec: 782800083 }) })
[0.617279000s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5251308032))), payload: Frame })
[0.617299208s] [INFO ] [alacritty] winit event: AboutToWait
[0.620497166s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 774460166 }, requested_resume: Some(Instant { tv_sec: 80146, tv_nsec: 782800083 }) })
[0.620658500s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5232411280)), event: ModifiersChanged(Modifiers { state: ModifiersState(SUPER), pressed_mods: ModifiersKeys(LSUPER) }) }
[0.620677208s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5232411280)), event: KeyboardInput { device_id: DeviceId(DeviceId), event: KeyEvent { physical_key: Code(KeyT), logical_key: Character("t"), text: None, location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("t"), key_without_modifiers: Character("t") } }, is_synthetic: false } }
[0.620699833s] [INFO ] [alacritty] winit event: AboutToWait
[0.626678000s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 80146, tv_nsec: 777864083 }, requested_resume: Instant { tv_sec: 80146, tv_nsec: 782800083 } })
[0.626714666s] [INFO ] [alacritty] winit event: AboutToWait
[0.626736083s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 783879291 }, requested_resume: None })
[0.626749125s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5232411280))), payload: Frame })
[0.626760458s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5232411280))), payload: Frame })
[0.626769458s] [INFO ] [alacritty] winit event: AboutToWait
[0.626780666s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 783927541 }, requested_resume: None })
[0.626791083s] [INFO ] [alacritty] winit event: AboutToWait
[0.628121375s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 783948958 }, requested_resume: None })
[0.628140166s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5232411280))), payload: Terminal(Wakeup) })
[0.628154333s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5232411280)), event: RedrawRequested }
[0.628714083s] [INFO ] [alacritty] winit event: AboutToWait
[0.628741500s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 785882291 }, requested_resume: Some(Instant { tv_sec: 80146, tv_nsec: 799466167 }) })
[0.628756041s] [INFO ] [alacritty] winit event: AboutToWait
[0.635104666s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 785915500 }, requested_resume: Some(Instant { tv_sec: 80146, tv_nsec: 799466167 }) })
[0.635188041s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5232411280)), event: Occluded(false) }
[0.635206250s] [INFO ] [alacritty] winit event: AboutToWait
[0.636883458s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 792369250 }, requested_resume: Some(Instant { tv_sec: 80146, tv_nsec: 799466167 }) })
[0.637039750s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5232411280)), event: ModifiersChanged(Modifiers { state: ModifiersState(0x0), pressed_mods: ModifiersKeys(0x0) }) }
[0.637068166s] [INFO ] [alacritty] winit event: AboutToWait
[0.642605708s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 80146, tv_nsec: 794231166 }, requested_resume: Instant { tv_sec: 80146, tv_nsec: 799466167 } })
[0.642642958s] [INFO ] [alacritty] winit event: AboutToWait
[0.642663375s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 799806958 }, requested_resume: None })
[0.642676166s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5232411280))), payload: Frame })
[0.642686083s] [INFO ] [alacritty] winit event: AboutToWait
[0.642695333s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 799842708 }, requested_resume: None })
[0.642704375s] [INFO ] [alacritty] winit event: AboutToWait
[0.706256750s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 799860500 }, requested_resume: None })
[0.707968166s] [INFO ] [alacritty] winit event: AboutToWait
[0.717111291s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 865132583 }, requested_resume: None })
[0.717760666s] [INFO ] [alacritty] winit event: AboutToWait
[0.720127666s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 874926708 }, requested_resume: None })
[0.720159125s] [INFO ] [alacritty] winit event: AboutToWait
[0.746097625s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 877321541 }, requested_resume: None })
[0.746142208s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5232411280))), payload: Terminal(Title(mteit@medelins-MacBook-Air:~)) })
[0.746159333s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5232411280))), payload: Terminal(Wakeup) })
[0.746172583s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5232411280)), event: RedrawRequested }
[0.747078833s] [INFO ] [alacritty] winit event: AboutToWait
[0.747112000s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 904253666 }, requested_resume: None })
[0.747452125s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5232411280))), payload: Frame })
[0.747473291s] [INFO ] [alacritty] winit event: AboutToWait
[0.748046000s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 904631583 }, requested_resume: None })
[0.748060666s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5232411280))), payload: Terminal(Wakeup) })
[0.748071583s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5232411280)), event: RedrawRequested }
[0.751209583s] [INFO ] [alacritty] winit event: AboutToWait
[0.751245125s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 908382958 }, requested_resume: Some(Instant { tv_sec: 80146, tv_nsec: 916128375 }) })
[0.751271708s] [INFO ] [alacritty] winit event: AboutToWait
[0.759222500s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 80146, tv_nsec: 908430583 }, requested_resume: Instant { tv_sec: 80146, tv_nsec: 916128375 } })
[0.759264000s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5232411280))), payload: Terminal(Wakeup) })
[0.759276958s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5232411280))), payload: Terminal(Wakeup) })
[0.759285250s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5232411280))), payload: Terminal(Wakeup) })
[0.759293750s] [INFO ] [alacritty] winit event: AboutToWait
[0.759328625s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 916467541 }, requested_resume: None })
[0.759338416s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5232411280))), payload: Frame })
[0.759348416s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5232411280)), event: RedrawRequested }
[0.760020708s] [INFO ] [alacritty] winit event: AboutToWait
[0.760044583s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 917186666 }, requested_resume: Some(Instant { tv_sec: 80146, tv_nsec: 932794208 }) })
[0.760058375s] [INFO ] [alacritty] winit event: AboutToWait
[0.776690166s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 80146, tv_nsec: 917215875 }, requested_resume: Instant { tv_sec: 80146, tv_nsec: 932794208 } })
[0.776725541s] [INFO ] [alacritty] winit event: AboutToWait
[0.776744416s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 933888083 }, requested_resume: None })
[0.776757708s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(5232411280))), payload: Frame })
[0.776767958s] [INFO ] [alacritty] winit event: AboutToWait
[0.776779166s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 933926125 }, requested_resume: None })
[0.776789541s] [INFO ] [alacritty] winit event: AboutToWait
[1.493150041s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80146, tv_nsec: 933947541 }, requested_resume: None })
[1.493399833s] [INFO ] [alacritty] winit event: AboutToWait
[1.493459875s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80147, tv_nsec: 650599916 }, requested_resume: None })
[1.501626458s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5232411280)), event: KeyboardInput { device_id: DeviceId(DeviceId), event: KeyEvent { physical_key: Code(SuperLeft), logical_key: Named(Super), text: None, location: Left, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: None, key_without_modifiers: Named(Super) } }, is_synthetic: false } }
[1.501801625s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5232411280)), event: ModifiersChanged(Modifiers { state: ModifiersState(SUPER), pressed_mods: ModifiersKeys(LSUPER) }) }
[1.501840000s] [INFO ] [alacritty] winit event: AboutToWait
[1.569030833s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80147, tv_nsec: 659053291 }, requested_resume: None })
[1.570275458s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5232411280)), event: KeyboardInput { device_id: DeviceId(DeviceId), event: KeyEvent { physical_key: Code(KeyT), logical_key: Character("t"), text: Some("t"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("t"), key_without_modifiers: Character("t") } }, is_synthetic: false } }
[1.570425208s] [INFO ] [alacritty] winit event: AboutToWait
[1.570651208s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 80147, tv_nsec: 727789625 }, requested_resume: None })
[1.570702541s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: None, payload: CreateWindow(WindowOptions { terminal_options: TerminalOptions { working_directory: Some("/Users/mteit"), hold: false, command: [] }, window_identity: WindowIdentity { title: None, class: None }, window_tabbing_id: Some("WinitWindow-WinitWindowDelegate-(null)-VT-"), option: [] }) })
[1.574069583s] [INFO ] [alacritty] Window scale factor: 2
[1.588624041s] [INFO ] [alacritty] Running on Apple M1
[1.588699708s] [INFO ] [alacritty] OpenGL version 4.1 Metal - 83.1, shader_version 4.10
[1.588723208s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[1.605101458s] [INFO ] [alacritty] Cell size: 20 x 45
[1.605172500s] [INFO ] [alacritty] Padding: 0 x 0
[1.605190875s] [INFO ] [alacritty] Width: 1800, Height: 1350
2024-03-03 00:02:15.372 alacritty[27088:647883] *** Assertion failure in -[WinitWindow titlebarAccessoryViewControllers], NSWindow.m:3682
fatal runtime error: Rust cannot catch foreign exceptions
[1]    27088 abort      ./alacritty --print-events
[0:02:15] ~/Develop/buid/alacritty/target/release/osx/Alacritty.app/Contents/MacOS on  master
[2] ƒ 
```
Config:
```
[0:18:36] ~/.config/alacritty
[2] ƒ cat alacritty.toml 
[window]
decorations = "None"
dimensions = { columns = 90, lines = 30 }
position = { x = 1450, y = 650 }

[colors.primary]
background = "0xfdf6e3"
foreground = "0x52676f"
[colors.cursor]
text = "0xffffff"
cursor = "0x000000"
[colors.selection]
text = "0xffffff"
background = "0x444444"
[colors.bright]
black = "0xffffd7"
blue = "0x808080"
cyan = "0x8a8a8a"
green = "0x585858"
magenta = "0x5f5f5f"
red = "0xd75f00"
white = "0x1c1c1c"
yellow = "0x626262"
[colors.normal]
black = "0xe4e4e4"
blue = "0x0087ff"
cyan = "0x00afaf"
green = "0x5f8700"
magenta = "0xaf005f"
red = "0xd70000"
white = "0x262626"
yellow = "0xaf8700"

[font]
size = 17
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Bold"
[font.bold]
family = "JetBrainsMono Nerd Font"
style = "ExtraBold"
[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"
[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "ExtraBold Italic"

[mouse]
hide_when_typing = true

[0:18:42] ~/.config/alacritty
[2] ƒ 
```

### PR DESCRIPTION
**Pull request by williamviktorsson**
Closes #7802, if decorations are set to None, a new window is created without attempting to attach to the previous tab.

If the attempt was made to connect to a previous tab, it didn't not connect, and Alacritty crashed on creating a 2nd tab.

With this change, windows still do not connect (as intended when decorations are off), but multiple new windows can be created without Alacrity crashing.

### CODE REVIEW

File: alacritty/src/input/mod.rs [hunk 1]
```diff
@@ -385,8 +387,13 @@ impl<T: EventListener> Execute<T> for Action {
...
             #[cfg(target_os = "macos")]
             Action::CreateNewTab => {
-                let tabbing_id = Some(ctx.window().tabbing_id());
-                ctx.create_new_window(tabbing_id);
+                // attatching new windows as tabs only work with decorations enabled
+                if ctx.config().window.decorations == Decorations::None {
+                    ctx.create_new_window(None);
+                } else {
+                    let tabbing_id = Some(ctx.window().tabbing_id());
+                    ctx.create_new_window(tabbing_id);
```
Comment (chrisduerr) [inline alacritty/src/input/mod.rs:395]: Is there a reason to create a new window here? If the user wanted to, they could bind that, right?

**Review by chrisduerr — CHANGES_REQUESTED** [review]
Missing changelog entry too.

File: alacritty/src/input/mod.rs (hunk 1 above)
Comment (williamviktorsson) [reply alacritty/src/input/mod.rs:395]: This code is same as the current code. I simply added the safeguard to not attempt to create the window with a tab id to avoid crashes.

**Comment by williamviktorsson** [comment]
I would like to add the consideration that perhaps the behaviour to add tabs should only be able when `decorations="full"` like this:

```rs
if ctx.config().window.decorations == Decorations::Full {
    let tabbing_id = Some(ctx.window().tabbing_id());
    ctx.create_new_window(tabbing_id);
} else {
    ctx.create_new_window(None);
}
```

For `decorations="transparent"` and `decorations="buttonless"` terminal contents clip through behind the tabs, and for None the application crashes as per https://github.com/alacritty/alacritty/issues/7802

Another decent option would be to accept this fix to avoid crashes, and add a config options such ass `enable_tabs` or similar.

**Comment by williamviktorsson** [comment]
> Missing changelog entry too.

Fixed I believe.

File: alacritty/src/input/mod.rs (hunk 1 above)
Comment (chrisduerr) [reply alacritty/src/input/mod.rs:395]: Yeah but why not no-op? The user didn't ask for a window.

**Comment by chrisduerr** [comment]
> For decorations="transparent" and decorations="buttonless" terminal contents clip through behind the tabs

That's kind of a separate issue so I'd be hesitant to try and work around it here. Realistically someone on macOS should just fix that by adding a way in winit to get the decoration height.

**Comment by williamviktorsson** [comment]
> > For decorations="transparent" and decorations="buttonless" terminal contents clip through behind the tabs
> 
> That's kind of a separate issue so I'd be hesitant to try and work around it here. Realistically someone on macOS should just fix that by adding a way in winit to get the decoration height.

Probably the better solution. How do you feel about the initial change, which avoids attempting to add tabs when it will result in a crash, like this:

```rs
if ctx.config().window.decorations == Decorations::None {
    ctx.create_new_window(None);
} else {
    let tabbing_id = Some(ctx.window().tabbing_id());
    ctx.create_new_window(tabbing_id);
}
```

**Comment by kchibisov** [comment]
Maybe we should just `no-op`?

File: alacritty/src/input/mod.rs (hunk 1 above)
Comment (williamviktorsson) [reply alacritty/src/input/mod.rs:393]: Now I understand, yes, if they asked for a tab, they shouldn't get a window. 

If they can't get a tab, the application shouldn't crash though.

Updated PR to reflect this.

File: alacritty/src/input/mod.rs [hunk 2]
```diff
@@ -385,8 +387,11 @@ impl<T: EventListener> Execute<T> for Action {
             Action::CreateNewWindow => ctx.create_new_window(None),
             #[cfg(target_os = "macos")]
             Action::CreateNewTab => {
-                let tabbing_id = Some(ctx.window().tabbing_id());
-                ctx.create_new_window(tabbing_id);
+                // tabs on macOS are not possible for decorations="none"
```
Comment (chrisduerr) [inline alacritty/src/input/mod.rs:390]:
```suggestion
                // Tabs on macOS are not possible without decorations.
```

File: CHANGELOG.md [hunk 3]
```diff
@@ -7,6 +7,11 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
 
 ## 0.14.0-dev
 
+### Fixed
+
+- Creating new tabs using `Cmd + T` on macOS is only enabled for decorations
+  set to full
```
Comment (chrisduerr) [inline CHANGELOG.md:13]:
```suggestion
- Crash when trying to create a new tab without decorations enabled
```

Should actually document what we fixed, not how we fixed it.

**Review by chrisduerr — CHANGES_REQUESTED** [review]

File: CHANGELOG.md (hunk 3 above)
Comment (williamviktorsson) [reply CHANGELOG.md]: My bad, a previous commit had this but I forgot it when I undid the formatting i accidentally committed.

File: CHANGELOG.md [hunk 4]
```diff
@@ -12,6 +12,8 @@ Notable changes to the `alacritty_terminal` crate are documented in its
 
 ### Fixed
 
+
```
Comment (chrisduerr) [inline CHANGELOG.md:15]:
```suggestion
```

**Review by chrisduerr — CHANGES_REQUESTED** [review]

**Review by chrisduerr — APPROVED** [review]
Thanks for the PR.
