### PR TITLE
Fix crash with large negative font offset

### LINKED ISSUE #4363: Crash when font: x: #someLargeNegativeNumber
Alacritty crashes when I set x offset of the font a large negative number like -10.

### System

OS: Linux
Version: 0.5.0
Linux/BSD: Manjaro MATE

### Logs

Crashes: SIGABRT

Font/Terminal size: Fullscreen, no decorations, Fira NERD Font:11, x:-10(yes), y:0
Keyboard and bindings: `alacritty --print-events`

Created log file at "/tmp/Alacritty-80782.log"
[2020-10-29 19:54:49.419330298] [INFO] Welcome to Alacritty
[2020-10-29 19:54:49.419424188] [INFO] Configuration loaded from "/home/ayb/.config/alacritty/alacritty.yml"
[2020-10-29 19:54:49.514412960] [INFO] Device pixel ratio: 1.001312255859375
[2020-10-29 19:54:49.520361420] [INFO] Initializing glyph cache...
[2020-10-29 19:54:49.576928628] [INFO] ... finished initializing glyph cache in 0.056511375s
[2020-10-29 19:54:49.576955261] [INFO] Cell Size: 1 x 18
[2020-10-29 19:54:49.576960889] [INFO] Padding: 0 x 0
[2020-10-29 19:54:49.576968556] [INFO] Width: 800, Height: 600
[2020-10-29 19:54:49.581499131] [INFO] PTY dimensions: Line(33) x Column(800)
[2020-10-29 19:54:49.603094211] [INFO] Initialisation complete
[2020-10-29 19:54:49.603125127] [INFO] glutin event: NewEvents(Init)
[2020-10-29 19:54:49.609036592] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(18))), event: Key(KeyboardInput { scancode: 28, state: Released, virtual_keycode: Some(Return), modifiers: (empty) }) }
[2020-10-29 19:54:49.609229717] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720258))), event: Resized(PhysicalSize { width: 800, height: 600 }) }
[2020-10-29 19:54:49.609241208] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720258))), event: Resized(PhysicalSize { width: 1920, height: 1028 }) }
[2020-10-29 19:54:49.609315672] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720258))), event: CursorEntered { device_id: DeviceId(X(DeviceId(2))) } }
[2020-10-29 19:54:49.609342122] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720258))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: PhysicalPosition { x: 913.0, y: 659.0 }, modifiers: (empty) } }
[2020-10-29 19:54:49.609353158] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720258))), event: Focused(true) }
[2020-10-29 19:54:49.609358212] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(58720258))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: PhysicalPosition { x: 913.0, y: 659.0 }, modifiers: (empty) } }
[2020-10-29 19:54:49.609384215] [INFO] glutin event: MainEventsCleared
[2020-10-29 19:54:49.609390052] [INFO] glutin event: RedrawRequested(WindowId(X(WindowId(58720258))))
[2020-10-29 19:54:49.609393898] [INFO] glutin event: RedrawEventsCleared
[2020-10-29 19:54:49.623089649] [INFO] Width: 1920, Height: 1028

### PR DESCRIPTION
**Pull request by chrisduerr**
Fixes #4363.

### CODE REVIEW

File: alacritty/src/cursor.rs [hunk 1]
```diff
@@ -15,10 +13,12 @@ pub fn get_cursor_glyph(
     cursor_thickness: f64,
 ) -> RasterizedGlyph {
     // Calculate the cell metrics.
-    let height = metrics.line_height as i32 + i32::from(offset_y);
-    let mut width = metrics.average_advance as i32 + i32::from(offset_x);
-
-    let line_width = cmp::max((cursor_thickness * f64::from(width)).round() as i32, 1);
```
Comment (nixpulvis) [inline alacritty/src/cursor.rs:21]: Just a small thing, but I personally have a much better time reading `max(x, y)` than I do `x.max(y)`. But it's not a problem if you really want to change it.

**Review by nixpulvis — APPROVED** [review]
Code makes sense to me, glad to see these `i32` types removed in more places. Thanks for leaving a note about `f64` clamping as well.

File: alacritty/src/cursor.rs (hunk 1 above)
Comment (chrisduerr) [reply alacritty/src/cursor.rs:21]: > Just a small thing, but I personally have a much better time reading max(x, y) than I do x.max(y). But it's not a problem if you really want to change it.

While I understand the sentiment, since I personally was confused the first time I read it, I'm not sure we want to set this as a policy. Generally methods do what they're documented to do, which is exactly what `.max()` does. It is also a shorthand that can reduce complexity when you know already what it does, since it is a good chunk shorter and takes just a single value. It's also used in multiple places in Alacritty already (including this file).

So I'd generally be against forcing the usage of `max(x, y)` over `x.max(y)`.

**Review by kchibisov — APPROVED** [review]
