### PR TITLE
Fix automatic scrolling on resize

### LINKED ISSUE #4944: Automatic scrolling breaks on resize
Since 58cae8f2edf44e6bf0721543c61edb57bdf7d776 there has been an issue where the viewport would get locked into place when the last line is longer than the new viewport width and thus broken onto a new line.

Since the viewport is kept in place, the new line is put below the viewport increasing the display offset to 1. But since we've been following the terminal output we now suddenly won't do that anymore. To a user it might look like the terminal suddenly "froze".

I think we should add a special case where we keep everything stuck at the bottom of the viewport if we're already at the bottom, just so we keep following all new output.

@st3iny you wrote the original PR, are you interested in looking into this?

### PR DESCRIPTION
**Pull request by st3iny**
Fixes #4944 

Only rotate viewport if it isn't scrolled. Please give this one a good test.

### CODE REVIEW

**Review by chrisduerr — CHANGES_REQUESTED** [review]
I've played around with this a little bit and honestly I think it might be better to just do `i < self.display_offset`.

It just feels somewhat more natural to see the new line visible when breaking when it is at the bottom, otherwise you're almost unsure if it's working properly or not.

The same thing applies to `grow_columns` too.

**Comment by st3iny** [comment]
Thanks for the feedback. Resizing looks less confusing now.

File: alacritty_terminal/src/grid/resize.rs [hunk 1]
```diff
@@ -355,7 +355,7 @@ impl<T: GridCell + Default + PartialEq + Clone> Grid<T> {
                     }
                     row = Row::from_vec(wrapped, occ);
 
-                    if i <= self.display_offset {
```
Comment (chrisduerr) [inline alacritty_terminal/src/grid/resize.rs:358]: I don't think the zero check is necessary anymore with this? Since both are a usize it's impossible for i to ever be smaller than the display offset if it is zero.

**Review by chrisduerr — CHANGES_REQUESTED** [review]

**Review by chrisduerr — APPROVED** [review]
Thanks.
