### PR TITLE
Fix padding update not updating renderer

### LINKED ISSUE #6502: Font size seems to be impacted by the padding setting
Changing the padding sometimes makes a bitmap font blurry:

https://user-images.githubusercontent.com/34467/201967909-d2178e98-2da1-4e8c-8a22-56f253f3b9bc.mp4

### System

OS: Linux (Arch, X11, i3)
Version: `alacritty 0.11.0 (8dbaa0bb)`

### Config

Minimal repro config:

```yml
font:
    normal:
        family: ProfontOTB
    bold:
        style: Regular
    size: 8.5

window:
    padding:
        x: 2
        y: 2
```

Font: https://tobiasjung.name/downloadfile.php?file=profont-otb-2.zip

### Logs

```
Created log file at "/tmp/Alacritty-26123.log"
[0.000033917s] [INFO ] [alacritty] Welcome to Alacritty
[0.000152819s] [INFO ] [alacritty] Version 0.11.0 (8dbaa0bb)
[0.000220521s] [INFO ] [alacritty] Running on X11
[0.001430871s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/ux/.config/alacritty/alacritty.yml"
[0.007340954s] [DEBUG] [alacritty] Loading "ProfontOTB" font
[0.033436695s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: MONOCHROME | TARGET_MONO, render_mode: "Mono", lcd_filter: 1 }
[0.035653558s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: MONOCHROME | TARGET_MONO, render_mode: "Mono", lcd_filter: 1 }
[0.037665566s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: MONOCHROME | TARGET_MONO, render_mode: "Mono", lcd_filter: 1 }
[0.039647422s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: MONOCHROME | TARGET_MONO, render_mode: "Mono", lcd_filter: 1 }
[0.040009205s] [DEBUG] [alacritty] Estimated scaling factor: 1
[0.040021640s] [DEBUG] [alacritty] Estimated window size: None
[0.040029392s] [DEBUG] [alacritty] Estimated cell size: 6 x 11
[0.102438997s] [INFO ] [alacritty] Running on Mesa Intel(R) Iris(R) Pro Graphics 580 (SKL GT4)
[0.102456981s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.111953282s] [INFO ] [alacritty] Display scale factor: 1
[0.111971745s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.120765688s] [INFO ] [alacritty] Cell size: 6 x 11
[0.120804104s] [INFO ] [alacritty] Padding: 2 x 2
[0.120811741s] [INFO ] [alacritty] Width: 800, Height: 600
[0.138505498s] [INFO ] [alacritty] PTY dimensions: 54 x 132
[0.141416507s] [INFO ] [alacritty] Initialisation complete
[0.145724491s] [DEBUG] [alacritty_terminal] New num_cols is 121 and num_lines is 46
[0.145842614s] [INFO ] [alacritty] Padding: 2 x 2
[0.145859583s] [INFO ] [alacritty] Width: 734, Height: 511
[0.184364773s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }

# Remove window 2x2 padding
[14.424131546s] [DEBUG] [alacritty] Reloading configuration file: "/home/ux/dotfiles/desktop/.config/alacritty/alacritty.yml"
[14.425456483s] [DEBUG] [alacritty_terminal] New num_cols is 122 and num_lines is 46

# Restore window 2x2 padding
[25.592280304s] [DEBUG] [alacritty] Reloading configuration file: "/home/ux/dotfiles/desktop/.config/alacritty/alacritty.yml"
[25.593488408s] [DEBUG] [alacritty_terminal] New num_cols is 121 and num_lines is 46

# Profont size 8.5 to 9
[37.168796363s] [DEBUG] [alacritty] Reloading configuration file: "/home/ux/dotfiles/desktop/.config/alacritty/alacritty.yml"
[37.187579592s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: MONOCHROME | TARGET_MONO, render_mode: "Mono", lcd_filter: 1 }
[37.205977656s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: MONOCHROME | TARGET_MONO, render_mode: "Mono", lcd_filter: 1 }
[37.209463367s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: MONOCHROME | TARGET_MONO, render_mode: "Mono", lcd_filter: 1 }
[37.227316023s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: MONOCHROME | TARGET_MONO, render_mode: "Mono", lcd_filter: 1 }
[37.228071753s] [INFO ] [alacritty] Font size changed to Size(18) with scale factor of 1
[37.228095417s] [INFO ] [alacritty] Cell size: 6 x 12
[37.228122615s] [DEBUG] [alacritty_terminal] New num_cols is 121 and num_lines is 42
[37.250158814s] [INFO ] [alacritty] Padding: 2 x 2
[37.250185559s] [INFO ] [alacritty] Width: 734, Height: 511
[37.250408981s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }

# Remove window 2x2 padding
[49.901855371s] [DEBUG] [alacritty] Reloading configuration file: "/home/ux/dotfiles/desktop/.config/alacritty/alacritty.yml"
[49.902182063s] [DEBUG] [alacritty_terminal] New num_cols is 122 and num_lines is 42
```

### PR DESCRIPTION
**Pull request by chrisduerr**
This fixes an issue where it was possible to update the padding of the terminal without actually queueing an update for the renderer projection, leading to a blurry projection.

Closes #6502.

### CODE REVIEW

File: alacritty/src/display/mod.rs [hunk 1]
```diff
@@ -637,6 +634,14 @@ impl Display {
             config.window.dynamic_padding,
         );
 
+        // Queue renderer update if terminal dimensions/padding changed.
+        if new_size != self.size_info {
```
Comment (kchibisov) [inline alacritty/src/display/mod.rs:638]: You should compare after reserve lines I think, since it mutates terminfo, so it could be the same here, but reserve lines make it different.

See `self.size_info.reserve_lines(message_bar_lines + search_lines);`, it also mutates the `self.size_info`.

File: alacritty/src/display/mod.rs [hunk 2]
```diff
@@ -637,6 +634,14 @@ impl Display {
...
+            let renderer_update = self.pending_renderer_update.get_or_insert(Default::default());
+            renderer_update.resize = true;
```
Comment (kchibisov) [inline alacritty/src/display/mod.rs:640]: It's not a resize anymore, since size could be the same, so something to `size_info` should be used.

File: CHANGELOG.md [hunk 3]
```diff
@@ -19,6 +19,7 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
 - Crash with `OT-SVG` fonts on Linux/BSD
 - Crash during text compose on old GNOME under Wayland
 - Mouse cursor staying hidden after window regains focus on macOS Ventura
+- Blurry fonts when changing padding size at runtime
```
Comment (kchibisov) [inline CHANGELOG.md:22]: It's not about fonts in the end, but general issue.

Maybe something like that, but blurry fonts is fine.
```suggestion
- Terminal becomes inconsistent when changing only padding
```

**Review by kchibisov — CHANGES_REQUESTED** [review]

File: alacritty/src/display/mod.rs (hunk 2 above)
Comment (chrisduerr) [reply alacritty/src/display/mod.rs:640]: What do you mean?

File: CHANGELOG.md (hunk 3 above)
Comment (chrisduerr) [reply CHANGELOG.md:22]: I mean fonts is the only thing we do. I think it's best to document what the user experiences, so they understand what bug was fixed.

We gain nothing by having overly detailed technical changelogs when the user then has no clue what it is about.

File: alacritty/src/display/mod.rs (hunk 2 above)
Comment (kchibisov) [reply alacritty/src/display/mod.rs:640]: I mean that `render_update.resize` should be named `render_update.size_info_changed`, since resize is about dimensions but we could have a change without dimensions change.

Comment (chrisduerr) [reply alacritty/src/display/mod.rs:640]: I think it's fine since it determines if a resize should be done, not that something was resized.

File: alacritty/src/display/mod.rs [hunk 4]
```diff
@@ -638,16 +635,22 @@ impl Display {
...
         // Resize terminal.
-        terminal.resize(self.size_info);
+        terminal.resize(new_size);
+
+        // Queue renderer update if terminal dimensions/padding changed.
+        if new_size != self.size_info {
+            let renderer_update = self.pending_renderer_update.get_or_insert(Default::default());
+            renderer_update.resize = true;
+        }
+        self.size_info = new_size;
```
Comment (kchibisov) [inline alacritty/src/display/mod.rs:653]: Could save extra copy here, but I don't really care.

**Review by kchibisov — APPROVED** [review]
After fixing CI should be good to go.
