### PR TITLE
Fix hint binding IPC overrides

### LINKED ISSUE #8568: Setting hints with `alacritty msg` doesn't update keyboard bindings
Hey!

Currently when using `alacritty msg config` to update hints, it doesn't update the keyboard shortcuts. 

To reproduce, start an alacritty and run:

```
$ # my-tag 
$ alacritty msg config 'hints.enabled = [ { command = "my-command", hyperlinks = true, post_processing = false, mouse.enabled = true, binding = { key = "M", mods = "Control|Shift" }, regex = "my-tag" } ]'
```
You'll notice that `Control+Shift+M` doesn't show my-tag as possible targets, however cursor hover will still work. 

Alacritty version: 0.15.0

### PR DESCRIPTION
**Pull request by chrisduerr**
This fixes an issue where changes made to the bindings of a hint through IPC were completely ignored, since the hint key bindings were only generated on config load without regeneration on IPC config override.

While it would be possible to just filter out remove hint key bindings based on their action and then repopulate them on IPC config reload, this solution would be quite hacky.

To have a better distinction between traditional and hint key bindings, the two have been entirely separated and hint bindings are just converted to key bindings on demand. This allows easily replacing the entire hint array without any post-processing, making it simpler to maintain for future changes.

Closes #8568.

### CODE REVIEW

File: alacritty/src/input/keyboard.rs [hunk 1]
```diff
@@ -218,7 +217,30 @@ impl<T: EventListener, A: ActionContext<T>> Processor<T, A> {
...
+        for i in 0..self.ctx.config().hints.enabled.len() {
+            let hint = &self.ctx.config().hints.enabled[i];
+            let binding = match hint.binding.as_ref() {
+                Some(binding) => binding.key_binding(&hint),
+                None => continue,
+            };
+
+            if let Some(action) = binding_action(binding) {
+                action.execute(&mut self.ctx);
             }
```
Comment (nixpulvis) [inline alacritty/src/input/keyboard.rs:244]: You could incorporate the conditional and execute parts into the helper closure I believe.

Comment (chrisduerr) [reply alacritty/src/input/keyboard.rs:244]: No, because that would pass a reference (binding) and mutable reference (self.ctx).

**Review by kchibisov — CHANGES_REQUESTED** [review]
I think that actually changes semantics we had up until now? So the `hints` and regular bindings no longer in the conflict?

We can also suppress one over the other that way now, like if you bind the key that matches the hint, we can disable the key if the binding was not triggered.

In general, that should be documented in changelog, since it changes semantics.

**Comment by chrisduerr** [comment]
> I think that actually changes semantics we had up until now? So the hints and regular bindings no longer in the conflict?

Were they in conflict before? We just called `.insert`, which suggests they were not? We always trigger all matching bindings, not just the first one. The only way overrides work is with the default bindings right now, which are explicitly removed. I don't see this happening for hints before.

**Review by kchibisov — CHANGES_REQUESTED** [review]
Need manual debug impl, otherwise it's recursive. 

```
diff --git a/alacritty/src/config/ui_config.rs b/alacritty/src/config/ui_config.rs
index 0ed40b9b..6939f860 100644
--- a/alacritty/src/config/ui_config.rs
+++ b/alacritty/src/config/ui_config.rs
@@ -441,7 +441,7 @@ impl<'de> Deserialize<'de> for HintContent {
 }

 /// Binding for triggering a keyboard hint.
-#[derive(Deserialize, Clone, Debug, PartialEq, Eq)]
+#[derive(Deserialize, Clone, PartialEq, Eq)]
 #[serde(deny_unknown_fields)]
 pub struct HintBinding {
     pub key: BindingKey,
@@ -468,6 +468,16 @@ impl HintBinding {
     }
 }

+impl fmt::Debug for HintBinding {
+    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
+        f.debug_struct("HintBinding")
+            .field("key", &self.key)
+            .field("mods", &self.mods)
+            .field("mode", &self.mode)
+            .finish()
+    }
+}
+
 /// Hint mouse highlighting.
 #[derive(ConfigDeserialize, Default, Copy, Clone, Debug, PartialEq, Eq)]
 pub struct HintMouse {
```

**Review by kchibisov — APPROVED** [review]
should be good once CI fixed.
