### PR TITLE
Fix crash due to wrong drop order of clipboard

### LINKED ISSUE #7309: SIGSEGV at exit on master (80d4dac)
Alacritty crashes (SIGSEGV) on exit

This issue was introduced with 80d4dac

The underlying issue is that the `zwp_primary_selection_device_manager_v1` object seen in the backtrace is destroyed after the wayland connection is here: https://github.com/Smithay/wayland-rs/blob/8581b9d298e3bfc872a598380a09eb386a9db408/wayland-backend/src/sys/client_impl/mod.rs#L1022

### System

OS: Arch Linux (6.5.8-arch1-1)
Version: alacritty 0.13.0-dev (80d4dac)
Linux: sway, Wayland

### Logs

Backtrace:
```
#0  0x00007ffff7fb7415 in wl_map_insert_at (map=map@entry=0x55555696c9b0, flags=flags@entry=1, i=29, data=<optimized out>) at ../wayland-1.22.0/src/wayland-util.c:276
#1  0x00007ffff7fb7573 in proxy_destroy (proxy=proxy@entry=0x7fffe00040c0) at ../wayland-1.22.0/src/wayland-client.c:538
#2  0x00007ffff7fb76bf in wl_proxy_destroy_caller_locks (proxy=0x7fffe00040c0) at ../wayland-1.22.0/src/wayland-client.c:562
#3  wl_proxy_destroy (proxy=0x7fffe00040c0) at ../wayland-1.22.0/src/wayland-client.c:585
#4  0x00005555563f3db3 in wayland_backend::sys::client_impl::InnerBackend::send_request (self=0x7ffff709ad80, data=..., child_spec=...) at src/sys/client_impl/mod.rs:739
#5  0x00005555563fa240 in wayland_backend::sys::client::Backend::send_request (self=0x7ffff709ad80, msg=<error reading variable: Cannot access memory at address 0x12>, data=..., child_spec=...)
    at src/sys/../client_api.rs:234
#6  0x00005555563766b5 in wayland_client::conn::Connection::send_request<wayland_protocols::wp::primary_selection::zv1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1> (self=0x7ffff709ad80, proxy=0x7ffff709b1f0, request=..., data=...) at /home/robin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-client-0.31.1/src/conn.rs:204
#7  0x0000555556398d51 in wayland_protocols::wp::primary_selection::zv1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1::destroy (self=0x7ffff709b1f0)
    at src/protocol_macro.rs:28
#8  0x000055555633485b in smithay_client_toolkit::primary_selection::{impl#1}::drop (self=0x7ffff709b1f0) at src/primary_selection/mod.rs:80
#9  0x0000555555b70dc7 in core::ptr::drop_in_place<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState> () at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ptr/mod.rs:497
#10 0x0000555555b6cc46 in core::ptr::drop_in_place<core::option::Option<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState>> ()
    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ptr/mod.rs:497
#11 0x0000555555b6f69e in core::ptr::drop_in_place<smithay_clipboard::state::State> () at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ptr/mod.rs:497
#12 0x0000555555b41a25 in smithay_clipboard::worker::worker_impl (connection=..., rx_chan=..., reply_tx=...) at src/worker.rs:104
#13 0x0000555555b41450 in smithay_clipboard::worker::spawn::{closure#0} () at src/worker.rs:23
#14 0x0000555555b2fb09 in std::sys_common::backtrace::__rust_begin_short_backtrace<smithay_clipboard::worker::spawn::{closure_env#0}, ()> (f=...)
    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:154
#15 0x0000555555b3905d in std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure#0}<smithay_clipboard::worker::spawn::{closure_env#0}, ()> ()
    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/thread/mod.rs:529
#16 0x0000555555b4a8b1 in core::panic::unwind_safe::{impl#23}::call_once<(), std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<smithay_clipboard::worker::spawn::{closure_env#0}, ()>> (
    self=...) at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panic/unwind_safe.rs:271
#17 0x0000555555b573bb in std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<smithay_clipboard::worker::spawn::{closure_env#0}, ()>>, ()> (data=0x7ffff709ba60) at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502
#18 0x0000555555b5cf1b in __rust_try ()
#19 0x0000555555b572b2 in std::panicking::try<(), core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<smithay_clipboard::worker::spawn::{closure_env#0}, ()>>> (f=...) at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466
#20 0x0000555555b38ea1 in std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<smithay_clipboard::worker::spawn::{closure_env#0}, ()>>, ()> (f=...) at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142
#21 std::thread::{impl#0}::spawn_unchecked_::{closure#1}<smithay_clipboard::worker::spawn::{closure_env#0}, ()> () at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/thread/mod.rs:528
#22 0x0000555555b6be5f in core::ops::function::FnOnce::call_once<std::thread::{impl#0}::spawn_unchecked_::{closure_env#1}<smithay_clipboard::worker::spawn::{closure_env#0}, ()>, ()> ()
    at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250
#23 0x000055555650a9e5 in alloc::boxed::{impl#47}::call_once<(), dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global> (self=..., args=<optimized out>) at library/alloc/src/boxed.rs:2007
#24 alloc::boxed::{impl#47}::call_once<(), alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>, alloc::alloc::Global> (self=0x555556982030, args=<optimized out>)
    at library/alloc/src/boxed.rs:2007
#25 std::sys::unix::thread::{impl#2}::new::thread_start (main=0x555556982030) at library/std/src/sys/unix/thread.rs:108
#26 0x00007ffff7c179eb in start_thread (arg=<optimized out>) at pthread_create.c:444
#27 0x00007ffff7c9b7cc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

Relevant Valgrind output:
```
==10704== Thread 5 smithay-clipboa:
==10704== Invalid read of size 4
==10704==    at 0x4B37DB4: pthread_mutex_lock@@GLIBC_2.2.5 (pthread_mutex_lock.c:80)
==10704==    by 0x485D81C: wl_display_cancel_read (wayland-client.c:1898)
==10704==    by 0xFA5B4C: <wayland_backend::sys::client_impl::InnerReadEventsGuard as core::ops::drop::Drop>::drop (mod.rs:466)
==10704==    by 0xFBAA16: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerReadEventsGuard> (mod.rs:497)
==10704==    by 0xF98E7A: core::ptr::drop_in_place<wayland_backend::sys::client::ReadEventsGuard> (mod.rs:497)
==10704==    by 0x725092: core::ptr::drop_in_place<core::option::Option<wayland_backend::sys::client::ReadEventsGuard>> (mod.rs:497)
==10704==    by 0x6D03CD: <calloop_wayland_source::WaylandSource<D> as calloop::sources::EventSource>::before_handle_events (lib.rs:219)
==10704==    by 0x7134D4: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::before_handle_events (mod.rs:388)
==10704==    by 0x6CBD62: calloop::loop_logic::EventLoop<Data>::dispatch_events (loop_logic.rs:414)
==10704==    by 0x6CCB68: calloop::loop_logic::EventLoop<Data>::dispatch (loop_logic.rs:554)
==10704==    by 0x6F59ED: smithay_clipboard::worker::worker_impl (worker.rs:98)
==10704==    by 0x6F544F: smithay_clipboard::worker::spawn::{{closure}} (worker.rs:23)
==10704==  Address 0x5086548 is 296 bytes inside a block of size 376 free'd
==10704==    at 0x484412F: free (vg_replace_malloc.c:974)
==10704==    by 0xFABC35: <wayland_backend::sys::client_impl::ConnectionState as core::ops::drop::Drop>::drop (mod.rs:1022)
==10704==    by 0xFBA826: core::ptr::drop_in_place<wayland_backend::sys::client_impl::ConnectionState> (mod.rs:497)
==10704==    by 0xFB9D4A: core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFB9D9E: core::ptr::drop_in_place<std::sync::mutex::Mutex<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFBA61A: core::ptr::drop_in_place<wayland_backend::sys::client_impl::Inner> (mod.rs:497)
==10704==    by 0xF9FDDE: alloc::sync::Arc<T,A>::drop_slow (sync.rs:1749)
==10704==    by 0xFA04B4: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop (sync.rs:2405)
==10704==    by 0xFBAACA: core::ptr::drop_in_place<alloc::sync::Arc<wayland_backend::sys::client_impl::Inner>> (mod.rs:497)
==10704==    by 0xFBA6EA: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerBackend> (mod.rs:497)
==10704==    by 0xFBA56A: core::ptr::drop_in_place<wayland_backend::sys::client::Backend> (mod.rs:497)
==10704==    by 0xF98ABA: core::ptr::drop_in_place<wayland_client::conn::Connection> (mod.rs:497)
==10704==  Block was alloc'd at
==10704==    at 0x48469B3: calloc (vg_replace_malloc.c:1554)
==10704==    by 0x4860D95: UnknownInlinedFun (wayland-private.h:234)
==10704==    by 0x4860D95: wl_display_connect_to_fd (wayland-client.c:1183)
==10704==    by 0xFA3FE5: wayland_backend::sys::client_impl::InnerBackend::connect (mod.rs:228)
==10704==    by 0xFAE1A9: wayland_backend::sys::client::Backend::connect (client_api.rs:164)
==10704==    by 0xF7B13C: wayland_client::conn::Connection::connect_to_env (conn.rs:92)
==10704==    by 0x3D7E80: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new (mod.rs:81)
==10704==    by 0x472DA9: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread (mod.rs:793)
==10704==    by 0x4730CC: winit::platform_impl::platform::EventLoop<T>::new (mod.rs:785)
==10704==    by 0x4B4DAC: winit::event_loop::EventLoopBuilder<T>::build (event_loop.rs:128)
==10704==    by 0x495924: alacritty::alacritty (main.rs:129)
==10704==    by 0x495049: alacritty::main (main.rs:85)
==10704==    by 0x4BFCAA: core::ops::function::FnOnce::call_once (function.rs:250)
==10704==
==10704== Invalid read of size 4
==10704==    at 0x4B376BD: __pthread_mutex_lock_full (pthread_mutex_lock.c:198)
==10704==    by 0x485D81C: wl_display_cancel_read (wayland-client.c:1898)
==10704==    by 0xFA5B4C: <wayland_backend::sys::client_impl::InnerReadEventsGuard as core::ops::drop::Drop>::drop (mod.rs:466)
==10704==    by 0xFBAA16: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerReadEventsGuard> (mod.rs:497)
==10704==    by 0xF98E7A: core::ptr::drop_in_place<wayland_backend::sys::client::ReadEventsGuard> (mod.rs:497)
==10704==    by 0x725092: core::ptr::drop_in_place<core::option::Option<wayland_backend::sys::client::ReadEventsGuard>> (mod.rs:497)
==10704==    by 0x6D03CD: <calloop_wayland_source::WaylandSource<D> as calloop::sources::EventSource>::before_handle_events (lib.rs:219)
==10704==    by 0x7134D4: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::before_handle_events (mod.rs:388)
==10704==    by 0x6CBD62: calloop::loop_logic::EventLoop<Data>::dispatch_events (loop_logic.rs:414)
==10704==    by 0x6CCB68: calloop::loop_logic::EventLoop<Data>::dispatch (loop_logic.rs:554)
==10704==    by 0x6F59ED: smithay_clipboard::worker::worker_impl (worker.rs:98)
==10704==    by 0x6F544F: smithay_clipboard::worker::spawn::{{closure}} (worker.rs:23)
==10704==  Address 0x5086548 is 296 bytes inside a block of size 376 free'd
==10704==    at 0x484412F: free (vg_replace_malloc.c:974)
==10704==    by 0xFABC35: <wayland_backend::sys::client_impl::ConnectionState as core::ops::drop::Drop>::drop (mod.rs:1022)
==10704==    by 0xFBA826: core::ptr::drop_in_place<wayland_backend::sys::client_impl::ConnectionState> (mod.rs:497)
==10704==    by 0xFB9D4A: core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFB9D9E: core::ptr::drop_in_place<std::sync::mutex::Mutex<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFBA61A: core::ptr::drop_in_place<wayland_backend::sys::client_impl::Inner> (mod.rs:497)
==10704==    by 0xF9FDDE: alloc::sync::Arc<T,A>::drop_slow (sync.rs:1749)
==10704==    by 0xFA04B4: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop (sync.rs:2405)
==10704==    by 0xFBAACA: core::ptr::drop_in_place<alloc::sync::Arc<wayland_backend::sys::client_impl::Inner>> (mod.rs:497)
==10704==    by 0xFBA6EA: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerBackend> (mod.rs:497)
==10704==    by 0xFBA56A: core::ptr::drop_in_place<wayland_backend::sys::client::Backend> (mod.rs:497)
==10704==    by 0xF98ABA: core::ptr::drop_in_place<wayland_client::conn::Connection> (mod.rs:497)
==10704==  Block was alloc'd at
==10704==    at 0x48469B3: calloc (vg_replace_malloc.c:1554)
==10704==    by 0x4860D95: UnknownInlinedFun (wayland-private.h:234)
==10704==    by 0x4860D95: wl_display_connect_to_fd (wayland-client.c:1183)
==10704==    by 0xFA3FE5: wayland_backend::sys::client_impl::InnerBackend::connect (mod.rs:228)
==10704==    by 0xFAE1A9: wayland_backend::sys::client::Backend::connect (client_api.rs:164)
==10704==    by 0xF7B13C: wayland_client::conn::Connection::connect_to_env (conn.rs:92)
==10704==    by 0x3D7E80: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new (mod.rs:81)
==10704==    by 0x472DA9: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread (mod.rs:793)
==10704==    by 0x4730CC: winit::platform_impl::platform::EventLoop<T>::new (mod.rs:785)
==10704==    by 0x4B4DAC: winit::event_loop::EventLoopBuilder<T>::build (event_loop.rs:128)
==10704==    by 0x495924: alacritty::alacritty (main.rs:129)
==10704==    by 0x495049: alacritty::main (main.rs:85)
==10704==    by 0x4BFCAA: core::ops::function::FnOnce::call_once (function.rs:250)
==10704==
==10704== Invalid read of size 4
==10704==    at 0x485D81D: UnknownInlinedFun (wayland-client.c:1698)
==10704==    by 0x485D81D: wl_display_cancel_read (wayland-client.c:1900)
==10704==    by 0xFA5B4C: <wayland_backend::sys::client_impl::InnerReadEventsGuard as core::ops::drop::Drop>::drop (mod.rs:466)
==10704==    by 0xFBAA16: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerReadEventsGuard> (mod.rs:497)
==10704==    by 0xF98E7A: core::ptr::drop_in_place<wayland_backend::sys::client::ReadEventsGuard> (mod.rs:497)
==10704==    by 0x725092: core::ptr::drop_in_place<core::option::Option<wayland_backend::sys::client::ReadEventsGuard>> (mod.rs:497)
==10704==    by 0x6D03CD: <calloop_wayland_source::WaylandSource<D> as calloop::sources::EventSource>::before_handle_events (lib.rs:219)
==10704==    by 0x7134D4: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::before_handle_events (mod.rs:388)
==10704==    by 0x6CBD62: calloop::loop_logic::EventLoop<Data>::dispatch_events (loop_logic.rs:414)
==10704==    by 0x6CCB68: calloop::loop_logic::EventLoop<Data>::dispatch (loop_logic.rs:554)
==10704==    by 0x6F59ED: smithay_clipboard::worker::worker_impl (worker.rs:98)
==10704==    by 0x6F544F: smithay_clipboard::worker::spawn::{{closure}} (worker.rs:23)
==10704==    by 0x6E3B08: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:154)
==10704==  Address 0x5086560 is 320 bytes inside a block of size 376 free'd
==10704==    at 0x484412F: free (vg_replace_malloc.c:974)
==10704==    by 0xFABC35: <wayland_backend::sys::client_impl::ConnectionState as core::ops::drop::Drop>::drop (mod.rs:1022)
==10704==    by 0xFBA826: core::ptr::drop_in_place<wayland_backend::sys::client_impl::ConnectionState> (mod.rs:497)
==10704==    by 0xFB9D4A: core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFB9D9E: core::ptr::drop_in_place<std::sync::mutex::Mutex<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFBA61A: core::ptr::drop_in_place<wayland_backend::sys::client_impl::Inner> (mod.rs:497)
==10704==    by 0xF9FDDE: alloc::sync::Arc<T,A>::drop_slow (sync.rs:1749)
==10704==    by 0xFA04B4: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop (sync.rs:2405)
==10704==    by 0xFBAACA: core::ptr::drop_in_place<alloc::sync::Arc<wayland_backend::sys::client_impl::Inner>> (mod.rs:497)
==10704==    by 0xFBA6EA: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerBackend> (mod.rs:497)
==10704==    by 0xFBA56A: core::ptr::drop_in_place<wayland_backend::sys::client::Backend> (mod.rs:497)
==10704==    by 0xF98ABA: core::ptr::drop_in_place<wayland_client::conn::Connection> (mod.rs:497)
==10704==  Block was alloc'd at
==10704==    at 0x48469B3: calloc (vg_replace_malloc.c:1554)
==10704==    by 0x4860D95: UnknownInlinedFun (wayland-private.h:234)
==10704==    by 0x4860D95: wl_display_connect_to_fd (wayland-client.c:1183)
==10704==    by 0xFA3FE5: wayland_backend::sys::client_impl::InnerBackend::connect (mod.rs:228)
==10704==    by 0xFAE1A9: wayland_backend::sys::client::Backend::connect (client_api.rs:164)
==10704==    by 0xF7B13C: wayland_client::conn::Connection::connect_to_env (conn.rs:92)
==10704==    by 0x3D7E80: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new (mod.rs:81)
==10704==    by 0x472DA9: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread (mod.rs:793)
==10704==    by 0x4730CC: winit::platform_impl::platform::EventLoop<T>::new (mod.rs:785)
==10704==    by 0x4B4DAC: winit::event_loop::EventLoopBuilder<T>::build (event_loop.rs:128)
==10704==    by 0x495924: alacritty::alacritty (main.rs:129)
==10704==    by 0x495049: alacritty::main (main.rs:85)
==10704==    by 0x4BFCAA: core::ops::function::FnOnce::call_once (function.rs:250)
==10704==
==10704== Invalid read of size 4
==10704==    at 0x485D83F: UnknownInlinedFun (wayland-client.c:133)
==10704==    by 0x485D83F: UnknownInlinedFun (wayland-client.c:1700)
==10704==    by 0x485D83F: UnknownInlinedFun (wayland-client.c:1696)
==10704==    by 0x485D83F: wl_display_cancel_read (wayland-client.c:1900)
==10704==    by 0xFA5B4C: <wayland_backend::sys::client_impl::InnerReadEventsGuard as core::ops::drop::Drop>::drop (mod.rs:466)
==10704==    by 0xFBAA16: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerReadEventsGuard> (mod.rs:497)
==10704==    by 0xF98E7A: core::ptr::drop_in_place<wayland_backend::sys::client::ReadEventsGuard> (mod.rs:497)
==10704==    by 0x725092: core::ptr::drop_in_place<core::option::Option<wayland_backend::sys::client::ReadEventsGuard>> (mod.rs:497)
==10704==    by 0x6D03CD: <calloop_wayland_source::WaylandSource<D> as calloop::sources::EventSource>::before_handle_events (lib.rs:219)
==10704==    by 0x7134D4: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::before_handle_events (mod.rs:388)
==10704==    by 0x6CBD62: calloop::loop_logic::EventLoop<Data>::dispatch_events (loop_logic.rs:414)
==10704==    by 0x6CCB68: calloop::loop_logic::EventLoop<Data>::dispatch (loop_logic.rs:554)
==10704==    by 0x6F59ED: smithay_clipboard::worker::worker_impl (worker.rs:98)
==10704==    by 0x6F544F: smithay_clipboard::worker::spawn::{{closure}} (worker.rs:23)
==10704==    by 0x6E3B08: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:154)
==10704==  Address 0x5086564 is 324 bytes inside a block of size 376 free'd
==10704==    at 0x484412F: free (vg_replace_malloc.c:974)
==10704==    by 0xFABC35: <wayland_backend::sys::client_impl::ConnectionState as core::ops::drop::Drop>::drop (mod.rs:1022)
==10704==    by 0xFBA826: core::ptr::drop_in_place<wayland_backend::sys::client_impl::ConnectionState> (mod.rs:497)
==10704==    by 0xFB9D4A: core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFB9D9E: core::ptr::drop_in_place<std::sync::mutex::Mutex<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFBA61A: core::ptr::drop_in_place<wayland_backend::sys::client_impl::Inner> (mod.rs:497)
==10704==    by 0xF9FDDE: alloc::sync::Arc<T,A>::drop_slow (sync.rs:1749)
==10704==    by 0xFA04B4: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop (sync.rs:2405)
==10704==    by 0xFBAACA: core::ptr::drop_in_place<alloc::sync::Arc<wayland_backend::sys::client_impl::Inner>> (mod.rs:497)
==10704==    by 0xFBA6EA: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerBackend> (mod.rs:497)
==10704==    by 0xFBA56A: core::ptr::drop_in_place<wayland_backend::sys::client::Backend> (mod.rs:497)
==10704==    by 0xF98ABA: core::ptr::drop_in_place<wayland_client::conn::Connection> (mod.rs:497)
==10704==  Block was alloc'd at
==10704==    at 0x48469B3: calloc (vg_replace_malloc.c:1554)
==10704==    by 0x4860D95: UnknownInlinedFun (wayland-private.h:234)
==10704==    by 0x4860D95: wl_display_connect_to_fd (wayland-client.c:1183)
==10704==    by 0xFA3FE5: wayland_backend::sys::client_impl::InnerBackend::connect (mod.rs:228)
==10704==    by 0xFAE1A9: wayland_backend::sys::client::Backend::connect (client_api.rs:164)
==10704==    by 0xF7B13C: wayland_client::conn::Connection::connect_to_env (conn.rs:92)
==10704==    by 0x3D7E80: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new (mod.rs:81)
==10704==    by 0x472DA9: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread (mod.rs:793)
==10704==    by 0x4730CC: winit::platform_impl::platform::EventLoop<T>::new (mod.rs:785)
==10704==    by 0x4B4DAC: winit::event_loop::EventLoopBuilder<T>::build (event_loop.rs:128)
==10704==    by 0x495924: alacritty::alacritty (main.rs:129)
==10704==    by 0x495049: alacritty::main (main.rs:85)
==10704==    by 0x4BFCAA: core::ops::function::FnOnce::call_once (function.rs:250)
==10704==
==10704== Invalid read of size 4
==10704==    at 0x4B33133: pthread_cond_broadcast@@GLIBC_2.3.2 (pthread_cond_broadcast.c:42)
==10704==    by 0x485D84B: UnknownInlinedFun (wayland-client.c:135)
==10704==    by 0x485D84B: UnknownInlinedFun (wayland-client.c:1700)
==10704==    by 0x485D84B: UnknownInlinedFun (wayland-client.c:1696)
==10704==    by 0x485D84B: wl_display_cancel_read (wayland-client.c:1900)
==10704==    by 0xFA5B4C: <wayland_backend::sys::client_impl::InnerReadEventsGuard as core::ops::drop::Drop>::drop (mod.rs:466)
==10704==    by 0xFBAA16: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerReadEventsGuard> (mod.rs:497)
==10704==    by 0xF98E7A: core::ptr::drop_in_place<wayland_backend::sys::client::ReadEventsGuard> (mod.rs:497)
==10704==    by 0x725092: core::ptr::drop_in_place<core::option::Option<wayland_backend::sys::client::ReadEventsGuard>> (mod.rs:497)
==10704==    by 0x6D03CD: <calloop_wayland_source::WaylandSource<D> as calloop::sources::EventSource>::before_handle_events (lib.rs:219)
==10704==    by 0x7134D4: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::before_handle_events (mod.rs:388)
==10704==    by 0x6CBD62: calloop::loop_logic::EventLoop<Data>::dispatch_events (loop_logic.rs:414)
==10704==    by 0x6CCB68: calloop::loop_logic::EventLoop<Data>::dispatch (loop_logic.rs:554)
==10704==    by 0x6F59ED: smithay_clipboard::worker::worker_impl (worker.rs:98)
==10704==    by 0x6F544F: smithay_clipboard::worker::spawn::{{closure}} (worker.rs:23)
==10704==  Address 0x508658c is 364 bytes inside a block of size 376 free'd
==10704==    at 0x484412F: free (vg_replace_malloc.c:974)
==10704==    by 0xFABC35: <wayland_backend::sys::client_impl::ConnectionState as core::ops::drop::Drop>::drop (mod.rs:1022)
==10704==    by 0xFBA826: core::ptr::drop_in_place<wayland_backend::sys::client_impl::ConnectionState> (mod.rs:497)
==10704==    by 0xFB9D4A: core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFB9D9E: core::ptr::drop_in_place<std::sync::mutex::Mutex<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFBA61A: core::ptr::drop_in_place<wayland_backend::sys::client_impl::Inner> (mod.rs:497)
==10704==    by 0xF9FDDE: alloc::sync::Arc<T,A>::drop_slow (sync.rs:1749)
==10704==    by 0xFA04B4: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop (sync.rs:2405)
==10704==    by 0xFBAACA: core::ptr::drop_in_place<alloc::sync::Arc<wayland_backend::sys::client_impl::Inner>> (mod.rs:497)
==10704==    by 0xFBA6EA: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerBackend> (mod.rs:497)
==10704==    by 0xFBA56A: core::ptr::drop_in_place<wayland_backend::sys::client::Backend> (mod.rs:497)
==10704==    by 0xF98ABA: core::ptr::drop_in_place<wayland_client::conn::Connection> (mod.rs:497)
==10704==  Block was alloc'd at
==10704==    at 0x48469B3: calloc (vg_replace_malloc.c:1554)
==10704==    by 0x4860D95: UnknownInlinedFun (wayland-private.h:234)
==10704==    by 0x4860D95: wl_display_connect_to_fd (wayland-client.c:1183)
==10704==    by 0xFA3FE5: wayland_backend::sys::client_impl::InnerBackend::connect (mod.rs:228)
==10704==    by 0xFAE1A9: wayland_backend::sys::client::Backend::connect (client_api.rs:164)
==10704==    by 0xF7B13C: wayland_client::conn::Connection::connect_to_env (conn.rs:92)
==10704==    by 0x3D7E80: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new (mod.rs:81)
==10704==    by 0x472DA9: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread (mod.rs:793)
==10704==    by 0x4730CC: winit::platform_impl::platform::EventLoop<T>::new (mod.rs:785)
==10704==    by 0x4B4DAC: winit::event_loop::EventLoopBuilder<T>::build (event_loop.rs:128)
==10704==    by 0x495924: alacritty::alacritty (main.rs:129)
==10704==    by 0x495049: alacritty::main (main.rs:85)
==10704==    by 0x4BFCAA: core::ops::function::FnOnce::call_once (function.rs:250)
==10704==
==10704== Invalid read of size 4
==10704==    at 0x4B39744: __pthread_mutex_unlock_usercnt (pthread_mutex_unlock.c:51)
==10704==    by 0xFA5B4C: <wayland_backend::sys::client_impl::InnerReadEventsGuard as core::ops::drop::Drop>::drop (mod.rs:466)
==10704==    by 0xFBAA16: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerReadEventsGuard> (mod.rs:497)
==10704==    by 0xF98E7A: core::ptr::drop_in_place<wayland_backend::sys::client::ReadEventsGuard> (mod.rs:497)
==10704==    by 0x725092: core::ptr::drop_in_place<core::option::Option<wayland_backend::sys::client::ReadEventsGuard>> (mod.rs:497)
==10704==    by 0x6D03CD: <calloop_wayland_source::WaylandSource<D> as calloop::sources::EventSource>::before_handle_events (lib.rs:219)
==10704==    by 0x7134D4: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::before_handle_events (mod.rs:388)
==10704==    by 0x6CBD62: calloop::loop_logic::EventLoop<Data>::dispatch_events (loop_logic.rs:414)
==10704==    by 0x6CCB68: calloop::loop_logic::EventLoop<Data>::dispatch (loop_logic.rs:554)
==10704==    by 0x6F59ED: smithay_clipboard::worker::worker_impl (worker.rs:98)
==10704==    by 0x6F544F: smithay_clipboard::worker::spawn::{{closure}} (worker.rs:23)
==10704==    by 0x6E3B08: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:154)
==10704==  Address 0x5086548 is 296 bytes inside a block of size 376 free'd
==10704==    at 0x484412F: free (vg_replace_malloc.c:974)
==10704==    by 0xFABC35: <wayland_backend::sys::client_impl::ConnectionState as core::ops::drop::Drop>::drop (mod.rs:1022)
==10704==    by 0xFBA826: core::ptr::drop_in_place<wayland_backend::sys::client_impl::ConnectionState> (mod.rs:497)
==10704==    by 0xFB9D4A: core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFB9D9E: core::ptr::drop_in_place<std::sync::mutex::Mutex<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFBA61A: core::ptr::drop_in_place<wayland_backend::sys::client_impl::Inner> (mod.rs:497)
==10704==    by 0xF9FDDE: alloc::sync::Arc<T,A>::drop_slow (sync.rs:1749)
==10704==    by 0xFA04B4: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop (sync.rs:2405)
==10704==    by 0xFBAACA: core::ptr::drop_in_place<alloc::sync::Arc<wayland_backend::sys::client_impl::Inner>> (mod.rs:497)
==10704==    by 0xFBA6EA: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerBackend> (mod.rs:497)
==10704==    by 0xFBA56A: core::ptr::drop_in_place<wayland_backend::sys::client::Backend> (mod.rs:497)
==10704==    by 0xF98ABA: core::ptr::drop_in_place<wayland_client::conn::Connection> (mod.rs:497)
==10704==  Block was alloc'd at
==10704==    at 0x48469B3: calloc (vg_replace_malloc.c:1554)
==10704==    by 0x4860D95: UnknownInlinedFun (wayland-private.h:234)
==10704==    by 0x4860D95: wl_display_connect_to_fd (wayland-client.c:1183)
==10704==    by 0xFA3FE5: wayland_backend::sys::client_impl::InnerBackend::connect (mod.rs:228)
==10704==    by 0xFAE1A9: wayland_backend::sys::client::Backend::connect (client_api.rs:164)
==10704==    by 0xF7B13C: wayland_client::conn::Connection::connect_to_env (conn.rs:92)
==10704==    by 0x3D7E80: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new (mod.rs:81)
==10704==    by 0x472DA9: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread (mod.rs:793)
==10704==    by 0x4730CC: winit::platform_impl::platform::EventLoop<T>::new (mod.rs:785)
==10704==    by 0x4B4DAC: winit::event_loop::EventLoopBuilder<T>::build (event_loop.rs:128)
==10704==    by 0x495924: alacritty::alacritty (main.rs:129)
==10704==    by 0x495049: alacritty::main (main.rs:85)
==10704==    by 0x4BFCAA: core::ops::function::FnOnce::call_once (function.rs:250)
==10704==
==10704== Invalid read of size 4
==10704==    at 0x4B397C0: __pthread_mutex_unlock_usercnt (pthread_mutex_unlock.c:55)
==10704==    by 0xFA5B4C: <wayland_backend::sys::client_impl::InnerReadEventsGuard as core::ops::drop::Drop>::drop (mod.rs:466)
==10704==    by 0xFBAA16: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerReadEventsGuard> (mod.rs:497)
==10704==    by 0xF98E7A: core::ptr::drop_in_place<wayland_backend::sys::client::ReadEventsGuard> (mod.rs:497)
==10704==    by 0x725092: core::ptr::drop_in_place<core::option::Option<wayland_backend::sys::client::ReadEventsGuard>> (mod.rs:497)
==10704==    by 0x6D03CD: <calloop_wayland_source::WaylandSource<D> as calloop::sources::EventSource>::before_handle_events (lib.rs:219)
==10704==    by 0x7134D4: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::before_handle_events (mod.rs:388)
==10704==    by 0x6CBD62: calloop::loop_logic::EventLoop<Data>::dispatch_events (loop_logic.rs:414)
==10704==    by 0x6CCB68: calloop::loop_logic::EventLoop<Data>::dispatch (loop_logic.rs:554)
==10704==    by 0x6F59ED: smithay_clipboard::worker::worker_impl (worker.rs:98)
==10704==    by 0x6F544F: smithay_clipboard::worker::spawn::{{closure}} (worker.rs:23)
==10704==    by 0x6E3B08: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:154)
==10704==  Address 0x5086548 is 296 bytes inside a block of size 376 free'd
==10704==    at 0x484412F: free (vg_replace_malloc.c:974)
==10704==    by 0xFABC35: <wayland_backend::sys::client_impl::ConnectionState as core::ops::drop::Drop>::drop (mod.rs:1022)
==10704==    by 0xFBA826: core::ptr::drop_in_place<wayland_backend::sys::client_impl::ConnectionState> (mod.rs:497)
==10704==    by 0xFB9D4A: core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFB9D9E: core::ptr::drop_in_place<std::sync::mutex::Mutex<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFBA61A: core::ptr::drop_in_place<wayland_backend::sys::client_impl::Inner> (mod.rs:497)
==10704==    by 0xF9FDDE: alloc::sync::Arc<T,A>::drop_slow (sync.rs:1749)
==10704==    by 0xFA04B4: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop (sync.rs:2405)
==10704==    by 0xFBAACA: core::ptr::drop_in_place<alloc::sync::Arc<wayland_backend::sys::client_impl::Inner>> (mod.rs:497)
==10704==    by 0xFBA6EA: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerBackend> (mod.rs:497)
==10704==    by 0xFBA56A: core::ptr::drop_in_place<wayland_backend::sys::client::Backend> (mod.rs:497)
==10704==    by 0xF98ABA: core::ptr::drop_in_place<wayland_client::conn::Connection> (mod.rs:497)
==10704==  Block was alloc'd at
==10704==    at 0x48469B3: calloc (vg_replace_malloc.c:1554)
==10704==    by 0x4860D95: UnknownInlinedFun (wayland-private.h:234)
==10704==    by 0x4860D95: wl_display_connect_to_fd (wayland-client.c:1183)
==10704==    by 0xFA3FE5: wayland_backend::sys::client_impl::InnerBackend::connect (mod.rs:228)
==10704==    by 0xFAE1A9: wayland_backend::sys::client::Backend::connect (client_api.rs:164)
==10704==    by 0xF7B13C: wayland_client::conn::Connection::connect_to_env (conn.rs:92)
==10704==    by 0x3D7E80: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new (mod.rs:81)
==10704==    by 0x472DA9: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread (mod.rs:793)
==10704==    by 0x4730CC: winit::platform_impl::platform::EventLoop<T>::new (mod.rs:785)
==10704==    by 0x4B4DAC: winit::event_loop::EventLoopBuilder<T>::build (event_loop.rs:128)
==10704==    by 0x495924: alacritty::alacritty (main.rs:129)
==10704==    by 0x495049: alacritty::main (main.rs:85)
==10704==    by 0x4BFCAA: core::ops::function::FnOnce::call_once (function.rs:250)
==10704==
==10704== Invalid read of size 4
==10704==    at 0x4B37DB4: pthread_mutex_lock@@GLIBC_2.2.5 (pthread_mutex_lock.c:80)
==10704==    by 0x485FDB6: wl_proxy_marshal_array_flags (wayland-client.c:866)
==10704==    by 0xFA7368: wayland_backend::sys::client_impl::InnerBackend::send_request (mod.rs:637)
==10704==    by 0xFAE23F: wayland_backend::sys::client::Backend::send_request (client_api.rs:234)
==10704==    by 0xF2A6B4: wayland_client::conn::Connection::send_request (conn.rs:204)
==10704==    by 0xF4CD50: wayland_protocols::wp::primary_selection::zv1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1::destroy (protocol_macro.rs:28)
==10704==    by 0xEE885A: <smithay_client_toolkit::primary_selection::PrimarySelectionManagerState as core::ops::drop::Drop>::drop (mod.rs:80)
==10704==    by 0x724DC6: core::ptr::drop_in_place<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState> (mod.rs:497)
==10704==    by 0x720C45: core::ptr::drop_in_place<core::option::Option<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState>> (mod.rs:497)
==10704==    by 0x72369D: core::ptr::drop_in_place<smithay_clipboard::state::State> (mod.rs:497)
==10704==    by 0x6F5A24: smithay_clipboard::worker::worker_impl (worker.rs:104)
==10704==    by 0x6F544F: smithay_clipboard::worker::spawn::{{closure}} (worker.rs:23)
==10704==  Address 0x5086548 is 296 bytes inside a block of size 376 free'd
==10704==    at 0x484412F: free (vg_replace_malloc.c:974)
==10704==    by 0xFABC35: <wayland_backend::sys::client_impl::ConnectionState as core::ops::drop::Drop>::drop (mod.rs:1022)
==10704==    by 0xFBA826: core::ptr::drop_in_place<wayland_backend::sys::client_impl::ConnectionState> (mod.rs:497)
==10704==    by 0xFB9D4A: core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFB9D9E: core::ptr::drop_in_place<std::sync::mutex::Mutex<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFBA61A: core::ptr::drop_in_place<wayland_backend::sys::client_impl::Inner> (mod.rs:497)
==10704==    by 0xF9FDDE: alloc::sync::Arc<T,A>::drop_slow (sync.rs:1749)
==10704==    by 0xFA04B4: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop (sync.rs:2405)
==10704==    by 0xFBAACA: core::ptr::drop_in_place<alloc::sync::Arc<wayland_backend::sys::client_impl::Inner>> (mod.rs:497)
==10704==    by 0xFBA6EA: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerBackend> (mod.rs:497)
==10704==    by 0xFBA56A: core::ptr::drop_in_place<wayland_backend::sys::client::Backend> (mod.rs:497)
==10704==    by 0xF98ABA: core::ptr::drop_in_place<wayland_client::conn::Connection> (mod.rs:497)
==10704==  Block was alloc'd at
==10704==    at 0x48469B3: calloc (vg_replace_malloc.c:1554)
==10704==    by 0x4860D95: UnknownInlinedFun (wayland-private.h:234)
==10704==    by 0x4860D95: wl_display_connect_to_fd (wayland-client.c:1183)
==10704==    by 0xFA3FE5: wayland_backend::sys::client_impl::InnerBackend::connect (mod.rs:228)
==10704==    by 0xFAE1A9: wayland_backend::sys::client::Backend::connect (client_api.rs:164)
==10704==    by 0xF7B13C: wayland_client::conn::Connection::connect_to_env (conn.rs:92)
==10704==    by 0x3D7E80: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new (mod.rs:81)
==10704==    by 0x472DA9: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread (mod.rs:793)
==10704==    by 0x4730CC: winit::platform_impl::platform::EventLoop<T>::new (mod.rs:785)
==10704==    by 0x4B4DAC: winit::event_loop::EventLoopBuilder<T>::build (event_loop.rs:128)
==10704==    by 0x495924: alacritty::alacritty (main.rs:129)
==10704==    by 0x495049: alacritty::main (main.rs:85)
==10704==    by 0x4BFCAA: core::ops::function::FnOnce::call_once (function.rs:250)
==10704==
==10704== Invalid read of size 4
==10704==    at 0x4B376BD: __pthread_mutex_lock_full (pthread_mutex_lock.c:198)
==10704==    by 0x485FDB6: wl_proxy_marshal_array_flags (wayland-client.c:866)
==10704==    by 0xFA7368: wayland_backend::sys::client_impl::InnerBackend::send_request (mod.rs:637)
==10704==    by 0xFAE23F: wayland_backend::sys::client::Backend::send_request (client_api.rs:234)
==10704==    by 0xF2A6B4: wayland_client::conn::Connection::send_request (conn.rs:204)
==10704==    by 0xF4CD50: wayland_protocols::wp::primary_selection::zv1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1::destroy (protocol_macro.rs:28)
==10704==    by 0xEE885A: <smithay_client_toolkit::primary_selection::PrimarySelectionManagerState as core::ops::drop::Drop>::drop (mod.rs:80)
==10704==    by 0x724DC6: core::ptr::drop_in_place<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState> (mod.rs:497)
==10704==    by 0x720C45: core::ptr::drop_in_place<core::option::Option<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState>> (mod.rs:497)
==10704==    by 0x72369D: core::ptr::drop_in_place<smithay_clipboard::state::State> (mod.rs:497)
==10704==    by 0x6F5A24: smithay_clipboard::worker::worker_impl (worker.rs:104)
==10704==    by 0x6F544F: smithay_clipboard::worker::spawn::{{closure}} (worker.rs:23)
==10704==  Address 0x5086548 is 296 bytes inside a block of size 376 free'd
==10704==    at 0x484412F: free (vg_replace_malloc.c:974)
==10704==    by 0xFABC35: <wayland_backend::sys::client_impl::ConnectionState as core::ops::drop::Drop>::drop (mod.rs:1022)
==10704==    by 0xFBA826: core::ptr::drop_in_place<wayland_backend::sys::client_impl::ConnectionState> (mod.rs:497)
==10704==    by 0xFB9D4A: core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFB9D9E: core::ptr::drop_in_place<std::sync::mutex::Mutex<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFBA61A: core::ptr::drop_in_place<wayland_backend::sys::client_impl::Inner> (mod.rs:497)
==10704==    by 0xF9FDDE: alloc::sync::Arc<T,A>::drop_slow (sync.rs:1749)
==10704==    by 0xFA04B4: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop (sync.rs:2405)
==10704==    by 0xFBAACA: core::ptr::drop_in_place<alloc::sync::Arc<wayland_backend::sys::client_impl::Inner>> (mod.rs:497)
==10704==    by 0xFBA6EA: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerBackend> (mod.rs:497)
==10704==    by 0xFBA56A: core::ptr::drop_in_place<wayland_backend::sys::client::Backend> (mod.rs:497)
==10704==    by 0xF98ABA: core::ptr::drop_in_place<wayland_client::conn::Connection> (mod.rs:497)
==10704==  Block was alloc'd at
==10704==    at 0x48469B3: calloc (vg_replace_malloc.c:1554)
==10704==    by 0x4860D95: UnknownInlinedFun (wayland-private.h:234)
==10704==    by 0x4860D95: wl_display_connect_to_fd (wayland-client.c:1183)
==10704==    by 0xFA3FE5: wayland_backend::sys::client_impl::InnerBackend::connect (mod.rs:228)
==10704==    by 0xFAE1A9: wayland_backend::sys::client::Backend::connect (client_api.rs:164)
==10704==    by 0xF7B13C: wayland_client::conn::Connection::connect_to_env (conn.rs:92)
==10704==    by 0x3D7E80: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new (mod.rs:81)
==10704==    by 0x472DA9: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread (mod.rs:793)
==10704==    by 0x4730CC: winit::platform_impl::platform::EventLoop<T>::new (mod.rs:785)
==10704==    by 0x4B4DAC: winit::event_loop::EventLoopBuilder<T>::build (event_loop.rs:128)
==10704==    by 0x495924: alacritty::alacritty (main.rs:129)
==10704==    by 0x495049: alacritty::main (main.rs:85)
==10704==    by 0x4BFCAA: core::ops::function::FnOnce::call_once (function.rs:250)
==10704==
==10704== Invalid read of size 4
==10704==    at 0x485FEBC: wl_proxy_marshal_array_flags (wayland-client.c:877)
==10704==    by 0xFA7368: wayland_backend::sys::client_impl::InnerBackend::send_request (mod.rs:637)
==10704==    by 0xFAE23F: wayland_backend::sys::client::Backend::send_request (client_api.rs:234)
==10704==    by 0xF2A6B4: wayland_client::conn::Connection::send_request (conn.rs:204)
==10704==    by 0xF4CD50: wayland_protocols::wp::primary_selection::zv1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1::destroy (protocol_macro.rs:28)
==10704==    by 0xEE885A: <smithay_client_toolkit::primary_selection::PrimarySelectionManagerState as core::ops::drop::Drop>::drop (mod.rs:80)
==10704==    by 0x724DC6: core::ptr::drop_in_place<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState> (mod.rs:497)
==10704==    by 0x720C45: core::ptr::drop_in_place<core::option::Option<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState>> (mod.rs:497)
==10704==    by 0x72369D: core::ptr::drop_in_place<smithay_clipboard::state::State> (mod.rs:497)
==10704==    by 0x6F5A24: smithay_clipboard::worker::worker_impl (worker.rs:104)
==10704==    by 0x6F544F: smithay_clipboard::worker::spawn::{{closure}} (worker.rs:23)
==10704==    by 0x6E3B08: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:154)
==10704==  Address 0x5086488 is 104 bytes inside a block of size 376 free'd
==10704==    at 0x484412F: free (vg_replace_malloc.c:974)
==10704==    by 0xFABC35: <wayland_backend::sys::client_impl::ConnectionState as core::ops::drop::Drop>::drop (mod.rs:1022)
==10704==    by 0xFBA826: core::ptr::drop_in_place<wayland_backend::sys::client_impl::ConnectionState> (mod.rs:497)
==10704==    by 0xFB9D4A: core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFB9D9E: core::ptr::drop_in_place<std::sync::mutex::Mutex<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFBA61A: core::ptr::drop_in_place<wayland_backend::sys::client_impl::Inner> (mod.rs:497)
==10704==    by 0xF9FDDE: alloc::sync::Arc<T,A>::drop_slow (sync.rs:1749)
==10704==    by 0xFA04B4: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop (sync.rs:2405)
==10704==    by 0xFBAACA: core::ptr::drop_in_place<alloc::sync::Arc<wayland_backend::sys::client_impl::Inner>> (mod.rs:497)
==10704==    by 0xFBA6EA: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerBackend> (mod.rs:497)
==10704==    by 0xFBA56A: core::ptr::drop_in_place<wayland_backend::sys::client::Backend> (mod.rs:497)
==10704==    by 0xF98ABA: core::ptr::drop_in_place<wayland_client::conn::Connection> (mod.rs:497)
==10704==  Block was alloc'd at
==10704==    at 0x48469B3: calloc (vg_replace_malloc.c:1554)
==10704==    by 0x4860D95: UnknownInlinedFun (wayland-private.h:234)
==10704==    by 0x4860D95: wl_display_connect_to_fd (wayland-client.c:1183)
==10704==    by 0xFA3FE5: wayland_backend::sys::client_impl::InnerBackend::connect (mod.rs:228)
==10704==    by 0xFAE1A9: wayland_backend::sys::client::Backend::connect (client_api.rs:164)
==10704==    by 0xF7B13C: wayland_client::conn::Connection::connect_to_env (conn.rs:92)
==10704==    by 0x3D7E80: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new (mod.rs:81)
==10704==    by 0x472DA9: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread (mod.rs:793)
==10704==    by 0x4730CC: winit::platform_impl::platform::EventLoop<T>::new (mod.rs:785)
==10704==    by 0x4B4DAC: winit::event_loop::EventLoopBuilder<T>::build (event_loop.rs:128)
==10704==    by 0x495924: alacritty::alacritty (main.rs:129)
==10704==    by 0x495049: alacritty::main (main.rs:85)
==10704==    by 0x4BFCAA: core::ops::function::FnOnce::call_once (function.rs:250)
==10704==
==10704== Invalid read of size 8
==10704==    at 0x485FFC6: wl_proxy_marshal_array_flags (wayland-client.c:891)
==10704==    by 0xFA7368: wayland_backend::sys::client_impl::InnerBackend::send_request (mod.rs:637)
==10704==    by 0xFAE23F: wayland_backend::sys::client::Backend::send_request (client_api.rs:234)
==10704==    by 0xF2A6B4: wayland_client::conn::Connection::send_request (conn.rs:204)
==10704==    by 0xF4CD50: wayland_protocols::wp::primary_selection::zv1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1::destroy (protocol_macro.rs:28)
==10704==    by 0xEE885A: <smithay_client_toolkit::primary_selection::PrimarySelectionManagerState as core::ops::drop::Drop>::drop (mod.rs:80)
==10704==    by 0x724DC6: core::ptr::drop_in_place<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState> (mod.rs:497)
==10704==    by 0x720C45: core::ptr::drop_in_place<core::option::Option<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState>> (mod.rs:497)
==10704==    by 0x72369D: core::ptr::drop_in_place<smithay_clipboard::state::State> (mod.rs:497)
==10704==    by 0x6F5A24: smithay_clipboard::worker::worker_impl (worker.rs:104)
==10704==    by 0x6F544F: smithay_clipboard::worker::spawn::{{closure}} (worker.rs:23)
==10704==    by 0x6E3B08: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:154)
==10704==  Address 0x5086480 is 96 bytes inside a block of size 376 free'd
==10704==    at 0x484412F: free (vg_replace_malloc.c:974)
==10704==    by 0xFABC35: <wayland_backend::sys::client_impl::ConnectionState as core::ops::drop::Drop>::drop (mod.rs:1022)
==10704==    by 0xFBA826: core::ptr::drop_in_place<wayland_backend::sys::client_impl::ConnectionState> (mod.rs:497)
==10704==    by 0xFB9D4A: core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFB9D9E: core::ptr::drop_in_place<std::sync::mutex::Mutex<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFBA61A: core::ptr::drop_in_place<wayland_backend::sys::client_impl::Inner> (mod.rs:497)
==10704==    by 0xF9FDDE: alloc::sync::Arc<T,A>::drop_slow (sync.rs:1749)
==10704==    by 0xFA04B4: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop (sync.rs:2405)
==10704==    by 0xFBAACA: core::ptr::drop_in_place<alloc::sync::Arc<wayland_backend::sys::client_impl::Inner>> (mod.rs:497)
==10704==    by 0xFBA6EA: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerBackend> (mod.rs:497)
==10704==    by 0xFBA56A: core::ptr::drop_in_place<wayland_backend::sys::client::Backend> (mod.rs:497)
==10704==    by 0xF98ABA: core::ptr::drop_in_place<wayland_client::conn::Connection> (mod.rs:497)
==10704==  Block was alloc'd at
==10704==    at 0x48469B3: calloc (vg_replace_malloc.c:1554)
==10704==    by 0x4860D95: UnknownInlinedFun (wayland-private.h:234)
==10704==    by 0x4860D95: wl_display_connect_to_fd (wayland-client.c:1183)
==10704==    by 0xFA3FE5: wayland_backend::sys::client_impl::InnerBackend::connect (mod.rs:228)
==10704==    by 0xFAE1A9: wayland_backend::sys::client::Backend::connect (client_api.rs:164)
==10704==    by 0xF7B13C: wayland_client::conn::Connection::connect_to_env (conn.rs:92)
==10704==    by 0x3D7E80: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new (mod.rs:81)
==10704==    by 0x472DA9: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread (mod.rs:793)
==10704==    by 0x4730CC: winit::platform_impl::platform::EventLoop<T>::new (mod.rs:785)
==10704==    by 0x4B4DAC: winit::event_loop::EventLoopBuilder<T>::build (event_loop.rs:128)
==10704==    by 0x495924: alacritty::alacritty (main.rs:129)
==10704==    by 0x495049: alacritty::main (main.rs:85)
==10704==    by 0x4BFCAA: core::ops::function::FnOnce::call_once (function.rs:250)
==10704==
==10704== Invalid read of size 4
==10704==    at 0x48603F2: UnknownInlinedFun (connection.c:379)
==10704==    by 0x48603F2: UnknownInlinedFun (connection.c:1231)
==10704==    by 0x48603F2: wl_proxy_marshal_array_flags (wayland-client.c:891)
==10704==    by 0xFA7368: wayland_backend::sys::client_impl::InnerBackend::send_request (mod.rs:637)
==10704==    by 0xFAE23F: wayland_backend::sys::client::Backend::send_request (client_api.rs:234)
==10704==    by 0xF2A6B4: wayland_client::conn::Connection::send_request (conn.rs:204)
==10704==    by 0xF4CD50: wayland_protocols::wp::primary_selection::zv1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1::destroy (protocol_macro.rs:28)
==10704==    by 0xEE885A: <smithay_client_toolkit::primary_selection::PrimarySelectionManagerState as core::ops::drop::Drop>::drop (mod.rs:80)
==10704==    by 0x724DC6: core::ptr::drop_in_place<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState> (mod.rs:497)
==10704==    by 0x720C45: core::ptr::drop_in_place<core::option::Option<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState>> (mod.rs:497)
==10704==    by 0x72369D: core::ptr::drop_in_place<smithay_clipboard::state::State> (mod.rs:497)
==10704==    by 0x6F5A24: smithay_clipboard::worker::worker_impl (worker.rs:104)
==10704==    by 0x6F544F: smithay_clipboard::worker::spawn::{{closure}} (worker.rs:23)
==10704==    by 0x6E3B08: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:154)
==10704==  Address 0x5088638 is 8,200 bytes inside a block of size 16,424 free'd
==10704==    at 0x484412F: free (vg_replace_malloc.c:974)
==10704==    by 0x485E27B: UnknownInlinedFun (connection.c:216)
==10704==    by 0x485E27B: wl_display_disconnect (wayland-client.c:1320)
==10704==    by 0xFABC35: <wayland_backend::sys::client_impl::ConnectionState as core::ops::drop::Drop>::drop (mod.rs:1022)
==10704==    by 0xFBA826: core::ptr::drop_in_place<wayland_backend::sys::client_impl::ConnectionState> (mod.rs:497)
==10704==    by 0xFB9D4A: core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFB9D9E: core::ptr::drop_in_place<std::sync::mutex::Mutex<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFBA61A: core::ptr::drop_in_place<wayland_backend::sys::client_impl::Inner> (mod.rs:497)
==10704==    by 0xF9FDDE: alloc::sync::Arc<T,A>::drop_slow (sync.rs:1749)
==10704==    by 0xFA04B4: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop (sync.rs:2405)
==10704==    by 0xFBAACA: core::ptr::drop_in_place<alloc::sync::Arc<wayland_backend::sys::client_impl::Inner>> (mod.rs:497)
==10704==    by 0xFBA6EA: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerBackend> (mod.rs:497)
==10704==    by 0xFBA56A: core::ptr::drop_in_place<wayland_backend::sys::client::Backend> (mod.rs:497)
==10704==  Block was alloc'd at
==10704==    at 0x48469B3: calloc (vg_replace_malloc.c:1554)
==10704==    by 0x4860EC6: UnknownInlinedFun (wayland-private.h:234)
==10704==    by 0x4860EC6: UnknownInlinedFun (connection.c:174)
==10704==    by 0x4860EC6: wl_display_connect_to_fd (wayland-client.c:1233)
==10704==    by 0xFA3FE5: wayland_backend::sys::client_impl::InnerBackend::connect (mod.rs:228)
==10704==    by 0xFAE1A9: wayland_backend::sys::client::Backend::connect (client_api.rs:164)
==10704==    by 0xF7B13C: wayland_client::conn::Connection::connect_to_env (conn.rs:92)
==10704==    by 0x3D7E80: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new (mod.rs:81)
==10704==    by 0x472DA9: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread (mod.rs:793)
==10704==    by 0x4730CC: winit::platform_impl::platform::EventLoop<T>::new (mod.rs:785)
==10704==    by 0x4B4DAC: winit::event_loop::EventLoopBuilder<T>::build (event_loop.rs:128)
==10704==    by 0x495924: alacritty::alacritty (main.rs:129)
==10704==    by 0x495049: alacritty::main (main.rs:85)
==10704==    by 0x4BFCAA: core::ops::function::FnOnce::call_once (function.rs:250)
==10704==
==10704== Invalid read of size 4
==10704==    at 0x48603F8: UnknownInlinedFun (connection.c:379)
==10704==    by 0x48603F8: UnknownInlinedFun (connection.c:1231)
==10704==    by 0x48603F8: wl_proxy_marshal_array_flags (wayland-client.c:891)
==10704==    by 0xFA7368: wayland_backend::sys::client_impl::InnerBackend::send_request (mod.rs:637)
==10704==    by 0xFAE23F: wayland_backend::sys::client::Backend::send_request (client_api.rs:234)
==10704==    by 0xF2A6B4: wayland_client::conn::Connection::send_request (conn.rs:204)
==10704==    by 0xF4CD50: wayland_protocols::wp::primary_selection::zv1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1::destroy (protocol_macro.rs:28)
==10704==    by 0xEE885A: <smithay_client_toolkit::primary_selection::PrimarySelectionManagerState as core::ops::drop::Drop>::drop (mod.rs:80)
==10704==    by 0x724DC6: core::ptr::drop_in_place<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState> (mod.rs:497)
==10704==    by 0x720C45: core::ptr::drop_in_place<core::option::Option<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState>> (mod.rs:497)
==10704==    by 0x72369D: core::ptr::drop_in_place<smithay_clipboard::state::State> (mod.rs:497)
==10704==    by 0x6F5A24: smithay_clipboard::worker::worker_impl (worker.rs:104)
==10704==    by 0x6F544F: smithay_clipboard::worker::spawn::{{closure}} (worker.rs:23)
==10704==    by 0x6E3B08: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:154)
==10704==  Address 0x508863c is 8,204 bytes inside a block of size 16,424 free'd
==10704==    at 0x484412F: free (vg_replace_malloc.c:974)
==10704==    by 0x485E27B: UnknownInlinedFun (connection.c:216)
==10704==    by 0x485E27B: wl_display_disconnect (wayland-client.c:1320)
==10704==    by 0xFABC35: <wayland_backend::sys::client_impl::ConnectionState as core::ops::drop::Drop>::drop (mod.rs:1022)
==10704==    by 0xFBA826: core::ptr::drop_in_place<wayland_backend::sys::client_impl::ConnectionState> (mod.rs:497)
==10704==    by 0xFB9D4A: core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFB9D9E: core::ptr::drop_in_place<std::sync::mutex::Mutex<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFBA61A: core::ptr::drop_in_place<wayland_backend::sys::client_impl::Inner> (mod.rs:497)
==10704==    by 0xF9FDDE: alloc::sync::Arc<T,A>::drop_slow (sync.rs:1749)
==10704==    by 0xFA04B4: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop (sync.rs:2405)
==10704==    by 0xFBAACA: core::ptr::drop_in_place<alloc::sync::Arc<wayland_backend::sys::client_impl::Inner>> (mod.rs:497)
==10704==    by 0xFBA6EA: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerBackend> (mod.rs:497)
==10704==    by 0xFBA56A: core::ptr::drop_in_place<wayland_backend::sys::client::Backend> (mod.rs:497)
==10704==  Block was alloc'd at
==10704==    at 0x48469B3: calloc (vg_replace_malloc.c:1554)
==10704==    by 0x4860EC6: UnknownInlinedFun (wayland-private.h:234)
==10704==    by 0x4860EC6: UnknownInlinedFun (connection.c:174)
==10704==    by 0x4860EC6: wl_display_connect_to_fd (wayland-client.c:1233)
==10704==    by 0xFA3FE5: wayland_backend::sys::client_impl::InnerBackend::connect (mod.rs:228)
==10704==    by 0xFAE1A9: wayland_backend::sys::client::Backend::connect (client_api.rs:164)
==10704==    by 0xF7B13C: wayland_client::conn::Connection::connect_to_env (conn.rs:92)
==10704==    by 0x3D7E80: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new (mod.rs:81)
==10704==    by 0x472DA9: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread (mod.rs:793)
==10704==    by 0x4730CC: winit::platform_impl::platform::EventLoop<T>::new (mod.rs:785)
==10704==    by 0x4B4DAC: winit::event_loop::EventLoopBuilder<T>::build (event_loop.rs:128)
==10704==    by 0x495924: alacritty::alacritty (main.rs:129)
==10704==    by 0x495049: alacritty::main (main.rs:85)
==10704==    by 0x4BFCAA: core::ops::function::FnOnce::call_once (function.rs:250)
==10704==
==10704== Invalid read of size 4
==10704==    at 0x485C5A6: ring_buffer_put (connection.c:86)
==10704==    by 0x4860443: UnknownInlinedFun (connection.c:386)
==10704==    by 0x4860443: UnknownInlinedFun (connection.c:1231)
==10704==    by 0x4860443: wl_proxy_marshal_array_flags (wayland-client.c:891)
==10704==    by 0xFA7368: wayland_backend::sys::client_impl::InnerBackend::send_request (mod.rs:637)
==10704==    by 0xFAE23F: wayland_backend::sys::client::Backend::send_request (client_api.rs:234)
==10704==    by 0xF2A6B4: wayland_client::conn::Connection::send_request (conn.rs:204)
==10704==    by 0xF4CD50: wayland_protocols::wp::primary_selection::zv1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1::destroy (protocol_macro.rs:28)
==10704==    by 0xEE885A: <smithay_client_toolkit::primary_selection::PrimarySelectionManagerState as core::ops::drop::Drop>::drop (mod.rs:80)
==10704==    by 0x724DC6: core::ptr::drop_in_place<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState> (mod.rs:497)
==10704==    by 0x720C45: core::ptr::drop_in_place<core::option::Option<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState>> (mod.rs:497)
==10704==    by 0x72369D: core::ptr::drop_in_place<smithay_clipboard::state::State> (mod.rs:497)
==10704==    by 0x6F5A24: smithay_clipboard::worker::worker_impl (worker.rs:104)
==10704==    by 0x6F544F: smithay_clipboard::worker::spawn::{{closure}} (worker.rs:23)
==10704==  Address 0x5088638 is 8,200 bytes inside a block of size 16,424 free'd
==10704==    at 0x484412F: free (vg_replace_malloc.c:974)
==10704==    by 0x485E27B: UnknownInlinedFun (connection.c:216)
==10704==    by 0x485E27B: wl_display_disconnect (wayland-client.c:1320)
==10704==    by 0xFABC35: <wayland_backend::sys::client_impl::ConnectionState as core::ops::drop::Drop>::drop (mod.rs:1022)
==10704==    by 0xFBA826: core::ptr::drop_in_place<wayland_backend::sys::client_impl::ConnectionState> (mod.rs:497)
==10704==    by 0xFB9D4A: core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFB9D9E: core::ptr::drop_in_place<std::sync::mutex::Mutex<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFBA61A: core::ptr::drop_in_place<wayland_backend::sys::client_impl::Inner> (mod.rs:497)
==10704==    by 0xF9FDDE: alloc::sync::Arc<T,A>::drop_slow (sync.rs:1749)
==10704==    by 0xFA04B4: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop (sync.rs:2405)
==10704==    by 0xFBAACA: core::ptr::drop_in_place<alloc::sync::Arc<wayland_backend::sys::client_impl::Inner>> (mod.rs:497)
==10704==    by 0xFBA6EA: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerBackend> (mod.rs:497)
==10704==    by 0xFBA56A: core::ptr::drop_in_place<wayland_backend::sys::client::Backend> (mod.rs:497)
==10704==  Block was alloc'd at
==10704==    at 0x48469B3: calloc (vg_replace_malloc.c:1554)
==10704==    by 0x4860EC6: UnknownInlinedFun (wayland-private.h:234)
==10704==    by 0x4860EC6: UnknownInlinedFun (connection.c:174)
==10704==    by 0x4860EC6: wl_display_connect_to_fd (wayland-client.c:1233)
==10704==    by 0xFA3FE5: wayland_backend::sys::client_impl::InnerBackend::connect (mod.rs:228)
==10704==    by 0xFAE1A9: wayland_backend::sys::client::Backend::connect (client_api.rs:164)
==10704==    by 0xF7B13C: wayland_client::conn::Connection::connect_to_env (conn.rs:92)
==10704==    by 0x3D7E80: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new (mod.rs:81)
==10704==    by 0x472DA9: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread (mod.rs:793)
==10704==    by 0x4730CC: winit::platform_impl::platform::EventLoop<T>::new (mod.rs:785)
==10704==    by 0x4B4DAC: winit::event_loop::EventLoopBuilder<T>::build (event_loop.rs:128)
==10704==    by 0x495924: alacritty::alacritty (main.rs:129)
==10704==    by 0x495049: alacritty::main (main.rs:85)
==10704==    by 0x4BFCAA: core::ops::function::FnOnce::call_once (function.rs:250)
==10704==
==10704== Invalid write of size 8
==10704==    at 0x484C081: memmove (vg_replace_strmem.c:1400)
==10704==    by 0x485C5D5: UnknownInlinedFun (string_fortified.h:29)
==10704==    by 0x485C5D5: ring_buffer_put (connection.c:88)
==10704==    by 0x4860443: UnknownInlinedFun (connection.c:386)
==10704==    by 0x4860443: UnknownInlinedFun (connection.c:1231)
==10704==    by 0x4860443: wl_proxy_marshal_array_flags (wayland-client.c:891)
==10704==    by 0xFA7368: wayland_backend::sys::client_impl::InnerBackend::send_request (mod.rs:637)
==10704==    by 0xFAE23F: wayland_backend::sys::client::Backend::send_request (client_api.rs:234)
==10704==    by 0xF2A6B4: wayland_client::conn::Connection::send_request (conn.rs:204)
==10704==    by 0xF4CD50: wayland_protocols::wp::primary_selection::zv1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1::destroy (protocol_macro.rs:28)
==10704==    by 0xEE885A: <smithay_client_toolkit::primary_selection::PrimarySelectionManagerState as core::ops::drop::Drop>::drop (mod.rs:80)
==10704==    by 0x724DC6: core::ptr::drop_in_place<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState> (mod.rs:497)
==10704==    by 0x720C45: core::ptr::drop_in_place<core::option::Option<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState>> (mod.rs:497)
==10704==    by 0x72369D: core::ptr::drop_in_place<smithay_clipboard::state::State> (mod.rs:497)
==10704==    by 0x6F5A24: smithay_clipboard::worker::worker_impl (worker.rs:104)
==10704==  Address 0x5088110 is 6,880 bytes inside a block of size 16,424 free'd
==10704==    at 0x484412F: free (vg_replace_malloc.c:974)
==10704==    by 0x485E27B: UnknownInlinedFun (connection.c:216)
==10704==    by 0x485E27B: wl_display_disconnect (wayland-client.c:1320)
==10704==    by 0xFABC35: <wayland_backend::sys::client_impl::ConnectionState as core::ops::drop::Drop>::drop (mod.rs:1022)
==10704==    by 0xFBA826: core::ptr::drop_in_place<wayland_backend::sys::client_impl::ConnectionState> (mod.rs:497)
==10704==    by 0xFB9D4A: core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFB9D9E: core::ptr::drop_in_place<std::sync::mutex::Mutex<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFBA61A: core::ptr::drop_in_place<wayland_backend::sys::client_impl::Inner> (mod.rs:497)
==10704==    by 0xF9FDDE: alloc::sync::Arc<T,A>::drop_slow (sync.rs:1749)
==10704==    by 0xFA04B4: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop (sync.rs:2405)
==10704==    by 0xFBAACA: core::ptr::drop_in_place<alloc::sync::Arc<wayland_backend::sys::client_impl::Inner>> (mod.rs:497)
==10704==    by 0xFBA6EA: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerBackend> (mod.rs:497)
==10704==    by 0xFBA56A: core::ptr::drop_in_place<wayland_backend::sys::client::Backend> (mod.rs:497)
==10704==  Block was alloc'd at
==10704==    at 0x48469B3: calloc (vg_replace_malloc.c:1554)
==10704==    by 0x4860EC6: UnknownInlinedFun (wayland-private.h:234)
==10704==    by 0x4860EC6: UnknownInlinedFun (connection.c:174)
==10704==    by 0x4860EC6: wl_display_connect_to_fd (wayland-client.c:1233)
==10704==    by 0xFA3FE5: wayland_backend::sys::client_impl::InnerBackend::connect (mod.rs:228)
==10704==    by 0xFAE1A9: wayland_backend::sys::client::Backend::connect (client_api.rs:164)
==10704==    by 0xF7B13C: wayland_client::conn::Connection::connect_to_env (conn.rs:92)
==10704==    by 0x3D7E80: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new (mod.rs:81)
==10704==    by 0x472DA9: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread (mod.rs:793)
==10704==    by 0x4730CC: winit::platform_impl::platform::EventLoop<T>::new (mod.rs:785)
==10704==    by 0x4B4DAC: winit::event_loop::EventLoopBuilder<T>::build (event_loop.rs:128)
==10704==    by 0x495924: alacritty::alacritty (main.rs:129)
==10704==    by 0x495049: alacritty::main (main.rs:85)
==10704==    by 0x4BFCAA: core::ops::function::FnOnce::call_once (function.rs:250)
==10704==
==10704== Invalid read of size 4
==10704==    at 0x485C5D6: ring_buffer_put (connection.c:95)
==10704==    by 0x4860443: UnknownInlinedFun (connection.c:386)
==10704==    by 0x4860443: UnknownInlinedFun (connection.c:1231)
==10704==    by 0x4860443: wl_proxy_marshal_array_flags (wayland-client.c:891)
==10704==    by 0xFA7368: wayland_backend::sys::client_impl::InnerBackend::send_request (mod.rs:637)
==10704==    by 0xFAE23F: wayland_backend::sys::client::Backend::send_request (client_api.rs:234)
==10704==    by 0xF2A6B4: wayland_client::conn::Connection::send_request (conn.rs:204)
==10704==    by 0xF4CD50: wayland_protocols::wp::primary_selection::zv1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1::destroy (protocol_macro.rs:28)
==10704==    by 0xEE885A: <smithay_client_toolkit::primary_selection::PrimarySelectionManagerState as core::ops::drop::Drop>::drop (mod.rs:80)
==10704==    by 0x724DC6: core::ptr::drop_in_place<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState> (mod.rs:497)
==10704==    by 0x720C45: core::ptr::drop_in_place<core::option::Option<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState>> (mod.rs:497)
==10704==    by 0x72369D: core::ptr::drop_in_place<smithay_clipboard::state::State> (mod.rs:497)
==10704==    by 0x6F5A24: smithay_clipboard::worker::worker_impl (worker.rs:104)
==10704==    by 0x6F544F: smithay_clipboard::worker::spawn::{{closure}} (worker.rs:23)
==10704==  Address 0x5088638 is 8,200 bytes inside a block of size 16,424 free'd
==10704==    at 0x484412F: free (vg_replace_malloc.c:974)
==10704==    by 0x485E27B: UnknownInlinedFun (connection.c:216)
==10704==    by 0x485E27B: wl_display_disconnect (wayland-client.c:1320)
==10704==    by 0xFABC35: <wayland_backend::sys::client_impl::ConnectionState as core::ops::drop::Drop>::drop (mod.rs:1022)
==10704==    by 0xFBA826: core::ptr::drop_in_place<wayland_backend::sys::client_impl::ConnectionState> (mod.rs:497)
==10704==    by 0xFB9D4A: core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFB9D9E: core::ptr::drop_in_place<std::sync::mutex::Mutex<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFBA61A: core::ptr::drop_in_place<wayland_backend::sys::client_impl::Inner> (mod.rs:497)
==10704==    by 0xF9FDDE: alloc::sync::Arc<T,A>::drop_slow (sync.rs:1749)
==10704==    by 0xFA04B4: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop (sync.rs:2405)
==10704==    by 0xFBAACA: core::ptr::drop_in_place<alloc::sync::Arc<wayland_backend::sys::client_impl::Inner>> (mod.rs:497)
==10704==    by 0xFBA6EA: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerBackend> (mod.rs:497)
==10704==    by 0xFBA56A: core::ptr::drop_in_place<wayland_backend::sys::client::Backend> (mod.rs:497)
==10704==  Block was alloc'd at
==10704==    at 0x48469B3: calloc (vg_replace_malloc.c:1554)
==10704==    by 0x4860EC6: UnknownInlinedFun (wayland-private.h:234)
==10704==    by 0x4860EC6: UnknownInlinedFun (connection.c:174)
==10704==    by 0x4860EC6: wl_display_connect_to_fd (wayland-client.c:1233)
==10704==    by 0xFA3FE5: wayland_backend::sys::client_impl::InnerBackend::connect (mod.rs:228)
==10704==    by 0xFAE1A9: wayland_backend::sys::client::Backend::connect (client_api.rs:164)
==10704==    by 0xF7B13C: wayland_client::conn::Connection::connect_to_env (conn.rs:92)
==10704==    by 0x3D7E80: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new (mod.rs:81)
==10704==    by 0x472DA9: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread (mod.rs:793)
==10704==    by 0x4730CC: winit::platform_impl::platform::EventLoop<T>::new (mod.rs:785)
==10704==    by 0x4B4DAC: winit::event_loop::EventLoopBuilder<T>::build (event_loop.rs:128)
==10704==    by 0x495924: alacritty::alacritty (main.rs:129)
==10704==    by 0x495049: alacritty::main (main.rs:85)
==10704==    by 0x4BFCAA: core::ops::function::FnOnce::call_once (function.rs:250)
==10704==
==10704== Invalid write of size 4
==10704==    at 0x4860451: UnknownInlinedFun (connection.c:389)
==10704==    by 0x4860451: UnknownInlinedFun (connection.c:1231)
==10704==    by 0x4860451: wl_proxy_marshal_array_flags (wayland-client.c:891)
==10704==    by 0xFA7368: wayland_backend::sys::client_impl::InnerBackend::send_request (mod.rs:637)
==10704==    by 0xFAE23F: wayland_backend::sys::client::Backend::send_request (client_api.rs:234)
==10704==    by 0xF2A6B4: wayland_client::conn::Connection::send_request (conn.rs:204)
==10704==    by 0xF4CD50: wayland_protocols::wp::primary_selection::zv1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1::destroy (protocol_macro.rs:28)
==10704==    by 0xEE885A: <smithay_client_toolkit::primary_selection::PrimarySelectionManagerState as core::ops::drop::Drop>::drop (mod.rs:80)
==10704==    by 0x724DC6: core::ptr::drop_in_place<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState> (mod.rs:497)
==10704==    by 0x720C45: core::ptr::drop_in_place<core::option::Option<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState>> (mod.rs:497)
==10704==    by 0x72369D: core::ptr::drop_in_place<smithay_clipboard::state::State> (mod.rs:497)
==10704==    by 0x6F5A24: smithay_clipboard::worker::worker_impl (worker.rs:104)
==10704==    by 0x6F544F: smithay_clipboard::worker::spawn::{{closure}} (worker.rs:23)
==10704==    by 0x6E3B08: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:154)
==10704==  Address 0x508a654 is 16,420 bytes inside a block of size 16,424 free'd
==10704==    at 0x484412F: free (vg_replace_malloc.c:974)
==10704==    by 0x485E27B: UnknownInlinedFun (connection.c:216)
==10704==    by 0x485E27B: wl_display_disconnect (wayland-client.c:1320)
==10704==    by 0xFABC35: <wayland_backend::sys::client_impl::ConnectionState as core::ops::drop::Drop>::drop (mod.rs:1022)
==10704==    by 0xFBA826: core::ptr::drop_in_place<wayland_backend::sys::client_impl::ConnectionState> (mod.rs:497)
==10704==    by 0xFB9D4A: core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFB9D9E: core::ptr::drop_in_place<std::sync::mutex::Mutex<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFBA61A: core::ptr::drop_in_place<wayland_backend::sys::client_impl::Inner> (mod.rs:497)
==10704==    by 0xF9FDDE: alloc::sync::Arc<T,A>::drop_slow (sync.rs:1749)
==10704==    by 0xFA04B4: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop (sync.rs:2405)
==10704==    by 0xFBAACA: core::ptr::drop_in_place<alloc::sync::Arc<wayland_backend::sys::client_impl::Inner>> (mod.rs:497)
==10704==    by 0xFBA6EA: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerBackend> (mod.rs:497)
==10704==    by 0xFBA56A: core::ptr::drop_in_place<wayland_backend::sys::client::Backend> (mod.rs:497)
==10704==  Block was alloc'd at
==10704==    at 0x48469B3: calloc (vg_replace_malloc.c:1554)
==10704==    by 0x4860EC6: UnknownInlinedFun (wayland-private.h:234)
==10704==    by 0x4860EC6: UnknownInlinedFun (connection.c:174)
==10704==    by 0x4860EC6: wl_display_connect_to_fd (wayland-client.c:1233)
==10704==    by 0xFA3FE5: wayland_backend::sys::client_impl::InnerBackend::connect (mod.rs:228)
==10704==    by 0xFAE1A9: wayland_backend::sys::client::Backend::connect (client_api.rs:164)
==10704==    by 0xF7B13C: wayland_client::conn::Connection::connect_to_env (conn.rs:92)
==10704==    by 0x3D7E80: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new (mod.rs:81)
==10704==    by 0x472DA9: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread (mod.rs:793)
==10704==    by 0x4730CC: winit::platform_impl::platform::EventLoop<T>::new (mod.rs:785)
==10704==    by 0x4B4DAC: winit::event_loop::EventLoopBuilder<T>::build (event_loop.rs:128)
==10704==    by 0x495924: alacritty::alacritty (main.rs:129)
==10704==    by 0x495049: alacritty::main (main.rs:85)
==10704==    by 0x4BFCAA: core::ops::function::FnOnce::call_once (function.rs:250)
==10704==
==10704== Invalid read of size 4
==10704==    at 0x4B39744: __pthread_mutex_unlock_usercnt (pthread_mutex_unlock.c:51)
==10704==    by 0x485FE7A: wl_proxy_marshal_array_flags (wayland-client.c:902)
==10704==    by 0xFA7368: wayland_backend::sys::client_impl::InnerBackend::send_request (mod.rs:637)
==10704==    by 0xFAE23F: wayland_backend::sys::client::Backend::send_request (client_api.rs:234)
==10704==    by 0xF2A6B4: wayland_client::conn::Connection::send_request (conn.rs:204)
==10704==    by 0xF4CD50: wayland_protocols::wp::primary_selection::zv1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1::destroy (protocol_macro.rs:28)
==10704==    by 0xEE885A: <smithay_client_toolkit::primary_selection::PrimarySelectionManagerState as core::ops::drop::Drop>::drop (mod.rs:80)
==10704==    by 0x724DC6: core::ptr::drop_in_place<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState> (mod.rs:497)
==10704==    by 0x720C45: core::ptr::drop_in_place<core::option::Option<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState>> (mod.rs:497)
==10704==    by 0x72369D: core::ptr::drop_in_place<smithay_clipboard::state::State> (mod.rs:497)
==10704==    by 0x6F5A24: smithay_clipboard::worker::worker_impl (worker.rs:104)
==10704==    by 0x6F544F: smithay_clipboard::worker::spawn::{{closure}} (worker.rs:23)
==10704==  Address 0x5086548 is 296 bytes inside a block of size 376 free'd
==10704==    at 0x484412F: free (vg_replace_malloc.c:974)
==10704==    by 0xFABC35: <wayland_backend::sys::client_impl::ConnectionState as core::ops::drop::Drop>::drop (mod.rs:1022)
==10704==    by 0xFBA826: core::ptr::drop_in_place<wayland_backend::sys::client_impl::ConnectionState> (mod.rs:497)
==10704==    by 0xFB9D4A: core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFB9D9E: core::ptr::drop_in_place<std::sync::mutex::Mutex<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFBA61A: core::ptr::drop_in_place<wayland_backend::sys::client_impl::Inner> (mod.rs:497)
==10704==    by 0xF9FDDE: alloc::sync::Arc<T,A>::drop_slow (sync.rs:1749)
==10704==    by 0xFA04B4: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop (sync.rs:2405)
==10704==    by 0xFBAACA: core::ptr::drop_in_place<alloc::sync::Arc<wayland_backend::sys::client_impl::Inner>> (mod.rs:497)
==10704==    by 0xFBA6EA: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerBackend> (mod.rs:497)
==10704==    by 0xFBA56A: core::ptr::drop_in_place<wayland_backend::sys::client::Backend> (mod.rs:497)
==10704==    by 0xF98ABA: core::ptr::drop_in_place<wayland_client::conn::Connection> (mod.rs:497)
==10704==  Block was alloc'd at
==10704==    at 0x48469B3: calloc (vg_replace_malloc.c:1554)
==10704==    by 0x4860D95: UnknownInlinedFun (wayland-private.h:234)
==10704==    by 0x4860D95: wl_display_connect_to_fd (wayland-client.c:1183)
==10704==    by 0xFA3FE5: wayland_backend::sys::client_impl::InnerBackend::connect (mod.rs:228)
==10704==    by 0xFAE1A9: wayland_backend::sys::client::Backend::connect (client_api.rs:164)
==10704==    by 0xF7B13C: wayland_client::conn::Connection::connect_to_env (conn.rs:92)
==10704==    by 0x3D7E80: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new (mod.rs:81)
==10704==    by 0x472DA9: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread (mod.rs:793)
==10704==    by 0x4730CC: winit::platform_impl::platform::EventLoop<T>::new (mod.rs:785)
==10704==    by 0x4B4DAC: winit::event_loop::EventLoopBuilder<T>::build (event_loop.rs:128)
==10704==    by 0x495924: alacritty::alacritty (main.rs:129)
==10704==    by 0x495049: alacritty::main (main.rs:85)
==10704==    by 0x4BFCAA: core::ops::function::FnOnce::call_once (function.rs:250)
==10704==
==10704== Invalid read of size 4
==10704==    at 0x4B397C0: __pthread_mutex_unlock_usercnt (pthread_mutex_unlock.c:55)
==10704==    by 0x485FE7A: wl_proxy_marshal_array_flags (wayland-client.c:902)
==10704==    by 0xFA7368: wayland_backend::sys::client_impl::InnerBackend::send_request (mod.rs:637)
==10704==    by 0xFAE23F: wayland_backend::sys::client::Backend::send_request (client_api.rs:234)
==10704==    by 0xF2A6B4: wayland_client::conn::Connection::send_request (conn.rs:204)
==10704==    by 0xF4CD50: wayland_protocols::wp::primary_selection::zv1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1::destroy (protocol_macro.rs:28)
==10704==    by 0xEE885A: <smithay_client_toolkit::primary_selection::PrimarySelectionManagerState as core::ops::drop::Drop>::drop (mod.rs:80)
==10704==    by 0x724DC6: core::ptr::drop_in_place<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState> (mod.rs:497)
==10704==    by 0x720C45: core::ptr::drop_in_place<core::option::Option<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState>> (mod.rs:497)
==10704==    by 0x72369D: core::ptr::drop_in_place<smithay_clipboard::state::State> (mod.rs:497)
==10704==    by 0x6F5A24: smithay_clipboard::worker::worker_impl (worker.rs:104)
==10704==    by 0x6F544F: smithay_clipboard::worker::spawn::{{closure}} (worker.rs:23)
==10704==  Address 0x5086548 is 296 bytes inside a block of size 376 free'd
==10704==    at 0x484412F: free (vg_replace_malloc.c:974)
==10704==    by 0xFABC35: <wayland_backend::sys::client_impl::ConnectionState as core::ops::drop::Drop>::drop (mod.rs:1022)
==10704==    by 0xFBA826: core::ptr::drop_in_place<wayland_backend::sys::client_impl::ConnectionState> (mod.rs:497)
==10704==    by 0xFB9D4A: core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFB9D9E: core::ptr::drop_in_place<std::sync::mutex::Mutex<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFBA61A: core::ptr::drop_in_place<wayland_backend::sys::client_impl::Inner> (mod.rs:497)
==10704==    by 0xF9FDDE: alloc::sync::Arc<T,A>::drop_slow (sync.rs:1749)
==10704==    by 0xFA04B4: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop (sync.rs:2405)
==10704==    by 0xFBAACA: core::ptr::drop_in_place<alloc::sync::Arc<wayland_backend::sys::client_impl::Inner>> (mod.rs:497)
==10704==    by 0xFBA6EA: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerBackend> (mod.rs:497)
==10704==    by 0xFBA56A: core::ptr::drop_in_place<wayland_backend::sys::client::Backend> (mod.rs:497)
==10704==    by 0xF98ABA: core::ptr::drop_in_place<wayland_client::conn::Connection> (mod.rs:497)
==10704==  Block was alloc'd at
==10704==    at 0x48469B3: calloc (vg_replace_malloc.c:1554)
==10704==    by 0x4860D95: UnknownInlinedFun (wayland-private.h:234)
==10704==    by 0x4860D95: wl_display_connect_to_fd (wayland-client.c:1183)
==10704==    by 0xFA3FE5: wayland_backend::sys::client_impl::InnerBackend::connect (mod.rs:228)
==10704==    by 0xFAE1A9: wayland_backend::sys::client::Backend::connect (client_api.rs:164)
==10704==    by 0xF7B13C: wayland_client::conn::Connection::connect_to_env (conn.rs:92)
==10704==    by 0x3D7E80: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new (mod.rs:81)
==10704==    by 0x472DA9: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread (mod.rs:793)
==10704==    by 0x4730CC: winit::platform_impl::platform::EventLoop<T>::new (mod.rs:785)
==10704==    by 0x4B4DAC: winit::event_loop::EventLoopBuilder<T>::build (event_loop.rs:128)
==10704==    by 0x495924: alacritty::alacritty (main.rs:129)
==10704==    by 0x495049: alacritty::main (main.rs:85)
==10704==    by 0x4BFCAA: core::ops::function::FnOnce::call_once (function.rs:250)
==10704==
==10704== Invalid read of size 4
==10704==    at 0x4B37DB4: pthread_mutex_lock@@GLIBC_2.2.5 (pthread_mutex_lock.c:80)
==10704==    by 0x485E6B0: wl_proxy_destroy (wayland-client.c:583)
==10704==    by 0xFA7DB2: wayland_backend::sys::client_impl::InnerBackend::send_request (mod.rs:739)
==10704==    by 0xFAE23F: wayland_backend::sys::client::Backend::send_request (client_api.rs:234)
==10704==    by 0xF2A6B4: wayland_client::conn::Connection::send_request (conn.rs:204)
==10704==    by 0xF4CD50: wayland_protocols::wp::primary_selection::zv1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1::destroy (protocol_macro.rs:28)
==10704==    by 0xEE885A: <smithay_client_toolkit::primary_selection::PrimarySelectionManagerState as core::ops::drop::Drop>::drop (mod.rs:80)
==10704==    by 0x724DC6: core::ptr::drop_in_place<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState> (mod.rs:497)
==10704==    by 0x720C45: core::ptr::drop_in_place<core::option::Option<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState>> (mod.rs:497)
==10704==    by 0x72369D: core::ptr::drop_in_place<smithay_clipboard::state::State> (mod.rs:497)
==10704==    by 0x6F5A24: smithay_clipboard::worker::worker_impl (worker.rs:104)
==10704==    by 0x6F544F: smithay_clipboard::worker::spawn::{{closure}} (worker.rs:23)
==10704==  Address 0x5086548 is 296 bytes inside a block of size 376 free'd
==10704==    at 0x484412F: free (vg_replace_malloc.c:974)
==10704==    by 0xFABC35: <wayland_backend::sys::client_impl::ConnectionState as core::ops::drop::Drop>::drop (mod.rs:1022)
==10704==    by 0xFBA826: core::ptr::drop_in_place<wayland_backend::sys::client_impl::ConnectionState> (mod.rs:497)
==10704==    by 0xFB9D4A: core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFB9D9E: core::ptr::drop_in_place<std::sync::mutex::Mutex<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFBA61A: core::ptr::drop_in_place<wayland_backend::sys::client_impl::Inner> (mod.rs:497)
==10704==    by 0xF9FDDE: alloc::sync::Arc<T,A>::drop_slow (sync.rs:1749)
==10704==    by 0xFA04B4: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop (sync.rs:2405)
==10704==    by 0xFBAACA: core::ptr::drop_in_place<alloc::sync::Arc<wayland_backend::sys::client_impl::Inner>> (mod.rs:497)
==10704==    by 0xFBA6EA: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerBackend> (mod.rs:497)
==10704==    by 0xFBA56A: core::ptr::drop_in_place<wayland_backend::sys::client::Backend> (mod.rs:497)
==10704==    by 0xF98ABA: core::ptr::drop_in_place<wayland_client::conn::Connection> (mod.rs:497)
==10704==  Block was alloc'd at
==10704==    at 0x48469B3: calloc (vg_replace_malloc.c:1554)
==10704==    by 0x4860D95: UnknownInlinedFun (wayland-private.h:234)
==10704==    by 0x4860D95: wl_display_connect_to_fd (wayland-client.c:1183)
==10704==    by 0xFA3FE5: wayland_backend::sys::client_impl::InnerBackend::connect (mod.rs:228)
==10704==    by 0xFAE1A9: wayland_backend::sys::client::Backend::connect (client_api.rs:164)
==10704==    by 0xF7B13C: wayland_client::conn::Connection::connect_to_env (conn.rs:92)
==10704==    by 0x3D7E80: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new (mod.rs:81)
==10704==    by 0x472DA9: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread (mod.rs:793)
==10704==    by 0x4730CC: winit::platform_impl::platform::EventLoop<T>::new (mod.rs:785)
==10704==    by 0x4B4DAC: winit::event_loop::EventLoopBuilder<T>::build (event_loop.rs:128)
==10704==    by 0x495924: alacritty::alacritty (main.rs:129)
==10704==    by 0x495049: alacritty::main (main.rs:85)
==10704==    by 0x4BFCAA: core::ops::function::FnOnce::call_once (function.rs:250)
==10704==
==10704== Invalid read of size 4
==10704==    at 0x4B376BD: __pthread_mutex_lock_full (pthread_mutex_lock.c:198)
==10704==    by 0x485E6B0: wl_proxy_destroy (wayland-client.c:583)
==10704==    by 0xFA7DB2: wayland_backend::sys::client_impl::InnerBackend::send_request (mod.rs:739)
==10704==    by 0xFAE23F: wayland_backend::sys::client::Backend::send_request (client_api.rs:234)
==10704==    by 0xF2A6B4: wayland_client::conn::Connection::send_request (conn.rs:204)
==10704==    by 0xF4CD50: wayland_protocols::wp::primary_selection::zv1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1::destroy (protocol_macro.rs:28)
==10704==    by 0xEE885A: <smithay_client_toolkit::primary_selection::PrimarySelectionManagerState as core::ops::drop::Drop>::drop (mod.rs:80)
==10704==    by 0x724DC6: core::ptr::drop_in_place<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState> (mod.rs:497)
==10704==    by 0x720C45: core::ptr::drop_in_place<core::option::Option<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState>> (mod.rs:497)
==10704==    by 0x72369D: core::ptr::drop_in_place<smithay_clipboard::state::State> (mod.rs:497)
==10704==    by 0x6F5A24: smithay_clipboard::worker::worker_impl (worker.rs:104)
==10704==    by 0x6F544F: smithay_clipboard::worker::spawn::{{closure}} (worker.rs:23)
==10704==  Address 0x5086548 is 296 bytes inside a block of size 376 free'd
==10704==    at 0x484412F: free (vg_replace_malloc.c:974)
==10704==    by 0xFABC35: <wayland_backend::sys::client_impl::ConnectionState as core::ops::drop::Drop>::drop (mod.rs:1022)
==10704==    by 0xFBA826: core::ptr::drop_in_place<wayland_backend::sys::client_impl::ConnectionState> (mod.rs:497)
==10704==    by 0xFB9D4A: core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFB9D9E: core::ptr::drop_in_place<std::sync::mutex::Mutex<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFBA61A: core::ptr::drop_in_place<wayland_backend::sys::client_impl::Inner> (mod.rs:497)
==10704==    by 0xF9FDDE: alloc::sync::Arc<T,A>::drop_slow (sync.rs:1749)
==10704==    by 0xFA04B4: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop (sync.rs:2405)
==10704==    by 0xFBAACA: core::ptr::drop_in_place<alloc::sync::Arc<wayland_backend::sys::client_impl::Inner>> (mod.rs:497)
==10704==    by 0xFBA6EA: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerBackend> (mod.rs:497)
==10704==    by 0xFBA56A: core::ptr::drop_in_place<wayland_backend::sys::client::Backend> (mod.rs:497)
==10704==    by 0xF98ABA: core::ptr::drop_in_place<wayland_client::conn::Connection> (mod.rs:497)
==10704==  Block was alloc'd at
==10704==    at 0x48469B3: calloc (vg_replace_malloc.c:1554)
==10704==    by 0x4860D95: UnknownInlinedFun (wayland-private.h:234)
==10704==    by 0x4860D95: wl_display_connect_to_fd (wayland-client.c:1183)
==10704==    by 0xFA3FE5: wayland_backend::sys::client_impl::InnerBackend::connect (mod.rs:228)
==10704==    by 0xFAE1A9: wayland_backend::sys::client::Backend::connect (client_api.rs:164)
==10704==    by 0xF7B13C: wayland_client::conn::Connection::connect_to_env (conn.rs:92)
==10704==    by 0x3D7E80: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new (mod.rs:81)
==10704==    by 0x472DA9: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread (mod.rs:793)
==10704==    by 0x4730CC: winit::platform_impl::platform::EventLoop<T>::new (mod.rs:785)
==10704==    by 0x4B4DAC: winit::event_loop::EventLoopBuilder<T>::build (event_loop.rs:128)
==10704==    by 0x495924: alacritty::alacritty (main.rs:129)
==10704==    by 0x495049: alacritty::main (main.rs:85)
==10704==    by 0x4BFCAA: core::ops::function::FnOnce::call_once (function.rs:250)
==10704==
==10704== Invalid read of size 8
==10704==    at 0x485E3FA: wl_map_insert_at (wayland-util.c:263)
==10704==    by 0x485E572: proxy_destroy (wayland-client.c:538)
==10704==    by 0x485E6BE: UnknownInlinedFun (wayland-client.c:562)
==10704==    by 0x485E6BE: wl_proxy_destroy (wayland-client.c:585)
==10704==    by 0xFA7DB2: wayland_backend::sys::client_impl::InnerBackend::send_request (mod.rs:739)
==10704==    by 0xFAE23F: wayland_backend::sys::client::Backend::send_request (client_api.rs:234)
==10704==    by 0xF2A6B4: wayland_client::conn::Connection::send_request (conn.rs:204)
==10704==    by 0xF4CD50: wayland_protocols::wp::primary_selection::zv1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1::destroy (protocol_macro.rs:28)
==10704==    by 0xEE885A: <smithay_client_toolkit::primary_selection::PrimarySelectionManagerState as core::ops::drop::Drop>::drop (mod.rs:80)
==10704==    by 0x724DC6: core::ptr::drop_in_place<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState> (mod.rs:497)
==10704==    by 0x720C45: core::ptr::drop_in_place<core::option::Option<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState>> (mod.rs:497)
==10704==    by 0x72369D: core::ptr::drop_in_place<smithay_clipboard::state::State> (mod.rs:497)
==10704==    by 0x6F5A24: smithay_clipboard::worker::worker_impl (worker.rs:104)
==10704==  Address 0x50864b0 is 144 bytes inside a block of size 376 free'd
==10704==    at 0x484412F: free (vg_replace_malloc.c:974)
==10704==    by 0xFABC35: <wayland_backend::sys::client_impl::ConnectionState as core::ops::drop::Drop>::drop (mod.rs:1022)
==10704==    by 0xFBA826: core::ptr::drop_in_place<wayland_backend::sys::client_impl::ConnectionState> (mod.rs:497)
==10704==    by 0xFB9D4A: core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFB9D9E: core::ptr::drop_in_place<std::sync::mutex::Mutex<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFBA61A: core::ptr::drop_in_place<wayland_backend::sys::client_impl::Inner> (mod.rs:497)
==10704==    by 0xF9FDDE: alloc::sync::Arc<T,A>::drop_slow (sync.rs:1749)
==10704==    by 0xFA04B4: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop (sync.rs:2405)
==10704==    by 0xFBAACA: core::ptr::drop_in_place<alloc::sync::Arc<wayland_backend::sys::client_impl::Inner>> (mod.rs:497)
==10704==    by 0xFBA6EA: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerBackend> (mod.rs:497)
==10704==    by 0xFBA56A: core::ptr::drop_in_place<wayland_backend::sys::client::Backend> (mod.rs:497)
==10704==    by 0xF98ABA: core::ptr::drop_in_place<wayland_client::conn::Connection> (mod.rs:497)
==10704==  Block was alloc'd at
==10704==    at 0x48469B3: calloc (vg_replace_malloc.c:1554)
==10704==    by 0x4860D95: UnknownInlinedFun (wayland-private.h:234)
==10704==    by 0x4860D95: wl_display_connect_to_fd (wayland-client.c:1183)
==10704==    by 0xFA3FE5: wayland_backend::sys::client_impl::InnerBackend::connect (mod.rs:228)
==10704==    by 0xFAE1A9: wayland_backend::sys::client::Backend::connect (client_api.rs:164)
==10704==    by 0xF7B13C: wayland_client::conn::Connection::connect_to_env (conn.rs:92)
==10704==    by 0x3D7E80: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new (mod.rs:81)
==10704==    by 0x472DA9: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread (mod.rs:793)
==10704==    by 0x4730CC: winit::platform_impl::platform::EventLoop<T>::new (mod.rs:785)
==10704==    by 0x4B4DAC: winit::event_loop::EventLoopBuilder<T>::build (event_loop.rs:128)
==10704==    by 0x495924: alacritty::alacritty (main.rs:129)
==10704==    by 0x495049: alacritty::main (main.rs:85)
==10704==    by 0x4BFCAA: core::ops::function::FnOnce::call_once (function.rs:250)
==10704==
==10704== Invalid read of size 8
==10704==    at 0x485E40A: wl_map_insert_at (wayland-util.c:276)
==10704==    by 0x485E572: proxy_destroy (wayland-client.c:538)
==10704==    by 0x485E6BE: UnknownInlinedFun (wayland-client.c:562)
==10704==    by 0x485E6BE: wl_proxy_destroy (wayland-client.c:585)
==10704==    by 0xFA7DB2: wayland_backend::sys::client_impl::InnerBackend::send_request (mod.rs:739)
==10704==    by 0xFAE23F: wayland_backend::sys::client::Backend::send_request (client_api.rs:234)
==10704==    by 0xF2A6B4: wayland_client::conn::Connection::send_request (conn.rs:204)
==10704==    by 0xF4CD50: wayland_protocols::wp::primary_selection::zv1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1::destroy (protocol_macro.rs:28)
==10704==    by 0xEE885A: <smithay_client_toolkit::primary_selection::PrimarySelectionManagerState as core::ops::drop::Drop>::drop (mod.rs:80)
==10704==    by 0x724DC6: core::ptr::drop_in_place<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState> (mod.rs:497)
==10704==    by 0x720C45: core::ptr::drop_in_place<core::option::Option<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState>> (mod.rs:497)
==10704==    by 0x72369D: core::ptr::drop_in_place<smithay_clipboard::state::State> (mod.rs:497)
==10704==    by 0x6F5A24: smithay_clipboard::worker::worker_impl (worker.rs:104)
==10704==  Address 0x50864c0 is 160 bytes inside a block of size 376 free'd
==10704==    at 0x484412F: free (vg_replace_malloc.c:974)
==10704==    by 0xFABC35: <wayland_backend::sys::client_impl::ConnectionState as core::ops::drop::Drop>::drop (mod.rs:1022)
==10704==    by 0xFBA826: core::ptr::drop_in_place<wayland_backend::sys::client_impl::ConnectionState> (mod.rs:497)
==10704==    by 0xFB9D4A: core::ptr::drop_in_place<core::cell::UnsafeCell<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFB9D9E: core::ptr::drop_in_place<std::sync::mutex::Mutex<wayland_backend::sys::client_impl::ConnectionState>> (mod.rs:497)
==10704==    by 0xFBA61A: core::ptr::drop_in_place<wayland_backend::sys::client_impl::Inner> (mod.rs:497)
==10704==    by 0xF9FDDE: alloc::sync::Arc<T,A>::drop_slow (sync.rs:1749)
==10704==    by 0xFA04B4: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop (sync.rs:2405)
==10704==    by 0xFBAACA: core::ptr::drop_in_place<alloc::sync::Arc<wayland_backend::sys::client_impl::Inner>> (mod.rs:497)
==10704==    by 0xFBA6EA: core::ptr::drop_in_place<wayland_backend::sys::client_impl::InnerBackend> (mod.rs:497)
==10704==    by 0xFBA56A: core::ptr::drop_in_place<wayland_backend::sys::client::Backend> (mod.rs:497)
==10704==    by 0xF98ABA: core::ptr::drop_in_place<wayland_client::conn::Connection> (mod.rs:497)
==10704==  Block was alloc'd at
==10704==    at 0x48469B3: calloc (vg_replace_malloc.c:1554)
==10704==    by 0x4860D95: UnknownInlinedFun (wayland-private.h:234)
==10704==    by 0x4860D95: wl_display_connect_to_fd (wayland-client.c:1183)
==10704==    by 0xFA3FE5: wayland_backend::sys::client_impl::InnerBackend::connect (mod.rs:228)
==10704==    by 0xFAE1A9: wayland_backend::sys::client::Backend::connect (client_api.rs:164)
==10704==    by 0xF7B13C: wayland_client::conn::Connection::connect_to_env (conn.rs:92)
==10704==    by 0x3D7E80: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::new (mod.rs:81)
==10704==    by 0x472DA9: winit::platform_impl::platform::EventLoop<T>::new_wayland_any_thread (mod.rs:793)
==10704==    by 0x4730CC: winit::platform_impl::platform::EventLoop<T>::new (mod.rs:785)
==10704==    by 0x4B4DAC: winit::event_loop::EventLoopBuilder<T>::build (event_loop.rs:128)
==10704==    by 0x495924: alacritty::alacritty (main.rs:129)
==10704==    by 0x495049: alacritty::main (main.rs:85)
==10704==    by 0x4BFCAA: core::ops::function::FnOnce::call_once (function.rs:250)
==10704==
==10704== Invalid write of size 8
==10704==    at 0x485E415: wl_map_insert_at (wayland-util.c:276)
==10704==    by 0x485E572: proxy_destroy (wayland-client.c:538)
==10704==    by 0x485E6BE: UnknownInlinedFun (wayland-client.c:562)
==10704==    by 0x485E6BE: wl_proxy_destroy (wayland-client.c:585)
==10704==    by 0xFA7DB2: wayland_backend::sys::client_impl::InnerBackend::send_request (mod.rs:739)
==10704==    by 0xFAE23F: wayland_backend::sys::client::Backend::send_request (client_api.rs:234)
==10704==    by 0xF2A6B4: wayland_client::conn::Connection::send_request (conn.rs:204)
==10704==    by 0xF4CD50: wayland_protocols::wp::primary_selection::zv1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1::destroy (protocol_macro.rs:28)
==10704==    by 0xEE885A: <smithay_client_toolkit::primary_selection::PrimarySelectionManagerState as core::ops::drop::Drop>::drop (mod.rs:80)
==10704==    by 0x724DC6: core::ptr::drop_in_place<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState> (mod.rs:497)
==10704==    by 0x720C45: core::ptr::drop_in_place<core::option::Option<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState>> (mod.rs:497)
==10704==    by 0x72369D: core::ptr::drop_in_place<smithay_clipboard::state::State> (mod.rs:497)
==10704==    by 0x6F5A24: smithay_clipboard::worker::worker_impl (worker.rs:104)
==10704==  Address 0xec is not stack'd, malloc'd or (recently) free'd
==10704==
==10704==
==10704== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==10704==  Access not within mapped region at address 0x11E
==10704==    at 0x485E415: wl_map_insert_at (wayland-util.c:276)
==10704==    by 0x485E572: proxy_destroy (wayland-client.c:538)
==10704==    by 0x485E6BE: UnknownInlinedFun (wayland-client.c:562)
==10704==    by 0x485E6BE: wl_proxy_destroy (wayland-client.c:585)
==10704==    by 0xFA7DB2: wayland_backend::sys::client_impl::InnerBackend::send_request (mod.rs:739)
==10704==    by 0xFAE23F: wayland_backend::sys::client::Backend::send_request (client_api.rs:234)
==10704==    by 0xF2A6B4: wayland_client::conn::Connection::send_request (conn.rs:204)
==10704==    by 0xF4CD50: wayland_protocols::wp::primary_selection::zv1::generated::client::zwp_primary_selection_device_manager_v1::ZwpPrimarySelectionDeviceManagerV1::destroy (protocol_macro.rs:28)
==10704==    by 0xEE885A: <smithay_client_toolkit::primary_selection::PrimarySelectionManagerState as core::ops::drop::Drop>::drop (mod.rs:80)
==10704==    by 0x724DC6: core::ptr::drop_in_place<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState> (mod.rs:497)
==10704==    by 0x720C45: core::ptr::drop_in_place<core::option::Option<smithay_client_toolkit::primary_selection::PrimarySelectionManagerState>> (mod.rs:497)
==10704==    by 0x72369D: core::ptr::drop_in_place<smithay_clipboard::state::State> (mod.rs:497)
==10704==    by 0x6F5A24: smithay_clipboard::worker::worker_impl (worker.rs:104)
```

### PR DESCRIPTION
**Pull request by kchibisov**
Fixes #7309.

### CODE REVIEW

File: alacritty/src/event.rs [hunk 1]
```diff
@@ -1551,14 +1552,15 @@ impl Processor {
...
 
-        // NOTE: Since this takes a pointer to the winit event loop, it MUST be dropped first.
-        let mut clipboard = unsafe { Clipboard::new(event_loop.raw_display_handle()) };
-
         // Disable all device events, since we don't care about them.
         event_loop.listen_device_events(DeviceEvents::Never);
 
-        let mut initial_window_error = Ok(());
-        let result = event_loop.run(|event, event_loop| {
+        let initial_window_error = Rc::new(RefCell::new(Ok(())));
```
Comment (chrisduerr) [inline alacritty/src/event.rs:1558]: Why was this changed, because of the `move`?

**Review by chrisduerr — CHANGES_REQUESTED** [review]

File: alacritty/src/event.rs (hunk 1 above)
Comment (kchibisov) [reply alacritty/src/event.rs:1558]: yes.

Comment (kchibisov) [reply alacritty/src/event.rs:1558]: `run` moves the `event_loop` however, the closure itself could be non-movable, but we need to `move` the clipboard into the closure so it's dropped before event loop is being dropped.

Unfortunately, we can't capture just one thing by ref...

Comment (chrisduerr) [reply alacritty/src/event.rs:1558]: There's no need for `Rc` or `RefCell`. Instead of cloning it you can just move a mutable reference into the event loop and that works just fine (I tested it).

**Review by chrisduerr — CHANGES_REQUESTED** [review]

File: alacritty/src/event.rs (hunk 1 above)
Comment (kchibisov) [reply alacritty/src/event.rs]: Ah, the closure is `FnMut` so we can do that. With `FnOnce` you can't iirc.

**Review by chrisduerr — APPROVED** [review]
