### PR TITLE
Fix reflow of empty wrapped cursor line

### LINKED ISSUE #3583: Reflow deleting history
When holding <kbd>space</kbd> until the cursor is on the next line of the prompt, then growing the shell width, content above the cursor will be deleted and the cursor is moved upwards.

Repro:
 * run `bash` or `zsh` (only ones tested, others probably also affected)
 * `ls -lah` to write some content
 * <kbd>space</kbd> until on the next line
 * grow terminal width
   -> The `ls` content is deleted

### PR DESCRIPTION
**Pull request by chrisduerr**
This bug was caused by trying to grow the terminal while the cursor line
was wrapped but entirely empty. Resizing the terminal now accounts for
the position of the deleted line and moves the cursor up only when the
line deleted was above it.

The deletion of the line was caused by the shell redrawing itself
whenever the cursor is moved.

Fixes #3583.

### CODE REVIEW

File: alacritty_terminal/src/grid/mod.rs [hunk 1]
```diff
@@ -187,11 +187,6 @@ impl<T: GridCell + Default + PartialEq + Copy> Grid<T> {
         Point { line: self.lines.0 + self.display_offset - point.line.0 - 1, col: point.col }
     }
 
-    /// Return the cursor position in buffer coordinates.
-    pub fn cursor_buffer_point(&self) -> Point<usize> {
-        Point { line: self.lines.0 - self.cursor.point.line.0 - 1, col: self.cursor.point.col }
-    }
```
Comment (chrisduerr) [inline alacritty_terminal/src/grid/mod.rs:193]: I've considered what to do with this function and decided to remove it.

If we'd want to keep the function, we'd have to basically create the same function but for the saved cursor, which seems a bit annoying. Alternatively we could of course create a generic function and pass a point to it, but I feel like at that point it's easier to just compute things ourselves. Especially because **all** instances where we need this currently only require the line, not the column.

What do you think @kchibisov?

Comment (kchibisov) [reply alacritty_terminal/src/grid/mod.rs:193]: It fine to just remove it.

**Comment by kchibisov** [comment]
Seems to crash now in debug build. Just typing `ls -lah` putting cursor and resize to some small size causes that issue.

```
thread 'main' panicked at 'attempt to subtract with overflow', /home/kchibisov/src/rust/alacritty-workspace/repo/alacritty_terminal/src/index.rs:420:28
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::panicking::panic
             at src/libcore/panicking.rs:54
  14: <alacritty_terminal::index::Column as core::ops::arith::Sub<usize>>::sub
             at ./alacritty_terminal/src/index.rs:420
  15: alacritty_terminal::grid::resize::<impl alacritty_terminal::grid::Grid<T>>::grow_cols::{{closure}}
             at ./alacritty_terminal/src/grid/resize.rs:84
  16: alacritty_terminal::grid::resize::<impl alacritty_terminal::grid::Grid<T>>::grow_cols
             at ./alacritty_terminal/src/grid/resize.rs:97
  17: alacritty_terminal::grid::resize::<impl alacritty_terminal::grid::Grid<T>>::resize
             at ./alacritty_terminal/src/grid/resize.rs:21
  18: alacritty_terminal::term::Term<T>::resize
             at ./alacritty_terminal/src/term/mod.rs:1048
  19: alacritty::display::Display::handle_update
             at alacritty/src/display.rs:376
  20: alacritty::event::Processor<N>::run::{{closure}}
             at alacritty/src/event.rs:543
  21: winit::platform_impl::platform::sticky_exit_callback
             at /home/kchibisov/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:698
  22: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return
             at /home/kchibisov/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/wayland/event_loop.rs:537
  23: winit::platform_impl::platform::EventLoop<T>::run_return
             at /home/kchibisov/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:634
  24: <winit::event_loop::EventLoop<T> as winit::platform::desktop::EventLoopExtDesktop>::run_return
             at /home/kchibisov/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform/desktop.rs:51
  25: alacritty::event::Processor<N>::run
             at alacritty/src/event.rs:467
  26: alacritty::run
             at alacritty/src/main.rs:190
  27: alacritty::main
             at alacritty/src/main.rs:102
  28: std::rt::lang_start::{{closure}}
             at /home/kchibisov/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  29: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  30: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  31: std::panicking::try
             at src/libstd/panicking.rs:274
  32: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  33: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  34: std::rt::lang_start
             at /home/kchibisov/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  35: main
  36: __libc_start_main
             at ../csu/libc-start.c:308
  37: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'PTY reader' panicked at 'assertion failed: requested < self.len', /home/kchibisov/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:13:23
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: std::panicking::begin_panic
             at /home/kchibisov/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:438
  12: alacritty_terminal::grid::storage::Storage<T>::compute_index
             at /home/kchibisov/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:13
  13: <alacritty_terminal::grid::storage::Storage<T> as core::ops::index::IndexMut<usize>>::index_mut
             at ./alacritty_terminal/src/grid/storage.rs:276
  14: <alacritty_terminal::grid::storage::Storage<T> as core::ops::index::IndexMut<alacritty_terminal::index::Line>>::index_mut
             at ./alacritty_terminal/src/grid/storage.rs:295
  15: <alacritty_terminal::grid::Grid<T> as core::ops::index::IndexMut<alacritty_terminal::index::Line>>::index_mut
             at ./alacritty_terminal/src/grid/mod.rs:505
  16: <alacritty_terminal::term::Term<T> as alacritty_terminal::ansi::Handler>::clear_screen
             at ./alacritty_terminal/src/term/mod.rs:1883
  17: <alacritty_terminal::ansi::Performer<H,W> as vte::Perform>::csi_dispatch
             at ./alacritty_terminal/src/ansi.rs:1033
  18: vte::Parser::perform_action
             at /home/kchibisov/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.8.0/src/lib.rs:287
  19: vte::Parser::perform_state_change
             at /home/kchibisov/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.8.0/src/lib.rs:151
  20: vte::Parser::advance
             at /home/kchibisov/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.8.0/src/lib.rs:128
  21: alacritty_terminal::ansi::Processor::advance
             at ./alacritty_terminal/src/ansi.rs:128
  22: alacritty_terminal::event_loop::EventLoop<T,U>::pty_read
             at ./alacritty_terminal/src/event_loop.rs:246
  23: alacritty_terminal::event_loop::EventLoop<T,U>::spawn::{{closure}}
             at ./alacritty_terminal/src/event_loop.rs:365
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

File: alacritty_terminal/src/grid/resize.rs [hunk 2]
```diff
@@ -67,10 +67,12 @@ impl<T: GridCell + Default + PartialEq + Copy> Grid<T> {
             self.scroll_up(&(Line(0)..self.lines), Line(required_scrolling), T::default());
 
             // Clamp cursors to the new viewport size.
-            self.saved_cursor.point.line = min(self.saved_cursor.point.line, target - 1);
             self.cursor.point.line = min(self.cursor.point.line, target - 1);
         }
 
+        // Clamp saved cursor, since only primary cursor is scrolled into viewport.
+        self.saved_cursor.point.line = min(self.saved_cursor.point.line, target - 1);
```
Comment (chrisduerr) [inline alacritty_terminal/src/grid/resize.rs:74]: Note that this is partially necessary because of #3584, since we do not reflow the cursor ourselves.

File: alacritty_terminal/src/grid/resize.rs [hunk 3]
```diff
@@ -144,6 +147,16 @@ impl<T: GridCell + Default + PartialEq + Copy> Grid<T> {
...
+
+                    // Rotate cursors down if content below them was pulled from history.
+                    if i < cursor_buffer_line {
+                        self.cursor.point.line += 1;
+                    }
+
+                    let saved_buffer_line = (self.lines - self.saved_cursor.point.line - 1).0;
+                    if i < saved_buffer_line {
+                        self.saved_cursor.point.line += 1;
+                    }
```
Comment (chrisduerr) [inline alacritty_terminal/src/grid/resize.rs:159]: I'm not sure how important this is, since we usually don't expect content to be below the cursor during resize.

However since this does delete things *above* the cursor and not below it, I do think it makes some sense at least for `self.cursor`.

Comment (kchibisov) [reply alacritty_terminal/src/grid/resize.rs:159]: The content below the cursor doesn't matter and can be safely cleared most of the time (maybe not all the time though). Alt screen is completely different here, but we don't reflow it, so fine.
