### PR TITLE
Fix highlight invalidation on grid scroll

### LINKED ISSUE #7737: underline url moves as more lines are added to terminal output
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux/BSD/macOS/Windows
Version: `alacritty --version` output
Linux/BSD: X11/Wayland, DE or Compositor and WM

i3, `Linux p14s 6.6.10-1-MANJARO #1 SMP PREEMPT_DYNAMIC Fri Jan  5 17:38:36 UTC 2024 x86_64 GNU/Linux`

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv` `alacritty 0.14.0-dev (f1853a03)`
Keyboard and bindings: `alacritty --print-events`

1) run this in your term:
```
while `sleep 0.5` ; do ; echo "`date` https://www.github.com" ; done
```
2) move your cursor on top of one of the urls
3) scroll upwards a bit
=> as more lines are added, the highlight will "move" to keep the same distance relative to the freshest line, so its no longer the actual lined underneath the cursor :laughing:

### PR DESCRIPTION
**Pull request by chrisduerr**
This fixes an issue where hints highlighted by vi or mouse cursor would
produce an underline on the incorrect line since the highlights only
store the initial match boundaries without accounting for new content
scrolling the terminal.

This patch takes the approach of adding a marker ID to one cell in the
hint, allowing us to verify with a single cell check whether the
contents of the hint boundaries could have changed.

This works pretty reliably, but comes with a set of drawbacks. It is
possible that only parts of the URL change, which means the single
stored cell ID is insufficient to track changes. The new ID method is
also somewhat leaking `alacritty` implementation details into
`alacritty_terminal`, but while dangerous if misused, I think the new
method could also be useful to other consumers of `alacritty_terminal`.
This also only does invalidation, so no attempt is made to re-check the
new content at the cursor location.

An alternative implementation that doesn't touch `alacritty_terminal`
would be to create some sort of hash for the hint, however this could
come with a bigger performance impact since hints can potentially be
very long.

Closes #7737.

---

This obviously isn't a perfect patch; it aims at providing an efficient solution for a very minor problem, so the focus is mostly on not harming performance. However I do think the resulting UX isn't too bad either. If there's any better ideas, please do let me know.

### CODE REVIEW

**Comment by chrisduerr** [comment]
Will re-record reftests once the general design of using extra cell storage is approved.

**Review by kchibisov — COMMENTED** [review]
Have you considered using damage information instead of ID stuff? I don't think it'll be any different here.

File: alacritty/src/display/hint.rs [hunk 1]
```diff
@@ -223,6 +223,25 @@ impl HintMatch {
     }
 }
 
+/// A hint being highlighted by the mouse or vi cursor.
+#[derive(PartialEq, Eq)]
+pub struct HighlightedHint {
+    pub last_cell_id: u32,
```
Comment (nixpulvis) [inline alacritty/src/display/hint.rs:229]: I might call this `last_end_cell_id` to make it clear where this points and a bit more clear what this does.

File: alacritty/src/display/hint.rs [hunk 2]
```diff
@@ -223,6 +223,25 @@ impl HintMatch {
...
+impl HighlightedHint {
+    fn new(hint: HintMatch, last_cell_id: u32) -> Self {
+        Self { last_cell_id, hint }
+    }
+
+    /// Check if the bounds of the highlight are still valid.
+    pub fn has_valid_range<T>(&self, term: &mut Term<T>) -> bool {
+        let current_id = term.grid_mut()[*self.hint.bounds.end()].id();
+        self.last_cell_id == current_id
+    }
```
Comment (nixpulvis) [inline alacritty/src/display/hint.rs:242]: Why does this need to take a `&mut Term` instead of just a `&Term`. I'm sure this isn't a mistake, I'm just not sure why since all it seems you're doing here is checking an id.

File: alacritty/src/display/hint.rs [hunk 3]
```diff
@@ -382,18 +401,19 @@ pub fn highlighted_at<T>(
...
+            return Some(HighlightedHint::new(hint, id));
         }
 
         let bounds = hint.content.regex.as_ref().and_then(|regex| {
             regex.with_compiled(|regex| regex_match_at(term, point, regex, hint.post_processing))
         });
         if let Some(bounds) = bounds.flatten() {
-            return Some(HintMatch { bounds, action: hint.action.clone(), hyperlink: None });
+            let id = term.grid_mut()[*bounds.end()].id();
+            let hint = HintMatch { bounds, action: hint.action.clone(), hyperlink: None };
```
Comment (nixpulvis) [inline alacritty/src/display/hint.rs:415]: I notice you're not using the `new` method here. Perhaps changing it to be `fn new(hint: HintMatch, term: &mut Term) -> Self` and moving the id extraction in there?

File: alacritty/src/display/mod.rs [hunk 4]
```diff
@@ -758,6 +758,17 @@ impl Display {
...
+        // Invalidate highlighted hints if grid has changed.
+        let mut filter_highlight = |highlight: &mut Option<HighlightedHint>| match highlight {
+            Some(hl) if !hl.has_valid_range(&mut terminal) => {
+                self.window.set_mouse_cursor(CursorIcon::Default);
+                *highlight = None;
+            },
+            _ => (),
+        };
+        filter_highlight(&mut self.vi_highlighted_hint);
+        filter_highlight(&mut self.highlighted_hint);
```
Comment (nixpulvis) [inline alacritty/src/display/mod.rs:770]: Perhaps I'm thinking about this wrong because I frankly forget the distinction between `highlighted_hint` and `vi_highlighted_hint` exactly, but if there are two overlapping highlights, wouldn't we only want to change the cursor if both are invalid?

File: alacritty/src/display/hint.rs (hunk 1 above)
Comment (chrisduerr) [reply alacritty/src/display/hint.rs:229]: That's what the `last` is for. It's not indicating that the value is historic. So if anything it should be `end_cell_id`?

**Comment by chrisduerr** [comment]
> Have you considered using damage information instead of ID stuff? I don't think it'll be any different here.

I've considered it, but I don't trust the damage information and it's pretty generic. This should be a pretty good metric that is directly connected to the actual URL, which also allows **not** invalidating in cases where the URL hasn't actually moved.

File: alacritty/src/display/hint.rs (hunk 2 above)
Comment (chrisduerr) [reply alacritty/src/display/hint.rs:242]: Because the `id` function dynamically assigns a new ID to the cell.

File: alacritty/src/display/mod.rs (hunk 4 above)
Comment (chrisduerr) [reply alacritty/src/display/mod.rs:770]: You're both wrong in your conclusion and right in the assumption that this is a bug.

The vi highlight should have no impact on the mouse cursor at all. I'm not sure why I didn't think of that.

File: alacritty/src/display/hint.rs (hunk 3 above)
Comment (chrisduerr) [reply alacritty/src/display/hint.rs:415]: Yeah I don't see why not tbh.

**Comment by kchibisov** [comment]
>I've considered it, but I don't trust the damage information and it's pretty generic. This should be a pretty good metric that is directly connected to the actual URL, which also allows not invalidating in cases where the URL hasn't actually moved.

well, the damage is accurate in terms of what changed, but it could report _more_ in some cases. Though, for scrolling it damages the entire screen all the time, since basically all screen content got changed.

For regular updates without any scrolling it's very accurate, since it's tied to actual write, so there's nothing that could be broken here.

I've assumed that with damage you can check if damage intersects the hint you basically recompute the thing, which should be possible and you have damage info right in hint already? The extra cell stuff sounds a bit like a second way to do things to figure out changes.

File: alacritty/src/display/hint.rs (hunk 1 above)
Comment (nixpulvis) [reply alacritty/src/display/hint.rs:229]: Yea I think I was sorta misinterpreting it at first. I like calling it `end_cell_id` since it's called `end()` where it's fetched. But I don't care much either way.

**Comment by kchibisov** [comment]
@perfbot

**Comment by chrisduerr** [comment]
@perfbot again if you would be so kind.

File: alacritty/src/display/mod.rs [hunk 5]
```diff
@@ -746,39 +745,59 @@ impl Display {
...
+                *hint = None;
             }
+        };
+        validate_hints(&mut self.vi_highlighted_hint, false);
+        validate_hints(&mut self.highlighted_hint, true);
 
-            let vi_cursor_viewport_point =
-                vi_cursor_point.and_then(|cursor| point_to_viewport(display_offset, cursor));
+        // Drop terminal as early as possible to free lock.
+        drop(terminal);
```
Comment (kchibisov) [inline alacritty/src/display/mod.rs:785]: This should be right after the `terminal.reset_damage()`.

File: alacritty/src/display/mod.rs [hunk 6]
```diff
@@ -746,39 +745,59 @@ impl Display {
...
+            // Clear invalidated hints.
+            if self.damage_tracker.frame().intersects(start, end) {
+                if reset_mouse {
+                    self.window.set_mouse_cursor(CursorIcon::Default);
+                }
                 self.damage_tracker.frame().mark_fully_damaged();
-                self.damage_tracker.next_frame().mark_fully_damaged();
+                *hint = None;
             }
+        };
```
Comment (kchibisov) [inline alacritty/src/display/mod.rs:779]: Can we extract this to a function? The `draw` function is already 300 lines.

File: alacritty_terminal/src/term/cell.rs [hunk 7]
```diff
@@ -124,9 +124,7 @@ impl ResetDiscriminant<Color> for Cell {
 #[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
 pub struct CellExtra {
     zerowidth: Vec<char>,
-
     underline_color: Option<Color>,
-
```
Comment (kchibisov) [inline alacritty_terminal/src/term/cell.rs:129]: I guess.

File: alacritty_terminal/src/grid/storage.rs [hunk 8]
```diff
@@ -66,7 +66,7 @@ impl<T> Storage<T> {
     #[inline]
     pub fn with_capacity(visible_lines: usize, columns: usize) -> Storage<T>
     where
-        T: Clone + Default,
```
Comment (kchibisov) [inline alacritty_terminal/src/grid/storage.rs:69]: This could be reverted? I think as well as other changes to `alacritty_terminal`?

**Review by kchibisov — CHANGES_REQUESTED** [review]
Also need a CHANGELOG entry.

File: alacritty/src/display/mod.rs (hunk 6 above)
Comment (chrisduerr) [reply alacritty/src/display/mod.rs:779]: Probably not a bad idea.

File: alacritty_terminal/src/grid/storage.rs (hunk 8 above)
Comment (chrisduerr) [reply alacritty_terminal/src/grid/storage.rs:69]: Why? I think it's better to have more accurate constraints. There's no reason why we'd require clone if we don't need it.

Comment (kchibisov) [reply alacritty_terminal/src/grid/storage.rs:69]: If you want to lower it in general, I'm fine with it. Maybe separate commit then, since these changes have nothing to do with the issue we're solving.

Comment (chrisduerr) [reply alacritty_terminal/src/grid/storage.rs:69]: The changes were made in a separate commit, yes.

**Review by kchibisov — APPROVED** [review]

**Comment by nixpulvis** [comment]
Nice work! Love that damage tracking is flexible like this.
