### PR TITLE
Fix hint highlight invalidation

### LINKED ISSUE #8270: Hyperlinks not working always
### System

OS: Linux (Archlinux)
Version: alacritty 0.14.0 (22a44757)
Linux/BSD: Gnome 47.1 + Wayland

There is something wrong with hyperlinks. I have opened two terminals: Alacritty and Gnome Console. On Gnome Console, hyperlinks are working just fine, on Alacritty I'm not sure how but when trying copy pasting the prompt or some gibberish on it, then it starts working

https://github.com/user-attachments/assets/20b78598-4364-4106-9570-445d3c927f75

### PR DESCRIPTION
**Pull request by chrisduerr**
This fixes a couple issues with hint highlight invalidation, which would
cause hints to lose their underline highlight despite the terminal
itself not having changed since the highlight started.

Closes #8270.

### CODE REVIEW

File: alacritty/src/display/damage.rs [hunk 1]
```diff
@@ -193,9 +193,11 @@ impl FrameDamage {
     /// Check if a range is damaged.
     #[inline]
     pub fn intersects(&self, start: Point<usize>, end: Point<usize>) -> bool {
+        let start_line = &self.lines[start.line];
+        let end_line = &self.lines[end.line];
         self.full
-            || self.lines[start.line].left <= start.column
-            || self.lines[end.line].right >= end.column
+            || (start_line.left..=start_line.right).contains(&start.column)
+            || (end_line.left..=end_line.right).contains(&end.column)
```
Comment (chrisduerr) [inline alacritty/src/display/damage.rs:200]: I've looked at your patch @kchibisov, but I think this is just the simpler solution here. I'm pretty sure it should be just as correct.

File: alacritty/src/display/mod.rs [hunk 2]
```diff
@@ -1331,16 +1339,25 @@ impl Display {
...
-                None => return,
+                None => continue,
             };
 
+            *hint_age += 1;
+
+            // Ignore hints that were created this frame.
+            if *hint_age == 1 {
+                continue;
+            }
```
Comment (chrisduerr) [inline alacritty/src/display/mod.rs:1359]: My initial plan was to fix search invalidating the hint by re-validating the hint on the second frame, but not re-validating on the third frame. However turns out that just not invalidating it on the first frame already does the job.

I still think it's best to keep this as an integer, because I can definitely see the concept of re-validating it on the second frame coming into play again with possible future issues.

File: alacritty/src/display/mod.rs [hunk 3]
```diff
@@ -1331,16 +1339,25 @@ impl Display {
...
-        {
+        let hints = [
+            (&mut self.highlighted_hint, &mut self.highlighted_hint_age, true),
+            (&mut self.vi_highlighted_hint, &mut self.vi_highlighted_hint_age, false),
+        ];
+        for (hint, hint_age, reset_mouse) in hints {
             let (start, end) = match hint {
                 Some(hint) => (*hint.bounds().start(), *hint.bounds().end()),
-                None => return,
+                None => continue,
```
Comment (chrisduerr) [inline alacritty/src/display/mod.rs:1351]: No clue why this was a return inside a loop. I'm pretty sure this was just a bug.

File: alacritty/src/display/mod.rs [hunk 4]
```diff
@@ -1331,16 +1339,24 @@ impl Display {
...
             };
 
+            // Ignore hints that were created this frame.
+            *hint_age += 1;
+            if *hint_age == 1 {
+                continue;
+            }
```
Comment (nixpulvis) [inline alacritty/src/display/mod.rs:1358]: I'm curious why this is necessary?

Comment (nixpulvis) [reply alacritty/src/display/mod.rs:1358]: OK I saw your comment that was outdated above and the new issue #8277. But I'm surprised that the age of the hint will be needed. What possible issues do you see this resolving?

As I understand it, this is mainly just to track when a hint gets invalidated by a change in the grid.

**Comment by nixpulvis** [comment]
Still having an issue with duplicate underlines when links are located on adjacent lines.

```sh
echo -e "https://nixpulvis.com\nhttps://nixpulvis.com"
```

Hover over the bottom one, then the top one.

**Comment by chrisduerr** [comment]
@nixpulvis Can you share a video? Are you on Wayland? I don't think I can reproduce.

**Comment by nixpulvis** [comment]
Yep, I'm running sway 1.9 and wayland 1.23.1.

Here's a video (sorry for the slow start):
links

**Comment by nixpulvis** [comment]
I did a slightly more aggressive test and I can confirm there's something really strange going on:
links2

What's worse. The video doesn't record the same effect as I see. I'll edit this post with a physical recording in a moment.

**Comment by chrisduerr** [comment]
It seems like a damage tracking issue tbh, which isn't a thing on X11.

**Comment by chrisduerr** [comment]
@nixpulvis Just to double check, this is only an issue if you switch between links directly, right? We're fully damaging whenever we clear a hint highlight, but we aren't when setting one.

**Comment by chrisduerr** [comment]
If you could test the following patch, I'd appreciate it:

```diff
diff --git a/alacritty/src/display/mod.rs b/alacritty/src/display/mod.rs
index 055479e6..d358a7c5 100644
--- a/alacritty/src/display/mod.rs
+++ b/alacritty/src/display/mod.rs
@@ -1026,7 +1026,7 @@ impl Display {
         self.vi_highlighted_hint_age = 0;

         // Force full redraw if the vi mode highlight was cleared.
-        if dirty && self.vi_highlighted_hint.is_none() {
+        if dirty {
             self.damage_tracker.frame().mark_fully_damaged();
         }

@@ -1064,8 +1064,8 @@ impl Display {
         self.highlighted_hint = highlighted_hint;
         self.highlighted_hint_age = 0;

-        // Force full redraw if the mouse cursor highlight was cleared.
-        if mouse_highlight_dirty && self.highlighted_hint.is_none() {
+        // Force full redraw if the mouse cursor highlight was changed.
+        if mouse_highlight_dirty {
             self.damage_tracker.frame().mark_fully_damaged();
         }
```

**Comment by nixpulvis** [comment]
That patch fixes the issue.

I'm still a little bit confused how the damage tracking works, so I can't say I completely understand what's going on here.

FWIW, moving the cursor with VI mode didn't trigger the issue before the patch.

**Comment by nixpulvis** [comment]
> Just to double check, this is only an issue if you switch between links directly, right?

Yes.

**Comment by chrisduerr** [comment]
> I'm still a little bit confused how the damage tracking works, so I can't say I completely understand what's going on here.

The old logic was only marking the full terminal damaged when the hint is cleared. The new logic always marks the entire terminal as damaged when the hint changes.

The issue here is that the new hint is no issue, but the old location of the hint needs to be redrawn to **clear** the existing underline. So we need to damage both. We could probably use the old hint for damaging but full damage is just simpler.

File: alacritty/src/display/mod.rs (hunk 4 above)
Comment (kchibisov) [reply alacritty/src/display/mod.rs:1358]: Cursor is always damaged, that's the reason.

**Review by kchibisov — APPROVED** [review]

File: alacritty/src/display/damage.rs (hunk 1 above)
Comment (kchibisov) [reply alacritty/src/display/damage.rs:200]: yeah, it's the same, just more cmps in total but it doesn't really matter.
