### PR TITLE
Fix notify doing active polling

### LINKED ISSUE #6652: Debouncer is constantly polling the events
With the notify v4 we were doing passive waiting, however update to notify v5 changed that and now we have active polling that wakes up every 10ms draining the battery.

### PR DESCRIPTION
**Pull request by kchibisov**
The `notify-debouncer-mini` spawn a thread which checks the events every timeout, which is not desired since we want to avoid active polling.

This commit re-implements debouncer based on the `RecommendedWatcher` without adding an extra thread on top and not doing any busy-waiting.

Fixes #6652.

### CODE REVIEW

File: alacritty/src/config/monitor.rs [hunk 1]
```diff
@@ -62,32 +64,68 @@ pub fn watch(mut paths: Vec<PathBuf>, event_proxy: EventLoopProxy<Event>) {
...
             if let Err(err) = watcher.watch(parent, RecursiveMode::NonRecursive) {
                 debug!("Unable to watch config directory {:?}: {}", parent, err);
             }
         }
 
+        // The current debouncing time.
+        let mut debouncing_time = None;
+
+        // The events accumulated during the debounce period.
+        let mut received_events = Vec::with_capacity(8);
```
Comment (chrisduerr) [inline alacritty/src/config/monitor.rs:78]: Is there any point in initializing this to a size of 8? Seems somewhat arbitrary and likely won't make any difference in practice?

File: alacritty/src/config/monitor.rs [hunk 2]
```diff
@@ -62,32 +64,68 @@ pub fn watch(mut paths: Vec<PathBuf>, event_proxy: EventLoopProxy<Event>) {
...
+            // We use `recv_timeout` to debounce the events comming from the watcher and reduce
+            // the amount of config reloads.
+            let event = if let Some(debouncing_time) = debouncing_time.as_mut() {
+                let time_waited = Instant::now();
+                let event = rx.recv_timeout(*debouncing_time);
+                // Adjust the debouncing time, so we debounce at least each `DEBOUNCE_DELAY`.
+                *debouncing_time = debouncing_time.saturating_sub(time_waited.elapsed());
+                event
+            } else {
+                debouncing_time = Some(DEBOUNCE_DELAY);
```
Comment (chrisduerr) [inline alacritty/src/config/monitor.rs:90]: Wouldn't it be more accurate to just store `Instant::now() + DEBOUNCE_DELAY` here and then pass that to `recv_timeout` rather than subtracting from the debounce time? The latter will definitely not be accurate, but I feel like the former is also going to be simpler code?

File: alacritty/src/config/monitor.rs [hunk 3]
```diff
@@ -62,32 +64,68 @@ pub fn watch(mut paths: Vec<PathBuf>, event_proxy: EventLoopProxy<Event>) {
...
+                rx.recv().map_err(Into::into)
+            };
+
+            match event {
+                Ok(Ok(event)) => {
+                    // Receiving any event should reset debouncing.
```
Comment (chrisduerr) [inline alacritty/src/config/monitor.rs:96]: It shouldn't and you're not actually resetting debouncing here? So the comment seems wrong?

**Review by chrisduerr — CHANGES_REQUESTED** [review]

File: alacritty/src/config/monitor.rs (hunk 1 above)
Comment (kchibisov) [reply alacritty/src/config/monitor.rs:78]: I just picked a value that will avoid any allocation.

File: alacritty/src/config/monitor.rs (hunk 2 above)
Comment (kchibisov) [reply alacritty/src/config/monitor.rs:90]: The `recv_timeout` only accept `Duration` unfortunately, there's a nightly API that accepts `Instant` that will simplify the code, but we can't use it. We subtract to block at max of `DEBOUNCE_DELAY`.

File: alacritty/src/config/monitor.rs (hunk 3 above)
Comment (kchibisov) [reply alacritty/src/config/monitor.rs:96]: Yes, you're correct. I was resetting in the first impl, but decided that I should change that to not do so, to prevent infinite wait if you update config each `9ms` for example.

File: alacritty/src/config/monitor.rs (hunk 1 above)
Comment (chrisduerr) [reply alacritty/src/config/monitor.rs:78]: If anything it would avoid re-allocation, right? And the value is arbitrary, isn't it? Like it could easily be bigger than 8.

File: alacritty/src/config/monitor.rs (hunk 2 above)
Comment (chrisduerr) [reply alacritty/src/config/monitor.rs:90]: Wouldn't it still be easier to just sub now from the deadline rather than recalculating the elapsed time every time? That just seems less efficient.

File: alacritty/src/config/monitor.rs (hunk 1 above)
Comment (kchibisov) [reply alacritty/src/config/monitor.rs:78]: The amount of events is `4` at max from what I've tested. Since you could have write/rename things. You can print the amount of events we're getting on writing to the file or replacing the file.

File: alacritty/src/config/monitor.rs (hunk 2 above)
Comment (kchibisov) [reply alacritty/src/config/monitor.rs:90]: But how do you know what to sub? You need to sub the amount you've blocked, and the amount you've blocked is the elapsed time.

File: alacritty/src/config/monitor.rs (hunk 1 above)
Comment (chrisduerr) [reply alacritty/src/config/monitor.rs:78]: That number seems arbitrary though? It will be completely different on other platforms.

File: alacritty/src/config/monitor.rs (hunk 2 above)
Comment (chrisduerr) [reply alacritty/src/config/monitor.rs]: All you need to do is `deadline - now` to get the duration until an instant.

Comment (kchibisov) [reply alacritty/src/config/monitor.rs]: But the `now` could be in the future and thus you panic?

File: alacritty/src/config/monitor.rs [hunk 4]
```diff
@@ -62,32 +64,63 @@ pub fn watch(mut paths: Vec<PathBuf>, event_proxy: EventLoopProxy<Event>) {
...
+        let mut debouncing_deadline: Option<Instant> = None;
+
+        // The events accumulated during the debounce period.
+        let mut received_events = Vec::new();
+
         loop {
-            let events = match rx.recv() {
-                Ok(Ok(events)) => events,
+            // We use `recv_timeout` to debounce the events comming from the watcher and reduce
+            // the amount of config reloads.
```
Comment (chrisduerr) [inline alacritty/src/config/monitor.rs:82]:
```suggestion
            // We use `recv_timeout` to debounce the events coming from the watcher and reduce
            // the amount of config reloads.
```

File: alacritty/src/config/monitor.rs [hunk 5]
```diff
@@ -62,32 +64,63 @@ pub fn watch(mut paths: Vec<PathBuf>, event_proxy: EventLoopProxy<Event>) {
...
+            let event = if let Some(debouncing_deadline) = debouncing_deadline {
```
Comment (chrisduerr) [inline alacritty/src/config/monitor.rs:83]: Should use match here.

**Review by chrisduerr — CHANGES_REQUESTED** [review]

**Review by chrisduerr — APPROVED** [review]
