### PR TITLE
Fix crash on ScaleFactorChange on Windows

### LINKED ISSUE #6949: changing windows display scale causes a crash
steps to reproduce:
1. start alacritty
2. minimize alacritty
3. change windows display scale
4. bringing alacritty back will cause the crash

### System

OS: Windows
Version: `alacritty 0.12.1 (5fdfd47)`

### Logs
[0.000003700s] [INFO ] [alacritty] Welcome to Alacritty
[0.000408900s] [INFO ] [alacritty] Version 0.12.1 (5fdfd47)
[0.002749700s] [INFO ] [alacritty] Configuration files loaded from:
                                     "C:\\Users\\jeff\\AppData\\Roaming\\alacritty\\alacritty.yml"
[0.012407700s] [INFO ] [alacritty] Window scale factor: 1
[0.068666100s] [INFO ] [alacritty] Using WGL
[0.080416300s] [DEBUG] [alacritty] Loading "Iosevka Curly" font
[0.099698200s] [INFO ] [alacritty] Running on AMD Radeon(TM) Graphics
[0.099952300s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.142406400s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.174504900s] [INFO ] [alacritty] Cell size: 9 x 25
[0.174729800s] [INFO ] [alacritty] Padding: 0 x 0
[0.174869300s] [INFO ] [alacritty] Width: 800, Height: 600
[0.198863600s] [INFO ] [alacritty] PTY dimensions: 24 x 88
[0.250253900s] [INFO ] [alacritty] Initialisation complete
[0.250894100s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[13.804558900s] [INFO ] [alacritty] Font size changed to Size(30) with scale factor of 1.25
[13.804808800s] [INFO ] [alacritty] Cell size: 12 x 31
[13.804960000s] [DEBUG] [alacritty_terminal] New num_cols is 2 and num_lines is 1
panicked at 'called `Option::unwrap()` on a `None` value', alacritty\src\display\mod.rs:681:72

### PR DESCRIPTION
**Pull request by kchibisov**
Windows is known to send zero sizes from winit in Risezed and now in ScaleFactorChanged events. They were handled in Resized, but not in ScaleFactorChanged.

Fixes #6949.

### CODE REVIEW

File: alacritty/src/event.rs [hunk 1]
```diff
@@ -1193,16 +1193,20 @@ impl input::Processor<EventProxy, ActionContext<'_, Notifier, EventProxy>> {
...
 
                     // Push current font to update its scale factor.
                     let font = self.ctx.config.font.clone();
                     display_update_pending.set_font(font.with_size(*self.ctx.font_size));
 
-                    // Resize to event's dimensions, since no resize event is emitted on Wayland.
-                    display_update_pending.set_dimensions(PhysicalSize::new(width, height));
-
-                    self.ctx.window().scale_factor = scale_factor;
+                    // Same reasoning as in resize event handling.
```
Comment (chrisduerr) [inline alacritty/src/event.rs:1204]: Just copy-paste it, then people don't have to go search.

**Review by chrisduerr — CHANGES_REQUESTED** [review]

**Review by chrisduerr — APPROVED** [review]
