### PR TITLE
Fix startup failure on macOS with dash as /bin/sh

### LINKED ISSUE #6426: Alacritty quits on launch
Alacritty immediately quits on launch, before even showing the window. Neither reinstalling Alacritty nor restarting the machine seems to help. I deleted my Alacritty config file and that didn't fix anything, so my config has nothing to do with this issue.

### System

OS: macOS 12.6
Version: alacritty 0.11.0 (8dbaa0b)

### Logs

Output of `alacritty -vv` (gives back an exit code of 0):
```
Created log file at "/var/folders/bg/vf7hd0vs49n39lcyk_s0smb00000gn/T/Alacritty-4385.log"
[0.000054389s] [INFO ] [alacritty] Welcome to Alacritty
[0.007115821s] [INFO ] [alacritty] Version 0.11.0 (8dbaa0b)
[0.042091590s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/Users/mhmdanas/.config/alacritty/alacritty.yml"
[0.042702146s] [DEBUG] [alacritty] Using environment locale: C/UTF-8/C/C/C/C
[0.074165062s] [DEBUG] [alacritty] Loading "Menlo" font
[0.199210390s] [DEBUG] [alacritty] Estimated scaling factor: 2
[0.199337580s] [DEBUG] [alacritty] Estimated window size: None
[0.199360840s] [DEBUG] [alacritty] Estimated cell size: 13 x 26
[0.265049290s] [INFO ] [alacritty] Running on Intel(R) Iris(TM) Plus Graphics 640
[0.265144366s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.271354065s] [INFO ] [alacritty] Display scale factor: 2
[0.271427590s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.297002248s] [INFO ] [alacritty] Cell size: 13 x 26
[0.297084338s] [INFO ] [alacritty] Padding: 0 x 0
[0.297107136s] [INFO ] [alacritty] Width: 1600, Height: 1200
[0.297327901s] [INFO ] [alacritty] PTY dimensions: 46 x 123
[0.302970512s] [INFO ] [alacritty] Initialisation complete
[0.340792693s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[0.341176627s] [INFO ] [alacritty] Padding: 0 x 0
[0.341226707s] [INFO ] [alacritty] Width: 1600, Height: 1200
[0.399888952s] [INFO ] [alacritty] Goodbye
Deleted log file at "/var/folders/bg/vf7hd0vs49n39lcyk_s0smb00000gn/T/Alacritty-4385.log"
```

### PR DESCRIPTION
**Pull request by kchibisov**
The dash's exec doesn't have `-a` argument we rely on when running login shell, so use bash instead.

Fixes #6426.

### CODE REVIEW

**Comment by chrisnc** [comment]
They haven't removed `/bin/bash` yet, but for what it's worth they have removed common stuff from `/bin` and `/usr/bin` before... For example they removed all versions of `python` including `python3` from the base install a few years ago: https://developer.apple.com/documentation/macos-release-notes/macos-catalina-10_15-release-notes
(There is a `/usr/bin/python3` but it prompts you to install the Xcode command-line tools.) IMO this makes `/bin/zsh` the safest bet to not have to make another change a few years from now.

**Comment by chrisduerr** [comment]
Removing `python` isn't even remotely as much of a change as removing `bash`. I'm not saying they would never do it, but that would be quite the slap in the face.

File: alacritty_terminal/src/tty/unix.rs [hunk 1]
```diff
@@ -143,7 +143,9 @@ fn default_shell_command(pw: &Passwd<'_>) -> Command {
     // -f: Bypasses authentication for the already-logged-in user.
     // -l: Skips changing directory to $HOME and prepending '-' to argv[0].
     // -p: Preserves the environment.
-    login_command.args(["-flp", pw.name, "/bin/sh", "-c", &exec]);
+    //
+    // XXX: we use bash here over sh due to `exec -a`.
+    login_command.args(["-flp", pw.name, "/bin/bash", "-c", &exec]);
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/unix.rs:148]: Why did you decide to go for bash over zsh?

Comment (kchibisov) [reply alacritty_terminal/src/tty/unix.rs:148]: Idk, that's what I concluded. Could use zsh.

Comment (chrisduerr) [reply alacritty_terminal/src/tty/unix.rs:148]: Honestly just use zsh, has been supported forever according to @chrisnc so should be fine.

**Review by chrisduerr — APPROVED** [review]

**Review by chrisduerr — APPROVED** [review]
