### PR TITLE
Fix selection rotating outside of scrolling region

### LINKED ISSUE #2983: TMUX: Pane scrolling output affect other panes selection
Hi, issue occurs with tmux. When top pane starts scrolling output, every bottom panes starts to move selections too. It works only with top pane. See gif.
Alacritty

```
# System
|                  |                               |
|------------------|-------------------------------|
| alacritty        | 0.3.3 (679e67d)
| Operating System | Arch Linux   
| Rust Version     | rustc 1.39.0-nightly (72b2abfd6 2019-08-29)
| Display Server   | X11 
| Window Manager   | KDE Plasma 
| Compositor       | kWin 

```

# Expectation
I checked it with Konsole and it works as expected. See gif.
Konsole

[alacritty.log](https://github.com/jwilm/alacritty/files/3850791/alacritty.log)

[alacritty.events.log](https://github.com/jwilm/alacritty/files/3850794/alacritty.events.log)

### PR DESCRIPTION
**Pull request by chrisduerr**
Fixes #2983.

### CODE REVIEW

**Comment by kchibisov** [comment]
Besides failing tests, just some glitches I don't like. So in a bottom pane selection is stuck on pane split. And on a top pane you see that sometimes selection is missing 0 cell for whatever reason.


selection

File: alacritty_terminal/src/selection.rs [hunk 1]
```diff
@@ -83,70 +92,115 @@ impl<L> SelectionRange<L> {
...
+            }
 
-        if let Some((_, end_side)) = self.sides_mut() {
-            *end_side = side;
+            // Clamp selection to start of region
+            if start.point.line >= region_start && region_start != num_lines {
+                start.point.line = region_start - 1;
+                start.point.col = Column(0);
+                start.side = Side::Left;
+            }
```
Comment (kchibisov) [inline alacritty_terminal/src/selection.rs]: You're likely clamping block selection here too...

File: alacritty_terminal/src/selection.rs [hunk 2]
```diff
@@ -66,6 +66,15 @@ impl<L> SelectionRange<L> {
...
 }
 
+/// Different kinds of selection.
+#[derive(Debug, Clone, PartialEq)]
+pub enum SelectionType {
+    Simple,
+    Block,
+    Semantic,
+    Lines,
+}
```
[the remark this answers is not in the document]
Comment (chrisduerr) [reply alacritty_terminal/src/selection.rs]: Shouldn't be relevant since it is never attempted to copy/clone, but seems easy enough to add.

I've also changed things to remove `pub` here, since it's never used publicly.

File: alacritty_terminal/src/selection.rs [hunk 3]
```diff
@@ -83,70 +92,119 @@ impl<L> SelectionRange<L> {
...
+        {
+            end.point.line = usize::try_from(end.point.line as isize + offset).unwrap_or(0);
+
+            // Delete selection if end has overtaken the start
+            if end.point.line > start.point.line {
+                return None;
+            }
+
+            // Clamp selection to end of region
+            if end.point.line < region_end {
```
Comment (kchibisov) [inline alacritty_terminal/src/selection.rs]: How could you even trigger this thing?

File: alacritty_terminal/src/selection.rs [hunk 4]
```diff
@@ -66,6 +66,15 @@ impl<L> SelectionRange<L> {
...
+enum SelectionType {
+    Simple,
+    Block,
+    Semantic,
+    Lines,
+}
+
 /// Describes a region of a 2-dimensional area.
 ///
 /// Used to track a text selection. There are three supported modes, each with its own constructor:
```
[the remark this answers is not in the document]
Comment (chrisduerr) [reply alacritty_terminal/src/selection.rs]: Great point.

File: alacritty_terminal/src/selection.rs (hunk 3 above)
Comment (chrisduerr) [reply alacritty_terminal/src/selection.rs]: You can scroll in both directions in scrolling regions. Think about vim for example.
