### PR TITLE
Port from mio to polling, take 2

### LINKED ISSUE #6486: Update Mio
It seems alacritty_terminal is still using Mio v0.6, which isn't supported any more. Any thing I can do to help move it to Mio v0.8?

### LINKED ISSUE #7104: alacritty fails to build in Windows on ARM
this error appears when try to build for `aarch64-pc-windows-gnullvm` target
```console
error[E0412]: cannot find type `ULONG_PTR` in this scope
    --> C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winapi-0.2.8\src\basetsd.rs:86:19
     |
  86 | pub type SIZE_T = ULONG_PTR;
     |                   ^^^^^^^^^ not found in this scope
```
that's because there is winapi 0.2, which doesn't support arm64 target. is there any possibility to update winapi package?

### PR DESCRIPTION
**Pull request by notgull**
Supersedes #6772 by replacing the `mio` crate with the `polling` crate. Now that smol-rs/polling#96 has been merged, we should be at full feature parity with `mio` v0.6 now.

Draft because I haven't ported the Windows code over to `polling` yet, but from what I understand that is low-priority.

Fixes #7104.
Fixes #6486.

### CODE REVIEW

**Comment by kchibisov** [comment]
>Draft because I haven't ported the Windows code over to polling yet, but from what I understand that is low-priority.

Yeah, the windows code could be as dirty as it can, because it's a "best effort" platform, though, we must have an implementation for it in case we want to merge it.

Even doing the thing with `thread` as we did before is fine for windows.

Also, don't forget to include the `Cargo.lock` update, since right now it's missing.

**Comment by kchibisov** [comment]
@davidhewitt sorry for pinging you, but given that you're the maintainer of mio-anonymous-pipe and the author of alacritty's ConPty integration bits, do you know whether your crate could be easily ported to `polling`, given that `mio v0.6.x` is not maintained anymore?

We'd like to remove `mio v0.6.x` from our dependency graph before the next alacritty release to remove future incompatible code, thx.

**Comment by notgull** [comment]
It should be easy enough once smol-rs/polling#104 lands, which would make it possible to push arbitrary events to the `Poller`, allowing much more flexibility in how external sources are handled.

**Comment by davidhewitt** [comment]
I wouldn't publish a new version of `mio-anonymous-pipe` with polling; the library is very small and it's named specifically for `mio`. 

The whole idea of that library is just to create a thread which reads from the pipe and pushes it into a buffer which implements the `mio` events. It's quite small (less than 500 lines) so should be straightforward to create a fork of that code which uses `polling`. Could maybe even inline directly into Alacritty depending on how much smaller the `polling` implementation would be.

I don't have much time at the moment, so I wouldn't be able to do this for you. Potentially some time can free up a few months down the line.

**Comment by kchibisov** [comment]
>I wouldn't publish a new version of mio-anonymous-pipe with polling; the library is very small and it's named specifically for mio.

I've asked given that mio version you were using is not maintained anymore, so your crate is sort of timed bombed due to future incompat code in mio `0.6`

**Comment by kchibisov** [comment]
>Right, I don't think it would be hard to publish a new version on a new mio, but I don't think that's what you need here? 

Right, but it's more like, we don't have plans on keep using `mio`, because it's `Edge` only and we won't use mio in any upstream crate anyway for that reason. It's more of a notice at this point that your crate is sort of dead with the `mio` `0.6`, but I guess no-one needs to
overlapped IO on windows besides alacritty anyway.

I think @notgull is more or less fine. It's just a matter of a code reuse, since I have a feeling that the core parts of it should stay the same, so the code could be taken from your crate. 

Though, I think given that the crate has `mio-anonymous-pipe`, it's better to stick with `mio`, so the only update to it could be to `0.8.0` mio, but not sure that it'll be used.

**Comment by notgull** [comment]
Ported the Windows code over to use `polling` now. I just need to test it on my Windows box and we should be good to go.

**Comment by notgull** [comment]
Seems to work on my Windows box, everything appears to be clean. I think this is ready to be reviewed/merged now.

File: alacritty_terminal/src/event_loop.rs [hunk 1]
```diff
@@ -313,17 +335,12 @@ where
             let mut state = State::default();
             let mut buf = [0u8; READ_BUFFER_SIZE];
 
-            let mut tokens = (0..).map(Into::into);
-
-            let poll_opts = PollOpt::edge() | PollOpt::oneshot();
-
-            let channel_token = tokens.next().unwrap();
-            self.poll.register(&self.rx, channel_token, Ready::readable(), poll_opts).unwrap();
+            let poll_opts = polling::PollMode::EdgeOneshot;
```
Comment (kchibisov) [inline alacritty_terminal/src/event_loop.rs:338]: Thinking about it, do we really need `OneShot`? Shouldn't we be fine with just `Edge`?

File: alacritty_terminal/src/tty/windows/blocking.rs [hunk 2]
```diff
@@ -0,0 +1,285 @@
+// SPDX-License-Identifier: MIT OR Apache-2.0
+//! Code for running a reader/writer on another thread while driving it through `polling`.
+
+use piper::{pipe, Reader, Writer};
+use polling::os::iocp::{CompletionPacket, PollerIocpExt};
+use polling::{Event, PollMode, Poller};
+
```
Comment (kchibisov) [inline alacritty_terminal/src/tty/windows/blocking.rs:7]: Do we really need this code here? I'd assume some other clients could be interested in it? We also don't have SPDX prefixes in the project in case they match our licenses.

File: alacritty_terminal/src/tty/windows/conpty.rs [hunk 3]
```diff
@@ -17,9 +15,13 @@ use windows_sys::Win32::System::Threading::{
 
 use crate::config::PtyConfig;
 use crate::event::{OnResize, WindowSize};
+use crate::tty::windows::blocking::{UnblockedReader, UnblockedWriter};
 use crate::tty::windows::child::ChildExitWatcher;
 use crate::tty::windows::{cmdline, win32_string, Pty};
 
+// Adjust to taste. Too high means higher memory consumption, too low means over-synchronization.
+const PIPE_CAPACITY: usize = 4 * 1024 * 1024;
```
Comment (kchibisov) [inline alacritty_terminal/src/tty/windows/conpty.rs:23]: Why that particular value was picked? We have a `READ_BUFFER_SIZE` inside the event_loop, so maybe it should be tuned based on it?

File: alacritty_terminal/src/tty/windows/child.rs [hunk 4]
```diff
@@ -12,27 +14,43 @@ use windows_sys::Win32::System::WindowsProgramming::INFINITE;
...
+    if let Some(interest) = interest.as_ref() {
+        interest.poller.post(CompletionPacket::new(interest.event)).ok();
+    }
 }
 
 pub struct ChildExitWatcher {
     wait_handle: AtomicPtr<c_void>,
-    event_rx: Receiver<ChildEvent>,
+    event_rx: mpsc::Receiver<ChildEvent>,
+    interest: Arc<Mutex<Option<Interest>>>,
```
Comment (kchibisov) [inline alacritty_terminal/src/tty/windows/child.rs:44]: Should it really be behind the `Mutex`? Don't we have a way to have `&mut` in the chain?

**Review by kchibisov — CHANGES_REQUESTED** [review]
I haven't got to actually testing it.

File: alacritty_terminal/src/tty/windows/blocking.rs (hunk 2 above)
Comment (notgull) [reply alacritty_terminal/src/tty/windows/blocking.rs:7]: I would definitely be willing to extract this into a `polling-utils`-esque crate for other users.

File: alacritty_terminal/src/event_loop.rs [hunk 5]
```diff
@@ -73,13 +97,25 @@ impl event::Notify for Notifier {
...
 impl event::OnResize for Notifier {
     fn on_resize(&mut self, window_size: WindowSize) {
-        let _ = self.0.send(Msg::Resize(window_size));
+        self.0.send(Msg::Resize(window_size));
+    }
+}
+
+pub struct EventLoopSender {
+    sender: Sender<Msg>,
+    poller: Arc<polling::Poller>,
```
[the remark this answers is not in the document]
Comment (notgull) [reply alacritty_terminal/src/event_loop.rs:112]: Passing around the `Poller` is necessary on Windows at least for passing packets to the IOCP.

File: alacritty_terminal/src/tty/windows/child.rs (hunk 4 above)
Comment (notgull) [reply alacritty_terminal/src/tty/windows/child.rs:44]: It is also used by the child event handler, so this is needed to share it between the two threads.

File: alacritty_terminal/src/event_loop.rs (hunk 1 above)
Comment (kchibisov) [reply alacritty_terminal/src/event_loop.rs:338]: Though, from what I see now the main reason for `OneShot` is because we change between read/write modes.

Comment (notgull) [reply alacritty_terminal/src/event_loop.rs]: Looks like everything still works on Linux under `Oneshot`.

File: alacritty_terminal/src/tty/windows/conpty.rs (hunk 3 above)
Comment (notgull) [reply alacritty_terminal/src/tty/windows/conpty.rs]: It's the default pipe capacity used in the `blocking` crate. I've fixed it to just equal `READ_BUFFER_SIZE`.

File: alacritty_terminal/src/event_loop.rs (hunk 1 above)
Comment (kchibisov) [reply alacritty_terminal/src/event_loop.rs]: I was curious to have just `Edge` and remove `OneShot`.

File: alacritty_terminal/src/tty/windows/conpty.rs (hunk 3 above)
Comment (kchibisov) [reply alacritty_terminal/src/tty/windows/conpty.rs]: Maybe it should be benchmarked, with e.g. vtebench, but from what I remember conpty is so slow that it doesn't matter what we pick.

File: alacritty_terminal/src/tty/windows/conpty.rs [hunk 6]
```diff
@@ -20,7 +20,7 @@ use crate::tty::windows::child::ChildExitWatcher;
 use crate::tty::windows::{cmdline, win32_string, Pty};
 
 // Adjust to taste. Too high means higher memory consumption, too low means over-synchronization.
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/windows/conpty.rs:22]: This comment needs updating.

**Comment by kchibisov** [comment]
I've tested on windows, and it was sort of working.

File: alacritty_terminal/src/tty/windows/conpty.rs (hunk 6 above)
Comment (kchibisov) [reply alacritty_terminal/src/tty/windows/conpty.rs:22]: I also meant that we can use `8 * BUFFER` or something based on that if it's "better".

**Comment by kchibisov** [comment]
Also "tb" macOS.

File: alacritty_terminal/src/tty/windows/conpty.rs (hunk 6 above)
Comment (kchibisov) [reply alacritty_terminal/src/tty/windows/conpty.rs:22]: We could check with `vtebench` whether changing anything results in change in performance.

**Comment by chrisduerr** [comment]
@perfbot

File: alacritty_terminal/src/event_loop.rs [hunk 7]
```diff
@@ -39,14 +36,41 @@ pub enum Msg {
     Resize(WindowSize),
 }
 
-/// The main event!.. loop.
+struct PeekableReceiver<T> {
```
Comment (chrisduerr) [inline alacritty_terminal/src/event_loop.rs:39]: This structure seems a bit strange and inefficient to me. Did you add it solely for synchronized updates? Why was it necessary if it worked without this before?

Also it seems like you're silently ignoring channel failure. How does this impact the behavior of the channel's death compared to master?

File: alacritty_terminal/src/event_loop.rs [hunk 8]
```diff
@@ -336,29 +353,29 @@ where
...
-                for event in events.iter() {
-                    match event.token() {
-                        token if token == channel_token => {
-                            if !self.channel_event(channel_token, &mut state) {
-                                break 'event_loop;
-                            }
-                        },
+                // Handle channel events, if there are any.
+                if !self.drain_recv_channel(&mut state) {
+                    break 'event_loop;
```
Comment (chrisduerr) [inline alacritty_terminal/src/event_loop.rs:373]: Seems like you can just use `break` here?

File: alacritty_terminal/src/tty/mod.rs [hunk 9]
```diff
@@ -24,18 +25,20 @@ pub trait EventedReadWrite {
...
     ) -> io::Result<()>;
-    fn reregister(&mut self, _: &mio::Poll, _: mio::Ready, _: mio::PollOpt) -> io::Result<()>;
-    fn deregister(&mut self, _: &mio::Poll) -> io::Result<()>;
+    fn reregister(
+        &mut self,
+        _: &Arc<polling::Poller>,
+        _: polling::Event,
+        _: polling::PollMode,
+    ) -> io::Result<()>;
+    fn deregister(&mut self, _: &Arc<polling::Poller>) -> io::Result<()>;
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/mod.rs:38]: Should probably import this stuff at the top of the file.

File: alacritty_terminal/src/tty/unix.rs [hunk 10]
```diff
@@ -5,23 +5,30 @@ use std::fs::File;
...
 use signal_hook::consts as sigconsts;
-use signal_hook_mio::v0_6::Signals;
 
 use crate::config::PtyConfig;
 use crate::event::{OnResize, WindowSize};
 use crate::tty::{ChildEvent, EventedPty, EventedReadWrite};
 
+// We use the same interest for reading and writing.
+pub(crate) const PTY_READ_TOKEN: usize = 0;
+pub(crate) const PTY_WRITE_TOKEN: usize = 0;
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/unix.rs:27]: Why are they separate constants then? Why not make it a `PTY_READ_WRITE_TOKEN`?

Also couldn't this just be an enum to avoid accidental conflicts?

File: alacritty_terminal/src/tty/unix.rs [hunk 11]
```diff
@@ -254,7 +261,14 @@ pub fn new(config: &PtyConfig, window_size: WindowSize, window_id: u64) -> Resul
     }
 
     // Prepare signal handling before spawning child.
-    let signals = Signals::new([sigconsts::SIGCHLD]).expect("error preparing signal handling");
+    let signals = {
+        let (sender, recv) = UnixStream::pair()?;
+
+        // Register the recv end of the pipe for SIGCHLD.
+        signal_hook::low_level::pipe::register(sigconsts::SIGCHLD, sender)?;
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/unix.rs:268]: Definitely shouldn't specify the fully qualified path here.

File: alacritty_terminal/src/tty/unix.rs [hunk 12]
```diff
@@ -302,89 +316,87 @@ impl EventedReadWrite for Pty {
...
 }
 
 impl EventedPty for Pty {
     #[inline]
     fn next_child_event(&mut self) -> Option<ChildEvent> {
-        self.signals.pending().next().and_then(|signal| {
-            if signal != sigconsts::SIGCHLD {
-                return None;
-            }
+        use std::io::Read;
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/unix.rs:372]: Please don't ever add imports inside a function like this.

File: alacritty_terminal/src/tty/unix.rs [hunk 13]
```diff
@@ -302,89 +316,87 @@ impl EventedReadWrite for Pty {
...
+                // We received the signal.
+            },
 
-    #[inline]
-    fn child_event_token(&self) -> mio::Token {
-        self.signals_token
+            Err(e) => {
+                // We didn't receive the signal.
+                // Either an error occurred or we got EAGAIN. We don't really care which one.
+                if e.kind() != std::io::ErrorKind::WouldBlock {
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/unix.rs:384]: No fully qualified path here please.

File: alacritty_terminal/src/tty/windows/blocking.rs (hunk 2 above)
Comment (chrisduerr) [reply alacritty_terminal/src/tty/windows/blocking.rs:7]: Why is a different license necessary here to begin with?

File: alacritty_terminal/src/tty/windows/blocking.rs [hunk 14]
```diff
@@ -0,0 +1,285 @@
...
+use std::task::{Context, Poll, Wake, Waker};
+use std::{io, thread};
+
+struct Registration {
+    interest: Mutex<Option<Interest>>,
+    end: End,
+}
+
+#[derive(Copy, Clone)]
+enum End {
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/windows/blocking.rs:20]: The enum name here isn't very descriptive.

File: alacritty_terminal/src/tty/windows/blocking.rs [hunk 15]
```diff
@@ -0,0 +1,285 @@
...
+        // Create a new pipe.
+        let (reader, mut writer) = pipe(pipe_capacity);
+        let interest = Arc::new(Registration {
+            interest: Mutex::<Option<Interest>>::new(None),
+            end: End::Reader,
+        });
+
+        // Spawn the reader thread.
+        thread::Builder::new()
+            .name("alacritty-tty-reader-thread".into())
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/windows/blocking.rs:63]: Pretty sure we have a utility to spawn a named thread that should make this a little less verbose.

**Review by chrisduerr — CHANGES_REQUESTED** [review]

File: alacritty_terminal/src/event_loop.rs (hunk 7 above)
Comment (notgull) [reply alacritty_terminal/src/event_loop.rs:39]: The channel was previously registered into the event loop, while this version isn't. I added a panic on channel death.

File: alacritty_terminal/src/tty/unix.rs (hunk 10 above)
Comment (notgull) [reply alacritty_terminal/src/tty/unix.rs:28]: They have to be separate in Windows but not Unix. They need to be `usize`, since that's the token type `polling` takes.

File: alacritty_terminal/src/tty/windows/blocking.rs (hunk 2 above)
Comment (notgull) [reply alacritty_terminal/src/tty/windows/blocking.rs]: Removed the notice. I thought there was an Apache 2.0 license, my bad

File: alacritty_terminal/src/event_loop.rs (hunk 1 above)
Comment (notgull) [reply alacritty_terminal/src/event_loop.rs]: That seems to work properly as well.

File: alacritty_terminal/src/tty/windows/blocking.rs (hunk 2 above)
Comment (kchibisov) [reply alacritty_terminal/src/tty/windows/blocking.rs]: The crate is apache only, so you should keep the notice if you want. Though, you can just move the part of you want to your utils.

File: alacritty_terminal/src/event_loop.rs (hunk 1 above)
Comment (kchibisov) [reply alacritty_terminal/src/event_loop.rs]: I mean, it's level, so it should work...

File: alacritty_terminal/src/tty/windows/blocking.rs (hunk 2 above)
Comment (chrisduerr) [reply alacritty_terminal/src/tty/windows/blocking.rs]: As the original code author @notgull can do whatever he wants with the code he wrote himself. This includes inclusion in his own projects under whatever license he wants.

The only difference this would make is that this would give a different license option to people using this code (like ourselves). But since Apache and MIT are compatible licenses this isn't really a major factor.

**Comment by kchibisov** [comment]
I think something like that should work.

```diff
diff --git a/alacritty_terminal/src/event_loop.rs b/alacritty_terminal/src/event_loop.rs
index ac2b7123..4eb9f0da 100644
--- a/alacritty_terminal/src/event_loop.rs
+++ b/alacritty_terminal/src/event_loop.rs
@@ -199,7 +199,7 @@ where
     ) -> EventLoop<T, U> {
         let (tx, rx) = mpsc::channel();
         EventLoop {
-            poll: polling::Poller::new().expect("create mio Poll").into(),
+            poll: polling::Poller::new().expect("create Poll").into(),
             pty,
             tx,
             rx: PeekableReceiver::new(rx),
@@ -338,10 +338,12 @@ where
             let mut state = State::default();
             let mut buf = [0u8; READ_BUFFER_SIZE];
 
-            let poll_opts = polling::PollMode::Edge;
+            let poll_opts = polling::PollMode::Level;
+
+            let mut interest = polling::Event::readable(0);
 
             // Register TTY through EventedRW interface.
-            self.pty.register(&self.poll, polling::Event::readable(0), poll_opts).unwrap();
+            self.pty.register(&self.poll, interest, poll_opts).unwrap();
 
             let mut events = Vec::with_capacity(1024);
 
@@ -394,7 +396,7 @@ where
                         },
 
                         token if token == tty::PTY_READ_TOKEN || token == tty::PTY_WRITE_TOKEN => {
-                            /*
+                            /* FIXME: once polling supports extra reported modes bring it back.
                             #[cfg(unix)]
                             if UnixReady::from(event.readiness()).is_hup() {
                                 // Don't try to do I/O on a dead PTY.
@@ -431,13 +433,16 @@ where
                     }
                 }
 
-                // Register write interest if necessary.
-                let mut interest = polling::Event::readable(0);
-                if state.needs_write() {
-                    interest.writable = true;
+                if state.needs_write() != interest.writable {
+                    if state.needs_write() {
+                        interest.writable = true;
+                    } else {
+                        interest.writable = false;
+                    }
+
+                    // Reregister with new interest.
+                    self.pty.reregister(&self.poll, interest, poll_opts).unwrap();
                 }
-                // Reregister with new interest.
-                self.pty.reregister(&self.poll, interest, poll_opts).unwrap();
             }
 
             // The evented instances are not dropped here so deregister them explicitly.

```

File: alacritty_terminal/src/event_loop.rs (hunk 7 above)
Comment (kchibisov) [reply alacritty_terminal/src/event_loop.rs:39]: Could you move it and related impl the bottom of the file.

File: alacritty_terminal/src/event_loop.rs [hunk 16]
```diff
@@ -158,28 +197,28 @@ where
         hold: bool,
         ref_test: bool,
     ) -> EventLoop<T, U> {
-        let (tx, rx) = channel::channel();
+        let (tx, rx) = mpsc::channel();
```
Comment (kchibisov) [inline alacritty_terminal/src/event_loop.rs:200]: Could you move `impl` below `EventLoop` struct definition while at it?

**Review by kchibisov — CHANGES_REQUESTED** [review]
It would be nice if you could provide the https://github.com/alacritty/vtebench/ results from windows platform wrt changing that or anonymous pipe size(it's zero now, which is meant default).

If running `vtebench` results in no change it's likely that windows is just bottlenecks on contpy. It was like that in the past for example and benchmark which runs like 10ms on the same machine was running 1 second(or even more) with conpty.

File: alacritty_terminal/src/event_loop.rs (hunk 16 above)
Comment (kchibisov) [reply alacritty_terminal/src/event_loop.rs:170]: it's still not there, it should be at line 59(60).

File: alacritty_terminal/src/event_loop.rs [hunk 17]
```diff
@@ -336,29 +327,29 @@ where
...
-                                break 'event_loop;
-                            }
-                        },
+                // Handle channel events, if there are any.
+                if !self.drain_recv_channel(&mut state) {
+                    break;
+                }
 
-                        token if token == self.pty.child_event_token() => {
+                for event in events.iter() {
```
Comment (kchibisov) [inline alacritty_terminal/src/event_loop.rs:350]: Can't we `drain` here instead of `clear` above?

**Comment by notgull** [comment]
Sorry that I haven't updated in a while! It's a combination of starting a new job, and the fact that if I look at the `polling-utils` code again I think I will die of a heart attack. I'll finish this at some point in the near future.

**Comment by chrisduerr** [comment]
No worries, take all the time you need.

**Comment by kchibisov** [comment]
We may keep the windows part in tree for a while, it's not like I really mind it.

**Comment by notgull** [comment]
> We may keep the windows part in tree for a while, it's not like I really mind it.

Ok, sounds good. Writing the Windows part of the code in a generic way is an effort that I don't want to undertake for the time being.

I've rebased on the latest `master`

File: alacritty_terminal/src/tty/windows/conpty.rs (hunk 6 above)
Comment (kchibisov) [reply alacritty_terminal/src/tty/windows/conpty.rs:26]: Could you drop this comment?

**Review by kchibisov — CHANGES_REQUESTED** [review]
Just one minor comment from me.

I'll also need to retest on Windows again just in case.

**Comment by kchibisov** [comment]
@perfbot

**Comment by kchibisov** [comment]
Windows ack.

**Review by kchibisov — APPROVED** [review]

File: alacritty_terminal/src/tty/unix.rs [hunk 18]
```diff
@@ -2,26 +2,34 @@
...
 use crate::config::PtyConfig;
 use crate::event::{OnResize, WindowSize};
 use crate::tty::{ChildEvent, EventedPty, EventedReadWrite};
 
+// We use the same interest for reading and writing.
+pub(crate) const PTY_READ_TOKEN: usize = 0;
+pub(crate) const PTY_WRITE_TOKEN: usize = 0;
+
+// Interest in new child events.
+pub(crate) const PTY_CHILD_EVENT_TOKEN: usize = 1;
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/unix.rs:31]: Is there a way to get these tokens in a way that is actually maintainable? Figuring out which token ID is free when it's just constants all over the place is basically impossible.

File: alacritty_terminal/src/tty/unix.rs [hunk 19]
```diff
@@ -267,9 +282,9 @@ pub fn new(config: &PtyConfig, window_size: WindowSize, window_id: u64) -> Resul
             let mut pty = Pty {
                 child,
                 file: unsafe { File::from_raw_fd(master) },
-                token: mio::Token::from(0),
+                token: 0,
                 signals,
-                signals_token: mio::Token::from(0),
+                signals_token: 0,
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/unix.rs:287]: These are just arbitrary token values unrelated to our read/write tokens I'd assume. Not great they're also zero tokens.

File: alacritty_terminal/src/tty/unix.rs [hunk 20]
```diff
@@ -302,89 +317,85 @@ impl EventedReadWrite for Pty {
     #[inline]
     fn register(
         &mut self,
-        poll: &mio::Poll,
-        token: &mut dyn Iterator<Item = mio::Token>,
-        interest: mio::Ready,
-        poll_opts: mio::PollOpt,
+        poll: &Arc<polling::Poller>,
+        mut interest: polling::Event,
+        poll_opts: polling::PollMode,
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/unix.rs:322]: Not a fan of full imports again, this applies all over the place.

File: alacritty_terminal/src/tty/unix.rs [hunk 21]
```diff
@@ -302,89 +317,85 @@ impl EventedReadWrite for Pty {
...
     ) -> Result<()> {
-        self.token = token.next().unwrap();
-        poll.register(&EventedFd(&self.file.as_raw_fd()), self.token, interest, poll_opts)?;
+        self.token = PTY_READ_TOKEN;
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/unix.rs:324]: Is there any point in this? It'll always be 0 anyway.

File: alacritty_terminal/src/tty/unix.rs [hunk 22]
```diff
@@ -302,89 +317,85 @@ impl EventedReadWrite for Pty {
...
-        self.signals.pending().next().and_then(|signal| {
-            if signal != sigconsts::SIGCHLD {
-                return None;
-            }
+        // See if there has been a SIGCHLD.
+        let mut buf = [0u8; 1];
+        match self.signals.read(&mut buf) {
+            Ok(_) => {
+                // We received the signal.
+            },
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/unix.rs:378]:
```suggestion
            // We received the signal.
            Ok(_) => (),
```

File: alacritty_terminal/src/tty/unix.rs [hunk 23]
```diff
@@ -302,89 +317,85 @@ impl EventedReadWrite for Pty {
...
-                    None
-                },
-                Ok(None) => None,
-                Ok(_) => Some(ChildEvent::Exited),
-            }
-        })
-    }
+            Err(e) => {
+                // We didn't receive the signal.
+                // Either an error occurred or we got EAGAIN. We don't really care which one.
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/unix.rs:382]:
```suggestion
            Err(e) => {
```

File: alacritty_terminal/src/tty/windows/blocking.rs [hunk 24]
```diff
@@ -0,0 +1,276 @@
...
+
+use piper::{pipe, Reader, Writer};
+use polling::os::iocp::{CompletionPacket, PollerIocpExt};
+use polling::{Event, PollMode, Poller};
+
+use std::io::prelude::*;
+use std::marker::PhantomData;
+use std::sync::{Arc, Mutex};
+use std::task::{Context, Poll, Wake, Waker};
+use std::{io, thread};
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/windows/blocking.rs:11]: STD imports go at the top.

File: alacritty_terminal/src/tty/windows/conpty.rs [hunk 25]
```diff
@@ -220,8 +221,8 @@ pub fn new(config: &PtyConfig, window_size: WindowSize) -> Option<Pty> {
         }
     }
 
-    let conin = EventedAnonWrite::new(conin);
-    let conout = EventedAnonRead::new(conout);
+    let conin = UnblockedWriter::new(conin, PIPE_CAPACITY);
+    let conout = UnblockedReader::new(conout, PIPE_CAPACITY);
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/windows/conpty.rs:225]: Are we double-buffering the PTY on Windows? That seems pretty inefficient.

Have you done any performance testing on Windows?

**Review by chrisduerr — CHANGES_REQUESTED** [review]

File: alacritty_terminal/src/tty/windows/conpty.rs (hunk 25 above)
Comment (kchibisov) [reply alacritty_terminal/src/tty/windows/conpty.rs:225]: That's sort of true, but it was the case before, nothing changed here.

File: alacritty_terminal/src/event_loop.rs [hunk 26]
```diff
@@ -414,19 +299,152 @@ where
...
-            let _ = self.poll.deregister(&self.rx);
             let _ = self.pty.deregister(&self.poll);
 
             (self, state)
         })
     }
 }
+
+/// Helper type which tracks how much of a buffer has been written.
+struct Writing {
```
[the remark this answers is not in the document]
Comment (kchibisov) [reply alacritty_terminal/src/event_loop.rs:320]: This was the case before, so if you don't like the name you can rename it on master or suggest a name change.

File: alacritty_terminal/src/event_loop.rs [hunk 27]
```diff
@@ -374,17 +261,15 @@ where
                             }
                         },
 
-                        token
-                            if token == self.pty.read_token()
-                                || token == self.pty.write_token() =>
-                        {
-                            #[cfg(unix)]
+                        token if token == tty::PTY_READ_TOKEN || token == tty::PTY_WRITE_TOKEN => {
+                            /* FIXME: once polling supports extra reported modes bring it back.
```
[the remark this answers is not in the document]
Comment (kchibisov) [reply alacritty_terminal/src/event_loop.rs:265]: In general, I don't think it provides that much value given that it worked only on Linux before.

But see https://github.com/smol-rs/polling/issues/112 , I remember that it'll require a breaking bump of polling.

File: alacritty_terminal/Cargo.toml [hunk 28]
```diff
@@ -36,10 +35,9 @@ vte = { version = "0.11.1", default-features = false, features = ["ansi", "serde
 [target.'cfg(unix)'.dependencies]
 nix = { version = "0.26.2", default-features = false, features = ["term"] }
 signal-hook = "0.3.10"
-signal-hook-mio = { version = "0.2.1", features = ["support-v0_6"] }
 
 [target.'cfg(windows)'.dependencies]
-mio-anonymous-pipes = "0.2"
+piper = "0.2"
```
[the remark this answers is not in the document]
Comment (kchibisov) [reply alacritty_terminal/Cargo.toml:40]: It's this https://github.com/smol-rs/piper/ . It's maintained.

File: alacritty_terminal/src/event_loop.rs (hunk 27 above)
[the remark this answers is not in the document]
Comment (chrisduerr) [reply alacritty_terminal/src/event_loop.rs:265]: I'm pretty sure without this it might cause occasional errors on exit?

File: alacritty_terminal/Cargo.toml (hunk 28 above)
[the remark this answers is not in the document]
Comment (chrisduerr) [reply alacritty_terminal/Cargo.toml:40]: I see a PR from two months ago with a trivial change that has seen zero action. So I have my doubts.

File: alacritty_terminal/src/event_loop.rs (hunk 27 above)
[the remark this answers is not in the document]
Comment (kchibisov) [reply alacritty_terminal/src/event_loop.rs:265]: It could cause an error when you try to read again, but we have those errors on anything other than linux already (if we even have them). You may even notice that this change was added as enhancement in the past.

File: alacritty_terminal/Cargo.toml (hunk 28 above)
[the remark this answers is not in the document]
Comment (kchibisov) [reply alacritty_terminal/Cargo.toml:40]: @chrisduerr from dependabot....

File: alacritty_terminal/src/event_loop.rs [hunk 29]
```diff
@@ -313,17 +205,13 @@ where
...
             let mut buf = [0u8; READ_BUFFER_SIZE];
 
-            let mut tokens = (0..).map(Into::into);
-
-            let poll_opts = PollOpt::edge() | PollOpt::oneshot();
-
-            let channel_token = tokens.next().unwrap();
-            self.poll.register(&self.rx, channel_token, Ready::readable(), poll_opts).unwrap();
+            let poll_opts = polling::PollMode::Level;
+            let mut interest = polling::Event::readable(0);
```
[the remark this answers is not in the document]
Comment (notgull) [reply alacritty_terminal/src/event_loop.rs:209]: The zero is just a placeholder for the token to be interested in.

File: alacritty_terminal/Cargo.toml (hunk 28 above)
[the remark this answers is not in the document]
Comment (notgull) [reply alacritty_terminal/Cargo.toml:40]: `piper` was extracted somewhat recently from `blocking`, which is already used in production in various places. The only reason no changes have been made is because `piper` has already been scrutinized very closely through its prior use in `blocking`. Not to mention it's not used directly in many places at the moment, so there's no issues to be filed (and therefore no changes to be made). For more context see [this](https://github.com/smol-rs/async-channel/issues/1) issue.

File: alacritty_terminal/src/event_loop.rs (hunk 27 above)
[the remark this answers is not in the document]
Comment (notgull) [reply alacritty_terminal/src/event_loop.rs:265]: As @kchibisov commented, this is just an optimization for now. It can be added back once we add greater event granularity to `polling`.

File: alacritty_terminal/src/tty/unix.rs (hunk 21 above)
Comment (notgull) [reply alacritty_terminal/src/tty/unix.rs:324]: It clarifies that the token is representative of the read token.

File: alacritty_terminal/Cargo.toml (hunk 28 above)
[the remark this answers is not in the document]
Comment (chrisduerr) [reply alacritty_terminal/Cargo.toml:40]: > @chrisduerr from dependabot....

Dependabot doesn't make random changes unless requested. If requested and not acted upon, there's clearly *some* maintenance issues.

File: alacritty_terminal/src/event_loop.rs (hunk 27 above)
[the remark this answers is not in the document]
Comment (chrisduerr) [reply alacritty_terminal/src/event_loop.rs:265]: Either way I don't like the documentation in the comments. If this is something we want to track, it should be removed from the code and added to the issue tracker.

File: alacritty_terminal/src/tty/unix.rs (hunk 21 above)
Comment (chrisduerr) [reply alacritty_terminal/src/tty/unix.rs:324]: How is that any different from just initializing it to the read token from the start?

File: alacritty_terminal/src/tty/unix.rs (hunk 18 above)
Comment (notgull) [reply alacritty_terminal/src/tty/unix.rs:31]: We could just have an `Iterator` like we did in the old code. This was how it was done originally but it was requested that we move to this constant based approach instead.

File: alacritty_terminal/src/tty/unix.rs (hunk 19 above)
Comment (notgull) [reply alacritty_terminal/src/tty/unix.rs:287]: Yes, these are empty tokens.

File: alacritty_terminal/src/tty/unix.rs (hunk 21 above)
Comment (notgull) [reply alacritty_terminal/src/tty/unix.rs:324]: This mirrors how it was done in the `mio` code. If you want I can change it to be initialized in this way from the start.

**Comment by ognevnydemon** [comment]
is there any progress? just for interest

**Comment by notgull** [comment]
I've updated to the new breaking release of `polling`, version 3.0. This adds some new (checked) unsafe code to this crate.

File: alacritty_terminal/src/event_loop.rs [hunk 30]
```diff
@@ -158,28 +66,28 @@ where
...
             terminal,
             event_proxy,
             hold,
             ref_test,
         }
     }
 
-    pub fn channel(&self) -> Sender<Msg> {
-        self.tx.clone()
+    pub fn channel(&self) -> EventLoopSender {
```
Comment (nixpulvis) [inline alacritty_terminal/src/event_loop.rs:82]: Might not be a bad idea to rename this function to be a bit more clear.

Maybe `send_channel`?

File: alacritty_terminal/src/event_loop.rs [hunk 31]
```diff
@@ -313,17 +207,15 @@ where
...
+            let mut interest = PollingEvent::readable(0);
 
             // Register TTY through EventedRW interface.
-            self.pty.register(&self.poll, &mut tokens, Ready::readable(), poll_opts).unwrap();
+            unsafe {
+                self.pty.register(&self.poll, interest, poll_opts).unwrap();
+            }
 
-            let mut events = Events::with_capacity(1024);
+            let mut events = Events::with_capacity(NonZeroUsize::new(128).unwrap());
```
Comment (nixpulvis) [inline alacritty_terminal/src/event_loop.rs:218]: Why the large decrease in size?

File: alacritty_terminal/src/event_loop.rs [hunk 32]
```diff
@@ -337,29 +229,29 @@ where
...
+                if let Err(err) = self.poll.wait(&mut events, timeout) {
                     match err.kind() {
                         ErrorKind::Interrupted => continue,
                         _ => panic!("EventLoop polling error: {err:?}"),
                     }
                 }
 
                 // Handle synchronized update timeout.
-                if events.is_empty() {
+                if events.is_empty() && self.rx.peek().is_none() {
```
Comment (nixpulvis) [inline alacritty_terminal/src/event_loop.rs:241]: Is there no way to setup the abstractions so that the calls to `poll` and the event buffer are always in sync, thus avoiding this extra peak condition?

File: alacritty_terminal/Cargo.toml [hunk 33]
```diff
@@ -36,10 +35,9 @@ vte = { version = "0.12.0", default-features = false, features = ["ansi", "serde
...
```
Comment (chrisduerr) [inline alacritty_terminal/Cargo.toml:40]:
```suggestion
piper = "0.2.1"
```

File: alacritty_terminal/src/event_loop.rs (hunk 30 above)
Comment (chrisduerr) [reply alacritty_terminal/src/event_loop.rs:82]: Not a bad suggestion, but won't block on this since it's unrelated to this PR.

File: alacritty_terminal/src/event_loop.rs (hunk 31 above)
Comment (chrisduerr) [reply alacritty_terminal/src/event_loop.rs:218]: +1 to this question. I don't really mind, but I'd like a reason stated.

File: alacritty_terminal/src/event_loop.rs [hunk 34]
```diff
@@ -374,17 +266,10 @@ where
...
-                            if token == self.pty.read_token()
-                                || token == self.pty.write_token() =>
-                        {
-                            #[cfg(unix)]
-                            if UnixReady::from(event.readiness()).is_hup() {
-                                // Don't try to do I/O on a dead PTY.
-                                continue;
-                            }
+                        token if token == tty::PTY_READ_TOKEN || token == tty::PTY_WRITE_TOKEN => {
+                            // FIXME: once polling supports extra reported modes bring it back.
```
Comment (chrisduerr) [inline alacritty_terminal/src/event_loop.rs:270]: This should be an issue. Comments are useless and just get lost.

Also missing what "it" is here. Bring what back?

File: alacritty_terminal/src/tty/mod.rs [hunk 35]
```diff
@@ -22,20 +25,15 @@ pub trait EventedReadWrite {
...
-        _: mio::Ready,
-        _: mio::PollOpt,
-    ) -> io::Result<()>;
-    fn reregister(&mut self, _: &mio::Poll, _: mio::Ready, _: mio::PollOpt) -> io::Result<()>;
-    fn deregister(&mut self, _: &mio::Poll) -> io::Result<()>;
+    /// # Safety
+    ///
+    /// The underlying sources must outlive their registration in the `Poller`.
+    unsafe fn register(&mut self, _: &Arc<Poller>, _: Event, _: PollMode) -> io::Result<()>;
+    fn reregister(&mut self, _: &Arc<Poller>, _: Event, _: PollMode) -> io::Result<()>;
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/mod.rs:32]: I'd assume that reregister has mostly the same properties as register. Is this safety note not also true for reregister?

File: alacritty_terminal/src/tty/unix.rs (hunk 10 above)
Comment (chrisduerr) [reply alacritty_terminal/src/tty/unix.rs:29]: +1

File: alacritty_terminal/src/tty/unix.rs (hunk 21 above)
Comment (chrisduerr) [reply alacritty_terminal/src/tty/unix.rs:325]: Would probably be cleaner this way. The mio code wasn't perfect, there's no need to keep things consistent for the sake of being similar to the mio code when there's a better solution available.

**Review by chrisduerr — CHANGES_REQUESTED** [review]

File: alacritty_terminal/src/tty/unix.rs [hunk 36]
```diff
@@ -300,91 +316,80 @@ impl EventedReadWrite for Pty {
...
-                    error!("Error checking child process termination: {}", e);
-                    None
-                },
-                Ok(None) => None,
-                Ok(_) => Some(ChildEvent::Exited),
-            }
-        })
-    }
+            },
+        }
```
Comment (kchibisov) [inline alacritty_terminal/src/tty/unix.rs:382]: Looks like `if let Err(err)`

File: alacritty_terminal/src/tty/unix.rs [hunk 37]
```diff
@@ -300,91 +316,80 @@ impl EventedReadWrite for Pty {
...
 
-    #[inline]
-    fn child_event_token(&self) -> mio::Token {
-        self.signals_token
+        // Match on the child process.
+        match self.child.try_wait() {
+            Err(e) => {
+                error!("Error checking child process termination: {}", e);
```
Comment (kchibisov) [inline alacritty_terminal/src/tty/unix.rs:387]:
```suggestion
            Err(err) => {
                error!("Error checking child process termination: {err}");
```

**Review by kchibisov — CHANGES_REQUESTED** [review]

File: alacritty_terminal/src/event_loop.rs [hunk 38]
```diff
@@ -337,29 +229,29 @@ where
                 let timeout =
                     handler.sync_timeout().map(|st| st.saturating_duration_since(Instant::now()));
 
-                if let Err(err) = self.poll.poll(&mut events, timeout) {
+                events.clear();
```
[the remark this answers is not in the document]
Comment (notgull) [reply alacritty_terminal/src/event_loop.rs:232]: `polling` v3.0.0 has a separate `Events` structure, with only `iter()` and `clear()`.

File: alacritty_terminal/src/tty/mod.rs (hunk 35 above)
Comment (notgull) [reply alacritty_terminal/src/tty/mod.rs:32]: "register" clones the raw file descriptor into the `Poller`, which is an unsafe operation. "reregister" does not do this.

File: Cargo.lock [hunk 39]
```diff
@@ -365,42 +357,40 @@ dependencies = [
 
 [[package]]
 name = "clap"
-version = "4.3.3"
+version = "4.4.2"
```
Comment (kchibisov) [inline Cargo.lock:360]: Could you please, update the lock file only by the means of added dependencies? So you actually won't have broken tests due to clap change? It'll also be easier for us to test things and see what was added.

You could though, remove dups if you see a way to do so.

**Review by kchibisov — APPROVED** [review]
Tested macOS/Windows

**Review by chrisduerr — APPROVED** [review]

**Comment by chrisduerr** [comment]
Thanks for working on this.
