### PR TITLE
Switch to TOML configuration format

### LINKED ISSUE #6592: Switch to TOML for configuration file
I'm quite honestly tired of looking at YAML files with broken indentation. While YAML is an awful format even for experienced users, clearly it's completely impossible for inexperienced ones to grasp its concept. And the documentation of our configuration file with everything commented out by default probably doesn't help.

Since as far as I know all previous issues with TOML have been fixed and escape sequences can be easily specified in TOML strings now, I think it would make sense to switch to TOML as our default format.

In a transitory period we could probably get away with just loading existing YAML files and writing them out as TOML, to allow for backward compatibility. This will probably produce somewhat messy TOML files, but I can't imagine an auto-generated TOML file would be much worse than a YAML file.

The only major drawbacks I see is that this is a rather big change that will no doubt annoy a bunch of people and some more advanced features of YAML (like anchors) are not supported in TOML. But nobody *really* needs anchors and I kinda like annoying people.

@kchibisov You proposed this a while ago on IRC, do you think this is a bad idea?

See https://github.com/alacritty/alacritty/issues/1217 for prior discussions.

### PR DESCRIPTION
**Pull request by chrisduerr**
This switches Alacritty's default configuration format from yaml to toml. While yaml is still supported, it is done by converting it to toml and should be removed entirely in the future.

All existing features were persisted based on my testing. Behavior should not change much, though `--option` might have slightly different behavior since the entire line is not interpreted as one line of toml.

TODO:
 - [x] Migrate alacritty.yml => Might want to reconsider defaults being commented out?
 - [X] Write/Test an `alacritty migrate` tool which converts the configuration file for the user
 - [x] Warn on unused keys
 - [x] Find solution to `key_bindings` at the top requirement

Closes #6592.

### CODE REVIEW

**Comment by chrisduerr** [comment]
While I do intend to finish this up with the remaining todos in the near future, I'm curious about what you think about this approach @kchibisov. For someone who doesn't want an automatic migration, all the code should be done already and behavior doesn't need any changes afaik.

File: alacritty/src/config/mod.rs [hunk 1]
```diff
@@ -186,18 +214,17 @@ fn parse_config(
         contents = contents.split_off(3);
     }
 
+    // Convert YAML to TOML as a transitionary fallback mechanism.
+    let extension = path.extension().unwrap_or_default();
+    if (extension == "yaml" || extension == "yml") && !contents.trim().is_empty() {
```
Comment (kchibisov) [inline alacritty/src/config/mod.rs:219]: From what I remember we don't allow `yaml` extension, just `yml`.

```suggestion
    if (extension == "yml") && !contents.trim().is_empty() {
```

File: alacritty/src/config/bindings.rs [hunk 2]
```diff
@@ -1010,19 +1010,20 @@ impl<'a> Deserialize<'a> for RawBinding {
...
+                            match value.as_integer() {
+                                Some(scancode) => {
+                                    if scancode > i64::from(u32::MAX) {
+                                        return Err(<V::Error as Error>::custom(format!(
+                                            "Invalid key binding, scancode too big: {}",
+                                            scancode
+                                        )));
+                                    }
+                                    key = Some(Key::Scancode(scancode as u32));
+                                },
```
Comment (kchibisov) [inline alacritty/src/config/bindings.rs:1023]: Maybe do explicit check for negative numbers?

File: alacritty.toml [hunk 3]
```diff
@@ -0,0 +1,905 @@
+# Configuration for Alacritty, the GPU enhanced terminal emulator.
```
Comment (kchibisov) [inline alacritty.toml:1]: That's not a `toml`.

**Review by kchibisov — COMMENTED** [review]
I can't say much, given that the code does very little useful. Most of it is simply conversion from `yaml` to `toml`, which is simply replace `serde_yaml` with `toml`.

From what I can see the `migrate` thing isn't written yet, and the entire config file is still `yaml`. If you plan on doing `migrate` I'd suggest to convert it file by file separately without `import` chaining. I'd also suggest to output to user provided path, instead of overwriting files. Maybe add a suggestion on how to migrate it.

**Comment by chrisduerr** [comment]
>  If you plan on doing migrate I'd suggest to convert it file by file separately without import chaining. I'd also suggest to output to user provided path, instead of overwriting files. Maybe add a suggestion on how to migrate it.

Since `.toml` and `.yml` aren't in conflict, my plan was just to go through every single configuration file, parse it with yaml, then write the toml to `alacritty.toml` in the same location the `.yml` was in. I think that should work pretty well and should be completely non-destructive. Then we can just ask people to delete their yaml files.

This also gives me an idea though: I kinda gotten used to loading the old stuff first, but I don't think we should be doing that. Right now yaml is loaded first and toml tried second. We should swap that around. For config values it makes sense to check the old one first because of the way our config struct is built, but for configuration files it should be trivial to just always pick the best available format.

I'm not entirely sure if I want to rewrite import paths to switch them from `yml` to `toml` since that requires changes in two places, but I think there shouldn't be much risk for failure.

File: alacritty/src/config/mod.rs (hunk 1 above)
Comment (chrisduerr) [reply alacritty/src/config/mod.rs:219]: Correct, but I intentionally accept both here since `--config-file` is a thing which some people might use in their weird setups. It costs nothing and should be a little safer.

Of course people could also do `--config-file /tmp/whatever`, but if you do that without a file suffix then fuck you, you deserve the error.

File: alacritty.toml (hunk 3 above)
Comment (chrisduerr) [reply alacritty.toml:1]: Shhh, don't tell anyone.

**Comment by kchibisov** [comment]
>Since .toml and .yml aren't in conflict, my plan was just to go through every single configuration file, parse it with yaml, then write the toml to alacritty.toml in the same location the .yml was in. I think that should work pretty well and should be completely non-destructive. Then we can just ask people to delete their yaml files.

The location might be RO.

>This also gives me an idea though: I kinda gotten used to loading the old stuff first, but I don't think we should be doing that. Right now yaml is loaded first and toml tried second. We should swap that around. For config values it makes sense to check the old one first because of the way our config struct is built, but for configuration files it should be trivial to just always pick the best available format.

Yeah, that's expected to try new first and then fallback to the old one.

>I'm not entirely sure if I want to rewrite import paths to switch them from yml to toml since that requires changes in two places, but I think there shouldn't be much risk for failure.

Nah, I think we should provide a manual way to convert all of them, writing might not work in the first place. Though you could provide option with output and option with automatic writing.

File: alacritty/src/config/bindings.rs (hunk 2 above)
Comment (chrisduerr) [reply alacritty/src/config/bindings.rs:1023]: We need to check for both negative numbers **and** positive numbers that are too big though. But there's no need why we would convert twice, so we can just use `u32::try_from` instead.

**Comment by chrisduerr** [comment]
> The location might be RO.

In which case we just print an error and exit the `migrate` tool. I'd assume this might happen with some shared config setups in like `/etc` or whatever, but it shouldn't be common enough to where we somehow need to explicitly support it.

If you have a system admin config and you run it without privileges we just fail and you can rerun it with the privileged user.

> Nah, I think we should provide a manual way to convert all of them, writing might not work in the first place. Though you could provide option with output and option with automatic writing.

How likely is it that writing won't work though? I'd assume you're thinking about your weird ass nixOS system?

But having an output-only option seems sensible.

**Comment by kchibisov** [comment]
>How likely is it that writing won't work though? I'd assume you're thinking about your weird ass nixOS system?

Yeah, your config is a symlink to RO filesystem, so you can't even write to it with 'root'.

**Comment by chrisduerr** [comment]
Testing that @perfbot is back online.

**Comment by fee1-dead** [comment]
> This switches Alacritty's default configuration format from toml to yaml

from toml to yaml? this should preferably be changed

**Comment by chrisduerr** [comment]
@perfbot test

**Comment by WuerfelDev** [comment]
Regarding configuration files, I'd love to have some fallback keys (maybe with `keyname_fallback = "value"` since toml doesn't allow duplicate keys). Maybe that's something we could integrate?
As example: currently I want to use `window: {decorations: buttonless}` on mac but when I use my config on linux I get an error. If there was a fallback I wouldn't have to maintain two versions of the same config file

**Comment by amtoine** [comment]
i like this idea :yum: 

what is the status of the PR? :open_mouth:

**Comment by chrisduerr** [comment]
> what is the status of the PR?

I don't think there's any rush to migrate. Currently the only thing somewhat uncertain is documentation I suppose.

**Comment by amtoine** [comment]
> > what is the status of the PR?
> 
> I don't think there's any rush to migrate. Currently the only thing somewhat uncertain is documentation I suppose.
>
oh yeah of course, just curious to see a new format :yum:

File: docs/features.md [hunk 4]
```diff
@@ -77,7 +77,7 @@ file. If an application captures your mouse clicks, which is indicated by a
 change in mouse cursor shape, you're required to hold <kbd>Shift</kbd> to bypass
 that.
 
-[configuration file]: ../alacritty.yml
+[configuration file]: ../alacritty.toml
```
Comment (kchibisov) [inline docs/features.md:80]: I don't think we have it.

File: extra/man/alacritty-bindings.5.scd [hunk 5]
```diff
@@ -0,0 +1,478 @@
...
+:[
+:  _"Copy"_
+|  _"L"_
+:  _"Control"_
+:[
+:  _"ClearLogNotice"_
+|  _"L"_
+:  _"Control"_
+:  _"~Vi|~Search"_
+:  *chars*: _"\x0c"_
```
Comment (kchibisov) [inline extra/man/alacritty-bindings.5.scd:48]: I'd assume you've ensured that `\x` bindings do work? I remember they were not a part of initial spec.

File: extra/man/alacritty.5.scd [hunk 6]
```diff
@@ -0,0 +1,800 @@
...
+
+	Allowed values are hexadecimal colors like _#ff00ff_, or
+	_CellForeground_/_CellBackground_, which references the affected cell.
+
+	Default: _{ text = "CellBackground", background = "CellForeground" }_
+
+*normal*
+
+	*black* <string>
+		Default: _"#1d1f21"_
```
Comment (kchibisov) [inline extra/man/alacritty.5.scd:336]: I see that you want me to port this as well...

File: alacritty/src/migrate.rs [hunk 7]
```diff
@@ -0,0 +1,130 @@
...
+use std::fs;
+use std::path::Path;
+
+use toml::Value;
+
+use crate::cli::MigrateOptions;
+use crate::config;
+
+/// Handle migration.
+pub fn migrate(options: MigrateOptions) {
```
[the remark this answers is not in the document]
Comment (chrisduerr) [reply alacritty/src/migrate.rs:12]: Seems like the easiest solution to me?

File: docs/features.md (hunk 4 above)
Comment (chrisduerr) [reply docs/features.md:80]: It wasn't actually a link anyway.

File: alacritty/src/migrate.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (kchibisov) [reply alacritty/src/migrate.rs:12]: I mean, it's a bit weird that we have normal error handling in other sub command and have lazy `eprintln` + `exit` here.

File: extra/man/alacritty.5.scd (hunk 6 above)
Comment (chrisduerr) [reply extra/man/alacritty.5.scd:336]: :)

File: extra/man/alacritty-bindings.5.scd (hunk 5 above)
Comment (chrisduerr) [reply extra/man/alacritty-bindings.5.scd:48]: They do not work… yet.

File: alacritty/src/config/mod.rs [hunk 8]
```diff
@@ -179,58 +208,101 @@ fn parse_config(
...
+                error!(target: LOG_TARGET_CONFIG, "Unable to import config {:?}: {}", path, err)
+            },
+        }
+    }
+
+    merged
+}
+
+// TODO: Merge back with `load_imports` once `alacritty migrate` is dropped.
+//
```
[the remark this answers is not in the document]
Comment (kchibisov) [reply alacritty/src/config/mod.rs:282]: That `//` comments flow into `///` comments.

[the remark this answers is not in the document]
Comment (chrisduerr) [reply alacritty/src/config/mod.rs:282]: I see no issue with it tbh.

**Comment by ngortheone** [comment]
I like this idea. 
What are the technical reasons for the switch?
Is yaml parsing too slow? Yaml dependencies too bloated? ...

Or simply out of pure hatred of yaml?
https://ruudvanasseldonk.com/2023/01/11/the-yaml-document-from-hell

**Comment by kchibisov** [comment]
folks can't write their configs with yaml because of indention.

**Comment by kchibisov** [comment]
also, we could warn on unused fields now.

**Comment by chrisduerr** [comment]
> Or simply out of pure hatred of yaml?

Yes.

**Comment by chrisduerr** [comment]
> also, we could warn on unused fields now.

We not only could, we do. It is implemented already in this PR.

**Review by kchibisov — CHANGES_REQUESTED** [review]
I think now I went through all the thing.

File: extra/man/alacritty.5.scd [hunk 9]
```diff
@@ -0,0 +1,800 @@
...
+
+		If the bright foreground color is not set, it is automatically
+		calculated based on the foreground color.
+
+		Default: _"#828482"_
+
+	*bright_foreground* <string>
+
+		If the bright foreground color is not set, or
+		_draw\_bold\_text\_with\_bright\_colors_ is _false_, the normal
```
[the remark this answers is not in the document]
Comment (chrisduerr) [reply extra/man/alacritty.5.scd:250]: I'm not sure what you mean by this.

File: extra/man/alacritty.5.scd [hunk 10]
```diff
@@ -0,0 +1,800 @@
...
+
+		Default: _"#1d1f21"_
+
+	*background* <string>
+
+		Default: _"#c5c8c6"_
+
+	*dim_foreground* <string>
+
+		If the bright foreground color is not set, it is automatically
```
Comment (kchibisov) [inline extra/man/alacritty.5.scd:242]:
```suggestion
		If the dim foreground color is not set, it is automatically
```

I think it's `dim`?

File: extra/man/alacritty.5.scd [hunk 11]
```diff
@@ -0,0 +1,800 @@
...
+
+		Default: _"#828482"_
+
+	*bright_foreground* <string>
+
+		If the bright foreground color is not set, or
+		_draw\_bold\_text\_with\_bright\_colors_ is _false_, the normal
+		foreground color will be used.
+
+		Default: _"#eaeaea"_
```
Comment (kchibisov) [inline extra/man/alacritty.5.scd:253]:
```suggestion
		Default: _None_
```

We don't set it, meaning that we don't use it, unlike dim which is used, but auto calculated.

File: extra/man/alacritty.5.scd (hunk 9 above)
[the remark this answers is not in the document]
Comment (kchibisov) [reply extra/man/alacritty.5.scd:250]: I wanted something like:

```
This will be used only when it's set and _draw_bold_text_with_bright_colors is true.
```

Or something similar.

File: INSTALL.md [hunk 12]
```diff
@@ -333,6 +333,8 @@ Installing the manual page requires the additional dependencies `gzip` and `scdo
 sudo mkdir -p /usr/local/share/man/man1
 scdoc < extra/man/alacritty.1.scd | gzip -c | sudo tee /usr/local/share/man/man1/alacritty.1.gz > /dev/null
 scdoc < extra/man/alacritty-msg.1.scd | gzip -c | sudo tee /usr/local/share/man/man1/alacritty-msg.1.gz > /dev/null
+scdoc < extra/man/alacritty.5.scd | gzip -c | sudo tee /usr/local/share/man/man5/alacritty.5.gz > /dev/null
+scdoc < extra/man/alacritty-bindings.5.scd | gzip -c | sudo tee /usr/local/share/man/man5/alacritty-bindings.5.gz > /dev/null
```
[the remark this answers is not in the document]
Comment (chrisduerr) [reply INSTALL.md:337]: I don't think it's relevant tbh.

File: extra/man/alacritty.5.scd (hunk 10 above)
Comment (kchibisov) [reply extra/man/alacritty.5.scd:242]: Also, the default in the config is `None`, when you look into color.rs, so it could be changed either here or in the configuration to specify the value explicitly. It's also a bit weird that we have `Dim` colors defined in the config, but not use `None`.

it's also weird that we have `Dim` colors defined in the `color.rs`, but they actually never used, but still being computed on demand.

File: alacritty/src/cli.rs [hunk 13]
```diff
@@ -30,17 +28,18 @@ pub struct Options {
...
     pub config_file: Option<PathBuf>,
 
-    /// Specify alternative configuration file [default: %APPDATA%\alacritty\alacritty.yml].
+    /// Specify alternative configuration file [default: %APPDATA%\alacritty\alacritty.toml].
     #[cfg(windows)]
     #[clap(long, value_hint = ValueHint::FilePath)]
     pub config_file: Option<PathBuf>,
 
-    /// Specify alternative configuration file [default: $HOME/.config/alacritty/alacritty.yml].
+    /// Specify alternative configuration file [default: $HOME/.config/alacritty/alacritty.toml].
```
[the remark this answers is not in the document]
Comment (chrisduerr) [reply alacritty/src/cli.rs:42]: I don't think it's relevant for macOS users though? They basically never have it set.

File: docs/features.md [hunk 14]
```diff
@@ -77,8 +77,6 @@ file. If an application captures your mouse clicks, which is indicated by a
 change in mouse cursor shape, you're required to hold <kbd>Shift</kbd> to bypass
 that.
 
-[configuration file]: ../alacritty.yml
```
[the remark this answers is not in the document]
Comment (chrisduerr) [reply docs/features.md:80]: Oh I thought this was never used because I couldn't find it. I didn't think it would be broken across lines.

File: alacritty_config_derive/src/config_deserialize/de_struct.rs [hunk 15]
```diff
@@ -42,20 +42,25 @@ pub fn derive_deserialize<T>(
...
+                            unused.insert(key, value);
                         },
                     }
                 }
 
                 #flatten
 
+                // Warn about unused keys.
+                for key in unused.keys() {
+                    log::warn!(target: #LOG_TARGET, "Unused config key: {}", key);
```
[the remark this answers is not in the document]
Comment (chrisduerr) [reply alacritty_config_derive/src/config_deserialize/de_struct.rs:61]: Add it where?

File: alacritty/src/migrate.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (chrisduerr) [reply alacritty/src/migrate.rs:12]: I want to keep it this way because it gives us more control over the error messages.

We're not just trying to print errors and bail here, but instead we're trying to have nice human-readable CLI output.

That's why I did it this way, letting Rust's `?` handle error printing is usually worse.

File: alacritty/src/config/ui_config.rs [hunk 16]
```diff
@@ -90,29 +97,36 @@ impl Default for UiConfig {
...
 }
 
 impl UiConfig {
     /// Generate key bindings for all keyboard hints.
     pub fn generate_hint_bindings(&mut self) {
+        let key_bindings = if self.keyboard.bindings.0.len() >= self.key_bindings.0.len() {
+            &mut self.keyboard.bindings.0
+        } else {
+            &mut self.key_bindings.0
+        };
```
[the remark this answers is not in the document]
Comment (chrisduerr) [reply alacritty/src/config/ui_config.rs:128]: It's because of our default bindings.

File: alacritty/src/migrate.rs [hunk 17]
```diff
@@ -0,0 +1,130 @@
...
+    // Migrate config imports.
+    if !options.skip_imports {
+        migrate_imports(options, &mut config, recursion_limit)?;
+    }
+
+    // Convert to TOML format.
+    let toml = toml::to_string(&config).map_err(|err| format!("conversion error: {err}"))?;
+    let new_path = format!("{prefix}.toml");
+
+    if options.dry_run && !options.silent {
```
[the remark this answers is not in the document]
Comment (chrisduerr) [reply alacritty/src/migrate.rs:89]: > Maybe we should move deprecated fields into the right sections automatically?

I'm looking into this.

> Also, each keybinding resulted in separate [[key_bindings]] after conversion, though, not sure what we should do about that.

I don't think there's any way we'll be able to format the keybindings nicely.

File: extra/man/alacritty.5.scd (hunk 11 above)
Comment (chrisduerr) [reply extra/man/alacritty.5.scd:253]: I believe we've intentionally specified colors here so people have an easier time copying Alacritty's colorscheme.

Your suggestion is technically correct, but I think in this very specific scenario it's better to be a little bit wrong.

File: alacritty/src/cli.rs (hunk 13 above)
[the remark this answers is not in the document]
Comment (kchibisov) [reply alacritty/src/cli.rs:42]: That's true, but it doesn't deny a fact that it's used as first.

File: extra/man/alacritty.5.scd (hunk 11 above)
Comment (kchibisov) [reply extra/man/alacritty.5.scd:253]: The thing is that it's not computed and such color is not used, so there's no such color and the value written here is arbitrary.

For dim colors it's correct, but not here.

File: alacritty_config_derive/src/config_deserialize/de_struct.rs (hunk 15 above)
[the remark this answers is not in the document]
Comment (kchibisov) [reply alacritty_config_derive/src/config_deserialize/de_struct.rs:61]: In the `CHANGELOG`.

**Review by kchibisov — CHANGES_REQUESTED** [review]

File: alacritty/src/migrate.rs [hunk 18]
```diff
@@ -0,0 +1,215 @@
...
+        Ok(true)
+    } else {
+        let next_table_value = table.entry(path[0]).or_insert_with(|| Value::Table(Table::new()));
+
+        let next_table = match next_table_value.as_table_mut() {
+            Some(next_table) => next_table,
+            None => return Err(format!("invalid `{}` table", path[0])),
+        };
+
+        insert_node_if_empty(next_table, &path[1..], node)
```
[the remark this answers is not in the document]
Comment (chrisduerr) [reply alacritty/src/migrate.rs:213]: Why? Doing it recursively is significantly cleaner imo and there's no chance this will bust the stack.

[the remark this answers is not in the document]
Comment (kchibisov) [reply alacritty/src/migrate.rs:213]: it's just you have tail recursion, so it's already sort of iteration, but it's up to you. If it was the library code I'd force iteration as it's efficient, but here it's probably fine.

[the remark this answers is not in the document]
Comment (chrisduerr) [reply alacritty/src/migrate.rs:213]: Yeah the **sole** reason for this is to make the code cleaner, which I think in this scenario should have priority.

A lot of times recursion can be confusing, but this is one of those things that just maps naturally to it imo.

File: alacritty/src/migrate.rs (hunk 17 above)
[the remark this answers is not in the document]
Comment (chrisduerr) [reply alacritty/src/migrate.rs:94]: I don't think there's a way to format them nicely automatically.

File: extra/man/alacritty.5.scd [hunk 19]
```diff
@@ -0,0 +1,823 @@
...
+
+	Allow terminal applications to change Alacritty's window title.
+
+	Default: _true_
+
+*class* { instance = <string>, general = <string> } _(Linux/BSD only)_
+
+	Window class
+
+	On Wayland, _general_ is used as app_id and _instance_ is ignored.
```
Comment (kchibisov) [inline extra/man/alacritty.5.scd:125]:
```suggestion
	On Wayland, _general_ is used as _app\_id_ and _instance_ is ignored.
```

**Review by kchibisov — APPROVED** [review]

**Comment by amtoine** [comment]
i've been subscribed to this for a while and i'm super happy to see it land :star_struck:

File: .github/workflows/release.yml [hunk 20]
```diff
@@ -87,4 +89,3 @@ jobs:
           ./.github/workflows/upload_asset.sh ./extra/completions/_alacritty $GITHUB_TOKEN
           ./.github/workflows/upload_asset.sh ./extra/linux/Alacritty.desktop $GITHUB_TOKEN
           ./.github/workflows/upload_asset.sh ./extra/alacritty.info $GITHUB_TOKEN
-          ./.github/workflows/upload_asset.sh ./alacritty.yml $GITHUB_TOKEN
```
Comment (aboqasem) [inline .github/workflows/release.yml:90]: Hello, my I know if there will be an alternative way to get the default TOML config with comments?

Comment (aboqasem) [reply .github/workflows/release.yml:90]: Ok it's already been asked: https://github.com/alacritty/alacritty/issues/6592#issuecomment-1603702638
