### PR TITLE
Fix FD leak after closing child windows

### LINKED ISSUE #7983: alacritty msg create-window leaves a unix fifo behind
I like my terminals popping up fast, so I use this script to start them:
```
/home/greg/.cargo/bin/alacritty msg create-window ||
exec /home/greg/.cargo/bin/alacritty -o 'font.normal.family: JetBrainsMono' -o 'draw_bold_text_with_bright_colors: true'
```

Curiously, starting a new window and closing it reliably leaves an extra fd behind.

The way I monitor it is I lookup the `alacritty` pid and then run this loop:
```
% while sleep 1; do lsof -p 17550 | grep -v mem | wc -l; done
31
31
31
... launched then closed a window captured logs of FDs attached
32
38 <- new window
33 <- closed
39 <- new window
34 <- closed
40 <- new window
35 <- closed
35
35
```

The delta between the initial set of FDs and after the second window is closed is this single FIFO.
% diff /tmp/{1,3}.txt
28a29
> alacritty 17550 greg   30u     unix 0x000000003920e72d       0t0  167503 type=STREAM (CONNECTED)

Starting more windows adds more such FIFOs left behind.

### System

OS: Linux 6.1.0-21-amd64 (also OpenBSD)
Version: alacritty 0.13.2
Linux/BSD: X11

### Logs

FDs right after the first process starts [1.txt](https://github.com/alacritty/alacritty/files/15329794/1.txt)
FDs when the second window is opened [2.txt](https://github.com/alacritty/alacritty/files/15329795/2.txt)
FDs after the second window is closed [3.txt](https://github.com/alacritty/alacritty/files/15329796/3.txt)

### PR DESCRIPTION
**Pull request by chrisduerr**
This patch fixes an issue with signal handling where Alacritty would permanently create one signal handling FD for each alacritty window created by an instance. This FD was never released, causing a leak of the FD.

Closes #7983.

### CODE REVIEW

**Comment by blackgnezdo** [comment]
Looks reasonable to me. Given that you see the issue fixed on your end, I expect it to not replicate for me either. 

Thanks for the prompt fix!

File: alacritty_terminal/src/tty/unix.rs [hunk 1]
```diff
@@ -260,13 +261,13 @@ pub fn from_fd(config: &Options, window_id: u64, master: OwnedFd, slave: OwnedFd
     }
 
     // Prepare signal handling before spawning child.
-    let signals = {
+    let (signals, sig_id) = {
         let (sender, recv) = UnixStream::pair()?;
 
         // Register the recv end of the pipe for SIGCHLD.
-        signal_pipe::register(sigconsts::SIGCHLD, sender)?;
+        let sig_id = signal_pipe::register(sigconsts::SIGCHLD, sender)?;
```
Comment (kchibisov) [inline alacritty_terminal/src/tty/unix.rs:268]: that's really unfortunate that it's not a `must_use`

**Review by kchibisov — APPROVED** [review]

File: alacritty_terminal/src/tty/unix.rs (hunk 1 above)
Comment (chrisduerr) [reply alacritty_terminal/src/tty/unix.rs:268]: Yeah the docs state the issue, but that's far too easy to miss.

**Comment by WGH-** [comment]
Any chance of doing 0.13.3 bugfix release with this patch?

**Comment by chrisduerr** [comment]
I'll try to get an RC out later today. So hopefully a release next week.
