### PR TITLE
Fix damage tracking on Wayland

### LINKED ISSUE #4736: Missing Wayland Input Redraws
I just updated to `alacritty 0.8.0-dev (530de000)`, and while using Wayland I now experience an issue where Alacritty seems to be missing redraw requests. Input will be received correctly, but the display isn't updated until another input is received. This causes the display to lag behind my typing (for example) by exactly one keystroke.

### PR DESCRIPTION
**Pull request by chrisduerr**
Since the Wayland event loop might delay rendering across event loop
callback executions, it's necessary to track the global damage globally
rather than just within a single loop execution.

Fixes #4736.

### CODE REVIEW

**Comment by mckellygit** [comment]
Hi,
I tested this commit and it is MUCH better now, feels like the issue is fixed.
thx again for awesome alacritty,
-m

File: alacritty/src/event.rs [hunk 1]
```diff
@@ -190,7 +190,7 @@ impl<'a, N: Notify + 'a, T: EventListener> input::ActionContext<T> for ActionCon
     /// Request a redraw.
     #[inline]
     fn mark_dirty(&mut self) {
-        self.dirty = true;
+        *self.dirty = true;
     }
```
Comment (nixpulvis) [inline alacritty/src/event.rs:194]: As a matter of good abstraction, I'd expect this to be the only place you need to update the dereference, then all the other spots should just call this function.

**Review by nixpulvis — APPROVED** [review]
Other than my one optional comment, everything looks good to me here, and is working as expected now.

Thanks.

File: alacritty/src/event.rs (hunk 1 above)
Comment (chrisduerr) [reply alacritty/src/event.rs:194]: I've considered this, but a dereference really isn't some complicated magical thing that justifies abstraction.

The main reason for this method is to expose it to `input.rs`, being able to see **all** the code that is executed rather than having to follow a method that contains the code doesn't seem worth it when it's just a single line. So I think it's a little nicer to just inline manually here to make that more transparent.

Comment (nixpulvis) [reply alacritty/src/event.rs:194]: Just hope we never need to add any logic to `fn mark_dirty`. :stuck_out_tongue_winking_eye:

Comment (chrisduerr) [reply alacritty/src/event.rs:194]: Yeah, but we can open that can when it gets to it.
