### PR TITLE
Fix regex memory usage

### LINKED ISSUE #7097: Hint regex with large chars amount. Hanging and continues memory consumption
### Problem

With the `Qm[0-9A-Za-z]{44}` as a hint regex pattern, Alacritty hangs upon activating Hints and memory consumption starts to growth continuously.

```yml
# ... rest of the config
hints:
  enabled:
    - regex: 'Qm[0-9A-Za-z]{44}'
      action: Copy
      binding:
        key: U
        mods: Control|Shift
```

But no issues with `sha256:([0-9a-f]{64})` pattern.

```yml
# ... rest of the config
hints:
  enabled:
    - regex: 'sha256:([0-9a-f]{64})'
      action: Copy
      binding:
        key: U
        mods: Control|Shift
```
No any hangs, hints highlighted almost immediately

### System

Version: 0.12.2
OS: Ubuntu 20.04
Compositor: compton
WM: xmonad

### Logs

Crashes: NONE

Font/Terminal size:
[screenshot](https://github.com/alacritty/alacritty/assets/29537473/e70f66a4-9ef0-4e26-b012-0c8c985db0b0)

Keyboard and bindings:
After activating Hints with the mentioned pattern Alacritty hangs and stops reporting any events with `--report-events` option

### PR DESCRIPTION
**Pull request by chrisduerr**
This fixes an issue where regexes with a large number of possible states
would consume excessive memory, since the entire DFA was compiled ahead
of time.

To solve this, the DFA is now built at runtime using `regex-automata`'s
hybrid DFA.

There are however still some checks performed ahead of time, causing
errors with obscenely large regexes (`[0-9A-Za-z]{999999999}`), which
shouldn't cause any issues.

A regex which is large, but not large enough to fail the NFA
construction (like `[0-9A-Za-z]{999999}`) will cause a long search of
the entire grid, but will complete and show the match.

Closes #7097.

### CODE REVIEW

File: alacritty_terminal/src/term/search.rs [hunk 1]
```diff
@@ -201,8 +222,29 @@ impl<T> Term<T> {
         end: Point,
         direction: Direction,
         anchored: bool,
-        regex: &impl Automaton,
+        regex: &mut LazyDfa,
     ) -> Option<Point> {
+        match self.regex_search_internal(start, end, direction, anchored, regex) {
+            Ok(regex_match) => regex_match,
+            Err(err) => {
+                log::warn!("Regex exceeded complexity limit");
```
Comment (kchibisov) [inline alacritty_terminal/src/term/search.rs:230]: Maybe we should say which regex somehow? Also, import `warn!` and `debug!`.

**Review by kchibisov — CHANGES_REQUESTED** [review]

File: alacritty_terminal/src/term/search.rs (hunk 1 above)
Comment (chrisduerr) [reply alacritty_terminal/src/term/search.rs:230]: I considered that but it's only really viable if we store the pattern in the dfa and I didn't want to do that just for log messages. It should be pretty clear anyway since it's triggered by user actions usually (and should be very rare).

File: alacritty_terminal/src/term/search.rs [hunk 2]
```diff
@@ -245,27 +287,27 @@ impl<T> Term<T> {
                 };
 
                 // Since we get the state from the DFA, it doesn't need to be checked.
```
Comment (nixpulvis) [inline alacritty_terminal/src/term/search.rs:289]: Perhaps update this comment since it doesn't need to mention being checked anymore?

File: alacritty_terminal/src/term/search.rs [hunk 3]
```diff
@@ -881,19 +923,34 @@ mod tests {
...
+    }
+
+    #[test]
+    fn runtime_cache_error() {
+        let term = mock_term(&str::repeat("i", 9999));
+
+        let mut regex = RegexSearch::new("[0-9A-Za-z]{9999}").unwrap();
+        let start = Point::new(Line(0), Column(0));
+        let end = Point::new(Line(0), Column(9999));
+        assert_eq!(term.regex_search_right(&mut regex, start, end), None);
```
Comment (nixpulvis) [inline alacritty_terminal/src/term/search.rs:954]: Would it be worth making these errors a little more descriptive, since they could in theory be hit by a crazy user configuration. Always nice to help tame insanity imo.

**Review by kchibisov — APPROVED** [review]
