### PR TITLE
Fix non-async-signal-safety in `pre_exec`

### LINKED ISSUE #8751: Non async-signal-safe closure in `pre_exec`
https://github.com/alacritty/alacritty/blob/bf68154f9e4b91e5ba21dfb8151dbde23c46d47d/alacritty_terminal/src/tty/unix.rs#L246-L272

This snippet is invalid in multi-threaded programs, which AFAIK `alacritty` is. The problem is due to two factors:

1. `Error::other` always allocates (see https://github.com/rust-lang/rust/pull/148971).
2. `env::set_current_dir` allocates on long paths, since it needs to add a terminating NUL character that may not be present in the `PathBuf`.

Allocating in `pre_exec` is bad because forking while the allocator lock is held by another thread can cause deadlocks, since there's no one left to unlock the mutex. I do not believe this is UB per se, but it seems less than ideal still. glibc and other modern libc offer protections against that, as far as I'm aware, but this isn't POSIX-compliant and should preferably be avoided.

For 1., `panic!`king would be a valid alternative. For 2., you could allocate `CString` in the parent process and invoke `chdir` from `libc`.

### PR DESCRIPTION
**Pull request by purplesyringa**
My proposed fix for #8751, with a couple additions. This resolves all the issues with async signal safety that I could find, specifically:

- `fork`(2) not being async-signal-safe due to invoking `pthread_atfork` handlers; replaced with a syscall.
- `die!` invoking the logger; replaced with an error code.
- `env::set_current_dir` allocating; replaced with `Command::current_dir`.
- `Error::other` allocating; replaced with an error code.

Closes #8751.

### CODE REVIEW

**Comment by purplesyringa** [comment]
Ah, that's fun, apparently macOS doesn't provide `SYS_fork`... Not sure how to deal with that.

File: alacritty/src/daemon.rs [hunk 1]
```diff
@@ -64,21 +63,22 @@ where
...
+    // Copy foreground process' working directory, ignoring invalid paths.
+    if let Ok(working_directory) = foreground_process_path(master_fd, shell_pid) {
+        command.current_dir(working_directory);
+    }
+
     unsafe {
         command
             .pre_exec(move || {
+                // FIXME: `libc::fork` calls `pthread_atfork` handlers, which are not
+                // async-signal-safe.
```
Comment (chrisduerr) [inline alacritty/src/daemon.rs]: This is only an issue if there are pthread_atfork handlers registered that are not async-signal-safe, right? So I'm not sure it is a problem here?

File: alacritty_terminal/src/tty/unix.rs [hunk 2]
```diff
@@ -241,21 +239,20 @@ pub fn from_fd(config: &Options, window_id: u64, master: OwnedFd, slave: OwnedFd
     builder.env_remove("XDG_ACTIVATION_TOKEN");
     builder.env_remove("DESKTOP_STARTUP_ID");
 
-    let working_directory = config.working_directory.clone();
+    // Set working directory, ignoring invalid paths.
+    if let Some(working_directory) = &config.working_directory {
+        builder.current_dir(working_directory);
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/unix.rs]: I'm not sure I want to switch to `builder.current_dir` here. I'd have to test it some more but I'd imagine there's probably a reason it wasn't done this way before.

**Review by chrisduerr — CHANGES_REQUESTED** [review]

File: alacritty_terminal/src/tty/unix.rs (hunk 2 above)
Comment (kchibisov) [reply alacritty_terminal/src/tty/unix.rs]: The only issue that comes to mind is not being able to start at all without said directory, which we try to avoid.

File: alacritty/src/daemon.rs (hunk 1 above)
Comment (purplesyringa) [reply alacritty/src/daemon.rs]: POSIX doesn't currently document `fork` as async-signal-safe, even conditionally. As far as I can tell, POSIX once said "`fork` is async-signal-safe as long as all registered handlers are async-signal-safe", but this guarantee was dropped. If I had to guess, that's because any dynamic libraries you link to can register arbitrary handlers, including `libc` itself, so it's impossible to reason about lack of async-signal-unsafe handlers.

File: alacritty_terminal/src/tty/unix.rs (hunk 2 above)
Comment (purplesyringa) [reply alacritty_terminal/src/tty/unix.rs]: That makes sense, I can replace it with `libc::chdir` as I initially planned to.

Comment (purplesyringa) [reply alacritty_terminal/src/tty/unix.rs]: Fixed and squashed.

File: alacritty/src/daemon.rs (hunk 1 above)
Comment (chrisduerr) [reply alacritty/src/daemon.rs]: This is the reasoning I believe:

> POSIX.1-2001 TC1 clarified that if an application calls fork(2) from a signal handler and any of the fork handlers registered by pthread_atfork(3) calls a function that is not async-signal-safe, the behavior is undefined.  A future revision of the standard is likely to remove fork(2) from the list of async-signal-safe functions.

Comment (chrisduerr) [reply alacritty/src/daemon.rs]: So while not ideal, I think it should be fine? I think a comment outlining this issue is probably sufficient, if there's ever any issues at that point at least people know what the cause might be.

**Review by chrisduerr — CHANGES_REQUESTED** [review]
Seems mostly good to go.

File: alacritty/src/daemon.rs (hunk 1 above)
Comment (purplesyringa) [reply alacritty/src/daemon.rs]: I improved the comment, please take a look.

File: alacritty/src/daemon.rs [hunk 3]
```diff
@@ -64,10 +67,28 @@ where
...
+                // > fork handlers to execute functions that are not async-signal-safe when fork()
+                // > is called from a signal handler.
+                //
+                // POSIX.1-2024 removes this guarantee and introduces an async-signal-safe
+                // replacement `_Fork`, which we'd like to use, but macOS doesn't support it yet.
+                //
+                // Since we aren't registering any fork handlers, and hopefully the OS doesn't
+                // either, we're fine on systems compatible with POSIX.1-2017, which should be
+                // enough for a long while. If this ever becomes a problem in the future, we should
+                // be able to switch to `_Fork`.
```
Comment (chrisduerr) [inline alacritty/src/daemon.rs:91]: Couldn't have put it better myself, thanks.

**Review by chrisduerr — APPROVED** [review]
LGTM, thanks for looking into this yourself.
