### PR TITLE
Fix fullwidth semantic escape characters

### LINKED ISSUE #8188: alacritty not honouring [semantic_escape_chars] setting
I hope I am not over-stepping any github/alacritty rules. My previous ticket has been closed, and I cannot find a way to reopen it (just joined yesterday).

Please feel free to delete this ticket if need be.

`semantic_escape_chars = ",│`|:\"' ()[]{}<>\t•-—－．"`

Here's a video of what happens after [Ctrl] + [Shift] + [Space]

https://github.com/user-attachments/assets/0657d09d-544f-46e6-8964-1e58f977de26

### PR DESCRIPTION
**Pull request by chrisduerr**
Semantic escape characters occupying two two grid cells were always skipped over, making it impossible to have functional fullwidth characters as part of semantic escape characters.

This patch fixes this by only skipping over fullwidth spacer cells, rather than skipping those cells entirely.

Closes #8188.

### CODE REVIEW

File: alacritty_terminal/src/term/search.rs [hunk 1]
```diff
@@ -516,7 +516,16 @@ impl<T> Term<T> {
...
         match self.inline_search_left(point, self.semantic_escape_chars()) {
-            Ok(point) => self.grid.iter_from(point).next().map_or(point, |cell| cell.point),
+            // If we found a match, reverse for at least one cell, skipping over wide cell spacers.
+            Ok(point) => {
+                let wide_spacer = Flags::WIDE_CHAR_SPACER | Flags::LEADING_WIDE_CHAR_SPACER;
+                for cell in self.grid.iter_from(point) {
+                    if !cell.flags.intersects(wide_spacer) {
+                        return cell.point;
+                    }
+                }
```
Comment (kchibisov) [inline alacritty_terminal/src/term/search.rs:526]: That looks like `find`.

**Review by kchibisov — CHANGES_REQUESTED** [review]

**Review by kchibisov — APPROVED** [review]
