### PR TITLE
Powerline glyphs being cut for narrow fonts

### LINKED ISSUE #7470: Powerline font cut off on 0.13
After updating to 0.13, powerline icons have started rendering incorrectly. On 0.12 it used to render as expected, but now it's cutting off the "points" of the powerline triangles. Here's a screenshot of what it looks like:

new

And here's what it used to look like before (downgraded to 0.12 for the screenshot):

old

I use the IosevkaTerm font with NerdFont patches (https://www.nerdfonts.com/font-downloads)

Here's my config, after migrating to toml:

```toml
import = ["/home/pavle/.config/alacritty/gruvbox.toml"]

[font]
size = 8

[font.normal]
family = "IosevkaTerm NFP"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 40000

[window]
dynamic_title = true

[window.class]
general = "Alacritty"
instance = "Alacritty"
```

gruvbox.toml just defines some colors and I get the same behaviour with and without that file included.

### System

OS: Linux
Version: alacritty 0.13.0 (78fa4d6f)
Linux: X11, i3, no compositor

### Logs

Crashes: N/A
Font/Terminal size: `alacritty -vv`

```
[0.000004989s] [INFO ] [alacritty] Welcome to Alacritty
[0.000079378s] [INFO ] [alacritty] Version 0.13.0 (78fa4d6f)
[0.000091781s] [INFO ] [alacritty] Running on X11
[0.000748226s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/pavle/.config/alacritty/alacritty.toml"
                                     "/home/pavle/.config/alacritty/gruvbox.toml"
[0.009097137s] [INFO ] [alacritty] Using GLX 1.4
[0.073722849s] [DEBUG] [alacritty] Picked GL Config:
                                     buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                                     alpha_size: 8
                                     num_samples: 0
                                     hardware_accelerated: true
                                     supports_transparency: Some(true)
                                     config_api: Api(OPENGL | GLES1 | GLES2)
                                     srgb_capable: false
[0.084864511s] [INFO ] [alacritty] Window scale factor: 2.0833333333333335
[0.087529144s] [DEBUG] [alacritty] Loading "MonoFont" font
[0.103752469s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.113076890s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.120644422s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.127604070s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.144804840s] [INFO ] [alacritty] Running on AMD Radeon Graphics (radeonsi, gfx1103_r1, LLVM 16.0.6, DRM 3.54, 6.6.8-arch1-1)
[0.144839404s] [INFO ] [alacritty] OpenGL version 4.6 (Core Profile) Mesa 23.3.1-arch1.1, shader_version 4.60
[0.144850114s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.154266316s] [DEBUG] [alacritty] Enabled debug logging for OpenGL
[0.154368277s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.191422396s] [INFO ] [alacritty] Cell size: 11 x 29
[0.191455027s] [INFO ] [alacritty] Padding: 0 x 0
[0.191463893s] [INFO ] [alacritty] Width: 800, Height: 600
[0.209875893s] [INFO ] [alacritty] PTY dimensions: 20 x 72
[0.214991469s] [INFO ] [alacritty] Initialisation complete
[0.221732670s] [DEBUG] [alacritty_terminal] New num_cols is 205 and num_lines is 48
[0.223415199s] [INFO ] [alacritty] Padding: 0 x 0
[0.223435497s] [INFO ] [alacritty] Width: 2256, Height: 1416
```

Keyboard and bindings: `alacritty --print-events`

```
[0.000004959s] [INFO ] [alacritty] Welcome to Alacritty
[0.000062587s] [INFO ] [alacritty] Version 0.13.0 (78fa4d6f)
[0.000072315s] [INFO ] [alacritty] Running on X11
[0.000711648s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/pavle/.config/alacritty/alacritty.toml"
                                     "/home/pavle/.config/alacritty/gruvbox.toml"
[0.006861084s] [INFO ] [alacritty] winit event: NewEvents(Init)
[0.006887523s] [INFO ] [alacritty] winit event: Resumed
[0.009332947s] [INFO ] [alacritty] Using GLX 1.4
[0.077207692s] [INFO ] [alacritty] Window scale factor: 2.0833333333333335
[0.134859680s] [INFO ] [alacritty] Running on AMD Radeon Graphics (radeonsi, gfx1103_r1, LLVM 16.0.6, DRM 3.54, 6.6.8-arch1-1)
[0.134890698s] [INFO ] [alacritty] OpenGL version 4.6 (Core Profile) Mesa 23.3.1-arch1.1, shader_version 4.60
[0.134896399s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.180725694s] [INFO ] [alacritty] Cell size: 11 x 29
[0.180777861s] [INFO ] [alacritty] Padding: 0 x 0
[0.180786918s] [INFO ] [alacritty] Width: 800, Height: 600
[0.197625542s] [INFO ] [alacritty] PTY dimensions: 20 x 72
[0.204319724s] [INFO ] [alacritty] Initialisation complete
[0.204378714s] [INFO ] [alacritty] winit event: DeviceEvent { device_id: DeviceId(X(DeviceId(12))), event: Key(RawKeyEvent { physical_key: Code(Enter), state: Released }) }
[0.209233604s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(73400323)), event: Ime(Disabled) }
[0.209321719s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(73400323)), event: Ime(Enabled) }
[0.209681099s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(73400323)), event: Resized(PhysicalSize { width: 2256, height: 1416 }) }
[0.209704112s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(73400323)), event: Focused(false) }
[0.209720272s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(73400323)), event: Occluded(false) }
[0.209892424s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(73400323)), event: CursorEntered { device_id: DeviceId(X(DeviceId(2))) } }
[0.209909095s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(73400323)), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: PhysicalPosition { x: 736.0, y: 968.0 } } }
[0.209936686s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(73400323)), event: Moved(PhysicalPosition { x: 0, y: 59 }) }
[0.210007659s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(73400323)), event: Focused(true) }
[0.210017697s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(73400323)), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: PhysicalPosition { x: 736.0, y: 968.0 } } }
[0.210786011s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(73400323)), event: RedrawRequested }
[0.214663447s] [INFO ] [alacritty] Padding: 0 x 0
[0.214751281s] [INFO ] [alacritty] Width: 2256, Height: 1416
[0.236200459s] [INFO ] [alacritty] winit event: AboutToWait
[0.236334679s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2055, tv_nsec: 436718989 }, requested_resume: Some(Instant { tv_sec: 2055, tv_nsec: 453279440 }) })
[0.236416342s] [INFO ] [alacritty] winit event: AboutToWait
[0.242346689s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2055, tv_nsec: 436849352 }, requested_resume: Some(Instant { tv_sec: 2055, tv_nsec: 453279440 }) })
[0.242674921s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(73400323)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(CapsLock), logical_key: Named(Control), text: None, location: Left, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Named(Control), text_with_all_modifiers: None } }, is_synthetic: false } }
[0.242735414s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(73400323)), event: ModifiersChanged(Modifiers { state: ModifiersState(CONTROL), pressed_mods: ModifiersKeys(0x0) }) }
[0.242788333s] [INFO ] [alacritty] winit event: AboutToWait
[0.252934056s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 2055, tv_nsec: 443241030 }, requested_resume: Instant { tv_sec: 2055, tv_nsec: 453279440 } })
[0.252988799s] [INFO ] [alacritty] winit event: AboutToWait
[0.253012282s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2055, tv_nsec: 453427419 }, requested_resume: None })
[0.253027651s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(73400323))), payload: Frame })
[0.253045144s] [INFO ] [alacritty] winit event: AboutToWait
[0.352253513s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2055, tv_nsec: 453479937 }, requested_resume: None })
[0.352313645s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(73400323))), payload: Terminal(Title(pavle@niccolum:~/.config/alacritty)) })
[0.352331759s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(73400323))), payload: Terminal(Wakeup) })
[0.352349171s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(73400323)), event: RedrawRequested }
[0.357282287s] [INFO ] [alacritty] winit event: AboutToWait
[0.357359331s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2055, tv_nsec: 557751645 }, requested_resume: None })
[0.357403584s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(73400323))), payload: Frame })
[0.357422819s] [INFO ] [alacritty] winit event: AboutToWait
[0.398924769s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2055, tv_nsec: 557857603 }, requested_resume: None })
[0.399017652s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(73400323))), payload: Terminal(Wakeup) })
[0.399042379s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(73400323))), payload: Terminal(Wakeup) })
[0.399059410s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(73400323)), event: RedrawRequested }
[0.401263964s] [INFO ] [alacritty] winit event: AboutToWait
[0.401314819s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2055, tv_nsec: 601722562 }, requested_resume: None })
[0.401337091s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(73400323))), payload: Frame })
[0.401351928s] [INFO ] [alacritty] winit event: AboutToWait
[0.434700943s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2055, tv_nsec: 601789106 }, requested_resume: None })
[0.434828592s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(73400323)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(KeyG), logical_key: Character("d"), text: Some("d"), location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("d"), text_with_all_modifiers: Some("\u{4}") } }, is_synthetic: false } }
[0.434882262s] [INFO ] [alacritty] winit event: AboutToWait
[0.435315650s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2055, tv_nsec: 635356228 }, requested_resume: None })
[0.435348672s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(73400323))), payload: Terminal(Wakeup) })
[0.435368990s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(73400323)), event: RedrawRequested }
[0.437200468s] [INFO ] [alacritty] winit event: AboutToWait
[0.437243739s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2055, tv_nsec: 637655870 }, requested_resume: None })
[0.437268815s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(73400323))), payload: Frame })
[0.437280086s] [INFO ] [alacritty] winit event: AboutToWait
[0.464670962s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2055, tv_nsec: 637711744 }, requested_resume: None })
[0.464714654s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(73400323))), payload: Terminal(Exit) })
[0.471298070s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(73400323))), payload: Terminal(Wakeup) })
[0.471327855s] [INFO ] [alacritty] winit event: AboutToWait
[0.471335900s] [INFO ] [alacritty] winit event: LoopExiting
[0.472613905s] [INFO ] [alacritty] Goodbye
```

### PR DESCRIPTION
**Pull request by kchibisov**
Fixes #7470.

--

Probably fine for now...

### CODE REVIEW

File: alacritty/src/renderer/text/builtin_font.rs [hunk 1]
```diff
@@ -519,6 +523,12 @@ fn powerline_drawing(character: char, metrics: &Metrics, offset: &Delta<i8>) ->
     // x = (H - 2) / (2 * slope).
     let x_intersection = (height as i32 + 1) / 2 - 1;
 
+    // Don't try to draw powerline symbols when we'll cut too much, for example when the font is
+    // really narrow.
```
Comment (chrisduerr) [inline alacritty/src/renderer/text/builtin_font.rs:527]:
```suggestion
    // Don't use built-in font if we'd cut the tip too much, for example when the font is really narrow.
```

**Review by chrisduerr — CHANGES_REQUESTED** [review]

File: alacritty/src/renderer/text/builtin_font.rs [hunk 2]
```diff
@@ -519,6 +523,12 @@ fn powerline_drawing(character: char, metrics: &Metrics, offset: &Delta<i8>) ->
     // x = (H - 2) / (2 * slope).
     let x_intersection = (height as i32 + 1) / 2 - 1;
 
+    // Don't use built-in font if we'd cut the tip too much, for example when the font is really
+    // narrow.
```
Comment (chrisduerr) [inline alacritty/src/renderer/text/builtin_font.rs:527]: I'm surprised this comment isn't wrapped at 80 columns. Is this only done for doc comments?

**Review by chrisduerr — APPROVED** [review]

File: alacritty/src/renderer/text/builtin_font.rs (hunk 2 above)
Comment (kchibisov) [reply alacritty/src/renderer/text/builtin_font.rs:527]: If you want to wrap at `80` you need to change

`comment_width = 100` in `rustfmt.toml` to `80`, we have it at `100`.
