### PR TITLE
Fix selection incorrectly expanding when scrolled in history

### LINKED ISSUE #4257: Selection selects by 2 chars after catting file with unicode
If you cat a file like https://github.com/alacritty/vtebench/blob/master/benchmarks/unicode/symbols

scroll to a point where you catted it, and try to select something, selection will always select by 2 chars.

record

### PR DESCRIPTION
**Pull request by kchibisov**
When doing selection expansion we were checking for wide char flags
on a cells from the bottom of the terminal instead of in a current
viewport when scrolled up in history, which was leading to expanding
more than needed if we had wide chars on the same viewport cell,
but in the bottom of the terminal.

Fixes #4257.

### CODE REVIEW

File: alacritty_terminal/src/term/mod.rs [hunk 1]
```diff
@@ -210,23 +210,29 @@ impl<'a, C> RenderableCellsIter<'a, C> {
         }
 
         let num_cols = self.grid.cols();
-        let cell = self.grid[&point];
+
+        // Since we can have non zero display offset, we must take points from a grid in buffer
+        // coordinates.
```
Comment (chrisduerr) [inline alacritty_terminal/src/term/mod.rs:215]:
```suggestion
        // Convert to absolute coordinates to adjust for the display offset.
```

Just a bit shorter and straight to the point.

File: alacritty_terminal/src/term/mod.rs [hunk 2]
```diff
@@ -210,23 +210,29 @@ impl<'a, C> RenderableCellsIter<'a, C> {
...
+        let buffer_point = self.grid.visible_to_buffer(point);
+        let cell = self.grid[buffer_point];
 
         // Check if wide char's spacers are selected.
         if cell.flags.contains(Flags::WIDE_CHAR) {
             let prev = point.sub(num_cols, 1);
```
Comment (chrisduerr) [inline alacritty_terminal/src/term/mod.rs:221]: Why do we keep using the viewport point here, instead of using `sub_absolute`?

File: CHANGELOG.md [hunk 3]
```diff
@@ -44,6 +44,7 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
 - Crash when copying/pasting with neither pointer nor keyboard focus on Wayland
 - Crash due to fd leak on Wayland
 - IME window position with fullwidth characters in the search bar
+- Selection sometimes expanding over 2 chars when scrolled up in history
```
Comment (chrisduerr) [inline CHANGELOG.md:47]:
```suggestion
- Selection expanding over 2 characters when scrolled in history with fullwidth characters in use
```

I don't like being so vague here, since we know exactly what the issue is.

**Review by chrisduerr — CHANGES_REQUESTED** [review]

File: CHANGELOG.md (hunk 3 above)
Comment (kchibisov) [reply CHANGELOG.md:47]: I thought about it, but it was really too long, but if it's fine I'll use it.

File: alacritty_terminal/src/term/mod.rs (hunk 2 above)
Comment (kchibisov) [reply alacritty_terminal/src/term/mod.rs:221]: The checks for selection are in visible coordinates. Also will `add_absolute`/`sub_absolute` clamp to viewport, I'm not sure that they will? Also, the point in `is_selected` is also in viewport, so you need to convert to viewport anyway.

File: CHANGELOG.md (hunk 3 above)
Comment (chrisduerr) [reply CHANGELOG.md:47]: This is still under the 100 col limit we usually have for changelog entries?

File: alacritty_terminal/src/term/mod.rs (hunk 2 above)
Comment (chrisduerr) [reply alacritty_terminal/src/term/mod.rs:221]: Sure, sounds good.

**Review by chrisduerr — CHANGES_REQUESTED** [review]

**Review by chrisduerr — APPROVED** [review]
