### PR TITLE
Pass activation token in alacritty msg create-window

### LINKED ISSUE #8337: Pass xdg-activation token through `alacritty msg create-window`
Currently, alacritty correctly activates itself on opening using the token from the compositor (`XDG_ACTIVATION_TOKEN`). However, spawning a new window through `alacritty msg create-window` doesn't thread through the token, so the new window cannot activate itself.

My use-case is a compositor bind to spawn a terminal which looks like: `alacritty msg create-window || alacritty`. This way, if an alacritty process already exists, it is re-used for (slightly) faster startup and less resource use. However, this currently doesn't work with xdg-activation because the token isn't passed through `msg create-window`.

I imagine it can become more of a problem as compositors start to adopt stricter new window autofocus policies, or it can break the various "show spinning cursor until the app opens" things.

### System

OS: Linux
Version: alacritty 0.14.0
Linux/BSD: Wayland, niri

### PR DESCRIPTION
**Pull request by kchibisov**
Fixes #8337.

### CODE REVIEW

File: alacritty/src/display/window.rs [hunk 1]
```diff
@@ -147,7 +148,12 @@ impl Window {
         }
 
         #[cfg(not(any(target_os = "macos", windows)))]
-        if let Some(token) = event_loop.read_token_from_env() {
+        if let Some(token) = _options
+            .activation_token
+            .take()
+            .map(ActivationToken::from_raw)
+            .or_else(|| event_loop.read_token_from_env())
```
Comment (chrisduerr) [inline alacritty/src/display/window.rs:155]: I think there's just a `.map_or_else` function?

File: alacritty/src/main.rs [hunk 2]
```diff
@@ -89,7 +89,14 @@ fn main() -> Result<(), Box<dyn Error>> {
...
 #[cfg(unix)]
-fn msg(options: MessageOptions) -> Result<(), Box<dyn Error>> {
+#[allow(unused_mut)]
+fn msg(mut options: MessageOptions) -> Result<(), Box<dyn Error>> {
+    #[cfg(not(any(target_os = "macos", windows)))]
+    if let cli::SocketMessage::CreateWindow(window_options) = &mut options.message {
+        window_options.activation_token = std::env::var("XDG_ACTIVATION_TOKEN")
+            .or_else(|_| std::env::var("DESKTOP_STARTUP_ID"))
+            .ok();
+    }
```
Comment (chrisduerr) [inline alacritty/src/main.rs:99]: Can probably add an import for `cli::SocketMessage` and `std::env` here.

**Review by chrisduerr — CHANGES_REQUESTED** [review]

File: alacritty/src/display/window.rs (hunk 1 above)
Comment (kchibisov) [reply alacritty/src/display/window.rs:155]: It works differently, I'd need to manually wrap in `Some` the result of building a token, so it'll be more verbose.

File: alacritty/src/main.rs (hunk 2 above)
Comment (kchibisov) [reply alacritty/src/main.rs:99]: The thing is that it's all deep in `cfg`, so you'd need a lot of `use` under cfg and it's just way more verbose for what it is.

Comment (chrisduerr) [reply alacritty/src/main.rs:99]: We still want the imports at the top because that's the only way to notice when the `cfg` is not necessary anymore. Anything else will just cause inconsistencies when in the future someone comes along and needs these imports for other locations in this file.

**Review by chrisduerr — APPROVED** [review]

**Comment by YaLTeR** [comment]
Just tested this, works fine, thanks!
