### PR TITLE
Set IUTF8 input setting on supported platforms

### LINKED ISSUE #3769: Utf-8 error when deleting Russian letters when they are submitted for input
I give an input that contains russian characters to my python program. All works fine until I delete a russian character with `Backspace`. Python then raises an UTF-8 error. Default Mint terminal does this with no errors.

**How to reproduce:** create a python script containing this one line:
`input()`
run it and then type a russian letter (for example `Б`), then delete it via `Backspace` and hit `Enter`

It outputs something like

`Traceback (most recent call last):
  File "test.py", line 1, in <module>
    input()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: unexpected end of data`

### System

OS: Linux Mint 19.3
Version: 0.4.2
X11

### PR DESCRIPTION
**Pull request by kchibisov**
Fixes #3769.

### CODE REVIEW

File: alacritty_terminal/src/tty/unix.rs [hunk 1]
```diff
@@ -148,6 +150,17 @@ pub fn new<C>(config: &Config<C>, size: &SizeInfo, window_id: Option<usize>) ->
 
     let (master, slave) = make_pty(win_size);
 
+    #[cfg(any(target_os = "android", target_os = "linux", target_os = "macos"))]
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/unix.rs:153]: Why is this gated behind linux/macos/android cfg?

File: alacritty_terminal/src/tty/unix.rs [hunk 2]
```diff
@@ -148,6 +150,17 @@ pub fn new<C>(config: &Config<C>, size: &SizeInfo, window_id: Option<usize>) ->
...
+    {
+        if let Ok(mut now) = termios::tcgetattr(master) {
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/unix.rs:155]: Why is this named `now`?

File: alacritty_terminal/src/tty/unix.rs [hunk 3]
```diff
@@ -148,6 +150,17 @@ pub fn new<C>(config: &Config<C>, size: &SizeInfo, window_id: Option<usize>) ->
...
+            // Assume UTF-8 encoded characters.
+            now.input_flags.set(InputFlags::IUTF8, true);
+            if let Err(error) = termios::tcsetattr(master, SetArg::TCSANOW, &now) {
+                error!("Failind to set IUTF8 input flag {}", error);
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/unix.rs:159]: Why is this an error logged to the user? What can they do about this?

File: CHANGELOG.md [hunk 4]
```diff
@@ -30,6 +30,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 - Don't hide cursor on modifier press with `mouse.hide_when_typing` enabled
 - `Shift + Backspace` now sends `^?` instead of `^H`
 - Default color scheme is now `Tomorrow Night` with the bright colors of `Tomorrow Night Bright`
+- IUTF8 input setting is now set by default on supported platforms
```
Comment (chrisduerr) [inline CHANGELOG.md:33]: This should get rid of the `now` and making it a little easier to understand what this does for "normal" humans:

```suggestion
- Set IUTF8 termios flag for improved UTF8 input support
```

File: alacritty_terminal/src/tty/unix.rs [hunk 5]
```diff
@@ -22,6 +22,8 @@ use crate::tty::{ChildEvent, EventedPty, EventedReadWrite};
 use libc::{self, c_int, pid_t, winsize, TIOCSCTTY};
 use log::error;
 use nix::pty::openpty;
+#[cfg(any(target_os = "android", target_os = "linux", target_os = "macos"))]
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/unix.rs:25]:
```suggestion
#[cfg(any(target_os = "linux", target_os = "macos"))]
```

File: alacritty_terminal/src/tty/unix.rs [hunk 6]
```diff
@@ -148,6 +150,15 @@ pub fn new<C>(config: &Config<C>, size: &SizeInfo, window_id: Option<usize>) ->
 
     let (master, slave) = make_pty(win_size);
 
+    #[cfg(any(target_os = "linux", target_os = "macos"))]
+    {
+        if let Ok(mut termios) = termios::tcgetattr(master) {
+            // Assume UTF-8 encoded characters.
```
Comment (chrisduerr) [inline alacritty_terminal/src/tty/unix.rs:156]: I think `assume` is a bit misleading here, since UTF-8 is basically all Alacritty does.

We know we want UTF-8, we just need to tell that to the kernel.

```suggestion
            // Set character encoding to UTF-8.
```
