### PR TITLE
fixed the incorrect underline thickness on wide cell

### LINKED ISSUE #4922: Cursor thickness is increased incorrectly on wide cells
When a cursor like the underline is below a wide cell, its thickness is increased (I'd assume doubled).

### PR DESCRIPTION
**Pull request by stokhos**
fixes #4922

### CODE REVIEW

File: alacritty/src/display/cursor.rs [hunk 1]
```diff
@@ -24,6 +24,7 @@ impl IntoRects for RenderableCursor {
 
         if self.is_wide() {
             width *= 2.;
+            thickness /= 2.;
```
Comment (chrisduerr) [inline alacritty/src/display/cursor.rs:27]: Why is the thickness doubled here in the first place? Looks like you're fixing a symptom here.

**Review by chrisduerr — CHANGES_REQUESTED** [review]

File: alacritty/src/display/cursor.rs [hunk 2]
```diff
@@ -26,7 +26,10 @@ impl IntoRects for RenderableCursor {
             width *= 2.;
         }
 
-        let thickness = (thickness * width as f32).round().max(1.);
+        let mut thickness = (thickness * width as f32).round().max(1.);
+        if self.is_wide() {
+            thickness /= 2.;
+        }
```
Comment (chrisduerr) [inline alacritty/src/display/cursor.rs:32]: I feel like there's a little bit of a lack of understanding here when it comes to this issue.

Try moving the line 29 above the `is_wide` check. I'm pretty sure just reordering these statements should resolve this issue.

Alternatively the `cell_width` could be used instead of the `width` variable, to make things a bit more explicit. But I personally think just reusing the existing `width` should be fine.

**Review by chrisduerr — CHANGES_REQUESTED** [review]

File: alacritty/src/display/cursor.rs (hunk 1 above)
Comment (stokhos) [reply alacritty/src/display/cursor.rs]: I see what you mean.

File: alacritty/src/display/cursor.rs (hunk 2 above)
Comment (stokhos) [reply alacritty/src/display/cursor.rs:32]: > Try moving the line 29 above the is_wide check. I'm pretty sure just reordering these statements should resolve this issue.

Yes. This is the best way. :+1:

**Review by chrisduerr — CHANGES_REQUESTED** [review]
Since I believe this is an issue with the latest release, could you please add a changelog entry too?

**Comment by stokhos** [comment]
> Since I believe this is an issue with the latest release, could you please add a changelog entry too?

Sure, how can I add this changelog, or where should I put it. Cause this is my first commit in such a large project, I'm totally lost.

**Comment by chrisduerr** [comment]
Correct, see https://github.com/alacritty/alacritty/blob/master/CONTRIBUTING.md#documentation.

**Review by chrisduerr — APPROVED** [review]
