### PR TITLE
Disable shadows for transparent windows on macOS

### LINKED ISSUE #4604: performance regression - shadow invalidation - macOS
Latest master (https://github.com/alacritty/alacritty/commit/5725f5812ca5e8d7d992da4ac66aa454a8a9a9ad) makes alacritty extremely unusable with opacity set to anything lower than 1.0

### System

OS: macOS
Version: master (https://github.com/alacritty/alacritty/commit/5725f5812ca5e8d7d992da4ac66aa454a8a9a9ad)

### Logs

vtebenches:

[master-opacity-1.0.txt](https://github.com/alacritty/alacritty/files/5726918/master-opacity-1.0.txt)
[master-opacity-0.8.txt](https://github.com/alacritty/alacritty/files/5726919/master-opacity-0.8.txt)

Note: Running vtebench will also make the rest of the system less responsive with opacity < 1.0

I ran the benchmarks on power and noticed that only the "Intel UHD graphics 630" iGPU was used and not my dGPU AMD Radeon Pro 5500M.

### PR DESCRIPTION
**Pull request by chrisduerr**
Commit 5725f58 introduced a performance regression on macOS due to
excessive calls to the `invalidateShadow` function, however calling this
function only on redraw after a resize was performed does not fix the
underlying problem.

As a solution, window shadows are now disabled completely for all
transparent windows. This makes sure there is no performance impact,
while still solving the problem with text artifacts on resize.

Fixes #4604.

### CODE REVIEW

File: alacritty/src/display.rs [hunk 1]
```diff
@@ -254,6 +254,10 @@ impl Display {
         #[cfg(target_os = "macos")]
         crossfont::set_font_smoothing(config.ui_config.font.use_thin_strokes);
 
+        // Disable shadows for transparent windows on macOS.
+        #[cfg(target_os = "macos")]
+        window.set_has_shadows(config.ui_config.background_opacity() >= 1.0);
```
Comment (DivineGod) [inline alacritty/src/display.rs]:
```suggestion
        window.set_has_shadow(config.ui_config.background_opacity() >= 1.0);
```

To fix build error

**Review by DivineGod — COMMENTED** [review]
Performance looks good to me with or without opacity.

[pr-4605-opacity-1.0.txt](https://github.com/alacritty/alacritty/files/5727445/pr-4605-opacity-1.0.txt)
[pr-4605-opacity-0.8.txt](https://github.com/alacritty/alacritty/files/5727446/pr-4605-opacity-0.8.txt)

Interestingly there's less GPU load with opacity 0.8: 
Screen Shot 2020-12-22 at 13 39 30

**Comment by chrisduerr** [comment]
> Interestingly there's less GPU load with opacity 0.8:

That isn't too much of a surprise, since we *disable* something when the opacity is below 1.
