### PR TITLE
fix assertion on 32-bit arch

### LINKED ISSUE #4687: Assertion failure on armv7
Quick and easy reproduction is to run vttest and start with 1 (test of cursor movements). The failure is [here](https://github.com/alacritty/alacritty/blob/master/alacritty_terminal/src/grid/storage.rs#L159). I suspect this to be an issue on armv7 (32-bit) simply because I can't reproduce it on a similar x86_64 system. 

### System

OS: Linux
Version: alacritty 0.8.0-dev (7045a1e)
WM: sway (wayland)

### Logs

Full log: 
```
Created log file at "/tmp/Alacritty-19825.log"
[2021-01-11 02:38:11.759927111] [INFO ] [alacritty] Welcome to Alacritty
[2021-01-11 02:38:11.760397829] [INFO ] [alacritty] Configuration files loaded from:
                                                      "/home/rcf/.config/alacritty/alacritty.yml"
[2021-01-11 02:38:11.797513130] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: MONOCHROME | TARGET_MONO, render_mode: "Mono", lcd_filter: 1 }
[2021-01-11 02:38:11.806169508] [DEBUG] [alacritty] Estimated DPR: 1
[2021-01-11 02:38:11.806457947] [DEBUG] [alacritty] Estimated window size: Some(PhysicalSize { width: 484, height: 268 })
[2021-01-11 02:38:11.806606978] [DEBUG] [alacritty] Estimated cell size: 6 x 11
[2021-01-11 02:38:11.967492932] [INFO ] [alacritty] Device pixel ratio: 1
[2021-01-11 02:38:12.007785729] [INFO ] [alacritty] Initializing glyph cache...
[2021-01-11 02:38:12.025379342] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: MONOCHROME | TARGET_MONO, render_mode: "Mono", lcd_filter: 1 }
[2021-01-11 02:38:12.050500952] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: MONOCHROME | TARGET_MONO, render_mode: "Mono", lcd_filter: 1 }
[2021-01-11 02:38:12.075976621] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: MONOCHROME | TARGET_MONO, render_mode: "Mono", lcd_filter: 1 }
[2021-01-11 02:38:12.101673068] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: MONOCHROME | TARGET_MONO, render_mode: "Mono", lcd_filter: 1 }
[2021-01-11 02:38:12.514669917] [INFO ] [alacritty] ... finished initializing glyph cache in 0.506685869s
[2021-01-11 02:38:12.515081139] [INFO ] [alacritty] Estimated DPR correctly, skipping resize
[2021-01-11 02:38:12.515373953] [INFO ] [alacritty] Cell size: 6 x 11
[2021-01-11 02:38:12.515585981] [INFO ] [alacritty] Padding: 2 x 2
[2021-01-11 02:38:12.515784884] [INFO ] [alacritty] Width: 484, Height: 268
[2021-01-11 02:38:12.516237812] [INFO ] [alacritty] PTY dimensions: Line(24) x Column(80)
[2021-01-11 02:38:12.523040190] [INFO ] [alacritty] Initialisation complete
[2021-01-11 02:38:12.523599569] [INFO ] [alacritty] glutin event: NewEvents(Init)
[2021-01-11 02:38:12.524030332] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:12.524426680] [INFO ] [alacritty] glutin event: RedrawRequested(WindowId(Wayland(WindowId(20929096))))
[2021-01-11 02:38:12.524830612] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:12.542510845] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4207, tv_nsec: 693416864 }, requested_resume: None })
[2021-01-11 02:38:12.542915651] [INFO ] [alacritty] glutin event: UserEvent(TerminalEvent(Wakeup))
[2021-01-11 02:38:12.543208756] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:12.543489321] [INFO ] [alacritty] glutin event: RedrawRequested(WindowId(Wayland(WindowId(20929096))))
[2021-01-11 02:38:12.543739846] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:12.548550274] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4207, tv_nsec: 699454252 }, requested_resume: None })
[2021-01-11 02:38:12.549977011] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(20929096))), event: Resized(PhysicalSize { width: 679, height: 709 }) }
[2021-01-11 02:38:12.550368985] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(20929096))), event: Focused(true) }
[2021-01-11 02:38:12.550533182] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(20929096))), event: ModifiersChanged((empty)) }
[2021-01-11 02:38:12.550669673] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:12.550831246] [INFO ] [alacritty] glutin event: RedrawRequested(WindowId(Wayland(WindowId(20929096))))
[2021-01-11 02:38:12.550967153] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:12.551325879] [DEBUG] [alacritty_terminal] New num_cols is 112 and num_lines is 64
[2021-01-11 02:38:12.592840975] [INFO ] [alacritty] Padding: 2 x 2
[2021-01-11 02:38:12.593334150] [INFO ] [alacritty] Width: 679, Height: 709
[2021-01-11 02:38:12.612073062] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4207, tv_nsec: 762997164 }, requested_resume: None })
[2021-01-11 02:38:12.612401165] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:12.612573820] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:12.623778320] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4207, tv_nsec: 774705922 }, requested_resume: None })
[2021-01-11 02:38:12.624088925] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:12.624250205] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:12.637127302] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4207, tv_nsec: 788053737 }, requested_resume: None })
[2021-01-11 02:38:12.637526566] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:12.637943622] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:12.725268609] [DEBUG] [alacritty_terminal] [Unhandled CSI] action='l', params=[4], intermediates=[63]
[2021-01-11 02:38:12.725538674] [DEBUG] [alacritty_terminal] [Unhandled CSI] action='l', params=[5], intermediates=[63]
[2021-01-11 02:38:12.725674582] [DEBUG] [alacritty_terminal] [Unhandled CSI] action='l', params=[8], intermediates=[63]
[2021-01-11 02:38:12.725781033] [DEBUG] [alacritty_terminal] [Unhandled CSI] action='h', params=[40], intermediates=[63]
[2021-01-11 02:38:12.725888067] [DEBUG] [alacritty_terminal] [Unhandled CSI] action='l', params=[45], intermediates=[63]
[2021-01-11 02:38:12.759296247] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4207, tv_nsec: 910193809 }, requested_resume: None })
[2021-01-11 02:38:12.759722635] [INFO ] [alacritty] glutin event: UserEvent(TerminalEvent(Wakeup))
[2021-01-11 02:38:12.760105568] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:12.760355218] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:12.774612388] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4207, tv_nsec: 925509950 }, requested_resume: None })
[2021-01-11 02:38:12.775104689] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:12.775452624] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:12.777289709] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4207, tv_nsec: 928220810 }, requested_resume: None })
[2021-01-11 02:38:12.777505236] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:12.777614604] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:12.789407065] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4207, tv_nsec: 940329125 }, requested_resume: None })
[2021-01-11 02:38:12.789721460] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:12.790093894] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:13.561942513] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4208, tv_nsec: 712871864 }, requested_resume: None })
[2021-01-11 02:38:13.562162415] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(20929096))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 2, state: Pressed, virtual_keycode: Some(Key1), modifiers: (empty) }, is_synthetic: false } }
[2021-01-11 02:38:13.562313196] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(20929096))), event: ReceivedCharacter('1') }
[2021-01-11 02:38:13.562417023] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:13.562495476] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:13.572310862] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4208, tv_nsec: 723241088 }, requested_resume: None })
[2021-01-11 02:38:13.572513848] [INFO ] [alacritty] glutin event: UserEvent(TerminalEvent(MouseCursorDirty))
[2021-01-11 02:38:13.572640423] [INFO ] [alacritty] glutin event: UserEvent(TerminalEvent(Wakeup))
[2021-01-11 02:38:13.572819786] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:13.572957443] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:13.581396838] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4208, tv_nsec: 732324440 }, requested_resume: None })
[2021-01-11 02:38:13.581632197] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:13.581750898] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:13.591493372] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4208, tv_nsec: 742421557 }, requested_resume: None })
[2021-01-11 02:38:13.591762271] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:13.591882721] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:13.600895202] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4208, tv_nsec: 751810263 }, requested_resume: None })
[2021-01-11 02:38:13.601300884] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:13.601504162] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:13.668854538] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4208, tv_nsec: 819783889 }, requested_resume: None })
[2021-01-11 02:38:13.669089897] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(20929096))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 2, state: Released, virtual_keycode: Some(Key1), modifiers: (empty) }, is_synthetic: false } }
[2021-01-11 02:38:13.669244179] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:13.669330798] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:13.998460480] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4209, tv_nsec: 149389540 }, requested_resume: None })
[2021-01-11 02:38:13.998680382] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(20929096))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 28, state: Pressed, virtual_keycode: Some(Return), modifiers: (empty) }, is_synthetic: false } }
[2021-01-11 02:38:13.998826206] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(20929096))), event: ReceivedCharacter('\r') }
[2021-01-11 02:38:13.998929449] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:13.999009944] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:14.008916616] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4209, tv_nsec: 159847135 }, requested_resume: None })
[2021-01-11 02:38:14.009136810] [INFO ] [alacritty] glutin event: UserEvent(TerminalEvent(MouseCursorDirty))
[2021-01-11 02:38:14.009291383] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:14.009446248] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:14.015677291] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4209, tv_nsec: 166603726 }, requested_resume: None })
[2021-01-11 02:38:14.015892235] [INFO ] [alacritty] glutin event: UserEvent(TerminalEvent(Wakeup))
[2021-01-11 02:38:14.016032809] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:14.016125261] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:14.018610096] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4209, tv_nsec: 169548196 }, requested_resume: None })
[2021-01-11 02:38:14.018774585] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:14.018876078] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:14.030849072] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4209, tv_nsec: 181774048 }, requested_resume: None })
[2021-01-11 02:38:14.031124678] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:14.031352746] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:14.032582914] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4209, tv_nsec: 183485434 }, requested_resume: None })
[2021-01-11 02:38:14.033125087] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:14.033304741] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:14.044337173] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4209, tv_nsec: 195251650 }, requested_resume: None })
[2021-01-11 02:38:14.044796517] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:14.045114996] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:14.120783454] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4209, tv_nsec: 271713680 }, requested_resume: None })
[2021-01-11 02:38:14.121123514] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(20929096))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 28, state: Released, virtual_keycode: Some(Return), modifiers: (empty) }, is_synthetic: false } }
[2021-01-11 02:38:14.121335250] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:14.121468241] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:14.957654686] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4210, tv_nsec: 108584037 }, requested_resume: None })
[2021-01-11 02:38:14.957937292] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(20929096))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 28, state: Pressed, virtual_keycode: Some(Return), modifiers: (empty) }, is_synthetic: false } }
[2021-01-11 02:38:14.958107322] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(20929096))), event: ReceivedCharacter('\r') }
[2021-01-11 02:38:14.958231272] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:14.958334515] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:14.977444700] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4210, tv_nsec: 128369677 }, requested_resume: None })
[2021-01-11 02:38:14.977766095] [INFO ] [alacritty] glutin event: UserEvent(TerminalEvent(MouseCursorDirty))
[2021-01-11 02:38:14.977953333] [INFO ] [alacritty] glutin event: UserEvent(TerminalEvent(Wakeup))
[2021-01-11 02:38:14.978167110] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:14.978332183] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:14.988109948] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4210, tv_nsec: 139033466 }, requested_resume: None })
[2021-01-11 02:38:14.988427552] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:14.988587666] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:15.003308269] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4210, tv_nsec: 154234704 }, requested_resume: None })
[2021-01-11 02:38:15.003541586] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:15.003657370] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:15.009951410] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4210, tv_nsec: 160886886 }, requested_resume: None })
[2021-01-11 02:38:15.010152939] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:15.010258806] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:15.017302380] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4210, tv_nsec: 168236106 }, requested_resume: None })
[2021-01-11 02:38:15.017489617] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:15.017589361] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:15.089155811] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4210, tv_nsec: 240084288 }, requested_resume: None })
[2021-01-11 02:38:15.089376880] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(20929096))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 28, state: Released, virtual_keycode: Some(Return), modifiers: (empty) }, is_synthetic: false } }
[2021-01-11 02:38:15.089528536] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:15.089614281] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:15.381437421] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4210, tv_nsec: 532367648 }, requested_resume: None })
[2021-01-11 02:38:15.381651782] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(20929096))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 28, state: Pressed, virtual_keycode: Some(Return), modifiers: (empty) }, is_synthetic: false } }
[2021-01-11 02:38:15.381797022] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(20929096))), event: ReceivedCharacter('\r') }
[2021-01-11 02:38:15.381897057] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:15.381974344] [INFO ] [alacritty] glutin event: RedrawEventsCleared
thread 'PTY reader' panicked at 'assertion failed: `(left == right)`
  left: `16`,
 right: `32`', /home/rcf/src/alacritty/alacritty_terminal/src/grid/storage.rs:159:9
stack backtrace:
[2021-01-11 02:38:15.394637669] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4210, tv_nsec: 545563812 }, requested_resume: None })
[2021-01-11 02:38:15.394882944] [INFO ] [alacritty] glutin event: UserEvent(TerminalEvent(MouseCursorDirty))
[2021-01-11 02:38:15.395084472] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:15.395348413] [INFO ] [alacritty] glutin event: RedrawEventsCleared
   0:   0xee5cd8 - std::backtrace_rs::backtrace::libunwind::trace::h066f7019c7eec5ed
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:   0xee5cd8 - std::backtrace_rs::backtrace::trace_unsynchronized::h1909c089dc64884b
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:   0xee5cd8 - std::sys_common::backtrace::_print_fmt::h45586ea428ce1f71
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/sys_common/backtrace.rs:67:5
   3:   0xee5cd8 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfa39acb5529934c5
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/sys_common/backtrace.rs:46:22
   4:   0xf0a810 - core::fmt::write::hdc4d3920d9f86f26
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/core/src/fmt/mod.rs:1078:17
   5:   0xee0d7c - std::io::Write::write_fmt::hcd50e09ef1ed031f
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/io/mod.rs:1518:15
   6:   0xee8364 - std::sys_common::backtrace::_print::hb8b13a96dc03949d
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/sys_common/backtrace.rs:49:5
   7:   0xee8364 - std::sys_common::backtrace::print::h8ddbe66db05efa4d
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/sys_common/backtrace.rs:36:9
   8:   0xee8364 - std::panicking::default_hook::{{closure}}::hd95ea092310b5406
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:208:50
   9:   0xee7dcc - std::panicking::default_hook::hb87350bee09d8465
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:225:9
  10:   0xee8b78 - std::panicking::rust_panic_with_hook::hd15b4e393de6e1bc
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:591:17
  11:   0xee86d8 - std::panicking::begin_panic_handler::{{closure}}::h68ba58b03c684121
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:497:13
  12:   0xee6264 - std::sys_common::backtrace::__rust_end_short_backtrace::h1752e6ba7401a4de
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/sys_common/backtrace.rs:141:18
  13:   0xee8620 - rust_begin_unwind
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:493:5
  14:   0xf083cc - core::panicking::panic_fmt::h267ac53fae4d334f
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/core/src/panicking.rs:92:14
  15:   0x551a04 - alacritty_terminal::grid::storage::Storage<T>::swap::h4d2539f274ea33b3
                       at /home/rcf/src/alacritty/alacritty_terminal/src/grid/storage.rs:159:9
  16:   0x47b990 - alacritty_terminal::grid::Grid<T>::scroll_up::hedf2acfc8ebad164
                       at /home/rcf/src/alacritty/alacritty_terminal/src/grid/mod.rs:320:13
  17:   0x651334 - alacritty_terminal::term::Term<T>::scroll_up_relative::h4fcdf0d2b42ee80e
                       at /home/rcf/src/alacritty/alacritty_terminal/src/term/mod.rs:780:9
  18:   0x65e734 - <alacritty_terminal::term::Term<T> as alacritty_terminal::ansi::Handler>::scroll_up::h3e7c388801ab23ec
                       at /home/rcf/src/alacritty/alacritty_terminal/src/term/mod.rs:1350:9
  19:   0x65da60 - <alacritty_terminal::term::Term<T> as alacritty_terminal::ansi::Handler>::linefeed::he824b900ad449640
                       at /home/rcf/src/alacritty/alacritty_terminal/src/term/mod.rs:1291:13
  20:   0x66f974 - <alacritty_terminal::ansi::Performer<H,W> as vte::Perform>::execute::ha407e08e9deff851
                       at /home/rcf/src/alacritty/alacritty_terminal/src/ansi.rs:771:41
  21:   0x5df964 - vte::Parser::perform_action::h108d5d46f6d43fdd
                       at /home/rcf/.cargo/registry/src/github.com-1285ae84e5963aae/vte-0.10.0/src/lib.rs:222:32
  22:   0x5e02ac - vte::Parser::perform_state_change::h2827b8f5355a3100
                       at /home/rcf/.cargo/registry/src/github.com-1285ae84e5963aae/vte-0.10.0/src/lib.rs:162:17
  23:   0x5e05d0 - vte::Parser::advance::he495c8b5fb22b362
                       at /home/rcf/.cargo/registry/src/github.com-1285ae84e5963aae/vte-0.10.0/src/lib.rs:130:9
  24:   0x66aa10 - alacritty_terminal::ansi::Processor::advance::h55602d9a1750bced
                       at /home/rcf/src/alacritty/alacritty_terminal/src/ansi.rs:135:9
  25:   0x597640 - alacritty_terminal::event_loop::EventLoop<T,U>::pty_read::h148cb2b3e693ce1a
                       at /home/rcf/src/alacritty/alacritty_terminal/src/event_loop.rs:247:25
  26:   0x596bd0 - alacritty_terminal::event_loop::EventLoop<T,U>::spawn::{{closure}}::ha9567ca7117b42c4
                       at /home/rcf/src/alacritty/alacritty_terminal/src/event_loop.rs:369:51
  27:   0x503378 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb441253020f3a88c
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/sys_common/backtrace.rs:125:18
  28:   0x599cd8 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h5c986404c0c08fe8
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/thread/mod.rs:474:17
  29:   0x65f8c0 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb3efe39406884d3c
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panic.rs:322:9
  30:   0x5b7c88 - std::panicking::try::do_call::h1d412fae2e6dd70b
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:379:40
  31:   0x5b8510 - __rust_try
  32:   0x5b7b38 - std::panicking::try::h29afd380248d37b4
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:343:19
  33:   0x660148 - std::panic::catch_unwind::h56ffd4a63ae70294
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panic.rs:396:14
  34:   0x599b68 - std::thread::Builder::spawn_unchecked::{{closure}}::h35d84677fcc980d8
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/thread/mod.rs:473:30
  35:   0x5339c8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h571e907e04ee45b5
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/core/src/ops/function.rs:227:5
  36:   0xeef4c8 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb876980aeed09687
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/alloc/src/boxed.rs:1480:9
  37:   0xeef4c8 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1cf66534db3e79e5
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/alloc/src/boxed.rs:1480:9
  38:   0xeef4c8 - std::sys::unix::thread::Thread::new::thread_start::h0670099cd3a4b567
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/sys/unix/thread.rs:71:17
[2021-01-11 02:38:15.556449994] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4210, tv_nsec: 707379346 }, requested_resume: None })
[2021-01-11 02:38:15.556665230] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(20929096))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 28, state: Released, virtual_keycode: Some(Return), modifiers: (empty) }, is_synthetic: false } }
[2021-01-11 02:38:15.556795013] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:15.556876383] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:15.557394056] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4210, tv_nsec: 708328658 }, requested_resume: None })
[2021-01-11 02:38:15.557634374] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:15.557768240] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-01-11 02:38:16.349981750] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 4211, tv_nsec: 500909352 }, requested_resume: None })
[2021-01-11 02:38:16.350286230] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(20929096))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 28, state: Pressed, virtual_keycode: Some(Return), modifiers: (empty) }, is_synthetic: false } }
[2021-01-11 02:38:16.350474634] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(20929096))), event: ReceivedCharacter('\r') }
[2021-01-11 02:38:16.350621333] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-01-11 02:38:16.350733909] [INFO ] [alacritty] glutin event: RedrawEventsCleared
thread 'main' panicked at 'send event loop msg: Disconnected', /home/rcf/src/alacritty/alacritty_terminal/src/event_loop.rs:84:40
stack backtrace:
   0:   0xee5cd8 - std::backtrace_rs::backtrace::libunwind::trace::h066f7019c7eec5ed
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:   0xee5cd8 - std::backtrace_rs::backtrace::trace_unsynchronized::h1909c089dc64884b
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:   0xee5cd8 - std::sys_common::backtrace::_print_fmt::h45586ea428ce1f71
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/sys_common/backtrace.rs:67:5
   3:   0xee5cd8 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfa39acb5529934c5
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/sys_common/backtrace.rs:46:22
   4:   0xf0a810 - core::fmt::write::hdc4d3920d9f86f26
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/core/src/fmt/mod.rs:1078:17
   5:   0xee0d7c - std::io::Write::write_fmt::hcd50e09ef1ed031f
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/io/mod.rs:1518:15
   6:   0xee8364 - std::sys_common::backtrace::_print::hb8b13a96dc03949d
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/sys_common/backtrace.rs:49:5
   7:   0xee8364 - std::sys_common::backtrace::print::h8ddbe66db05efa4d
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/sys_common/backtrace.rs:36:9
   8:   0xee8364 - std::panicking::default_hook::{{closure}}::hd95ea092310b5406
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:208:50
   9:   0xee7dcc - std::panicking::default_hook::hb87350bee09d8465
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:225:9
  10:   0xee8b78 - std::panicking::rust_panic_with_hook::hd15b4e393de6e1bc
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:591:17
  11:   0xee86d8 - std::panicking::begin_panic_handler::{{closure}}::h68ba58b03c684121
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:497:13
  12:   0xee6264 - std::sys_common::backtrace::__rust_end_short_backtrace::h1752e6ba7401a4de
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/sys_common/backtrace.rs:141:18
  13:   0xee8620 - rust_begin_unwind
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:493:5
  14:   0xf083cc - core::panicking::panic_fmt::h267ac53fae4d334f
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/core/src/panicking.rs:92:14
  15:   0xf08224 - core::option::expect_none_failed::hf7bbf8ea4f2648cd
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/core/src/option.rs:1266:5
  16:   0x905dac - core::result::Result<T,E>::expect::h762c0bbc115dd624
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/core/src/result.rs:929:23
  17:   0x597e70 - <alacritty_terminal::event_loop::Notifier as alacritty_terminal::event::Notify>::notify::h7d6213d143a7c22b
                       at /home/rcf/src/alacritty/alacritty_terminal/src/event_loop.rs:84:9
  18:   0x4f368c - <alacritty::event::ActionContext<N,T> as alacritty::input::ActionContext<T>>::write_to_pty::hbfc6fc7fb8f61b83
                       at /home/rcf/src/alacritty/alacritty/src/event.rs:177:9
  19:   0x52f430 - alacritty::input::Processor<T,A>::received_char::h113d57023357e085
                       at /home/rcf/src/alacritty/alacritty/src/input.rs:896:9
  20:   0x4f8604 - alacritty::event::Processor<N>::handle_event::haec047556af3a5a2
                       at /home/rcf/src/alacritty/alacritty/src/event.rs:1167:58
  21:   0x4f7930 - alacritty::event::Processor<N>::run::{{closure}}::h98c8211d8a36a133
                       at /home/rcf/src/alacritty/alacritty/src/event.rs:1034:17
  22:   0x54cb40 - winit::platform_impl::platform::sticky_exit_callback::h1207a9b3383da445
                       at /home/rcf/.cargo/registry/src/github.com-1285ae84e5963aae/winit-0.24.0/src/platform_impl/linux/mod.rs:736:5
  23:   0x581114 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return::h35c464df4a7d90ec
                       at /home/rcf/.cargo/registry/src/github.com-1285ae84e5963aae/winit-0.24.0/src/platform_impl/linux/wayland/event_loop/mod.rs:388:13
  24:   0x54c130 - winit::platform_impl::platform::EventLoop<T>::run_return::he757b07c2594c768
                       at /home/rcf/.cargo/registry/src/github.com-1285ae84e5963aae/winit-0.24.0/src/platform_impl/linux/mod.rs:645:56
  25:   0x4e0c28 - <winit::event_loop::EventLoop<T> as winit::platform::run_return::EventLoopExtRunReturn>::run_return::hef9e115a07bfeac2
                       at /home/rcf/.cargo/registry/src/github.com-1285ae84e5963aae/winit-0.24.0/src/platform/run_return.rs:56:9
  26:   0x4f70f0 - alacritty::event::Processor<N>::run::h441247090cadc439
                       at /home/rcf/src/alacritty/alacritty/src/event.rs:959:9
  27:   0x50ad64 - alacritty::run::hec53fb8329ecbef3
                       at /home/rcf/src/alacritty/alacritty/src/main.rs:211:5
  28:   0x509ef8 - alacritty::main::h5af05b0851c844b2
                       at /home/rcf/src/alacritty/alacritty/src/main.rs:109:23
  29:   0x535b90 - core::ops::function::FnOnce::call_once::hf60510ab670ad455
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/core/src/ops/function.rs:227:5
  30:   0x503320 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4bc7d83b52dcbe7e
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/sys_common/backtrace.rs:125:18
  31:   0x616ca4 - std::rt::lang_start::{{closure}}::h609da82e7bacb1d8
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/rt.rs:66:18
  32:   0xee8f84 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h386ec4d44fef3192
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/core/src/ops/function.rs:259:13
  33:   0xee8f84 - std::panicking::try::do_call::hc2cdb9e7ccafb401
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:379:40
  34:   0xee8f84 - std::panicking::try::h6ee92fe9ddc966bf
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:343:19
  35:   0xee8f84 - std::panic::catch_unwind::h97bc3c5df5437661
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panic.rs:396:14
  36:   0xee8f84 - std::rt::lang_start_internal::h3b802538951dbf44
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/rt.rs:51:25
  37:   0x616c78 - std::rt::lang_start::h12f4733aea7d6ec4
                       at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/rt.rs:65:5
  38:   0x50b644 - main
  39: 0xb6bbc154 - __libc_start_main
```

### PR DESCRIPTION
**Pull request by r-c-f**
Closes #4687, uses the actual size of usize rather than a fixed
constant.

### CODE REVIEW

**Review by chrisduerr — CHANGES_REQUESTED** [review]
This is missing a changelog entry.

File: alacritty_terminal/src/grid/storage.rs [hunk 1]
```diff
@@ -156,7 +156,7 @@ impl<T> Storage<T> {
     /// instructions. This implementation achieves the swap in only 8 movups
     /// instructions.
     pub fn swap(&mut self, a: usize, b: usize) {
-        debug_assert_eq!(std::mem::size_of::<Row<T>>(), 32);
+        debug_assert_eq!(std::mem::size_of::<Row<T>>(), std::mem::size_of::<usize>() * 4);
```
Comment (chrisduerr) [inline alacritty_terminal/src/grid/storage.rs:159]: Could you add an import for `std::mem` here?

File: CHANGELOG.md [hunk 2]
```diff
@@ -7,6 +7,10 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
 
 ## 0.8.0-dev
 
+### Fixed
+
+- Assertion failure on 32-bit architectures
```
Comment (chrisduerr) [inline CHANGELOG.md:12]: This is a bit unspecific as to what the actual issue is, I'd propose something more on the nose:

```suggestion
- Crash due to assertion failure on 32-bit architectures
```

**Review by chrisduerr — CHANGES_REQUESTED** [review]

**Review by chrisduerr — APPROVED** [review]
Thanks!
