### PR TITLE
Fix vi cursor on topmost of the display moving downward

### LINKED ISSUE #5652: Vi cursor on topmost of the display moves downward when scrolled into history with active output
### Reproduction steps

1. Create a scrollback buffer(history).

```sh
$ seq $LINES
```

2. Run a repeated output command.

```sh
$ ( declare -i n=0; while (( 1 )); do echo "$n"; n+=1; sleep 1; done )
```

3. Enable vi mode.
4. Move the vi cursor to topmost of the scrollback buffer or topmost of the display area on scrollback buffer.

This is a movie in which I run steps above.

https://user-images.githubusercontent.com/12132068/144487691-b3bcdd3f-2a64-4944-bfa9-a0dd184a73ec.mp4

### System

OS: Linux
Version: alacritty 0.10.0-dev (8681f710)
Linux/BSD: X11/Wayland, Xmonad

### PR DESCRIPTION
**Pull request by a5ob7r**
Fixes #5652.

### CODE REVIEW

File: alacritty_terminal/src/term/mod.rs [hunk 1]
```diff
@@ -587,16 +587,16 @@ impl<T> Term<T> {
         // Scroll selection.
         self.selection = self.selection.take().and_then(|s| s.rotate(self, &region, lines as i32));
 
+        // Scroll from origin to bottom less number of lines.
```
Comment (chrisduerr) [inline alacritty_terminal/src/term/mod.rs:590]: You got any clue at all what this comment is supposed to tell me? It seems rather broken to me.

Let's maybe just change it up while we're at it. I think I might just suggest removing the comment completely since the line itself is pretty self-explanatory?

File: alacritty_terminal/src/term/mod.rs [hunk 2]
```diff
@@ -2140,6 +2140,26 @@ mod tests {
         assert_eq!(term.grid, scrolled_grid);
     }
 
+    #[test]
+    fn vi_cursor_keep_pos_on_scrollback_buffer() {
```
Comment (chrisduerr) [inline alacritty_terminal/src/term/mod.rs:2144]: Always appreciated. :+1:

**Review by chrisduerr — CHANGES_REQUESTED** [review]
Good catch, nice patch. Thanks.

File: alacritty_terminal/src/term/mod.rs (hunk 2 above)
Comment (a5ob7r) [reply alacritty_terminal/src/term/mod.rs:2144]: My pleasure! :smile:

File: alacritty_terminal/src/term/mod.rs (hunk 1 above)
Comment (a5ob7r) [reply alacritty_terminal/src/term/mod.rs:590]: > Let's maybe just change it up while we're at it.

Yes, I have done it without thinking...

> I think I might just suggest removing the comment completely since the line itself is pretty self-explanatory?

I agree too. Come to think of it, this comment may be incorrect. "from origin to `bottom`" but the function name is `scroll_up`!

**Comment by a5ob7r** [comment]
I have done to fix a problem above and to rebase with origin/master.

**Review by chrisduerr — APPROVED** [review]

**Comment by a5ob7r** [comment]
Thank you!
