### PR TITLE
Fix highlighting multiple hints in the same line

### LINKED ISSUE #5010: Mouse enabled hint only highlights first match
With this simple hint:

```yaml
hints:
  enabled:
    - regex: foo
      action: Select
      mouse:
        enabled: true
```

And the following text in the grid:

```
foo foo
```

Only  the first `foo` will be highlighted on mouseover.

This does not seem to be an issue for the keyboard hints.

### PR DESCRIPTION
**Pull request by chrisduerr**
Fixes #5010.

### CODE REVIEW

File: alacritty/src/display/hint.rs [hunk 1]
```diff
@@ -266,11 +266,12 @@ pub fn highlighted_at<T>(
             let mut end = term.line_search_right(point);
             end.line = min(end.line, point.line + MAX_SEARCH_LINES);
 
-            // Function to verify if the specified point is inside the match.
-            let at_point = |rm: &Match| *rm.start() <= point && *rm.end() >= point;
+            // Function to verify that the specified point is inside the match.
+            let at_point = |rm: &Match| *rm.end() >= point && *rm.start() <= point;
```
Comment (chrisduerr) [inline alacritty/src/display/hint.rs:270]: Swapping these should improve performance.
