### PR TITLE
Fix visual bell getting stuck on macOS

### LINKED ISSUE #7325: Visual bell animation on Mac is really long
On macOS, the visual bell animation lasts for around 1 second regardless of what non-zero duration is in the config file. This seems to be the case since commit 80d4daccc307622f8e604af4f36ac89ecccf5db7.

Before that commit, visual bell animation worked fine.

### PR DESCRIPTION
**Pull request by kchibisov**
Fixes #7325.

### CODE REVIEW

File: alacritty/src/window_context.rs [hunk 1]
```diff
@@ -380,7 +380,13 @@ impl WindowContext {
 
         // Request immediate re-draw if visual bell animation is not finished yet.
         if !self.display.visual_bell.completed() {
-            self.display.window.request_redraw();
+            // We can get an OS redraw which by-passes alacritty's _frame_ throttling, thus
```
Comment (chrisduerr) [inline alacritty/src/window_context.rs:383]:
```suggestion
            // We can get an OS redraw which bypasses alacritty's frame throttling, thus
```

File: alacritty/src/window_context.rs [hunk 2]
```diff
@@ -380,7 +380,13 @@ impl WindowContext {
...
+            // mark the window as dirty when we don't have frame yet.
```
Comment (chrisduerr) [inline alacritty/src/window_context.rs:384]:
```suggestion
            // marking the window as dirty when we don't have frame yet.
```

**Review by chrisduerr — CHANGES_REQUESTED** [review]

**Review by chrisduerr — APPROVED** [review]
