### PR TITLE
Fix cursor and underlines always being black

### LINKED ISSUE #6417: Too many ALU instructions compiling fragment shader
### Info
The neovim cursor is barely visible because of it being completely black, as shown in the picture:
Screenshot_20221018_102445

I just want to change my cursor's color. It's fine in normal mode. Just the insert mode is bugging me.
### System
OS: Linux
Version: alacritty 0.11.0 (8dbaa0bb)
Linux/BSD: Xmonad WM, xfce4 desktop, picom compositor 
### Logs

Crashes: STDERR, STDOUT
```
Font/Terminal size: [0.000005518s] [INFO ] [alacritty] Welcome to Alacritty
[0.000228046s] [INFO ] [alacritty] Version 0.11.0 (8dbaa0bb)
[0.000276847s] [INFO ] [alacritty] Running on X11
[0.002294592s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/neon/.config/alacritty/alacritty.yml"
[0.004452006s] [DEBUG] [alacritty] Loading "JetBrainsMono Nerd Font" font
[0.029842854s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: FORCE_AUTOHINT | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.038495868s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: FORCE_AUTOHINT | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.046759446s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: FORCE_AUTOHINT | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.054382958s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: FORCE_AUTOHINT | TARGET_LIGHT, render_mode: "Lcd", lcd_filter: 1 }
[0.059619651s] [DEBUG] [alacritty] Estimated scaling factor: 1
[0.059654838s] [DEBUG] [alacritty] Estimated window size: None
[0.059666932s] [DEBUG] [alacritty] Estimated cell size: 10 x 24
[0.101826239s] [INFO ] [alacritty] Running on ATI RV370
[0.101854827s] [INFO ] [alacritty] Using OpenGL ES 2.0 renderer
r300 FP: Compiler Error:
../mesa-22.2.1/src/gallium/drivers/r300/compiler/r300_fragprog_emit.c::emit_alu(): Too many ALU instructions
Using a dummy shader instead.
[0.113617992s] [INFO ] [alacritty] Display scale factor: 1
[0.113653235s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.141414059s] [INFO ] [alacritty] Cell size: 10 x 24
[0.141448871s] [INFO ] [alacritty] Padding: 6 x 6
[0.141458502s] [INFO ] [alacritty] Width: 800, Height: 600
[0.149715288s] [INFO ] [alacritty] PTY dimensions: 24 x 78
[0.151850074s] [INFO ] [alacritty] Initialisation complete
[0.161465229s] [DEBUG] [alacritty_terminal] New num_cols is 68 and num_lines is 10
[0.170283027s] [INFO ] [alacritty] Padding: 6 x 6
[0.170319421s] [INFO ] [alacritty] Width: 696, Height: 271
[2.787286040s] [DEBUG] [alacritty_terminal] New num_cols is 141 and num_lines is 35
[2.789450867s] [INFO ] [alacritty] Padding: 6 x 6
[2.789496430s] [INFO ] [alacritty] Width: 1430, Height: 860
[3.538816155s] [DEBUG] [alacritty_terminal] New num_cols is 68 and num_lines is 10
[3.542015949s] [INFO ] [alacritty] Padding: 6 x 6
[3.542064000s] [INFO ] [alacritty] Width: 696, Height: 271
```
```
Keyboard and bindings: [0.000005560s] [INFO ] [alacritty] Welcome to Alacritty
[0.000059064s] [INFO ] [alacritty] Version 0.11.0 (8dbaa0bb)
[0.000084041s] [INFO ] [alacritty] Running on X11
[0.001952224s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/neon/.config/alacritty/alacritty.yml"
[0.003977042s] [INFO ] [alacritty] glutin event: NewEvents(Init)
[0.004000607s] [INFO ] [alacritty] glutin event: Resumed
[0.089179759s] [INFO ] [alacritty] Running on ATI RV370
[0.089207834s] [INFO ] [alacritty] Using OpenGL ES 2.0 renderer
r300 FP: Compiler Error:
../mesa-22.2.1/src/gallium/drivers/r300/compiler/r300_fragprog_emit.c::emit_alu(): Too many ALU instructions
Using a dummy shader instead.
[0.100369054s] [INFO ] [alacritty] Display scale factor: 1
[0.128478020s] [INFO ] [alacritty] Cell size: 10 x 24
[0.128512777s] [INFO ] [alacritty] Padding: 6 x 6
[0.128524819s] [INFO ] [alacritty] Width: 800, Height: 600
[0.156566142s] [INFO ] [alacritty] PTY dimensions: 24 x 78
[0.160891024s] [INFO ] [alacritty] Initialisation complete
[0.162834912s] [INFO ] [alacritty] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(9))), event: Key(KeyboardInput { scancode: 28, state: Released, virtual_keycode: Some(Return), modifiers: (empty) }) }
[0.165217586s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(37748738)), event: Ime(Disabled) }
[0.165410080s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(37748738)), event: Resized(PhysicalSize { width: 800, height: 600 }) }
[0.165443145s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(37748738)), event: Ime(Enabled) }
[0.165469149s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(37748738)), event: Resized(PhysicalSize { width: 1430, height: 860 }) }
[0.165489322s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(37748738)), event: Occluded(false) }
[0.165673131s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(37748738)), event: CursorEntered { device_id: DeviceId(X(DeviceId(2))) } }
[0.165736221s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(37748738)), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: PhysicalPosition { x: 635.0, y: 565.0 }, modifiers: (empty) } }
[0.165763334s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(37748738)), event: Focused(true) }
[0.165777803s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(37748738)), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: PhysicalPosition { x: 635.0, y: 565.0 }, modifiers: (empty) } }
[0.165958600s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.165976474s] [INFO ] [alacritty] glutin event: RedrawRequested(WindowId(WindowId(37748738)))
[0.165991063s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.175711731s] [INFO ] [alacritty] Padding: 6 x 6
[0.175749514s] [INFO ] [alacritty] Width: 1430, Height: 860
[0.237363518s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6282, tv_nsec: 553579810 }, requested_resume: None })
[0.237410020s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(37748738))), payload: Terminal(Wakeup) })
[0.237431667s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.237444534s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.256184303s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6282, tv_nsec: 596454856 }, requested_resume: None })
[0.256225488s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(37748738))), payload: Terminal(Wakeup) })
[0.256247578s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(37748738))), payload: Terminal(Wakeup) })
[0.256263027s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(37748738))), payload: Terminal(Wakeup) })
[0.256274601s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(37748738))), payload: Terminal(Wakeup) })
[0.256287303s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(37748738))), payload: Terminal(Wakeup) })
[0.256308789s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(37748738))), payload: Terminal(Wakeup) })
[0.256323035s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(37748738))), payload: Terminal(Wakeup) })
[0.256334837s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.256351134s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.398748086s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6282, tv_nsec: 637464768 }, requested_resume: None })
[0.398790683s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(37748738))), payload: Terminal(Wakeup) })
[0.398808364s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.398821014s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.403705242s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6282, tv_nsec: 743976093 }, requested_resume: None })
[0.403749033s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(37748738))), payload: Terminal(Wakeup) })
[0.403771097s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.403782992s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.441815729s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6282, tv_nsec: 782087696 }, requested_resume: None })
[0.441851101s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(37748738))), payload: Terminal(Wakeup) })
[0.441869826s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(37748738))), payload: Terminal(Wakeup) })
[0.441882627s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(37748738))), payload: Terminal(Wakeup) })
[0.441894033s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(37748738))), payload: Terminal(Wakeup) })
[0.441905918s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(37748738))), payload: Terminal(Wakeup) })
[0.441917525s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(37748738))), payload: Terminal(Wakeup) })
[0.441930003s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(37748738))), payload: Terminal(Wakeup) })
[0.441941335s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.441952461s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[0.505608179s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6282, tv_nsec: 845892880 }, requested_resume: None })
[0.505652536s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(37748738))), payload: Terminal(Title(~)) })
[0.505675534s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(37748738))), payload: Terminal(Wakeup) })
[0.505687505s] [INFO ] [alacritty] glutin event: UserEvent(Event { window_id: Some(WindowId(WindowId(37748738))), payload: Terminal(Wakeup) })
[0.505701252s] [INFO ] [alacritty] glutin event: MainEventsCleared
[0.505714610s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[1.300972870s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6282, tv_nsec: 853627113 }, requested_resume: None })
[1.301045635s] [INFO ] [alacritty] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(9))), event: Key(KeyboardInput { scancode: 125, state: Pressed, virtual_keycode: None, modifiers: (empty) }) }
[1.301081881s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(37748738)), event: ModifiersChanged(LOGO) }
[1.301168439s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(37748738)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 125, state: Pressed, virtual_keycode: None, modifiers: LOGO }, is_synthetic: false } }
[1.301236978s] [INFO ] [alacritty] glutin event: MainEventsCleared
[1.301266128s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2.085015207s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6283, tv_nsec: 641885317 }, requested_resume: None })
[2.085084729s] [INFO ] [alacritty] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(9))), event: Key(KeyboardInput { scancode: 16, state: Pressed, virtual_keycode: Some(Q), modifiers: LOGO }) }
[2.085812922s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(37748738)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 16, state: Released, virtual_keycode: Some(Q), modifiers: LOGO }, is_synthetic: true } }
[2.085868790s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(37748738)), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 125, state: Released, virtual_keycode: None, modifiers: LOGO }, is_synthetic: true } }
[2.085897493s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(37748738)), event: ModifiersChanged((empty)) }
[2.085913877s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(37748738)), event: Focused(false) }
[2.085947382s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(37748738)), event: CloseRequested }
[2.085972146s] [INFO ] [alacritty] glutin event: MainEventsCleared
[2.085986358s] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2.118505802s] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 6284, tv_nsec: 458772470 }, requested_res
```

### PR DESCRIPTION
**Pull request by kchibisov**
Some old hardware doesn't like universal shader approach for all the rectangle kinds leading to ALU instruction limits. This commit fixes it by splitting the shader per rectangle kind.

Fixes #6417.

### CODE REVIEW

File: alacritty/src/renderer/rects.rs [hunk 1]
```diff
@@ -399,44 +402,47 @@ pub struct RectShaderProgram {
     /// Shader program.
     program: ShaderProgram,
 
-    /// Kind of rect we're drawing.
-    u_rect_kind: GLint,
-
     /// Cell width.
-    u_cell_width: GLint,
+    u_cell_width: Option<GLint>,
```
Comment (chrisduerr) [inline alacritty/src/renderer/rects.rs:406]: This isn't actually how this struct works, right? But instead we have a very specific set of available combinations that are allowed?

We might want to make this a `union` instead?

File: alacritty/src/renderer/rects.rs [hunk 2]
```diff
@@ -399,44 +402,47 @@ pub struct RectShaderProgram {
...
     /// Undercurl position.
-    u_undercurl_position: GLint,
+    u_undercurl_position: Option<GLint>,
 }
 
 impl RectShaderProgram {
-    pub fn new(shader_version: ShaderVersion) -> Result<Self, ShaderError> {
-        let program = ShaderProgram::new(shader_version, RECT_SHADER_V, RECT_SHADER_F)?;
+    pub fn new(shader_version: ShaderVersion, kind: RectKind) -> Result<Self, ShaderError> {
+        // XXX this should be in-sync with fragment shader defines.
```
Comment (chrisduerr) [inline alacritty/src/renderer/rects.rs:429]:
```suggestion
        // XXX: This must be in-sync with fragment shader defines.
```

**Review by chrisduerr — CHANGES_REQUESTED** [review]

File: alacritty/src/renderer/rects.rs (hunk 1 above)
Comment (chrisduerr) [reply alacritty/src/renderer/rects.rs:406]: I don't think this is clear at all though, is it?

You could easily create an invalid struct, could you not? There's only a very limited amount of combinations that are actually "legal" and this struct does nothing to prevent the construction from illegal variants?

Comment (kchibisov) [reply alacritty/src/renderer/rects.rs:406]: By unions you mean `enum`? Since I won't use C union for that.

**Review by chrisduerr — APPROVED** [review]
