### PR TITLE
Draw cursor with rect renderer

### LINKED ISSUE #3471: Underline cursor cannot be seen on underlined text.
Hello, 
I am using emacs in the cli and it uses underline as the highlight (for linting and such). When I place the cursor on the underlined text the cursor is hidden by the underline.

Is there a way to somehow render the cursor in a different color to enable it to be seen? I tried the different settings and checked the issues but I could not find the answer.

Maybe the simplest solution would be to set the underline color to the cursor color with priority. Or just reorder rendering and firstly draw underline and override it with the cursor.

## Step to reproduce
I set the cursor color to pink to better visualize it.
image

Now when I go into tmux `copy-mode` and move the cursor to the first letter of the word "[u]nderline"

image

### System

OS: Linux
Version: alacritty 0.4.1
Linux: Wayland, sway

### Logs

Font/Terminal size: 
```
[2020-03-16 21:13] [INFO] Welcome to Alacritty
[2020-03-16 21:13] [INFO] Configuration loaded from "<home_dir>/.config/alacritty/alacritty.yml"
[2020-03-16 21:13] [DEBUG] Estimated DPR: 1
[2020-03-16 21:13] [DEBUG] Estimated Cell Size: 11 x 20
[2020-03-16 21:13] [DEBUG] Estimated Dimensions: None
[2020-03-16 21:13] [INFO] Device pixel ratio: 1
[2020-03-16 21:13] [INFO] Initializing glyph cache...
[2020-03-16 21:13] [INFO] ... finished initializing glyph cache in 0.010245541s
[2020-03-16 21:13] [INFO] Cell Size: 11 x 20
[2020-03-16 21:13] [INFO] Padding: 0 x 0
[2020-03-16 21:13] [INFO] Width: 800, Height: 600
[2020-03-16 21:13] [INFO] PTY Dimensions: Line(30) x Column(72)
[2020-03-16 21:13] [INFO] Initialisation complete
[2020-03-16 21:13] [DEBUG] New num_cols is 97 and num_lines is 47
[2020-03-16 21:13] [INFO] Width: 1076, Height: 944
```

### LINKED ISSUE #4404: Cursor vanishes when there're a lot of altases around
To repro you can 'cat' symbols file from vtebench unicode benchmark, enter vi mode, and then trying to enable selection, the cursor will vanish on certain glyphs, but will wok on other glyphs.

picture

### PR DESCRIPTION
**Pull request by kchibisov**
This commit makes cursors being drawn via rects, thus it's always above
underlines/strikeouts. Also, since cursor isn't a glyph anymore, it
can't be obscured due to atlas switching during glyphs drawing.

Fixes #4404.
Fixes #3471.

### CODE REVIEW

**Comment by chrisduerr** [comment]
Just applying inverse to the cell's below the cursor and having a different method to get the cursor glyphs seems fine to me.

**Comment by kchibisov** [comment]
I've updated everything, but I'd like to merge it after #4452, so it'd draw things faster.

**Comment by chrisduerr** [comment]
> I've updated everything, but I'd like to merge it after #4452, so it'd draw things faster.

I'm sorry, but I don't understand. Even if this is merged before #4452, this would still become faster once #4452 is merged, right? Why should this wait until a PR opened after it is merged? Are there some changes in #4452 that you'd like to explicitly make use of, that wouldn't have to be made just by rebasing #4452 on top of this?

**Comment by kchibisov** [comment]
>I'm sorry, but I don't understand. Even if this is merged before #4452, this would still become faster once #4452 is merged, right? Why should this wait until a PR opened after it is merged? Are there some changes in #4452 that you'd like to explicitly make use of, that wouldn't have to be made just by rebasing #4452 on top of this?

I just want things a bit faster and don't want to invoke rect renderer without any rect being present.

**Comment by kchibisov** [comment]
>I've updated everything, but I'd like to merge it after #4452, so it'd draw things faster.

this one is merged.

File: alacritty/src/cursor.rs [hunk 1]
```diff
@@ -1,112 +1,66 @@
...
+use alacritty_terminal::ansi::CursorShape;
+use alacritty_terminal::term::color::Rgb;
+use alacritty_terminal::term::{CursorKey, SizeInfo};
 
-use crossfont::{BitmapBuffer, Metrics, RasterizedGlyph};
+use crate::renderer::rects::RenderRect;
 
-use alacritty_terminal::ansi::CursorShape;
+pub struct Cursor {
+    /// Coordinates of top left corner of the cursor cell.
```
Comment (chrisduerr) [inline alacritty/src/cursor.rs:9]:
```suggestion
    /// Coordinates of the top left corner of the cursor cell.
```

File: alacritty/src/cursor.rs [hunk 2]
```diff
@@ -1,112 +1,66 @@
...
-            if y < line_width
-                || y >= height - line_width
-                || x < line_width
-                || x >= width - line_width
-            {
-                buf.append(&mut vec![255u8; 3]);
-            } else {
-                buf.append(&mut vec![0u8; 3]);
-            }
+    pub fn into_rects(self, size_info: &SizeInfo) -> Vec<RenderRect> {
```
Comment (chrisduerr) [inline alacritty/src/cursor.rs:25]: Multiple rects for the box cursor, correct?

File: alacritty/src/cursor.rs [hunk 3]
```diff
@@ -1,112 +1,66 @@
...
+        let height = size_info.cell_height();
+        let line_width = (self.thickness * width as f64).round().max(1.) as f32;
+
+        if self.key.is_wide {
+            width *= 2.;
+        }
+
+        match self.key.shape {
+            CursorShape::Beam => self.beam(height, line_width),
+            CursorShape::Block | CursorShape::Hidden => vec![],
```
Comment (chrisduerr) [inline alacritty/src/cursor.rs:36]:
```suggestion
            CursorShape::Block | CursorShape::Hidden => Vec::new(),
```

**Review by chrisduerr — CHANGES_REQUESTED** [review]

File: alacritty_terminal/src/term/mod.rs [hunk 4]
```diff
@@ -201,12 +201,20 @@ impl<'a, C> RenderableCellsIter<'a, C> {
...
+                _ => {
+                    let fg = cell.fg;
+                    cell.fg = self.cursor.text_color.color(fg, cell.bg);
+                    cell.bg = self.cursor.cursor_color.color(fg, cell.bg);
+                },
+            }
+
+            // Since we draw Block cursor by drawing cell below it with a proper color,
+            // we must adjust alpha to make it visible.
+            cell.bg_alpha = 1.;
```
[the remark this answers is not in the document]
Comment (kchibisov) [reply alacritty_terminal/src/term/mod.rs:217]: next_cursor_cell is the cell below cursor, and next_cursor is a cursor cell, so I modify the cell below it? I don't see a problem here.

File: alacritty/src/cursor.rs (hunk 2 above)
Comment (kchibisov) [reply alacritty/src/cursor.rs:25]: Yes, however what do you think about passing a mutable reference to a vector? I think it should be more clear, and especially since reduce allocations on each draw.

File: alacritty/src/renderer/mod.rs [hunk 5]
```diff
@@ -823,21 +808,10 @@ impl<'a> RenderApi<'a> {
...
-                        cursor_key.is_wide,
-                        self.cursor_config.thickness(),
-                    ))
-                });
-                self.add_render_item(&cell, glyph);
-                return;
+            RenderableCellContent::Cursor(_) => {
+                // TODO maybe yield cells that can't be rendered and not pattern match in
+                // a loop inside display.rs.
+                unreachable!("Trying to draw cursor from cell renderer.")
```
[the remark this answers is not in the document]
Comment (kchibisov) [reply alacritty/src/renderer/mod.rs:814]: I'll try to refactor it so the cursor will be returned somewhere else.

File: alacritty/src/cursor.rs (hunk 2 above)
Comment (chrisduerr) [reply alacritty/src/cursor.rs:25]: I'm not sure what you mean, why would it need to be mutable?

And the Vecs are created in this function, right? So that would create lifetime problems. Or do you plan to store the vector on the `Cursor`?

File: alacritty_terminal/src/term/mod.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (chrisduerr) [reply alacritty_terminal/src/term/mod.rs:217]: Huh, I'm not sure what I've been thinking. I must have confused myself. You're right of course.

**Comment by kchibisov** [comment]
I've refactored things a bit, however I'm not sure if it's the right way to do that, but it actually works...

File: alacritty_terminal/src/term/mod.rs [hunk 6]
```diff
@@ -124,6 +138,16 @@ impl<'a> RenderableSearch<'a> {
     }
 }
 
+/// Common rendering primitives stored in one structure to simplify passing them around.
+struct RenderableContentInner<'a, T, C> {
```
Comment (kchibisov) [inline alacritty_terminal/src/term/mod.rs:142]: I have no clue how to name it, maybe `RenderableContext`.

File: alacritty_terminal/src/term/mod.rs [hunk 7]
```diff
@@ -124,6 +138,16 @@ impl<'a> RenderableSearch<'a> {
...
+    term: &'a Term<T>,
+    selection: Option<SelectionRange<Line>>,
+    search: RenderableSearch<'a>,
+    config: &'a Config<C>,
+    cursor_point: Point,
+    cursor_shape: CursorShape,
```
Comment (kchibisov) [inline alacritty_terminal/src/term/mod.rs:148]: We don't pass cursor here, since when getting rendering cursor we need to get cell first before getting color. I also decided to not create like 2 different renderable cursor and decided to stick with one.

File: alacritty_terminal/src/term/mod.rs [hunk 8]
```diff
@@ -938,6 +888,58 @@ impl<T> Term<T> {
         res
     }
 
+    /// Check selection state of a cell.
+    pub fn is_selected(
```
Comment (kchibisov) [inline alacritty_terminal/src/term/mod.rs:892]: since it's on `Term` now maybe we can use it somewhere else, but that cursor stuff annoys me a bit. Passing selection also sounds questionable, but I think it's fine, if we hide this function for now...

File: alacritty_terminal/src/term/mod.rs [hunk 9]
```diff
@@ -50,12 +50,26 @@ pub const MIN_SCREEN_LINES: usize = 1;
 
 /// Cursor storing all information relevant for rendering.
 #[derive(Debug, Eq, PartialEq, Copy, Clone, Deserialize)]
-struct RenderableCursor {
+pub struct RenderableCursor {
+    color: Rgb,
```
Comment (kchibisov) [inline alacritty_terminal/src/term/mod.rs:54]: Decided to store here just to avoid creating one more struct, but it makes certain things a bit more uglier, I guess.

File: alacritty/src/cursor.rs [hunk 10]
```diff
@@ -1,112 +1,79 @@
...
-    // Create a custom glyph with the rectangle data attached to it.
-    RasterizedGlyph {
-        c: ' ',
-        top: line_width as i32,
-        left: 0,
-        height: line_width as i32,
-        width: width as i32,
-        buf: BitmapBuffer::RGB(buf),
+impl Cursor {
+    fn new(cursor: RenderableCursor, size_info: &SizeInfo, thickness: f64) -> Self {
```
Comment (chrisduerr) [inline alacritty/src/cursor.rs:21]: I find this API a bit strange, how you create a cursor first and then create a cursor rect from it.

You should know what kind of cursor you have from the beginning, right? So why not just create one immediately?

You also do strange stuff like creating a cursor, passing `size_info` to it, but then getting the `width` out of size info, multiplying it by the width the created cursor gives you, just to pass it back to the cursor. After you passed the `size_info` to the cursor it had all the information it ever needed, why juggle around with the `width` outside of it?

File: alacritty_terminal/src/term/mod.rs (hunk 6 above)
Comment (chrisduerr) [reply alacritty_terminal/src/term/mod.rs:142]: `RenderContext` maybe? `RenderableContext` would mean it's a context that can be rendered.

File: alacritty_terminal/src/term/mod.rs (hunk 8 above)
Comment (chrisduerr) [reply alacritty_terminal/src/term/mod.rs:892]: Why move it on `Term`, it seems out of place. Passing `selection` to something on `Term` doesn't make a ton of sense, because it already has selection stored on it. So that makes all of this rather questionable.

Also passing a cursor to a function that checks if a cell is selected doesn't really make sense to me for a terminal selection check?

File: alacritty_terminal/src/term/mod.rs [hunk 11]
```diff
@@ -1440,22 +1442,44 @@ impl<T> Term<T> {
...
+            cursor_shape,
+            search: RenderableSearch::new(self),
+        };
+
+        let cell = Indexed {
+            inner: &self.grid[buffer_point.line][buffer_point.col],
+            column: cursor_point.col,
+            line: cursor_point.line,
+        };
+        let mut cell = RenderableCell::new(&mut inner, cell);
```
Comment (chrisduerr) [inline alacritty_terminal/src/term/mod.rs:1470]: Do we create an entire `RenderableContentInner` including selection, config, term and search, then create a cell from it, just to check which color our cursor is supposed to be?

It feels like there's got to be an easier way to figure out a cursor's color than that.

**Review by chrisduerr — CHANGES_REQUESTED** [review]

File: alacritty_terminal/src/term/mod.rs (hunk 8 above)
Comment (kchibisov) [reply alacritty_terminal/src/term/mod.rs:892]: Because I can't create a renderable cell otherwise? I need selection and searcher to perform that. I'd like to not do so, but then I need to change the logic entirely, though, maybe selection logic doesn't really matter for is_selected. The main issue is that it originates from renderable cell constructor, and i need it to create a cursor...

File: alacritty_terminal/src/term/mod.rs (hunk 11 above)
Comment (kchibisov) [reply alacritty_terminal/src/term/mod.rs:1470]: Well, all coloring stuff is handles by renderable cell. And we have a lot of fancy logic to get colors, etc, etc. Maybe we can craft something simple, but I'm not sure.

Comment (chrisduerr) [reply alacritty_terminal/src/term/mod.rs:1470]: Yeah, but you don't need stuff like `bg_alpha`, `column/line`, `zerowidth`, `flags` or `match` detection. Sure the color logic is here, but it just seems like there's also a lot of other logic that we don't really care about here?

I think the biggest problem is just that we kinda construct a full renderable cell here, when we know that the renderable cell will already be created in a different place. It would be nice if we could just access the information from that cell instead of having to build it twice.

Comment (kchibisov) [reply alacritty_terminal/src/term/mod.rs:1470]: But the information will be there only when iteration is done, we could pass a mutable reference to a renderable cursor and finish initialization there.

Comment (chrisduerr) [reply alacritty_terminal/src/term/mod.rs:1470]: At that point we could just return a struct from `renderable_cells` which contains cursor and cells.

**Review by chrisduerr — APPROVED** [review]
