### PR TITLE
Ignore errors from swap_buffers

### LINKED ISSUE #6538: Focused alacritty windows crash when restarting i3
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Debian 11 stable
Version: 0.12.0-dev (2d619850)
Linux/BSD: X11, i3 and picom

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: 

```
Created log file at "/tmp/Alacritty-68231.log"
[0.000011548s] [INFO ] [alacritty] Welcome to Alacritty
[0.000192596s] [INFO ] [alacritty] Version 0.12.0-dev (2d619850)
[0.000234186s] [INFO ] [alacritty] Running on X11
[0.000527993s] [INFO ] [alacritty_config_derive] No config file found; using default
[0.006203612s] [INFO ] [alacritty] Using GLX 1.4
[0.113863181s] [INFO ] [alacritty] Window scale factor: 1
[0.115189900s] [DEBUG] [alacritty] Loading "monospace" font
[0.124206036s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.125783913s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.127487960s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.129240457s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.134742738s] [INFO ] [alacritty] Running on NVE7
[0.134768184s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.143704161s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.177438838s] [INFO ] [alacritty] Cell size: 9 x 18
[0.177514079s] [INFO ] [alacritty] Padding: 0 x 0
[0.177538802s] [INFO ] [alacritty] Width: 800, Height: 600
[0.189248977s] [INFO ] [alacritty] PTY dimensions: 33 x 88
[0.192290824s] [INFO ] [alacritty] Initialisation complete
[0.213466719s] [DEBUG] [alacritty_terminal] New num_cols is 73 and num_lines is 19
[0.229562548s] [INFO ] [alacritty] Padding: 0 x 0
[0.229620166s] [INFO ] [alacritty] Width: 658, Height: 346
[0.300711358s] [DEBUG] [alacritty_terminal] unknown device status query: 1337
[2.334171186s] [INFO ] [alacritty] Goodbye
Deleted log file at "/tmp/Alacritty-68231.log"
```

Keyboard and bindings: `alacritty --print-events`

So I recently cloned the repo and after i set everything up, it works until I restart i3. After that, it just blacked out like in this picture:
Screenshot_2022-11-30_23-10-49
This only happen with the focused windows, unfocused windows work just fine
when I restart, the terminal session I opened it from gives me this message:
`thread 'main' panicked at 'failed to swap buffers.: Error { raw_code: Some(3), raw_os_message: Some("BadWindow (invalid Window parameter)"), kind: BadNativeWindow }', alacritty/src/display/mod.rs:557:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

That's all I have for now. I am willing to provide more info, just tell me how to actually get the extra info that you need

### PR DESCRIPTION
**Pull request by kchibisov**
Most of them are innocent and require just swap again. It was like that before anyway due to old glutin bug in the error handling implementation where errors won't pulled on swap buffers, but old observed error was used.

Fixes #6538.

### CODE REVIEW

File: alacritty/src/display/mod.rs [hunk 1]
```diff
@@ -545,16 +545,20 @@ impl Display {
...
             #[cfg(not(any(target_os = "macos", windows)))]
             (Surface::Egl(surface), PossiblyCurrentContext::Egl(context))
                 if self.is_wayland && !self.debug_damage =>
             {
                 surface.swap_buffers_with_damage(context, &self.damage_rects)
             },
             (surface, context) => surface.swap_buffers(context),
+        };
+        // We ignore the errors, but log them into `debug` so we can at least
+        // troubleshoot them in case they could be suspicious to real issues.
```
Comment (chrisduerr) [inline alacritty/src/display/mod.rs:558]:
```suggestion

```

Was thinking how to improve this doc message since it sounds a bit weird, but honestly developers can probably read and we don't need to explicitly document this.

**Review by chrisduerr — CHANGES_REQUESTED** [review]
This affects 0.12.0, right? Needs a changelog entry then?

File: alacritty/src/display/mod.rs (hunk 1 above)
Comment (kchibisov) [reply alacritty/src/display/mod.rs:558]: I don't how to improve it either, I just stated that we log here for our own purposes, and it's not really a user warning or anything like that. They don't show real issues from what we know and only a subject to potential issues.

Comment (chrisduerr) [reply alacritty/src/display/mod.rs:558]: I mean that's exactly what `debug!` says anyway though. Debug logs are stuff we log for troubleshooting that aren't user errors.

Comment (kchibisov) [reply alacritty/src/display/mod.rs:558]: Hm, I guess, so.

**Review by chrisduerr — APPROVED** [review]
