### PR TITLE
Account for glyph offset when determining strikeout position

### LINKED ISSUE #8524: Wrong strikeout position
It seems the strikeout position is wrong when `font.glyph_offset.y` is not `0`;

With  `font.glyph_offset.y` = `4`:
Image

With  `font.glyph_offset.y` = `0`:
Image

I tested with a couple different fonts with the same results.

Version: 0.15.1

### PR DESCRIPTION
**Pull request by twharmon**
It seems the strikeout position is wrong when `font.glyph_offset.y` is not `0`;

Before:
Screenshot From 2025-03-21 11-30-39

After:
image

Closes #8524

### CODE REVIEW

**Comment by kchibisov** [comment]
I think just strikethrough will work though, since it's not passed into other rects. You need to test all the lines though (undercurl/etc) for tests.

**Comment by chrisduerr** [comment]
> If this PR doesn't solve it effectively, or if there is something else wrong with it, please suggest a better path forward.

No matter what, the only reasonable action to encountering a font with broken metrics is switching fonts in my opinion.

**Comment by kchibisov** [comment]
>No matter what, the only reasonable action to encountering a font with broken metrics is switching fonts in my opinion.

I mean, we generally want to make it work, it's just the one before got reverted because all underlines were broken. Just strikethrough should work.

**Comment by chrisduerr** [comment]
> Just strikethrough should work.

Why do you think just strikethrough should work? It comes from font metrics just like underline, which means it's just as likely to cause the same issues.

**Comment by kchibisov** [comment]
The issue is that shaders use underline metrics to draw `undercurl`/`dotted`/etc lines and also operate with certain assumptions, however strikethrough is not part of that equation. But I reverted both since they were in the same patch.

The issue is not that `offset` makes it worse, and the issue is not the metrics of the font either, it's more of a "how shaders work" type of issue.

I'm not saying that the patch the way it was provided is how it should be handled, but logically, if we offset the font, we should offset its metrics in general, so it's consistent. Not confuse with e.g. offset, since offset is fine.

In general, I don't like `glyph_offset` all together, and rather have a line height kind of setting. But some use it to align glyphs when multiple fonts are involved.

**Comment by kchibisov** [comment]
I think something like that:

```
diff --git a/alacritty/src/renderer/text/glyph_cache.rs b/alacritty/src/renderer/text/glyph_cache.rs
index 6acc3189..537e8d23 100644
--- a/alacritty/src/renderer/text/glyph_cache.rs
+++ b/alacritty/src/renderer/text/glyph_cache.rs
@@ -284,7 +284,9 @@ impl GlyphCache {
             character: 'm',
             size: font.size(),
         })?;
-        let metrics = self.rasterizer.metrics(regular, font.size())?;
+        let mut metrics = self.rasterizer.metrics(regular, font.size())?;
+        metrics.underline_position += font.glyph_offset.y as f32;
+        metrics.strikeout_position += font.glyph_offset.y as f32;
 
         info!("Font size changed to {:?} px", font.size().as_px());
 

```

This will make `underline`, `strikeout`, `dashed` work, however not others, but the thing is that it doesn't break anything.

**Comment by kchibisov** [comment]
Hm, no, it does break dotted a bit, but you can just apply the `strikeout` part of the patch, that should be fine.

File: alacritty/src/renderer/text/glyph_cache.rs [hunk 1]
```diff
@@ -104,6 +98,22 @@ impl GlyphCache {
         })
     }
 
+    // Get metrics adjusted for glyph offset.
+    fn get_offset_adjusted_metrics(
```
Comment (kchibisov) [inline alacritty/src/renderer/text/glyph_cache.rs:102]:
```suggestion
    fn load_font_metrics(
```

And a CHANGELOG entry.

**Review by kchibisov — CHANGES_REQUESTED** [review]

File: CHANGELOG.md [hunk 2]
```diff
@@ -18,6 +18,7 @@ Notable changes to the `alacritty_terminal` crate are documented in its
 
 - Crash when OpenGL context resets
 - Modifier keys clearing selection with kitty keyboard protocol enabled
+- Strikeout rendering not displaying correctly when `glyph_offset` config is set greater than 0
```
Comment (kchibisov) [inline CHANGELOG.md:21]:
```suggestion
- `glyph_offset.y` not applied to strikeout
```

**Review by kchibisov — APPROVED** [review]
