### PR TITLE
Fix selection expansion across full-width glyphs

### LINKED ISSUE #3106: Expand full-width glyphs individually instead of relying on selection start/end
Currently when a selection starts/ends with a zero-width glyph, expansion is done based on that. However with things like block selection this does not work.

Instead of checking for expansion at the start/end of the selection, we should just have the selection as a fixed span from start/end of two points and then whenever a full-width glyph is selected, we should automatically apply that selection to the spacer glyphs too.

### PR DESCRIPTION
**Pull request by chrisduerr**
Instead of trying to expand the start and end of a selection across
full-width glyphs, the selection should now only go from its origin to
the end without any kind of expansion.

Instead, the expansion is now done where the cells are actually checked
for their selection status, expanding across the entire full-width glyph
whenever any part of it is selected.

Fixes #3106.

### CODE REVIEW

File: alacritty_terminal/src/term/mod.rs [hunk 1]
```diff
@@ -281,6 +281,52 @@ impl<'a, C> RenderableCellsIter<'a, C> {
...
+
+            // Check trailing spacer
+            return selection.contains(next.col, next.line)
+                // Check line-wrapping, leading spacer
+                || (self.grid[&prev].flags.contains(Flags::WIDE_CHAR_SPACER)
+                    && !self.grid[&prevprev].flags.contains(Flags::WIDE_CHAR)
+                    && selection.contains(prev.col, prev.line));
+        }
+
+        // Check if spacer's wide char is selected
```
Comment (kchibisov) [inline alacritty_terminal/src/term/mod.rs]: This comment seems strange, I guess wording is a bit messed up.

File: alacritty_terminal/src/term/mod.rs [hunk 2]
```diff
@@ -281,6 +281,52 @@ impl<'a, C> RenderableCellsIter<'a, C> {
...
+        if cell.flags.contains(Flags::WIDE_CHAR_SPACER) {
+            let prev = point.sub(num_cols, 1, false);
+
+            if self.grid[&prev].flags.contains(Flags::WIDE_CHAR) {
+                // Check previous cell for trailing spacer
+                return self.is_selected(prev);
+            } else {
+                // Check next cell for line-wrapping, leading spacer
+                let next = point.add(num_cols, 1, false);
+                return self.is_selected(next);
```
Comment (kchibisov) [inline alacritty_terminal/src/term/mod.rs]: Could you explain to me why do we need recursion?

File: alacritty_terminal/src/term/mod.rs [hunk 3]
```diff
@@ -281,6 +281,52 @@ impl<'a, C> RenderableCellsIter<'a, C> {
...
+            }
+        }
+
+        false
```
Comment (kchibisov) [inline alacritty_terminal/src/term/mod.rs]: I feel like you can just do the following instead of this strange `return` logic.

This is pseudo code.

```rust

if cell.flags... {
	let prev = point.sub
	let point = if self.grid... {
		&prev
	} else {
		&next
	}
	
	self.is_selected(point)
} else {
	false
}

```

File: alacritty_terminal/src/term/mod.rs [hunk 4]
```diff
@@ -949,9 +987,9 @@ impl<T> Term<T> {
 
         if is_block {
             for line in (end.line + 1..=start.line).rev() {
-                res += &(self.line_to_string(line, start.col..end.col) + "\n");
+                res += &(self.line_to_string(line, start.col..end.col, start.col.0 == 0) + "\n");
```
Comment (kchibisov) [inline alacritty_terminal/src/term/mod.rs]: Could you explain to me the idea behind including wrap here? I feel like we shouldn't do it?

File: alacritty_terminal/src/term/mod.rs [hunk 5]
```diff
@@ -1017,6 +1064,15 @@ impl<T> Term<T> {
             text.push('\n');
         }
 
+        // If wide char is not part of the selection, but leading spacer is, include it
+        if line_end == self.grid.num_cols()
```
Comment (kchibisov) [inline alacritty_terminal/src/term/mod.rs]: It seems like `line_end` is zero based, but `self.grid.num_cols()`?

File: alacritty_terminal/src/index.rs [hunk 6]
```diff
@@ -44,33 +44,38 @@ impl<L> Point<L> {
...
+        let line_changes =
+            f32::ceil(rhs.saturating_sub(self.col.0) as f32 / num_cols as f32) as usize;
         if absolute_indexing {
-            self.line = self.line + line_changes as usize;
+            self.line = self.line + line_changes;
+        } else if self.line.into() > Line(line_changes) {
+            self.line = self.line - line_changes;
         } else {
-            self.line = self.line - line_changes as usize;
+            self.line = Default::default();
```
[the remark this answers is not in the document]
Comment (chrisduerr) [reply alacritty_terminal/src/index.rs]: Yeah, we don't want to underflow. Partially because that panics in debug mode and partially because that doesn't logically make sense. If you move a point down and it goes below the viewport, you don't want it to appear at the top.

File: alacritty_terminal/src/term/mod.rs [hunk 7]
```diff
@@ -281,6 +281,52 @@ impl<'a, C> RenderableCellsIter<'a, C> {
...
+                return self.is_selected(prev);
+            } else {
+                // Check next cell for line-wrapping, leading spacer
+                let next = point.add(num_cols, 1, false);
+                return self.is_selected(next);
+            }
+        }
+
+        false
+    }
```
[the remark this answers is not in the document]
Comment (chrisduerr) [reply alacritty_terminal/src/term/mod.rs]: I think the current approach should be pretty good for perf actually, because in most cases we exit early and never go inside of the WIDE_CHAR and WIDE_CHAR_SPACER blocks.

So we just have two conditionals that are absolutely necessary anyways and everything else is skipped. Except for the `self.grid[&point]` and `num_cols` parts, but maybe the optimizer even helps with that, I don't know. They shouldn't impact performance much though.

But the main goal is making things more readable, I think that's definitely worth it here. The performance impact should not be measurable, I certainly can't.

File: alacritty_terminal/src/term/mod.rs (hunk 1 above)
Comment (chrisduerr) [reply alacritty_terminal/src/term/mod.rs]: How so?

File: alacritty_terminal/src/term/mod.rs (hunk 2 above)
Comment (chrisduerr) [reply alacritty_terminal/src/term/mod.rs]: Because I did not want any duplicate code in this already way too complex logic. These codepaths should rarely be hit, so performance isn't really much of an issue.

But basically what we're doing here is that the `WIDE_CHAR` cell itself has full authority on checking if it is selected or not. So the spacers around it just query that cell for the selection information.

Otherwise we'd have to check in the left spacer if either WIDE_CHAR or right spacer is selected, check in the right spacer if WIDE_CHAR or left spacer is selected and then check in the WIDE_CHAR if either left spacer or right spacer are selected.

File: alacritty_terminal/src/term/mod.rs (hunk 3 above)
Comment (chrisduerr) [reply alacritty_terminal/src/term/mod.rs]: I don't think the `let point = if { ... } else { }` benefits us here, but the rest of this looks good.

File: alacritty_terminal/src/term/mod.rs (hunk 5 above)
Comment (chrisduerr) [reply alacritty_terminal/src/term/mod.rs]: If you look at where `line_end` is defined, you can see that it is not zero based. We check with `min(line_length, cols.end + 1)`, where `cols.end` is zero-based. So we add one because the final line length specifically isn't.

Comment (kchibisov) [reply alacritty_terminal/src/term/mod.rs]: and now if you look at the check above `line-end == Column(0)`, you'll see some odd logic.

File: alacritty_terminal/src/term/mod.rs (hunk 4 above)
Comment (chrisduerr) [reply alacritty_terminal/src/term/mod.rs]: If we have a block selection that includes part of a wide char at the right, but which doesn't start at the left side of the terminal (in column 0), we need to expand across the wide char.

Comment (chrisduerr) [reply alacritty_terminal/src/term/mod.rs]: But it should be `start.col.0 != 0`.

Comment (kchibisov) [reply alacritty_terminal/src/term/mod.rs]: not it make more sense.

File: alacritty_terminal/src/term/mod.rs [hunk 8]
```diff
@@ -281,6 +281,49 @@ impl<'a, C> RenderableCellsIter<'a, C> {
...
+            if self.grid[&prev].flags.contains(Flags::WIDE_CHAR) {
+                // Check previous cell for trailing spacer
+                self.is_selected(prev)
+            } else {
+                // Check next cell for line-wrapping, leading spacer
+                self.is_selected(point.add(num_cols, 1))
+            }
+        } else {
+            false
+        }
```
Comment (kchibisov) [inline alacritty_terminal/src/term/mod.rs]: absolute beast.

File: alacritty_terminal/src/term/mod.rs (hunk 5 above)
Comment (chrisduerr) [reply alacritty_terminal/src/term/mod.rs]: It's not actually that odd. You have to look at it more like a count, the count of included cells.

So even if it's 1-based, because the "first element" is at 1, that doesn't mean that a length of 0 doesn't exist. This will be the case when the entire line is empty for example.

File: alacritty_terminal/src/term/mod.rs (hunk 1 above)
Comment (kchibisov) [reply alacritty_terminal/src/term/mod.rs]: idk, it was hard to read it tbh. maybe `check if wide spacer's wide char is selected`, but you can ignore this one.

File: alacritty_terminal/src/term/mod.rs (hunk 5 above)
Comment (kchibisov) [reply alacritty_terminal/src/term/mod.rs]: Could you name it `line_len`, since it's what you're trying to say to me.

Comment (chrisduerr) [reply alacritty_terminal/src/term/mod.rs]: Sounds like a great idea, yeah.

**Comment by kchibisov** [comment]
note: I'll give (hopefully) a final look on this thing today and merge it later this evening in case everything will be fine.
